* 什么是订单
  今天读到一篇很好的博文：

  他用非常精炼的，深刻的语言说明了：什么是业务。比如你应该停下来，好好思考一下：什么是订单。

  你自己思考你订机票，订iphone，订旅店等的过程，然后抽象出一个数据模型。这个的整个过程就是Domain。

  What is Domain？What is Order Domain？思考清楚这个问题，那么你就知道，作为一个软件架构师，
  程序设计师，业务应该怎么玩。

** 什么是订单？
   拿订火车票为例子？
   火车票：
   首先我们要注册，登录（其实这步可以不需要，后面会说到），
   然后输入：起点，终点，日期，进行查询。
   然后列出了当天所有的火车票班次信息
   每个火车班次，有班次信息，开车时间，到点时间，商务座，软硬卧，软硬座等的余票数量，价格。
   车次类型，出发站点，到达站点，

   我草，我发现根据这上面的就不得了了。

   根据以上得到数据结构信息

   得到数据结构，就可以建表？建完表，就可以开始写CRUD了。

   最关键的是数据，数据结构（也就是组织数据的方式）
   这里面要找到一个最关键的 *实体类* 也就是用来连接其他实体类的中心类。

*** 车次
    车次id， 也是唯一标示一次车次的，只是会结合到日期？
    高铁，动车，普通，城际，trainType
    车次 G87,K12。。。 trainNo
    起点，北京南站，北京北站，startStation
    重点，上海北站，虹桥站等，endStation
    出发时间，10:00 startTime
    到站时间 18:00  arrivalTime

    车次不是唯一的，每天都应该有，但是有些天，会多出几个车次，有些天有些车次不能用。
    这个该怎么搞了？？？

    车次都是固定的，所以可以直接放到缓存中，类似redis。
*** 车票
    车票编号  SFDLSJXX，唯一表示
    车票类型，商务座，软硬卧，软硬座，站票等，
    车票价格，商务座1K块，硬座100块
    车票数量，这个该怎么搞？
*** 用户信息
    用户id，唯一表示
    手机号，
    身份证号，
    姓名，性别，等

*** 支付
    是否已经支付
    支付方式
    支付用到的银行卡，支付宝（退款要用的）

    光写这个以上的估计没撒用吧，还是要干啊。看看怎么具体实现啊。

    easyui感觉太丑，怎么搞？但是之前用过，也学过，能很好的搞。
    这个业务方面的能力，怎么提升了？也没人让干个撒，设计个撒。妈的，蛋疼的很。
