* 我的简历
** 2015年5月求职时简历
宋鑫－长江大学-计算机科学与技术－4年-JAVA高级-英语读写精通
个人信息：
电话:18025360608                邮箱:504252262@163.com
技术博客地址：3gods.com    github地址：songxin1990.git.com
职业技能：
熟悉jquery，ajax，html，easyui，extjs等web技术
熟练使用spring，struts，ibatis，hibernate等web框架
熟练进行webservice，http接口开发
熟悉缓存，一致性hash，负载均衡等技术
深入理解tcp/ip，http协议，能够设计良好的通信协议
熟悉socket多线程网络编程，熟悉高并发编程
深入理解jms，activemq，kafka，jafka等消息中间件，研读过源码
深入理解nio等线程模型，深入理解netty架构设计，源码实现
对架构设计，接口化，服务化，模块化等有一定理解
对于系统重构有一定理解与实际经验，代码简洁优雅
熟练使用zookeeper，mongodb，redis，了解hadoop，hdfs，storm
熟悉集群，分布式,,高并发，秒杀系统设计，了解大数据
能够在Linux上进行开发，部署
熟练使用intelj，eclipse，git，svn，maven
熟练编写常见sql语句，熟悉索引，了解存储过程

工作经验：
2012/07/至2014/04/  中国安防
智慧城市的国内领头羊，中国第一家从纳斯达克成功退市私有化的公司。旗下有50多家子公司，上海中安消子公司现已借壳飞乐股份上市，中国安防是一家综合性的大公司。
在中国安防研究院参与一个2000人使用的工资核算系统开发，之后和另外一个同事2人一起开发b/s版本的多媒体信息发布系统

2014/05/至今 宁远科技
就医160，国内最大的互联网医疗服务平台，致力于打造中国人的网上医院，旗下产品有就医通，蓝蜻蜓等多款知名软件。
在宁远科技全面独立负责PHP,JAVA平台日志系统的架构设计，技术选型，模块代码开发以及性能优化等工作，协助运维人员进行系统的部署。
之后在架构师分配下负责技术平台消息总线服务系统的架构设计，技术选型，逻辑实现，代码编写等工作。

项目经验：
2015-08-01至今：基础平台消息总线服务
在架构师分配任务下，负责宁远科技基础信息平台的消息总线服务，提供给各个平台功能模块调用，转发各种类型的消息，或者调用第三方接口，比如短信，微信，QQ等。
系统主要有2个独立的子项目，sms-service和sms-sender，sms-service。
使用到的技术有netty,multi-thread，mysql，webservice,httpclient,jmx等

2014-05至2015-06PHP,JAVA平台日志系统
此日志系统主要功能是负责异步接收PHP,JAVA平台发送过来的业务日志，操作日志等，并将日志保存到Mongodb（后改为elasticsearch）中，在kibana中进行后一步的处理，比如日志分析，后期定位回溯各种问题等。
后期改造对日志进行清洗，数据分析等工作。
使用到的技术有netty,pb,mongodb,multi-thread,es，kibana,zookeeper,jmx等。

2013-04至2014-04多媒体信息发布系统
用java web来实现的B/S版多媒体信息发布系统，用来控制智慧大厦中的视频设备，进行视频，音频，图片，文本等多媒体信息发布的系统。主要的模块功能有用户管理，权限管理，素材管理，设备分组管理，节目发布，播放列表制作等功能。
本人主要负责c++协议解析，包数据的处理，素材管理和设备管理等模块的开发，还有文档的撰写，后期测试等工作。
使用到了spring,mybatis,jndi，webservice，ajax等

2012-07至2013-02中国安防工资核算系统
一个B/S架构，mvc框架的web系统，使用到了一些常用的设计模式，工厂模式，单例模式等。使用SSH框架，tomcat服务器，mysql数据库，实现对员工的工资信息化管理。主要模块包括员工管理，员工考勤，绩效考核，薪资异动等。并对访问者进行权限控制。
主要负责模块设计文档编写，用户管理，日志管理等模块开发，以及后期的bug修复，实施维护等。
使用到了struts，hibernate，mysql，tomcat，extjs等


** 2017年5月在职简历
