* 五年的楼主程序员经验之谈
谢谢朋友的关心，简单的说下吧：1 我只是基础比较扎实而已，其实万丈高楼平地起，基础扎实才是王道 2 Coding，坚持Coding，中间一段理解面向对象，也很痛苦纠结吧，编码有什么诀窍呢，不过孰能生巧。 3 反思，任何错误都是原因的，分析，找个方案解决。比如，我们经常会遇到列表访问越界，怎么办呢，for i := 0 to Count - 1 do .我无法保证我是否每次清醒的会添加  - 1，怎么办，用Pred()代替，就再也没有犯过这个错误了。 4 我是一个很重感情的人吧，刚来的时候领导对我很信任，一直觉得我做事踏实，然后领导跟我聊天的时候总是说，再给个机会吧？我知道他有苦衷，但是我一则答应了下一家，但是又要辜负现在的领导，所以，走，不走，都是很头痛的。
   今天补了一个邮件，跟领导着重说了下我的苦衷，缓和了一些吧。

你怎么就觉得自己技术一般呢？是你自己觉得，还是别人告诉你的呢？有网络，一切皆有可能。人与人的差别在于有效时间的利用上。虽然我已经不相信励志学了，但是有时候，你得告诉自己，一切皆有可能，缺啥补啥。很多事，你觉得做不到，往往是因为你没有遇到，没有尝试。反正我不相信年龄大的技术就好这个理论，时光易逝，抓紧时间吧。我以前也曾踌躇，犹豫过，不过现在我已经能够珍惜时间，好好利用时间了。这也是我最近真的能做到的。加油。

刚毕业的时候，我觉得无所谓了，甚至洋洋得意的跟06年出来的比年轻。现在突然28、29，一下子觉得时间过得好快啊。能有多少年准备呢？家庭，朋友，社会，无一不盯着你。过了青春年少，只有奋起直追。时间是个盒子，不能盒子太空。

年纪大了确实都好面子，其实这也是中国文化的一部分，中国人从小就被教育不要犯错，犯错了就被长辈否定，长大了就会特别注重所谓的面子了。这时候要想正常交流就得是中国式的交流方法，可是这个搞技术的都搞不了，换个环境吧

自古文人相轻，文中也隐约透着楼主这种心理。希望楼主有自己的大局观，培养容忍操控整合资源的能力，比你说的“技术”，无论在层次上还是能力要求上要求高的不是一丁点。

这几年比较多接触那些做生意的，他们有些甚至文化程度很低，但是他们情商很高，无论是玩世不羁搞艺术的，贪财好色的官员，满嘴义气的江湖人士，文弱好面子的学者，名校毕业生。。。，都能根据需要把不同的人，把他们整合在一起，觉得这才是真正人才，而不是几个腐儒摇头晃脑的争着一些快速过时的“技术”，说的比较直白，楼主勿怪。

在一个公司要注意提高那些能够带的走的技术，重复性的工作或是不通用能力可以少花点时间，好的设计好的代码该偷的就得偷，慢慢形成自己的源码库，这些都是你的资产，工作可以换，但是要在一个技术方向上持续积累

------------------------------------
因为在单位每多玩10分钟，也许回家就会被骚扰半个小时，我们现在能够把家庭和生活尽量的分开，工作就是工作，是养活我们家庭的职业，要对家庭负责的前提就是你要对你的工作负责。
上司交给你不同的任务，就会有不同的意图。有些任务是为了测试或者训练职员而布置的，所以应该加以重视。特别是新职员，更应该引起重视，因为这些都是为你贏得加分的大好时机。有些任务的目的则是为了转换气氛或者奖励业绩优异者，特别是海外出差等安排。有时还会有明知你辛苦却还向你下达任务的情况，以及为了公司的未来而必须要完成的任务。
部下要在上司布置任务时，最大限度地读懂其意图。因为这样才能有成果，并得到相应的评价。如果不知道上司的意图，那么就先去问明白，免得自己误解而导致不好的结果。
在部下看来,上司布置任务非常简单。但事实并非如此:首先要考虑，把事托付给谁做。每个任务的难度都不同，个人的业务能力也不同。同时还要考虑新职员的训练程度，以及接受任务的职员的性格、能力、甚至情绪。
假设上司通过认真考虑后，把任务托付给了李经理。而李经理回答“是，知道了”，那么上司就会松口气，“嗯，果然是李经理。”这样就解决了一个难题。
也许有人会说“我现在很忙,能让其他经理做吗？”这是绝对不行的。 如果这么回答，上司肯定会问：“你到底忙什么呢？”上司会这么认为：“你再忙还会比我忙吗？还有，你算什么，让其他经理做这做那的？你想代替我吗？可恶！”
因此不要以自己繁忙为托辞。如果真的很忙，应该这么回答：“我现在正写A公司的报告书，并帮助张副总监处理相关的业务。如果您的事很着急，请先调整一下任务。”
上司布置任务时，会读懂部下的心思。脸上写着“不想做”的人， 勉强说OK的人，想方设法逃避的人，先接受后又推给别人的人等，回答都千差万别。不管是什么，如果躲不开就用笑脸和积极的心态回答“是，我去做”。反正都是要做的事，积极的部下会给上司更深刻的印象。
但有一点，不要过多地使用这句话，并不是多接受任务就有好处。
从事视频招聘工作多年的资深HR李先生表示：每个公司都有努力工作的人，但很多时候人们对他们的评价并不像他们的努力一样好。这些人大部分都不会拒绝他人，换句话说就是人太好了。但可惜的是，公司并不喜欢一下子做很多事的人。为什么呢？从公司的角度分析的话，他们更愿意均匀分配任务并希望尽快完成，而不愿意看到在一个地方堆积过多的任务，导致拖延整体效率。而且如果那个努力工作的人辞职或者转到其他部门的话，原有部门以后该怎么办呢？
因此，如果觉得自己的任务太繁重，那么就跟上司建议，探讨出合适的解决方案，这也是为了公司考虑。
