* 大学生程序员生涯人物访谈录

被访谈人职位：某公司的技术部经理
访谈内容：

 * 问：平常在工作方面，您每天都做些什么工作？您是否满意这样的工作状态？
        * 答：主要的工作就是软件开发，也就是写程序，不过还有其他很多的工作要做，我们的公司是个做医学影像软件的公司，经常要跟医院打交道，他们的系统出了什么问题的话会第一时间就找我们去管理，有时要深夜打的去三十多里外的地方，为的就是解决一个很小的问题。在公司最困难的时候，就只有我一个人在写程序，很多事情也得我自己一个人解决，有时真是觉得到了四面楚歌的地步，不过我还是坚持下来了。
        *
问：你一天要工作多少小时，你的月薪是多少？

        *
答：工作多少小时？这些我也没有认真地计算，如果闲的话，一天就坐在办公室里8小时就可以了，不过这样的日子是少得可怜，我经常性要加班，因为经常有任务，程序员的性格，就是代码要一气呵成，不然回到家里是睡不着觉的。而且很多时候，老板交给我的任务是我不熟悉的领域，公司就我一个人写程序，我不做还有谁能做。任务是有期限的，我得花大量时间去钻研那门技术，以便能更快地进行开发。那段日子，我一天起码工作十六小时，也就是说，我除了吃饭睡觉外，所有时间都是用于工作，而且，那样的时期经历了很多次。不过，我也算是个厉害的人，很多时候，任务期还有很久才结束，但我已经把程序写完了。有一次，老板让我破解一个软件，给我一星期的时间，我用一个晚上就破解出来了。每当这个时候，老板就拍拍我的肩膀说：“小绝呀，你真是从来没有让我失望。”然后又会交给我一个更难，时间更赶的任务。至于月薪，我都不好意思和我的同学说，现在广州的程序员的平均月薪都有六七千了，我现在都是部门经理了，还三千都不够，不过这主要也是我公司的事。我在这间公司，经历了两个月的实习试用期，两个月的正式实习期，三个月的试用期才转正的，实习期每个月只有250块做补贴，转正后，月薪也只有1500元。另外，无论你怎么加班，都是没有加班费的，老板没有要求加班，但是任务没有加班是完成不了的。我们的奖金，都是在完成了一项任务时发的。记得我第一次拿奖金时，公司还有另一个程序员和我一起做这个项目的，老板对我说：“小绝呀，这个项目里公司并没有赚到多少钱，你在这个项目里贡献最大，所以这次的奖金就只发你一个人了，你不要对其他人声张。”奖金有500元，当时我高兴得飘飘然的，谁知，一会儿后，老板就叫了另一个程序员入他的办公室，跟他说了同样的一番说话。

        *
问：你认为做程序员需要怎样的性格和品质？

        *
答：不要对公司只求太多，要对技术拥有无比的热爱，另外，还要勇于承认错误。公司的另一个程序员，本来也只是早退的一点小事，但是他随便找了个借口推搪，让老板大发雷霆，就把他炒了，从此，公司就只有我一个在写程序了。热爱技术这一点很重要，真正牛的程序员，他们都是热爱技术多于热爱金钱的，虽然我是一个特例，但大多的程序员他们都是付出远大于收入的，他们没什么远大的目标，不断提升自己的技术和向同行吹嘘是他们唯一的目的。如果只想赚钱养活自己，换一份更轻松的工作也能赚到这么多钱。如果我像现在一样用这么多时间来用于研究怎样赚钱和在办公室勾心斗角，我早就财源广进官运亨通了。为什么我还留在这里呢，因为我更喜欢的是写完代码后的那种激动，发现自己技术更进一步的那种激动。

        *
问：你认为学哪种计算机语言更好？用什么工具更好？

        *
答：这是很多计算机菜鸟爱问的问题，说实话，我是很反感这类问题的，无论什么语言，只要能活到现在不被淘汰，那它就有自己的优点，现在JAVA很热门，但是有一大堆的竞争者，就跟大学里的专业一样。想当年的我们，还不是能学什么学什么，精通后才发挥出它们的好处。不过既然你问到，我就认真答你这个问题吧。当时我进公司时，精通的是汇编语言。当时想的是，虽然C语言等其他语言的功能更强大更容易，但从C到C++再到C#，高级语言在不断更新换代，开发人员就得不断地学习更高级、更难的语言才能不让自己被淘汰。而汇编语言，除非微软把他们的操作系统全换了，否则汇编永远不会被淘汰。不过C++也有自己的优点，它更简单，功能又和汇编差不多，开发起来更轻松，比汇编更适合开发大型软件，所以我后来也是花了很多时间钻研C++。总之，语言没好坏，学精才最重要。

        *
问：现在很多毕业生都说现在人才爆满，很难找到好单位，而很多公司却说招不到想要的人才。你是部门经理，也负责过招新人的任务，你对他们有什么看法？

        *
答：当时我是以大学实习生的身份被招进来的，于是老板就认为可以从大学生中招到像我一样水平的人，一直不肯拿出钱来招一些有经验的程序员，所以我在几年的时间里都是一个人在写程序。为什么，就是因为招进来的大学生一个也不能用。那个时候，应聘的一大把，机试就刷下了90%以上，基本没有人能通过面试，就算侥幸能通过面试，也通不过一个月的试用期。他们要不就什么都不会，要不就写的程序有一大把BUG，把他们招进来不仅没有减轻我的工作量，还加大了我的工作量。有个女生声称自己是这个城市里编程最好的人，结果机试时发现她只会Turbo C；应聘者当中有我的同学，他有多少斤两我是知道的，一看他的简历，凡是想得出的计算机语言他都“精通”，凡是常用的计算机环境他都“熟悉”，除了工作经验，他完全符合微软架构工程师的要求；还有的人在简历里一开始就强调他熟悉Office，搞编程的人，熟悉Office是基本要求，如此强调熟悉Office，说明他对他的技术很不放心。真不知现在的大学生在学校里究竟学了些什么。他们总是想着：“我现在什么都不会，等我进了公司，就什么都能学会了”。我们公司都是在任务最赶的时候才考虑招人，那有时间教人啊。就算我教，他们基本没有基础，根本就听不明白我的意思。说大学没有学过没些东西，哼，大学也没有教你们玩游戏，却玩得这么好，老子当年还是自学汇编的呢！说要炒他们，他们居然比公司还牛，说什么“此处不留爷，自有留爷外”，气死我了。

        *
问：在工作上有没有什么不愉快的事？

        *
答：要是说工作上，我倒是没有什么不愉快的事，我是公司中唯一能做产品的人，老板也要让我三分，每次老板让我做一些很难的项目，我反而很开心，我觉得很具挑战性，等我做完后我的技术也上了一大截。真正不愉快的，就在生活上。我的女朋友跟我吹了，我们同居已经三年多，从一无所有熬到了现在，她终于熬不住了。她说：“你比别人多花了三倍的时间和精力在工作上，但别人拿这么多工资，你也拿这么多工资。”我说：“也许我花了三倍精力，也拿不到别人的三倍工资，但是如果我不花这三倍精力，可能连别人的一倍工资也拿不到。”这明显说服不了她，所以她走了。其实这不主要是钱的问题，我们最穷的时候，要用五块钱渡过一个星期。那样的日子也过来了，现在总也比过去好吧。最主要的是我没时间陪她了，我每天工作到深夜，回家后想的也还是工作上的事，经常要出差，一出就是几个月。如果不能用浪漫体贴留住女人，就得用钱留住女人，但我所有的钱就是那么点，所以终还是留不住她。我的老板很抠门，很少提加工资的事，我也不好意思向他要。其实以我现在在公司的地们，我再多要一倍工资老板也不会有异议。其实一开始她愿意和我一起熬，也就是觉得我最终能出人投地，无论熬得多辛苦，她一直都抱着能熬出头的希望的。但熬了三年，她终于看清楚现状，对我绝望了。一切一切，要坚持下去，凭的就是希望，其实，我对我现在的公司也绝望了，这倒不是因为工资的问题，我在乎别人对我实力的肯定，只要客户在用了我的软件后说了声“这个软件不错，能用”，就是对我最大的称赞了。但在女朋友走后我才发现，我最我缺的就是我最不在乎的金钱。我对这个公司绝望了，绝望的不是工资，而是承诺。每次要搞大项目，老板都会拍拍我的肩膀说：“小绝，好好干，如果公司能借着这个项目发大财，年底分你1%股份”，结果项目搞完了，我的股权还是遥遥无期；承诺公司业绩上升就加工资，结果我的工资还是这么少；承诺去北京做项目能有什么什么优异待遇，结果我们去到住民工房，还要自己掏钱买盒饭；对客户也是这样，承诺这样承诺那样，一收了钱就翻脸不认人；最重要的是，老板在我刚进公司时就对我承诺过，一定会用心把公司搞好，把公司搞得越来越火红，结果三年了，我用尽心血为公司干活，公司还是这么小，我的工资还是这么少。

        *
问：你对这间公司感受最大的是什么？

        *
答：我在这间公司里学到了很多东西，如果不是老板在有意无意地逼我，我不可能钻研那些枯燥的类、函数还有各种平台和反编译，爆发出我的潜能来完成那些几乎不可能完成的项目任务。所以说，人的潜能是逼出来的。没有这间公司，就没有现在的我，虽然我决定要走了，但我还是希望这间公司能一路走好的。

        *
问：程序员有“吃青春饭之称”，你对此有什么看法？

        *
答：谁说这是吃青春饭的？这是因为他们不了解，他们认为写程序就是写代码。程序员刚开始时是在公司写代码，但是慢慢你会知道，写程序并不是一辈子都只是写代码。随着你技术的进步，你会慢慢发现，你应该去追求更高的东西，比如软件设计，比如自己创业。我感觉IT这一行是相当广博的，不管你是男的女的，不管你技术是初级中级还是高级，你都能在这行中找到你自己合适的位置，如果你真的用了心了，它带给你的，会是一生的回报。
