* 对中集电商北分公司无能连到张亚峰的投诉
   对中级电商北分公司无能领导张亚峰的投诉

    职场里，有一个普遍的共识——我的领导很无能很傻逼。那么，这句话当然会引起争议了。因为领导毕竟是领导啊！这个说法如果成为普遍共识，那这个圈子的秩序还怎么维持？可是偏偏这种人却如影随形，嘴上总是反复这这样几句话：要反思自己是不是没有用心体会上司的优点；神马不在这个位置，根本不知道这个位置的苦处；神马自我驱动力才是王道；神马要抬高自己认知高度；巴拉巴拉一堆理由。那么我就很好奇了，如果这个领导真的很优秀，手下人为什么会一致吐槽她？如果说是仅仅是因为领导手下人特别挫，特别懒，优秀的领导又怎么会能够忍受？不得不说，优秀真跟职级没有半毛钱关系！！！但是某些小领导丶某些地方区域所谓的负责人（北分张亚峰），哎哟，那家伙就真把自己当回事,领导范做的连自己都能领导了。真的都已经不忍吐槽了，自己做的那些事儿，做的那些决策，用人的方式，怎么让手下人不吐槽呢？所以，我只能说一句，你真的很无能.....送你一句格言：一个众所周知的事实是那些总想统治人民的人最不适合做领导者…任何想让自己做总统的人最不胜任这个职位。 ——道格拉斯·亚当斯
发完牢骚就该说说正事儿了。其实我们发现，越来越多的年轻人（90年的孩纸都已经工作了3年了呀！！！）已经走上工作岗位，这帮人更有个性，更追求自我实现，更追求爽！在这个年代里，领导的个人魅力已经越来越重要了。职业人追求的就2点，要么钱给够，要么干得爽。我们回头看看，真正死心塌地地跟着它人打江山的人，都是目睹过它人的逆天表现才愿意臣服的。我喜欢看NBA，一方面在场上球星们都会抵死相争，但是，另一方面，谁逆天谁牛逼，谁是球队老大，就是拿表现说话。怎么让你的手下觉得跟着你混，有意思，有收获才是王道。这就跟你追求一个姑娘一样，这姑娘对你倾心，一般都是从对你的崇拜开始。做个领导也是，这年头，服务型的领导才是王道。你的下属跟着你混，你（张亚峰）挫到让他们对你无法产生一点敬意，你（张亚峰）又傻到非得自己追究到细节，什么都要横插竖杠来体现自己的存在感，不给大家背黑锅就算了还把责任推给手下兄弟们，自己啥也不懂啥也没体验就直接给大家揽一堆活让大家干，没能力就算了还没脑子，自己干不了还一顿瞎指挥瞎安排。这样的领导，真的是说活该！约翰·昆西·亚当斯曾说过：加入你能用行动激发她人梦想得更多，学习更多，做更多事或者成为更伟大的人，你就是一个领导者。（反之则共勉）
所以，问题出在了这里——有时候，很多优秀的人因为各种原因就得被权高者压着，背起无法翻身的五指山，日复一日后实在忍无可忍，就离开，最后留下一个傻吊独自狂欢（还认为自己保住了那微不足道的职位和权利）。哎继续引用安德鲁·卡内基的依据格言：自私的人或者将一切成果都据为己有的人不可能成为一名伟大的领导者！（没错张亚峰就是一个极度自私自利的小人）
那么，问题又来了——这样的人其实对她（张亚峰）本身来说，她也没有太多损失反正公司也不是她的，工作也不是她干的，有邮件了转发下告知所有人我把工作分配了下面有负责人去干了（我们用你转发吗？你转发的邮件我们也看到了需要你走个过手吗？自己看看你转发的时间里有多少邮件我们已经私自回复完解决掉了，你连已经解决完的邮件还要在转发一下是何居心？不就是想让人家感受你的存在，认为是你把工作安排的嘛！！！），干好了沾点光，干不好别人擦屁股，就算出了问题，最多是绩效少一点，基本工资又不少，也并不会额外扣钱（你永远都只会动嘴，很简单的东西一分钟就可以回复的邮件如果我们不在你都能拖一天？也对你根本就不懂任何系统，你到现在都不知道SF系统的很多用法及后台操作吧）。即使不干了，一堆烂摊子扔在这里，然后去下一家继续混资历。谁知道你在上一家公司具体做了个啥？！别跟我扯什么以前就是什么什么职位，以后想干到多大多大的职位，完全就是扯淡。（你说的这些话你自己信吗也就骗骗自己还可以吧）现在还真有这么一种人外面的做得惨不忍睹的，摇身一变来到我司居然身居高位。（自己的职位怎么来的心里没数嘛，只是徒有凤凰之虚名而已，实体还是一只山鸡）
请问，公司怎么办？
对于这些无能领导，公司该怎么办？
     身为部门的领导者，首先应该严格要求自己，以身作则，这样才能给下属做一个好榜样，从而带动下属的工作积极性，为企业带来高利润和效益，可是你（张亚峰）就是整个北京的麻烦制造终端，没有你（张亚峰）北京不会像现在这样停滞不前，没有你（张亚峰）团队不会濒临溃散，没有你工作不会一团乱麻懂吗？因为你整个北京运维团队每一个人像是一只斗败的公鸡一样无精打采，因为他们每一天所面对的是永无止尽的要求，而没有赞美。（拿运维举例，例如一个点位同时进行安装验收，故障处理，资源盘点，巡检排查，逾期包裹清理五项工作同时进行只让签到一次，多余签到无效，北京点位考核量为日均7个点，根据平均点位处理时间以上工作全部进行按照最低时间50分钟计算，每日最多可以打9个点，在抛出坐车路上时间和出现加急故障需要到达偏远地区一天需要什么样的工作量，北京市六环内总面积1.超过1.2万平方千米，外勤人员12人负责1.2万平方千米是什么概念）。你自己有没有计算过，我们是超吗？能飞吗？不能！！！！只能坐车可是北京的交通全世界都知道堵车情况，这些情况下我们都在尽力克服困难完成任务，可是呢努力的同时我们获得了什么，依旧是不为人意的工作结果，没有人能看到我们的辛苦，为什么?就是因为没有人去真正的为兄弟们诉苦，每天都只会用一张破嘴皮子得啵得啵得拍拍马屁，装装样子。人前人后自己什么样子我想不需要任何人说明什么，为了自己的利益出卖自己的兄弟，为了向上爬不择手段的出卖者多少人，干了多少昧良心的事，承诺了多少无法兑现的假慈悲，张亚峰请你自己好好掂量....
为人上司的人必须要有人性化的思考逻辑，而非只是从结果上去做唯一的考量。再者，身为上司的人在要求他人之前也要思考一下你（张亚峰）到底在他们身上付出了多少教育和培养的功夫，如果你（张亚峰）没有教过，你（张亚峰）就失去要求的资格。你有教育、协助和督导的责任，而非只是要求这么简单而已，因为你（张亚峰）也是责无旁贷的责任者，这一点是不容被忽略的，所以在要求他人的同时也应该是在要求自己才对，这就像是一只刮胡刀广告中的广告词一样 “要刮别人的胡子之前，先把自己的刮干净!”。
还有很多立场于工作的抉择上你（张亚峰）所站的立场一定是以心中坚持在自己是正确的前提上，嘴上总说大家商量商量，有哪一次是真正和大家商量的，还不是自己最后用自己的想法订的（你从来不会觉得你的办法不可行，10多个人都说不行你还认为行，你特么就是个傻吊，继续我行我素按照你的意愿执行），在自我意识过高的状态下，沟通的语言如果失去了对于他人意见的尊重和客观的评估，没有在乎到他人的立场、想法、心情，甚至是难处，那么你（张亚峰）只会引起他人的不悦。而一个环境如果失去了人和的力量，即使争赢了现在，可能也要输了未来，因为任何一个企业策略的推动不是你（张亚峰）一个人就做的到的事，必须要团队齐心协力才能成事，一个推不动的好策略不具有任何的价值，策略的推动需要有共同的愿景，所以古人有云：“欲成就大业，必天时、地利、人和”!你（张亚峰）最大的问题就是在自己的身上而不自知，因为一个无法与上司或是下属达成共识的领导，会在企业中造成相当大的压力，因为他对团队的和谐会生成负面的影响，甚至影响他人工作的质量和效率，毕竟要改变所有人去配合他是一件比较难的事，相对之下要请他另谋高就是一件比较容易的事了!所有的人都有必须要跟你配合的责任和义务。一个好的领导应该就要像大海一样能纳百川，透过良性的沟通和协调来找出最佳方式，要顾及团队内全面的人际平衡，但是如果你（张亚峰）不具备有沟通协调的能力，那么那就是你（张亚峰）不具备的部分，要自我期许让自己成为团队中的助力，而不是成为企业中的阻力。
      你很喜欢习惯性的命令他人：没有人喜欢被人用命令的语言和态度去驱动，即使你（张亚峰）的下属也是一样的，因为那叫做人性，我相信当你（张亚峰）为人下属的时候也会有一样的感受，同样是进行一样的工作，下属可以有心甘情愿的心情和态度，当然也可以有不甘不愿的心情和态度去运行。然而都是一样在运行，一个具有生命力和热情，而另一个却没有。真正要接受对事不对人这样成熟态度考验的人不应该是下属，应该是那些为人领导的上司才对。
  永无止尽的物质欲望：许多人在功成名就时喜欢藉由外在的改变来表现出自己高高在上的优越感，喜欢凸显自己，甚至希望透过这样的改变来引人注意。虽然好的形象对一个领导或者经理是百分百应该要做到的，但是却不需要太过，当然更不能沈迷，因为当心思被外观完全占据的时候，你（张亚峰）大部分的焦点就会从工作上转移到你（张亚峰）的举止上（天天一种高高在上的感觉是不是很爽，以前从来没有体会过，可是你知道你在所有人眼中就是个逗逼嘛，天天牛气冲天的做给谁看。大领导在的时候你咋不这样，你还真是把人前人后展现的淋漓尽致），你真的懂工作嘛你知道什么叫全力以赴嘛？年轻气盛、追求名利的你能有什么作为。我不是君子做不到君子坦荡荡，既然经历过又为何假装看不见，就算是自己离开也要让公司引起重视不要因为一个人毁掉一个团队，或许团队可以重新建立，但是继续如此管理下去怎样重组都是无用功。先不说自己能站在公司层面为公司争取多大的利益，但是兄弟们的血汗不能白流，一个强大的团队不能就这么垮了，人员易留人心难留，人员易改人心难聚，正所谓：当立大权之人，需用心感“官”。对招致祸乱之人，弃或杀之。对大才大勇之人，礼贤而引之。
     最后我想用塔列朗的名言作为我离职的的阐述：我更害怕由1只狮子领导的100只羊，而不是由1只羊领导的100只狮子。 所以本人自愿离职中集电商的大家庭，由衷的感谢中集电商这一年来的栽培，谢谢所有领导及同僚。



                                             离职人：李阳（北京分公司）

                                              2017年3月24日
