* 工作还是Freelance的选择

现在我的每一个决定都非常重要。这就是在岔路口上。

** 工作
工作明显有很大的瓶颈，但是又不能少了这份固定的薪水。
所以就用周末时间投入到Freelance中。这样的话，缺点是：

*** 之前的周末
    看书，游泳，学习，几乎就是这么几点。
*** 加入Freelance的周末
    会忙很多，然后需要从头开始去了解，关键是坚持。

** Freelance

** 成为一个牛逼的人
   通过昨天想到的，如果自己不牛逼的话，好像干什么都不行，也不好搞。
   但是如何成为一个牛逼的人了？和个人的学历，成长经历，工作经历等等都分不开。
   过去的很多事情无法改变，也因为家庭等原因造成的，那么如何从现在开始变得牛逼了？

   从身边的事做起！？
   从每天必须要做的，并且能够产生价值的事情做起。工作。心无旁骛的专研一门东西。
   说白了，我想这么多，就是因为钱给少了，心不定。钱少，但是有时间。如何最大化创造产出你的时间价值？
*** 从工作做起
    使用java语言，如何精通java？
    1. 常用的API，工具类是否非常熟悉，看过源代码，能够自己实现，改进？这是写代码
    2. 除了写代码而外，还需要搞架构设计，如何设计的好，搭建框架等。这是架构
    3. 除了架构，还有项目管理，人员管理，产品知识等。还有UI交互设计等。3里面可能很多东西都搞不来。
       但是可以选择一两个？比如产品和设计。

*** 敏捷开发，快速迭代
    不仅是迭代项目需求，更是迭代我个人的人生目标。
    制定以下计划：
    1. 将常用的JDK相关的API，工具类搞到滚瓜烂熟。
    2. 这个时代竞争真的太激烈了，任何一个领域都有顶尖的人才，他们都是花了大量时间，精力打磨自己的技能，
       然后才能达到现在这个水平。为什么你就认为你可以不花很多时间，精力，力气就能达到他们的那个水平了？
       你是在侮辱别人的智商还是自己的智商？所以，核心概念就是：缩小你的精力范围。认为自己就是一个普通到
       再普通不过的人，或者认为自己是个很笨的人，然后将自己的时间，精力，全部以排山倒海之势push过去。

       或许，你不想这样，或许你认为自己应该成为一个诗人，而不是一个程序员，但是没得很多选择。
       等你强大到一定程度之后，你才有选择的权利。
