* Remote Jobs
** TimeZone
   UTC+2~UTC+4

** Skills Required
   JavaScript, AngularJS, Python and PostgreSQL

** VS Freelancer
Advantages of a Remote Full-time Job Pocket friendly.
There is no commuting so you save on bus fare or gas for your car Absenteeism is at a minimal.
 Even when mildly unwell, you can still get a few things done when working from home No fixed working hours.
You work at a pace comfortable to you It works well with technology

Advantages of Freelance Jobs You can create your own working schedule.
You have the freedom to choose your clients and the type of projects to take up.
 There is no boss to decide which jobs you do or the client you work for.
You can work wherever you want.
With a computer and internet connection, you can work from almost anywhere and for clients in any part of the world.
You are not bound by job agreements that tether full-time employees. You can work for more than one client without breaching contractual arrangements. In most cases there is no revenue sharing. You keep all the money that you have worked for.

Read more at: https://www.freelancinggig.com/blog/2016/02/26/which-is-right-for-you-freelance-vs-remote-full-time-job/

Disadvantages of Remote Jobs
You don’t have any colleagues to interact and socialize with Can easily get distracted by other things.
This can happen when other family members are not cooperative and respecting your schedule.
 It is fully dependent on technology. The internet and related technologies is the mainstay of this occupation.
Without a connection, nothing gets done.
 Internet security risks are a big concern since your system could get hacked and valuable data stolen.
 If you are not self-motivated, you could land into problems with your employer because of putting in fewer hours.

 Disadvantages of Freelance Jobs
Work availability can be erratic with seasons of too much and risk of burnout to times of no jobs and the fear of not meeting your financial obligations.
You have to look, find and convince clients to hire you.
You have to meet your own obligations such as insurance and retirement schemes.
You have to play many roles including prospecting, selling, marketing and advertising your business.
Chances of losing money you have worked for are there.
A client in another location under a different jurisdiction can easily refuse to pay you knowing very well
that there isn’t much that you can do about it.
Related to the immediate above point, the risk of falling into the hands of scammers and fraudsters is high
when working online as a freelancer.
There is a possibility of failing to create a boundary between your own time and work time.

Read more at: https://www.freelancinggig.com/blog/2016/02/26/which-is-right-for-you-freelance-vs-remote-full-time-job/
