* 境外银行卡
  招行香港、工银亚洲、建行陆港通、中银香港、香港汇丰银行、香港花旗银行
  护照（或通行证）和地址证明是必须要的，不要这两个项目的国际卡原则上都不是境外卡。当然还需要身份证，一般还会需要存入1万港币等，具体每家银行不一样。
** 招行香港
   地址：香港中环夏愨道12号美国银行中心21楼）

　　招商银行在香港只有一个网点。
只要前三个月平均余额高于10万港币，之后就可以免去10港币的月费

  如果去香港直接开户，那么可以在官网查看相应的网点，建议先打客服95555转香港业务咨询清楚情况后再去。
  一般情况下，办招商银行香港一卡通需要的材料：招商金卡级别以上卡；身份证有效期6个月以上；
  港澳通行证有效期6个月以上；已经开通招行金卡U盾；地址证明。


  地址证明

不管是国内代办还是直接去香港办理，一定需要地址证明，如果没有地址证明，可能会白跑一趟。地址证明只要水电煤气单、银行账单等其中一项就可以，比如让信用卡寄一次纸质账单。
一般最好同行转账，会便宜一点。
身份资料：身份证、护照/港澳通行证（有效期半年以上，还有那张过关的小纸条也要带着）
地址证明：信用卡账单、公共事业费单等（近三个月的，附有姓名、地址、日期，且要纸质版并盖章）
账户管理费：50港币/月（日均超过10万则免除，选择电子账单形式则只收10港币/月）


主要注意点：

就业情况：根据我多年经验，如果你是金融行业，选择金融/保险，好像审核会更加严格（行业内更容易钻漏洞）....所以我选的是“商业服务”，你们自己按真实情况就行.....
联络情况：正常写（拼音）
银行服务选项：
账单类型：电子
银行卡领取：邮寄
开通网银：是
网上汇款每日最高上限：200万港币（您可以自选）
刷卡消费每日最高上限：50万（您可以自选）
账户目的和理由：
账户目的：自己填写
月均交易额：自己填写
主要资金来源：自己填写

我感觉被那个资料坑了，但是第二天我朋友去开户，填写资料基本差不多，跟柜台说开户理由是“给小孩准备海外教育资金”（他近40岁），就通过了.....所以我觉得可能是“开户理由”说错了，导致开户失败.....

一般周一周五人特别多，周二周三周四认比较少
** 工银亚洲
   尖沙咀东分行，

　　地址：加连威老道94号）

   虽然0资金门槛开户，但是还要带1万港币现金过去，现场激活账户。

开户当中没招行问的那么多，我当时找的借口是“准备账户去国外读MBA”....记得跟客户经理说要开通网银，办好之后马上会给你账号，但是最重要的是“密码器（U盾）”，没有密码器每次汇款必须来柜台！有网银也不能网上转账！所以密码器一定问清楚，当场拿到最好，拿不到要求邮寄过来，否则你这个账户不能网银转账....

另外应为工银亚洲申请太多，现在需要提前一个礼拜打客服预约。
工银亚洲首年免年费，同名跨境划转每次15HKD，建行香港深港通免年费至2018年12月低，同名跨境划转无费用，但是申请非常繁琐，手续时间长。
** 香港民生
