* Life Ana
** 成长
*** 同样 25 岁，为什么有的人事业小成、家庭幸福，有的人却还在一无所有的起点上？
大部分的人生都是从恶性循环开始的，有些轻一点的顶多就是被压抑了天赋，重一点的性格扭曲，都是恶性循环的开始
有的人可以在早期冲破恶性循环，比如中学，高中，突然醒悟，发动自身的能力，把恶性循环强行扭转为良性，从此走上正常节奏的生活。
这些人，就是题主提到的有一部分成绩的人，因为他们从某个时间点开始，人生的轨迹就被他们自行改变了，
也许付出了一些代价，但是从世俗的角度来说，他们还是比较幸运的。
至于另外一部分人，其实还迷茫着哪，既找不到方向也找不到出路，所以他们的恶性循环在持续下去，
生活的希望越来越渺茫，反戈一击的力量越来越差，每天都充盈着绝望感，自然生活的境地也越来越差。
各位，我希望你们无论希望如何渺茫，都不要做一个放弃了挣扎的人，叫你们不要放弃挣扎不是因为挣扎才有希望，
而是因为不停挣扎我们才不会被自己看不起，才不会成为自己眼中的行尸走肉，各位不妨想想看，如果一个人放弃了挣扎，那人生真的就提前结束了。
我希望多年后可以看到大家事业有成，儿孙满堂，最起码能过着自己想要的生活，最不济的，我也希望可以看到大家在绝望当中仍然绽露着乐观的笑容，
以及在黑暗中那双熠熠发光的眸子，折射出人间最自由的执念

** 原点
*** 如何找到你的原点
    1. 请你幻想，当你成为墓地里的那块墓碑的时候，你给世界能留下什么？
    2. 请你回溯，你赚到的第一桶金做的是什么工作，这有可能就是你一辈子的宿命，宿命即原点。
    3. 当你通过上述两点也找不到你的原点时，那么在你50+岁的时候你会理解你的原点是什么。
    但有可能你发现已经偏离你的原点太远，没有回到轨道的机会。
**趋势
*** 拥抱趋势
天地万物之间有一种大趋势，这种人与自然一起造就的趋势是恒古不变的，认识这些大趋势，并驾驭这些大趋势的人必将乘风破凉。
而看清这个趋势的同时还要具备相应的驾驭这种趋势的能力，这就涉及到了技。

人性的丑陋，和自然社会的发生，发展有些事情虽然我们不能预测，但是必然有它爆发的时刻。我们要做的就是找到它，并在它爆发之前拥抱它。

** 认知
*** 正确的认知
要热爱生命，热爱生活，一颗积极向上，热爱一切的心态是最重要的。
一切都来不得半点强求，
所有的行动，成就，是否能够坚持都来源于自己的认知。
只有拥有正确的认知，才能做出正确的行动，不断坚持。

没有人能够救你，没有人能够帮你做决定，没人能依赖，这是对的。
因为有这个想法的起初就已经是错的。
