* 3个年轻小伙 厦门草根创业
　十来年前的时候，三个厦门的草根创业者，站在海峡国际社区的外面（厦门的东海岸的高端楼盘，从最早一期，二期建到现在好像都七期了）立下一个约定，如果日后能有所成就，大家来这里买房做邻居。
　　到了十年后，2013 年的时候，他们兑现了这个约定。（当然，必须说明，这其实并不是他们第一次购房，他们每个人都已经有了其他房产，有的甚至已经购置了多套别墅，但是他们还是决定一起搬到这个小区做邻居）。 听上去像是一个中国合伙人的故事吧。 但要解释的是，这三个人并不是一起创业成功，而是在三个不同的领域创业，各自获得了成功。
　　一个是姚剑军，网名阿飞，他创办的飞鱼科技在香港上市，一个是吴欣鸿，绰号宝马哥，他创建的美图秀秀相信不用再解释，还有一个叫孔德菁，网名丸子，他创建的易名中国是国内最大的域名交易平台，此外新创建云朵科技投入到智能硬件领域，虽然名气不如前两位，但重资拿下迪士尼，漫威，小黄人等版权授权，实力也相当惊人。
　　但是十年前，他们都只是默默无闻的个人站长，盘算赚的钱够不够养服务器。
　　有些朋友知道说我有个神秘的群，里面很多大佬，创业的成功人士，但是他们普遍存在一个误解，以为说，我很有人脉，把认识的很多牛人塞进我的群里。但是错了，实际不是这样的，在十来年前，我创建群的时候，只是对社交网络好奇，那时候有一个概念特别火，叫做六度人际，但是我总觉得这个概念不太靠谱，所以我想做个测试，六度人际是什么不清楚，但是二度人际我是可以自己来测试的，于是我把不同时期认识的不同背景的朋友放在一起，看他们会不会有聚合，有交互，当然，有的人流失了，有的人还在，有意思的是，在这个群里，当时媒体圈的人全流失了，大概是因为，这个群里没有一个是他们认为有价值的人，都是一些草根，整天讲的都是很 low 的一些话题，不过我相信，如果他们知道后来的发展，肯定会后悔退群的决定。 那么十年过去了，这个群的发展远远超出我的想象，就说一个数字吧，平均身价的增幅是 100 倍！ 我没说错，是 100 倍！（可惜我自己远远达不到。） 现在上市公司的创始人和 CEO 有好几个，把公司卖给上市公司的有好几个，从打工到创业估值几亿美元的，即便是继续打工的，这些年来平均年收入跃升十倍也是有的。上面例子提到的三个人，就是在这个群里，属于比较典型有代表性的。这事我也一直思考，是什么魔力让这么一圈人的成功率远远高于行业的平均值？难道我真的有光环加持不成？
　　寻找合理的解释我只总结了两点
　　1、物以类聚，人以群分，这些人没有流失，是因为有共同话题，共同的兴趣，主要是因为价值观相对趋同，简单说就是，靠谱的人喜欢跟靠谱的人做朋友。所以产生了幸存者偏差。
　　2、不同背景、不同领域的人，产生交集后，大家的视野和思考问题的方式都会得到扩展，我相信这一点也非常重要，而其中形成了新的合作机会和互补性。
　　其他的，比如信息的价值和传递，分享精神，其实都可以归并于这两点里。
　　所以，回到创业这个话题，认识最优秀的人，并不是说你要认识很多大佬，但是你应该可以从身边找到这样的人，并与优秀的人多沟通，多交流，那么，怎么判别优秀的人？只说最简单的几个要素。
　　1、对信息的敏锐度和钻研精神。
　　遇到自己不了解但是却非常有价值的信息，这些人会立即记录下来，并随后通过搜索引擎或其他途径获得更进一步的信息。我所遇到的所有成功的创业者，都具有这样的特质。
　　2、担当与责任。
　　遇到困境和挫折，主动从自己身上找原因，找问题，不推托，不懈怠。很多草根创业者早就习惯了在没有钱，没有技术，没有人才的情况下做事情，他们永远不会等待外部环境满足了才动手，而是基于自己已有的资源快速实战，不断摸索。
　　很多创业者，并不是业务发展不起来而死掉的，而是发展到一定阶段，因为某个门槛过不去而死掉的，与其坐等哀怨没有人才，没有合伙人，不如想想自己如何解决。
　　3、对未来保持乐观。
　　十来年前，我其实挺瞧不起那些做投资的，我觉得他们什么都不懂，很多项目都是滥投，看他们投的那些项目各种吹牛，各种不靠谱，我也喜欢写文章冷嘲热讽，绝大部分情况下，我是对的。
　　可是最近这两年，我才发现是自己错了，错的离谱。
　　我们做个最简单的假设，十多年前，投资人投了 10 个项目，其中 9 个黄了，彻底 gameover 了，我嘲讽技能使用了 10 次，其中 9 次证明是我对了，成功率 90%，哈哈，投资人比我笨多了。 但是，投资人这 10 个项目中，唯一投对的那个上市了，拿到了 100 倍回报。整体投资回报率是 10 倍。那么现在，谁应该笑谁是 SB？这个假设其实一点都不夸张，十几年前，百倍回报的项目还不俯拾皆是？
　　中国互联网最初的那些巨头，不论是马化腾，李彦宏，还是马云，乃至丁磊，张朝阳，史玉柱，雷军，我们有一个算一个，第一步走对了，知道未来正确路线图的，有么？一个都没有。
　　所以，既然连那些行业领袖在内，都没有人可以清晰判断未来，那么，不够乐观的人就会失去一切机会。
　　我知道还有一些圈子，从十几年前就天天内部互相吹捧，好像比谁都懂互联网，今天骂腾讯弱智，明天骂百度流氓，然后点评别人说的头头是道，真下水试试？ 然后就开始哀怨，巨头垄断，合伙人不给力，投资人不懂，这个那个全来了，总之，绝对没有自己的问题。 所以，在他们眼里，创业是个九死一生的事情，那是必然的了。
