* 如何学习设计？
** 头脑风暴
   首先要有切入点，也就是最初的问题，解决这个问题，然后由这个问题带出其他的问题。
   我现在要做的事，其实很简单就是一个浏览小说章节的页面，如何让它看起来舒适，简洁，美观。

   首先要关注一下几个属性：
   1. 字体
   2. 行间距，字间距
   3. 字颜色，背景颜色
   4. 文字的排版

   *对，好好看看word中的功能。*

   我们一直在用这些产品，但是对这些产品的功能却熟视无睹，视而不见，
   需要培养敏锐的观察能力，

   字体：那么问题就是：大众最喜欢那种字体，看小说的喜欢那种字体。
   （这里研究的是网站的用户群体，受众）

   行间距，字间距：这个是为了不挤在一起，看起来不那么累。
   那么行间距，字间距设置多少比较好？
   有没一个准则，或者具体的黄金比例？

   颜色：字体和背景的颜色如何搭配了？颜色对字体是否有影响？

   个性化，对，要将自己的小说网站和其他网站区分开来。
   设计（艺术？）最本质上来说应该是传达一种感觉？设计要功能好用。
*** 字体
    字体非常的多，张三，李四都能有相应的字体

    微软雅黑，宋体，仿宋，楷体，
    一套中文字体最少也要有几千个字符，体积为几个MB；
    单单为了浏览网页，开发者不可能让用户去下载字体，只能依靠操作系统的预装字体。

    font-family: Georgia, "Times New Roman",
             "Microsoft YaHei", "微软雅黑",
             STXihei, "华文细黑",
             serif;

1）优先使用排在前面的字体。

（2）如果找不到该种字体，或者该种字体不包括所要渲染的文字，则使用下一种字体。

（3）如果所列出的字体，都无法满足需要，则让操作系统自行决定使用哪种字体。

根据这些规则，font-family应该优先指定英文字体，然后再指定中文字体。

为了保证兼容性，中文字体的中文名称和英文名称，应该都写入font-family。比如，"微软雅黑"的英文名称是Microsoft YaHei。

此外，中文字体的中文名称，以及由多个单词组成的英文名称，应该放在双引号内。

所谓"衬线体"（Serif），指的是笔画的末端带有衬线的字体。
（就是看起来很自然，像手写）
一般来说，衬线体装饰性强，往往用于标题；无衬线体清晰度好，往往用于正文。

微软雅黑的美观度和清晰度都较好，可以作为网页的首选字体。它在Mac平台的对应字体是华文细黑（STXihei）。

冬青簡黑、微軟正黑跟信黑
微軟正黑，是Windows的系統字型，PC用家沒得走。選正黑體原因純粹因為雅黑讀壞眼－字與字貼在一起，讀到眼坦。
信黑，是新秀，柯老師的歐體結構相信沒有人覺得不好讀，加上適當的字間距，待字體修得更成熟時會比冬青更優秀。

草，原来一个字体都有这么多学问。

一些常用字体例子：
知乎之前
font: 13px/22px 'Helvetica Neue',Arial,'Liberation Sans',FreeSans,'Hiragino Sans GB',sans-serif;

font-family: "Hiragino Sans GB", "Microsoft YaHei", sans-serif;

font-family: Helvetica, Tahoma, Arial, STXihei, "华文细黑", "Microsoft YaHei", "微软雅黑", sans-serif;

知乎当前（我采用的方案）
font-family: -apple-system,BlinkMacSystemFont,Helvetica Neue,PingFang SC,Microsoft YaHei,Source Han Sans SC,Noto Sans CJK SC,WenQuanYi Micro Hei,sans-serif;
font-size: 1.2em;
line-height: 1.8em
text-align: CENTER;
background-color: #f5f5d5;

*行距为字号的1.5倍，段距为字号的1倍*

OS X 一直用华文黑体（重组后称「黑体-简」），西文部分很差
系统自带了冬青黑体简体中文，最好的，但是10.6开始
IOS简中字体只有自带的华文黑体（黑体-简）可
对于 Windows：在中易宋体和微软雅黑之间二选一。粗体和较大字号的文本用微软雅黑。没有微软雅黑的系统会回退到中易宋体。
对于 OS X：尽量使用冬青黑体简体中文。没有冬青黑体简体中文的系统会回退到华文黑体。
对于 iOS：系统会自动使用华文黑体。
对于 Linux：尽量使用文泉驿微米黑。没有文泉驿微米黑的系统会回退到别的字体。
对于 Android：系统会自动使用 Droid Sans。

但大字号时如果用的是中易宋体就非常难看了


最后补充英文字体族的名称，也就是非衬线和衬线
*** 中文网页排版
    有2个原则
    行距为字号的1.5倍，段距为字号的1倍
    多给标题 旁边悬浮目录 让文字有条有理。可参考百度百科的做法。（就是加目录）
    文字弹幕？
*** 其他
    OK，关于字体，中文排版什么的搞完了。现在要思考的是外部如何排版。妈的，上班时间很多事情都不能做，我曹。
** 好好想想
   现在的问题是， *排版*
   pdf的可以直接用哪个撒PDFLayout搞出来，然后txt的了？
   txt的貌似可以通过编程来处理啊。仔细观察txt的格式，然后得到相应的特点，然后进行分段落还是换行。

   明天来搞这个事情，今天剩余时间，把那个算法的2章看了。
** 2018-07-31 今日想到的
   首先要思考的是，我们的设计要达到什么目的，传达什么理念，感觉等。
   设计涉及到字体，图形，颜色，材质。主要是视觉上的，使用感受上的东西。

   还要符合用户的使用习惯等，我个人觉得，最好的学习方式是：先做个什么东西？然后遇到问题了，网上找？
   还是说：先刷一遍设计相关的课程，然后开始做东西，边做边复习，练习。

   怎么学？最好还是找个设计的教程？
   还是说直接通过观察，学习来？都不太对，理论上来说：应该先掌握最核心，最基本的一些概念，理解透彻，然后临摹，然后再研究产品，看看别人如何设计的。
   平面设计、产品设计、排版设计、字体设计、用户体验设计
** 其他人的建议
   学习绘画的目的是通过动手实践去锻炼我们的思考能力，刚开始画的不好没关系，重点是带着思考去不断的练习，每一次实践都应该让你感受到自己对物体深层次的理解
   绘画不仅可以帮助你建立原型设计草图的能力，更能增进你界面的排版和配色能力。
   设计中的理论基础包括：字体、色彩、排版等很多方面，
** 推荐书籍
   推荐两本烂大街的书《写给大家看的设计书》、《文字设计的原理》
   除此之外还有很多设计师聚集的网站，比如：Dribbble、Behance、优设网、站酷网、UI 中国等等。
关于临摹的四个阶段

平面设计：
原研哉《设计中的设计》
杉浦康平《造型的诞生》号称平面设计的“葵花宝典”
田中一光《设计的觉醒》
李德庚、蒋华、罗怡《平面设计死了嘛》
李永铨《消费森林×品牌再生--李永铨的设计七大法则》
排版设计杉
浦康平《亚洲的书籍文字与设计》
字体设计
廖洁连《中国字体设计人——一字一人生》
拉斯•缪勒《字体传奇——影响世界的 Helvetica》
崔生国 《文字意态》+《图形语意》 （这两本是我导师出的，值得一看）用
户体验设计诺曼 《情感化设计》Jeff Johnson
《认知与设计》Alan Cooper ，
Robert M. Reimann《软件观念革命——交互设计精髓》


《平面设计法则》

学习三大构成，素描基础，
https://www.zhihu.com/question/21640477
学习平面设计的主要途径是看书学理论，和看视频学软件技法，浏览设计类网站看作品/经验/教程分享，开拓眼界。

【必学】设计基础三大构成（包含色彩构成、平面构成、立体构成）、素描基础（掌握透视原理、光影关系）同时再专研一下色彩搭配、色彩心理学。
【掌握】文案设计/营销知识，各行各业都能综合运用，编写个简单的广告语什么的，都是要会的。
【必学】版式布局、原理（画册、广告、网页设计用得多）掌握版式形成原理、网格设计理论、页面的基本元素类型。
【软件】至少选一个矢量和位图软件学习：CorelDRAW[矢量软件选学]、photoshop[位图软件必学]、illustrator[矢量软件选学]、Indesign[排版软件选学]。

** 资源汇总
设计 /摄影 /图站
创造狮导航
Dribbble
Behance
站酷
设计师网址
牛大拿
UI 中国
字由
MyFont
千库网
摄图网
图虫网
图片压缩
包图网
花瓣
UIgradients
优优教程网
阿里巴巴图标库
EASYICON 图标库
Noun 图标库
TOICON 图标库
WORLDVECTOR
FreeDownloads
ICONFINDER
ICONS8
UEDC
网易用户体验中心
阿里巴巴 UED
阿里巴巴中国站
淘宝前端 FED
腾讯 CDC
新浪 UED
百度 UXC
原型工具

墨刀
Axure
Sketch
Mockplus
XIAOPIN

** 总结
   先入门，掌握最基本的核心概念，术语等，有个基础认知，然后提出问题，解决问题。
先看一本设计入门书籍，然后开始搞搞任务，做小东西，小产品，然后遇到问题记录下来，思考，去书中，视频等寻找答案。

** 设计的学习计划
   不对，还是应该继续写，坚持写完那个红绿指数。
