* 如何学习设计？
** 头脑风暴
   首先要有切入点，也就是最初的问题，解决这个问题，然后由这个问题带出其他的问题。
   我现在要做的事，其实很简单就是一个浏览小说章节的页面，如何让它看起来舒适，简洁，美观。

   首先要关注一下几个属性：
   1. 字体
   2. 行间距，字间距
   3. 字颜色，背景颜色
   4. 文字的排版

   *对，好好看看word中的功能。*

   我们一直在用这些产品，但是对这些产品的功能却熟视无睹，视而不见，
   需要培养敏锐的观察能力，

   字体：那么问题就是：大众最喜欢那种字体，看小说的喜欢那种字体。
   （这里研究的是网站的用户群体，受众）

   行间距，字间距：这个是为了不挤在一起，看起来不那么累。
   那么行间距，字间距设置多少比较好？
   有没一个准则，或者具体的黄金比例？

   颜色：字体和背景的颜色如何搭配了？颜色对字体是否有影响？

   个性化，对，要将自己的小说网站和其他网站区分开来。
   设计（艺术？）最本质上来说应该是传达一种感觉？设计要功能好用。
*** 字体
    字体非常的多，张三，李四都能有相应的字体

    微软雅黑，宋体，仿宋，楷体，
    一套中文字体最少也要有几千个字符，体积为几个MB；
    单单为了浏览网页，开发者不可能让用户去下载字体，只能依靠操作系统的预装字体。

    font-family: Georgia, "Times New Roman",
             "Microsoft YaHei", "微软雅黑",
             STXihei, "华文细黑",
             serif;

1）优先使用排在前面的字体。

（2）如果找不到该种字体，或者该种字体不包括所要渲染的文字，则使用下一种字体。

（3）如果所列出的字体，都无法满足需要，则让操作系统自行决定使用哪种字体。

根据这些规则，font-family应该优先指定英文字体，然后再指定中文字体。

为了保证兼容性，中文字体的中文名称和英文名称，应该都写入font-family。比如，"微软雅黑"的英文名称是Microsoft YaHei。

此外，中文字体的中文名称，以及由多个单词组成的英文名称，应该放在双引号内。

所谓"衬线体"（Serif），指的是笔画的末端带有衬线的字体。
（就是看起来很自然，像手写）
一般来说，衬线体装饰性强，往往用于标题；无衬线体清晰度好，往往用于正文。

微软雅黑的美观度和清晰度都较好，可以作为网页的首选字体。它在Mac平台的对应字体是华文细黑（STXihei）。

冬青簡黑、微軟正黑跟信黑
微軟正黑，是Windows的系統字型，PC用家沒得走。選正黑體原因純粹因為雅黑讀壞眼－字與字貼在一起，讀到眼坦。
信黑，是新秀，柯老師的歐體結構相信沒有人覺得不好讀，加上適當的字間距，待字體修得更成熟時會比冬青更優秀。

草，原来一个字体都有这么多学问。

一些常用字体例子：
知乎之前
font: 13px/22px 'Helvetica Neue',Arial,'Liberation Sans',FreeSans,'Hiragino Sans GB',sans-serif;

font-family: "Hiragino Sans GB", "Microsoft YaHei", sans-serif;

font-family: Helvetica, Tahoma, Arial, STXihei, "华文细黑", "Microsoft YaHei", "微软雅黑", sans-serif;

知乎当前（我采用的方案）
font-family: -apple-system,BlinkMacSystemFont,Helvetica Neue,PingFang SC,Microsoft YaHei,Source Han Sans SC,Noto Sans CJK SC,WenQuanYi Micro Hei,sans-serif;
font-size: 1.2em;
line-height: 1.8em
text-align: CENTER;
background-color: #f5f5d5;

*行距为字号的1.5倍，段距为字号的1倍*

OS X 一直用华文黑体（重组后称「黑体-简」），西文部分很差
系统自带了冬青黑体简体中文，最好的，但是10.6开始
IOS简中字体只有自带的华文黑体（黑体-简）可
对于 Windows：在中易宋体和微软雅黑之间二选一。粗体和较大字号的文本用微软雅黑。没有微软雅黑的系统会回退到中易宋体。
对于 OS X：尽量使用冬青黑体简体中文。没有冬青黑体简体中文的系统会回退到华文黑体。
对于 iOS：系统会自动使用华文黑体。
对于 Linux：尽量使用文泉驿微米黑。没有文泉驿微米黑的系统会回退到别的字体。
对于 Android：系统会自动使用 Droid Sans。

但大字号时如果用的是中易宋体就非常难看了


最后补充英文字体族的名称，也就是非衬线和衬线
*** 中文网页排版
    有2个原则
    行距为字号的1.5倍，段距为字号的1倍
    多给标题 旁边悬浮目录 让文字有条有理。可参考百度百科的做法。（就是加目录）
    文字弹幕？
*** 其他
    OK，关于字体，中文排版什么的搞完了。现在要思考的是外部如何排版。妈的，上班时间很多事情都不能做，我曹。
** 好好想想
   现在的问题是， *排版*
   pdf的可以直接用哪个撒PDFLayout搞出来，然后txt的了？
   txt的貌似可以通过编程来处理啊。仔细观察txt的格式，然后得到相应的特点，然后进行分段落还是换行。

   明天来搞这个事情，今天剩余时间，把那个算法的2章看了。
