* 袁大头被骗记
** 事情的前因后果
   事情的大概经过是这样的，我妈之前在小区附近的幼儿园做厨师，认识的一个同事，有2，3年了。
   然后近期有一天，他给了我妈30个袁大头让帮忙卖，说最低200块钱。
   （如何行文，如何组织文章，问题在哪里？？）

   刚开始的时候，我一听就知道是骗局，我妹夫也劝我妈说了是很明显的骗局，
   然后我妈就拿了1，2个去问小区里面的老头老太婆，然后别人说一摸就知道是真的，
   回来之后和我爸说，然后让我网上查下袁大头的价格，一看不知道，有的拍卖最多卖了几百万，
   最差的也值6，700块钱，我爸妈当时还是不相信。

   然后又去问我亲戚，之前三伯家插秧的时候从田里摸出来一袋子，然后全部5块钱卖了（几十年前的5块钱）
   ，然后我三伯一看就说是假的，我妈还是不信，然后去问我的小姨。
   小姨一听，让她赶紧将东西退给别人，绝对是骗局，然后她们就相互聊天，看各种鉴别的方法。

   这是怀疑阶段，事情的转折是这样。

   我爸妈过了几天去古玩城，然后找到一老板，那个老板说普通的袁大头600一块，带龙的银币1000一块，
   有多少收多少。我爸妈一听，就相信了，这个是真的。

   而且第二天去西丽一个拍卖会，人家告诉他们，都是真的，刚刚拍卖出去的，一个卖了300万。
   回来之后，我一听一看他们的
** 真假袁大头的识别
   其实这东西很好辨认真假，前提是：你见过真的。只有见过真的，才知道什么是j

** 从整个事情得出的教训
   第一点：太相信自己对别人的判断了。
   我妈老在说沈是个傻子，非常倔，而且之前根据沈做的几件事，也发现的确非常傻。
   这个我没什么意见，毕竟一起共事2年多，但是可能别人只是某一方面比较傻而已。

   但是我爸了，就和人家一起吃过一顿饭，然后相处，聊天不到一个下午的时间，
   就老在说这肯定是真的，不相信这个傻子还会骗人。然后第二次沈又背100个袁大头过来的
   时候，还背地里骂别人是个败家子（因为听他说是从家里他老头哪里偷出来的）

   我自己看整个事件就像一场荒诞剧，老头他们骂别人傻，败家子，最好的结果却是自己被骗了。
   自己被一个傻子骗了，自己不是更傻吗？？

   第二点：无论多么理智的人都会被其他人影响判断，特别是哪些你信任的人，与你关系亲密的人
   我一直都觉得是个骗局，但是知道我父母的脾性，他们一个是非常天真，顽固，另外一个是
   自己说了算，她是老大，别人都必须听她的。
   我一直问我老头，你怎么知道是真的？？
   老头每次的回到都是：肯定是真的，肯定是真的，你听这声音，看着包浆。
   要不就是回到：我还不知道？他个傻子还会骗人，如果是假的，怎么会放在这里？
   然后我反问的是：在你没有卖出去拿到钱之前，真的也是假的。即使是假的，只有你卖出去了，
   假的也是真的。关键的要卖出去。

   后来那100多块，我妈问我撒意见，看她那焦急的样子就是得了发财的病，很想一口气全部买下来。
   我当时说：没撒意见啊，肯定是将之前收的那30个卖出去再说啊。你做生意难道不是进了货，卖出去
   之后，再进一批货卖？要是全部都砸自己手上了，那还玩毛啊。连这都不懂。

   第三点：自身贪恋起了，别人说什么都不会信的。
   我没有劝很多，因为很多事情我都懒得管。但是我妹夫，还有我妹，几个亲戚都劝过了的，
   但是不听，主要我们也拿不出非常让人信服的理由。而且我妈200块钱一块买的，你让她破费
   一块出来做实验，她死活不会同意的，她看到的是200块钱。
   而我的认知是这样的：我自己多少水平自己知道，不懂的东西不碰，不属于自己的钱不赚。
   但是属于我的，我就一定要拿，只是自身水平问题，拿多拿少罢了。
   而我爸妈他们是根据对一个人的判断来推测的，很多都毫无逻辑，只是给一些不合理的现象
   找让自身信服的理由。


   所有人都是骗子，


   坚决不打工，为自由而战。
