* 学习理财
  节约开支是非常大的一步。而且我发现学习理财，更多的会接触，思考到商业。

  比如你每天的开销啊，花费啊，然后如果存钱要多少本钱来赚啊。
  还有：办事失败啊，付出的成本啊，打的费啊，精力啊等等

  为什么我了解到这些了？还不是因为马上离职，收入成为很大的问题，
  如何理财，生存下去等等。

  记账
  做预算，
** 如何理财-自我的思考
   我发现阅读资料，看知乎非常的浪费时间，而且没有触及到问题的本质。
   要理财，首先必须的有财可理，工薪族如何积累一笔钱财，这就是首先要解决的问题。

   大多数人月收入就几千块，除去基本的吃，住，交通等开销外，就所剩无几。
   而升职加薪遥遥无期，意外横财更加不太可能（你一直2点一线的生活，蹲坐在办公室）。
   所以，很明显，必须要控制住自己的大额消费，甚至是百元左右的消费。
   没用到，不必买的东西，不要买。

   吃：在家解决。
   住：在家解决，租便宜的房子，但是又会比较远，浪费时间。
   所以，你看，很多事情都是矛盾的，必然有一些成本在哪里，得了一头，失了另外一头。
   所以，这时你的认知就起到关键作用，必然说有人认为每个月多花500块租在公司附近，
   虽然多花了500块钱，但是不用上下班挤公交了，每天来回2个小时上班时间可以用来
   提升自己了，而且走路上下班，爽多了。
   穿：尽量买过季的，质量好，舒适的，不要追求打牌，潮流。

   这是节流的一方面。

   开源，这个真是让人头痛的问题。

   想想你妈，是怎么理财的。
   用钱去赚钱，当年的大学贷款，4年无利率；省吃俭用，口里夺食，攒下的买房钱；

   股票风险较大，期货风险更大，而且这个东西太分散精力，而我现在要做的是：
   学习设计，产品，技术，对商业，经济等有一定的把控。
   所以，宝贵的时间不能浪费了。

   那么理财就到此为止吧，节流是重中之重。
   不去共享办公，太贵；买条mac连显示器的线就行了。
   少买书，必须要看，解决问题时候再买。

   对，成本有很多形式。
   不去刷知乎，刷微信。把那个15W块钱全部买了理财。
   还是先将之前定的任务搞完吧。
** 其他
  69块钱一本书，如果是一天理财，那么就是要69W，如果是一个月就要2.3W，
  如果是一年，就要0.19W？
