* 北京旅游攻略
  交通：购买公交卡，地铁出行最好，打车贵堵
  景点：天安门，观看升国旗，
天安门广场南边的新前门大街，前门大街商贾林立，全聚德烤鸭、都一处烧麦、六必居酱园、同仁堂药店、瑞蚨祥绸布、内联升鞋店、张一元茶庄，还有鲜鱼口小吃，这里是吃货们的天堂，购物的好去处！
** 行程景点
*** D1 5月2号 天坛公园2-恭王府2.5
**** 天坛
     主要看看寰丘坛和祈谷坛就可以了，建议可以从东门进入，距离祈年殿、回音壁和寰丘坛都非常近。没吃的。
     建议从南门进、北门出，这样能够按照圜丘坛、回音壁、祈年殿的顺序参观，以获得最佳的游览体验。
     吃：
     阿兰菜馆，宏源南门刷肉，老磁器口豆汁店，
     交通：
     北京南站14号线-永定门外站换乘8号线-天桥站d出口 花费35分钟
**** 恭王府
     门票：普通40，联票70，建议导游说细节
     交通：天坛东门站5号线-东西站转乘6号线-北海北站b出口
     吃：
     聚德华天烤肉，李记风味美食餐烤肉，同和居鲁菜，日昌餐馆，
*** D2 5月3号 颐和园4-圆明园4
    颐和园主要分为三个部分：万寿前山（以佛香阁为中心）、昆明湖（湖中有一座南湖岛，连接两岸的为十七孔桥）、后山后湖（西段有苏州街、东段有谐趣园）。
    里面非常大也没有任何的代步工具
    带老人参观建议从东宫门入园，参观仁寿殿—昆明湖—十七孔桥—玉兰园—乐寿堂—长廊—石舫—苏州街，从北宫门出，或者从石舫乘船到龙王庙游览后从颐和园南门出，这样最节省体力，逛累了出来可以到苏州街吃美食。

    交通：4号线，北宫门a1出口，1小时
    吃：渝是乎川菜，巴依老爷新疆美食新疆菜，小吊梨汤官府菜
**** 圆明园
     交通：4号线，圆明园站b出口，20分钟
     推荐从南门进入景区（圆明园地铁站下车即到），这样可以先游览十二生肖、西洋楼遗址﻿等最重要的景点，接着沿福海岸向西游览诸多自然景观，最后从西南角的藻园处离开。
*** D3 5月4号 天安门广场1.5 故宫3 国家博物馆2
    先看毛主席纪念堂，再故宫最后广场
    毛纪完事出天安门广场，地下通道走到天安门东地铁附近北边的出口，
    人民英雄纪念碑和毛主席纪念堂，西侧是人民大会堂，东侧是国家博物馆，广场的对面是天安门城楼。天安门广场对面有天安门城楼，可以上去登楼参观。
    毛主席纪念堂周一闭馆，下午闭馆，城楼门票15
    国家博物馆免费，提前预约，要是好好玩需要3-5天,粗略看一下大概3-5个小时(领票+安检大概40分钟)
**** 故宫：
     这里外朝以太和殿、中和殿、保和殿三大殿为中心，内廷主要以乾清宫、交泰殿、坤宁宫后三宫为中心，只允许单线参观，
     门票60+10+10，网上购买，
     周一闭馆，开馆时间8点到12点，故宫后面有景山公园，上午11点到下午3点人最多，带食物
     地铁一号线-天安门东站

     交通：
     洋桥北里坐4号线，北京南站上-西单站转1号线-王府井c1；或公交14路，六部口下，花费1小时
     吃：
     南边的前门大街，全聚德烤鸭，东来顺火锅，爆肚冯，四季明福烤鸭，
*** D4 5月5号 北海公园2-南铜鼓巷-什刹海
    交通：4号线平安里站换乘6号线，北海北站d，35分钟
    吃饭：南铜鼓巷各种小吃，去什刹海可以去烤肉季（价格中上），实惠可以去隆福寺小吃、馄饨候（鼓楼东侧）。
*** D5 5月6号 八达岭长城4小时去，4小时回
     交通：洋桥北里到德胜门：4号线宣武门-转乘2号线积水潭啊出口，50分钟，德胜门坐877，919慢，花费2小时50分钟
     市区的公交是德胜门城楼北侧的877路，一站高速直达，票价12。6：00～12：00。回程末班17：00。
     919路快车是去延庆的，不到八达岭。919慢，沿途要停十几站才到八达岭。
     长城上没卫生间，早上早点出发，逛完去下面博物馆看，
     门票40，老人25，缆车80，往返100，
     吃饭：自带干粮中饭，回市区吃晚饭，
*** D6 5月7号 奥铃匹克公园-鸟巢-水立方
    4号线宣武门转乘2号线-鼓楼大街站-转乘地铁8号线-奥林匹克公园站，1小时
** 美食
   北京烤鸭
   除了全聚德和便宜坊，大董烤鸭和金百万烤鸭店也是北京人常去的烤鸭店
   【老北京涮羊肉】涮羊肉，东来顺
   吃炸酱面排第一的必须是海碗居了，驴打滚，豌豆黄
   4，5月份带口罩
