* Sparkjava教程之todos
  一：TODOS
你自己先想想如何做。
功能：
     生成todos，编辑，根据状态过滤，
     用redis？

     根据状态过滤？？状态作为key？然后todo内容作为val？
     很多个todo的id放到里面去？

     首先生成一条todos：“完成redis教程”，得到id：123，状态是：待完成。
      那么数据结构是：
     todos:123

     todos 123 “完成redis教程”

    先把会搞的搞了，不会搞的放着。
     一个功能一个功能的搞，不会的google搜索，然后学习，学完之后，继续搞，往死里搞。妈个比。

** 功能1
   输入一个字符串，保存到redis中，然后下面刷新。
   主要是这个刷新是怎么做的了？应该是用javascript在页面上添加了一条东西。

   怎么将这个东西返回，然后渲染？？？
   搞清楚问题是什么？用javascript在ul中添加一条

   JAVA每次都要重新部署，启动，真尼玛坑爹。

   现在的问题是：
   1.怎么不让页面跳转？
   2.怎么返回模型之类的？

   *还是得从头开始学servlet和jsp？我RTM的。*
   不对，这里思维又错了！撕逼一样的思维还是认为应该先去学习，等完全，全部学好之后，
   再来干活，解决问题。死逼一样的思维啊。
   *正确的思维是掌握刚刚好，刚刚足够的知识就去解决问题。*


   在学习thymeleaf的时，我不一定非要看教程，不一定非要将教程从头看到尾，然后才开始干活。
   我可以使用 *不断尝试，调整的方式* 直到我想要的预期的效果，
   如果还是一直没到我想要的效果，我会思考一下，为什么不起作用，最后实在不行，我才去看文档，而且只看必要看的部分。
   That's cool!

   搞定。

   下一个问题：
   如何勾选一个checkbox之后，将后面文字加上那个线，并且发起请求？
   问题在哪里？将问题分解，一个个解决。
   checkbox勾选之后，后面的文字加线，并且发起请求？
   我发现每次Google之后，都能在stackoverflow上找到答案，说明国外的学习氛围，方式，就是如此。

   ok，勾选checkbox的事件有了，现在要做的是
   怎么得到这个元素旁边的？Ok，又解决一个问题。

   现在的问题是：
   不要从首页跳转，那么就是form中的action不要直接写url？
   而是使用ajax来发送请求？？？然后将获取的值塞进去？

   他妈的，不对，模板引擎将所有都返回了。
   整个流程还是没搞清楚啊。
   用户访问首页，请求的是/，也就是首页，那么此时，我们就应该将首页返回，
   如果是已登录用户，那么我们要返回他所有的todos，我们只考虑这种情况。

   我草草草，

   如果只用ajax，能做到吗？
   不要模板行吗？？？

   模板的本质是什么？？？
   1.在一个写好的html页面中，我们插入模板的取值代码。
   2.页面发送一个http  /todo/list请求到后台，后台从数据库或者nosql中拿到数据
   3.将 数据和模板文件混合在一起，得到一个完整的html页面。

   对模板就是得到数据填充之后，得到一个完整的html页面。

   那么问题：
   请求首页，得到用户的所哟todos，是什么样的流程？
   那么应该是访问首页的时候，会异步，主动发送一个ajax请求，
   在后台得到所有数据，然后将数据填充到模板文件（这个是只和数据有关的，），
   然后返回一个这个模板文件生成的完整html（其实是主页的一部分）。

   然后用javascript或者jquery将它添加到首页上去？
   看这些东西都没撒用，现在的问题是

   果然没错，都是TM include进去的。

   先把后台程序给它换了。然后再把前台程序给它换了？
   最后给css给他换了。




   问题：
   这里要将id，状态，content全部传递过去。
   先传递，在想怎么隐藏。

     *现在要搞的原则就是粗，快，猛。*
     *下定决心：走全栈工程师道路，学术悟道，*
