* Time Management
** From Wikipedia
   Time management is the process of planning and exercising conscious control over the amount of time spent on specific activities-especially to
increase effectivness,efficiency or productivity.
   时间管理是一项有意计划和锻炼控制花费在特定项目上的时间过程，主要是为了提高有效性，效率性和产出性。
*** 几大主题
    - Create an environment conducive to effectiveness
      - "get organized" -the triage of paperwork and of tasks. 有条理性的，像抢救别人一样的按照先后顺序施加手术样的来完成工作和任务。
      - "protecting one's time" by insulation,isolation and delegation. 保护时间，通过绝缘，隔离，委托。打个比方就是：关掉手机，关掉QQ，微信，将自己关到小房间
        其他事物交代给别人，自己专心做一件事情。
      - "achievement through goal-management and through goal-focus" -motivational emphasis. 通过目标管理和锁定目标注意力获取成就。
      - "recovering from bad time-habits" -recovery from underlying psychological problems,e.g.procrastination. 从坏的时间习惯上恢复过来，比如一些心理上
        的重要问题，例如拖延症。
    - Setting of priorities
      - "Work in Priority Order" -set goals and prioritize. 在任务优先级顺序下开展工作，设定工作目标和优先级。
      - "Set gravitational goals" -that attract actions automatically. 设置万有引力的目标，自动被吸引注意力的目标。
    - Carrying out activity around prioritization
      - ABC anylysis.A重要并紧急；B重要但不紧急；C不重要；
      - Pareto anylysis.This is the idea 80% of tasks can be completed in 20% of the disposable time.The remaining 20% of tasks will take up 80% of
        the time.因此我们应该先做那些20%的任务，也就是要花费80%时间的，因为这些是最重要的。
    - The related process of reduction of time spend on non-priorities 减少那些无意义的活动。
    - Incentives to modify behavior to ensure compliance wtih time-related deadlines

*** 一些方法
    多米诺效应方法：投资一次，却能多次从多个方面获得产出，比如写一本书。
*** 相关概念
    - Project management
    - Attention mangement

** From some websites
   There are only three ways to spend time:thoughts,conversations and actions.

** Reference
[][Wikipaid The Time management]
[][]
