* 边界
  今天我们来讲解下边界的概念。

  我最初注意到“边界”这个概念是看了，别人写的一篇微服务的文章，
  一个事务，在边界上最难处理。后面又看到了edge，这个英文单词，

  edge居然有“优势”的含义，后面我慢慢想，边界，boundary，edge的概念越来越清晰。

  这个概念真的是强大到：无所用，无所不用。
** 用边界来看职业生涯发展
   总是有人焦虑自己的职业发展生涯规划的问题，而每次别人给的答案都是那么几个。
   比如，作为一个程序员的职业发展应该怎么规划？

   那我到底应该做什么了？？？老是牛逼漫天，帮别人解决问题，自己的都没搞定。

   优势
   优势
   优势

   所谓优势，就是比别人有更大的边界，别人不会的你会，别人没去过的地方你去过，
   别人没搞过的你搞过。

   核心优势：
   思维优势

   可行性方案：
   从屌丝培训生到大神？
   创业，做产品，开公司？
   继续修炼，成为一代股神？


** 用边界来看待打工和创业
   为什么有人打工十几年，能力，水平还是一般般；而有的人工作几年，就出任CEO，
   迎娶白富美，走上人生巅峰？

   因为“边界”。
   打工会非常严重的阻碍你个人能力的发展，为什么？
   因为，打工，说白了，就是负责自己的一亩三分地，每天完成重复性的工作。
   本质是：你的能力“边界”并没有扩展，即使再如何牛叉，你也只是在“技术”
   这一个稍大的边界里。

   而有些人，除了敲代码，他还要搞需求，公司却产品，就顶上，搞不定，撒时候
   还做做前端，帮忙招聘下人员，等等一系列看似闲杂人等的工作，他都做了。

   这就是为什么：很多CEO说不要怕苦怕累，怕多做事，因为多做事，能让你的能力边界向外扩大。

   再谈谈创业，这是很多打工族的梦想，因为只会出现在梦中，他们也仅仅只是想一想。
   但是创业非常的艰难，是真的很艰难吗？

   你没看到马云一个有一个公司，瓜子网老总一个有一个公司，史玉柱一个有一个公司？
   这里缺了前提条件，是对于打工族很难！为什么难？
   因为创业的能力边界和打工的能力 *边界之间有巨大的鸿沟。*

   而打工族去创业要做的就是：在钱没烧完，自己没猝死的前提下，一步步跨过这个鸿沟，
   进入另外一个能力边界。

   而之前有成功创业校验的人，他们的能力边界，已经在那里了，所以并不困难，
   有时候遇到的新问题，只是需要换个方向，向外继续扩展。

   所以，我劝想创业的人，“先干成功一件事情”，就是任何一个领域成为很牛逼，
   很有影响力的人，再考虑去创业。


   个人英雄主义；
   想的太多，做的太少，所以我开始写作；
   后续开始做小规模可迭代产品；

** 用边界来看待人物关系
   从普通人，同事，同学这个关系，跨越边界，就成了朋友；
   从朋友这个关系，跨过边界，就成了“情侣”，“知己”；

   任何一次“边界”的跨越，肯定都是通过一件事情，这件事情的能量大到
   一定程度，然后就跨过了这条边界，你们就进入一种更加亲密的关系。

   “边界”的本质就是：从空间的角度来看待问题。

   任何问题，最终都可以转换为：“时间”或者“空间”的问题。
** 获取更大，更好的发展
   思考一个问题？
   我想要获取更大，更好的发展，应该怎么做？
   *尽快，努力的扩大自己的边界。*
   *并且在一个拥有足够大边界的行当里，并且这个行当的边界本身在迅速扩大。*

   先缩小你的边界，让边界中的质量足够高，密度足够大，再向外扩展。

   互联网
   人工智能；
   区域链；


  个人技能：
  独特思维；
  编程；
  炒股，投机；
  写作；
  摄影；

  以上是按照：最硬通货的排序；
  真TM难搞，我草。

  小规模迭代，先弄清楚比特币的大概历史；
  然后再弄清楚大数据招聘的可行性之类的；
  还要学习很多东西，怎么抓网页，出报告等；

  先不要想那么多，先把基础打好，与此同时，写作，锻炼；
  后续，研究这些东西，搞干货出来，分享给别人；
  写书，创造影响力；
  技术过硬，能搞一些可用产品，就发布到开源社区。

  妈的，主要是技术落后太多了。
  但是，你想想，如果你技术不落后，你其他方面，能这样吗？
  会炒股，有这个分析思维？？？

** 分析大环境
   现在身在中国，因此要分析整个中国的大环境，然后了解美国，国际的更大环境，
   记住是，了解

** 使用边界来掌握知识
   我们经常使用到的知识要精通，我们有接触的知识，只需要理解，掌握；
   非常前沿的知识我们需要了解；

   根据知识掌握程度的不同，分配自己的时间和精力，以获取最大化的价值。

   有一次，他上司的上司来到他办公室，对他说“Jim啊，你看现在市场上已经出现了这么多的操作系统，但是还没有一个像样的网络操作系统和数据库系统，如果你真想在IBM做出点成绩的话，研究网络操作系统和数据库系统是很有前途的！”

   Jim Gray有个好习惯，就是经常记笔记写备忘录。
** 学习
   用边界同样能用来解释，和构造高效的学习方法。
   我们都说不要一直看书，要问题驱动，其实这个不太对。

   正确的方法是：以我们目前掌握的知识，提出合适的问题，然后去解决这个问题。
   之后，将解决问题所学到的东西和目前的知识结构链接起来，想象一下，就像水漫金山，
   慢慢的漫过去，侵蚀。

   所以，我在学习前端的时候，都是遇到有不懂的问题，就google，然后查询资料，搞清楚。
   遇到问题一定搞要透彻，不然再遇到复杂的问题时候，知识结构的密度和强度不够，
   中间的缝隙会导致问题无法解决，而且越是艰难的问题，知识结构的缝隙会无限放大。

   很多人，科学家，好像是有灵感，突然解决了某个问题，其实不是，是他掌握的知识结构
   面对当前的问题，还有空隙，所以整个逻辑，推理，思考等的引擎，无法运动。
   直到，他的灵感让它将这个空隙填充了，然后整个知识结构，逻辑链路和思考回路，联通了。
   这时，问题对于他就是轻而易举，易如反掌。

   解决问题，为什么会有快感？
   因为遇到问题，人的整个思维是受阻的，而当解决问题时，整个思维通路都顺畅了。
   这个和便秘之后，然后顺畅的拉出来的感觉一样。

   我刚才好像有想到，关于道和水的问题，水这种物质的特性。。。。do
