* 人生就像打Dota
  这篇文章，我将讲述如何从成为Dota高手中学习到的一些关于人生的道理。
  这些东西可能你在从事某一项你非常热衷的事务，活动时，已经具备掌握，但是你还没有意识到这一点。
  虽然你在此方面能够很好的达成目标，但是如果换到一个全新的行业，你未必就能很快成为高手。

  我希望你们看过这篇文章之后，能够将游戏中所学习到的，总结到的经验用于其他更需要的方面，比如：工作，商业竞争。
** 永不服输
   在将wow九个职业的装备全部刷到顶级之后，在等待WLK的耐心慢慢被耗干中，我逐渐喜欢上了一个叫Dota的游戏。
   几乎每个周末总是我最先起床，匆匆洗完口脸，连早饭都顾不上吃。打开电脑，输入VS账号，进房间排位。
   舍友大多是被我吵醒的，不是被”疯狂杀戮“的声音，而是被我情不自禁，破口大骂的声音吵醒。
   他们经常看到这么一个景象：一个人穿着裤衩，手里猛敲键盘，一边打字，一边还在破声大骂：”一群傻逼，猪一样的，都TM是菜逼。“
   他们经常拿这个取消我，但我毫不在意，只想杀的这群菜逼像龟儿子一样。“近卫菜逼”，“天灾傻逼”我这两个ID可不是浪得虚名。

   虽然我不断被虐，经常超鬼，有时被骂，还经常的不断大骂他人，但是我没有退缩，而是一把又一把的不断战斗。
   而且我喜欢选hard模式，总是坐镇天灾六楼。
   终于在几个月之后，我开始在VS菜鸟房横行无忌，叱咤风云。经常同学喊我：”宋大神，快快快，带我搞2把。“

   想要成为高手，你就要永不服输，不要认怂，面对面狠狠的干他娘的。不要怕输，总结经验，下次再来，直到将他打败。

   但是现实中的情况却是：
   大多数人不是害怕失败，而是害怕失败后承担结果和失去面子。他们输不起，因为他们在乎的太多，看似拥有的太多。
   这样的人永远不会成功。

** 不断学习，实践
   每天我只要有时间，就要上VS去“坚持被虐”，终于在几个月后，我也成为了一名菜鸟房高手，不断虐别人。
   *但是并不是所有人花上几个月时间就能”自动”成为高手。*
   这给了现在的一个流行观点，程序员经常问的问题狠狠的一个耳光。
   ”我工作了多少年，这样的工作经历，薪水应该给多少？“，“只有多少年工作经验，我们公司才能给多少薪水”
   这些都是傻逼人力资源帮老板压榨人力成本的借口。只要你觉得够牛逼，你可以随便开，实在不爽，自己开公司，搞。

   为了早日成为鸟房高手，为了不再被虐，扭转每次只能挨打，各种被喷却不能反喷的情况，我想了各种办法提升自己的技术。

   我去各大论坛，uuu9，nga，贴吧，到处看精华帖子，研究：
   如何补刀，打钱，出装，控线，控符，怎么放技能，怎么走位，团战切入时机，团战站位等等一系列的问题。

   除了帖子，还有各种精华视频，每周的wodota top10都是必不可少的。

   除了以上，我们还会经常组织开黑，开完黑，还会讨论刚才哪里打的不好，哪里打的好等等。

   如果大家都拿出这种劲头出来，干什么事情能够不成功了！？

   虽然这只是一个游戏，但你一样需要不断的学习，练习，并从实战中，从结果中获得反馈，校验你的学习成果是否有效，然后做出调整，
   这样你就能不断总结经验，玩的越来越好，直到达到你当初想要设定的目标。

   现在我有个观点就是：“在任何一个行业，你都要努力尝试成为顶级玩家。”

** 要想成为高手，基础必须扎实
   有人说你这么牛逼，怎么不去打职业了？当时，的确也有人建议或者半开玩笑的说：”你好好搞搞，说不定成为像09那样的大神，以后还能看你打比赛的视频。“
   我当时根本不以为然。一方面，我没有将打游戏作为职业的想法，这会让家里人，亲戚等瞧不起（但是你看现在的游戏主播，各种大神，都是年薪千万）
   第二方面，我知道当你把游戏当做工作来做的时候，就会失去游戏本身的乐趣，它就变成了仅仅只是一份工作而已。

   我们平时也经常看职业选手的比赛，不得不说差距还是很大的。但是我认为只要苦练补刀，走位，这些基本功，然后加上大量不断得高竞争比赛中积累的经验，
   和磨炼出来的意识，成为职业选手也不是不可能。但是看了下当时他们的待遇，的确是太差，太辛苦了。

   在这里，我想说的是：任何行当，你想往上走的话，必须的基础扎实，因为越是基础扎实，宽厚得，越是能够走的更远，爬的更高。
   而所谓的高水平发挥，神级操作在于你对基础知识，基本元素得深刻，非同一般的理解。
   玩游戏之前，你必须对游戏里面的各种装备都非常了解。从最基础的出门装到最顶级的神级装备，都要了如指掌。
   对英雄的技能也是如此，还要清楚英雄的技能如何和装备进行匹配，才能发挥出最大的效果。

   对英雄各方面的成长性，长处，弱点，也要非常熟悉。还有就英雄之间相生相克的道理，装备之间相生相克的道理，都要非常了解。
   这样你才能更好的发挥出一个英雄的强大实力。
** 人的天性和英雄的关联
   为什么有的人总是玩不好某些英雄，而有的英雄却玩的非常好。虽然真正的高手，大多数英雄的水准都是很高的。
   但是他总是有玩的最好的几个和玩的最差的几个英雄。

   我想这可能和他的观念以及自身的个性有密切的关系。
   拿我举例：我总是喜欢玩中单的伪核类英雄，赏金，影魔，屠夫等，很少玩法师类的。这样我能够把握住全场的走势。
   特别是在路人局中，我一般都要强制中单，因为坑爹货太多了，而且即使输了，我一样可以杀到超神，最少自己爽了一把。

   而每个英雄它自身也是有特点的，比如影魔，非常的飘逸，屠夫，非常的恐怖暴力，赏金，非常的猥琐恶心。
   每个英雄都有自己的优点，擅长的一面，但是也有自己的短板，所以如何发挥出一个英雄最大的有点就是一个真正的Dota高手必备的能力。

   所以寻找你自己的才华所在，长处所在吧，然后将它发挥到极致。
** 你必须得有激情
   在我工作多年以后，虽然认知，理解事物的程度，学习掌握知识的能力和速度都比以前提升了很大一个层次。
   但是，如果让我现在去玩Dota，肯定会玩的像一坨狗屎一样。即使我的大脑想玩好它，但是我的内心做不到。

   因为缺乏激情。

   如果在干一件事情之前，只携带一样品质的话：我会选择对这件事情的激情。
   我知道即使我什么都不会，只要有发自内心的热情，就一定能够克服困难，改掉我的缺点，磨炼我的意志。
   如果这种激情能够从始至终的保持，那么我肯定会成功。

   没有激情，最多只能让你完成一件任务，却不能让你干好它，更不可能有让你想去干一件看似不可能事情的想法。
   而现在的那些所谓“主流文化”却在要求维稳，和保持所谓的“中间路线”。

   无论是所谓“主流的东西”或者“流行的东西”，最多只能算作“三流的东西”。这是由二八定律和社会人群结构决定的。
** 打出自己的节奏感
   所谓节奏感，就是对于双方局势有着全面的了解，并且你不因队友的乱指挥，互相埋怨而变得毫无主见，生闷气，
   也不因对面敌人的各种恶心，喷子而受到影响，确切的知道自己在干什么，以及接下来该干什么，不该干什么。
   特别是在极度逆风的情况下，你必须要抗得住压力。

   这一点是我从Dota中得到的最重要的一条经验原则。但也是最难做到的。

   转换到现实生活中就更加困难了，现实中的很多因素都超出了我们的掌控范围，而且局面更加复杂。
   还有一种情况就是你刚开始进入一个狗屁不懂的全新领域，比如：工作，创业，也会变得毫无主见。
   这时，如果你纠缠了自己的感情进去，那么肯定会做出一个非常糟糕的决定或行动。

   保持自己的节奏感的最强大之处在于：
   你永远处在最佳状态，并且能够以自己的行动慢慢扭转局势，也就是局势会被你的节奏感所影响，而你不会按照原有的趋势发展。

   总结来说，就是：永远清醒的知道自己在干什么。
** 从开黑学看人
   我们大学时，经常几个人一起开黑，有个人叫M吧，他总是能够包鸡包眼，但是永远改不了打酱油的个性，对于团队的整体胜利无法起到什么决定性作用，
   有时候，还会发挥失误，坑你1，2次。这种人的话，你可以带着他玩，给他一个打酱油的角色，但是千万不能将重要的任务委托给他。

   另外一个人叫Q，他是好大哥，总是凡事先为他人着想，比如缺肉盾，他就玩力量型英雄，缺辅助，他就玩巫医，冰女，缺控制，就玩潮汐，人马等。
   即使有时候，好不容易选到自己喜欢的英雄，如果大家有强烈要求，他也会更换英雄。除此之外，还有很多。

   这种人可以成为活动的组织者，公司里面的小领导，如果能力得到锻炼，有点野心，能够成就一番小的事业，有自己的一帮兄弟。

   而我了，就是那种总是只顾自己，一路杀人，想玩什么英雄就玩什么英雄，也不顾及团队需要。
   虽然的确是最有水平的，但是却不能经常带领团队获胜。
   有时甚至因为其他人的失误，大骂一通，而有时因为自己的超神表现，轻松赢得比赛，但这更加加深了我的这种观点。
   我这种人，就是非常适合那种，单人作战的项目，比如路人局的Dota，炒股，扑克等。

   不得不说，我这个人还是欠缺领袖能力，虽然个人有能力，但是不能很好的带领团队走向胜利。
** 如何逆袭，翻盘，并一路超神
   这将会在我后面一篇文章中讲到。

   你必须的减少失误。

   你要稳扎稳打，把握住每一次机会。团战要少死，多混人头，混助攻，如果你是后期，就不客气的抢人头吧。
