* How to Read a Book Note 如何阅读一本书 笔记
** 序
*** 译序
   益智游戏这个电影找了看看。
   密尔的自传找来看看。
   如果没有经历这么多年的寻觅与颠簸，发现与失落，我读这本书的感受不会这么深刻。
   （所以可见，实践和阅读思考是相辅相成的。）
*** 序言
    教导年轻人阅读，以最基本的阅读概念来阅读，成了最重要的教育问题。
    （做事遵循最基本的概念，原则行事，但必须建立在对基本概念的深刻理解及灵活组装上。）

    要达到阅读的所有目的，就必须在阅读不同书籍的时候，运用适当的不同速度。
    我们的目标是要读得更好，永远更好，不过，有时候要读的慢一点，有时候要读的快一点。
    （阅读的目的永远在于理解的更加深刻，吸收的更加通透。）

    许多学生进入中学之后成绩很差，就是因为读不懂书中的意义。
    要一般中学生掌握一段文字的中心思想是什么，或是论述文的重点及次要重点在哪里，简直就是难上加难。
    （可见，阅读的最终目的是为了“会意”，而不是死记硬背。而掌握作者传递的中心思想，想表达的观点是最重要的。
    而重点及次要重点是为了表述中心思想最重要得材料或思考。）

    对于复杂的阅读艺术更深的理解与更完整的分析理念；对于如何弹性运用基本规则做不同形态的阅读（事实上可以引申到所有种类的读物上）；
    对于新发明的阅读规则；对于读书应如金字塔——基础厚实，顶端尖锐等等概念。
    （弹性运用基本规则做不同形态的阅读，也就是阅读的核心，本质没有变化，只是方式有所改变。引申到所有种类的读物上，这个就我看：最大的一点就是上网搜索资料。
    多运用规则；这是对金字塔原理在阅读方面的应用，其实金字塔原理非常强大，可以用来解释和运用到很多事物上。后面我会写文章介绍：金字塔原理以及二八原理的运用。）
** 第一篇 阅读的层次
*** 第一章 阅读的活力与艺术

    读书的最要目的是：增进理解能力。

    在某种范围内，知识也成了理解的先决条件。

    太多的咨询就如同太少的资讯一样，都是一种对理解力的阻碍。换句话说，现代的媒体正以压倒性的泛滥资讯阻碍了我们的理解力，他们的目的是：
    让人不需要面对困难或努力，很容易就整理出“自己”得思绪。
    （也就是说现代的媒体最大的问题在于：掐断了你大脑思考，推理得到结论的过程，让你的脑壳装的只是他人的观点，而不是你的。并且我认为不仅仅只是所谓”自己“的思绪，
    给多的是给了大脑更多更大的刺激，像巴多安一样。人们会有更多的”良好感受“，”自我情绪满足“，”获取，懂得了很多知识“，而这些都不过是自欺欺人的幻想。
    （就连”知识“本身也并不那么靠谱），之所以这样，和我们大脑的机制有关系——只走捷径，一切都自动化，习惯化的思维方式（因为现代人面临太多选择了。））

    这些阅读技巧可以应用在任何印刷品的阅读上——报纸，杂志，小册子，文章，短讯，甚至广告。
    （这方面的能力还不太会，因为我从不看报纸，也不看杂志，小册子这种东西没见到过，广告——现代人都麻木了。只有一点：运用互联网搜索知识，看文章，解决问题。）
**** 主动的阅读
    阅读越主动，效果越好，要求的越多，获得的就越多。

    将一个类比的概念往前推（这是扩展思维广度，联结知识，概念的一种非常强大的方法）。

    成功的沟通都发生于作者想要传达给读者的讯息，刚好被读者掌握住了。
**** 阅读的目标
    阅读的2个目标：1.获得资讯；2.求得理解（我个人偏向于2，为什么了？因为现在这个互联网时代，资讯太多了，再者有搜索引擎。人脑的容量无论如何比不上硬盘。）

    真正的阅读是在没有任何外力帮助下，你只凭着内心的力量，玩味这延期的字句，慢慢的提升自己，是对既有理解力得挑战。
    以一己之力来提升自我的过程中所使用的阅读得运作技巧和进行的各种活动，就是阅读的艺术。

    这个作者的水平比读者高出一大截，通过理解作者想要表达的东西，能大大增加读者的理解力，给他全新的或更高层次的启发。这样你才能进步。
    否则，无论是透过演讲或书本，谁都永远不可能从别人身上学到东西。
    （你只能在某方面比你强的人身上学习到东西。如何通过他们的作品跟他们学习，这就是懂得阅读的艺术。）
**** 阅读就是学习
     指导型的学习以及自我发现型的学习之间的差异。

     你记得住的事情就是资讯，你能解释的事情就是获得了启发并理解了。
     要能被启发，除了知道作者所说的话之外，还要明白他的艺术，懂得他为什么会这么说。
     （我现在还没达到思考作者”为什么“会这么说。）

     阅读与倾听是同一种艺术——被教导的艺术。

     自我发现型的学习——严格来说，飞辅助型的自我发现学习—— *是阅读自我或世界的学习* 。

     主动型的阅读必须要思考，除了思考，还必须观察，技艺，在看不到的地方运用想象力。
     阅读的技艺术包括了所有非辅助型自我发现学习的技巧：敏锐的观察，灵敏可靠的技艺，想想的空间，再者当然就是训练有素的分析，省思能力。
     阅读也就是一种发现。
**** 老师的出席与缺席
     阅读与倾听都是想老师学习的方式，两种方式都是在被教导，因此需要被教导的技巧。
     思考如何提出问题？
*** 第二章 阅读的层次
    一共有四种层次的阅读。
    基础阅读层次要问的问题是：”这个句子在说什么？“。要掌握字，句的意思。
    检视阅读强调的是时间，如何在一定时间之内，抓出一本书的重点。
    检视阅读面对的问题是：”这本书在谈什么？“，”这本书的架构如何？“，”这本书包含哪些部分？“，”这是哪一类的书？“。

    分析阅读就是全盘的阅读，完整的阅读，你能做到的最好的阅读方式。做分析阅读必须要提出许多系统性的问题。
    分析阅读就是特别追求理解力提升的。

    主题阅读，也叫比较阅读，阅读者会同时读很多书，并里举出这些书之间相关支出，提出一个所有的书都谈到的主题。
    主题阅读是所有阅读活动中最有收获的，而且可以让你个人做某方面的研究。
*** 第三章 层次一：基础阅读
*** 第四章 层次二：检视阅读
    检视阅读一共有两种，是一体两面的。
**** 检视阅读一：有系统的略读或粗读
     略读或粗读的目的是为了发现这本书值不值得多花时间仔细阅读。

     如何去做？
     1.先看书名页，然后有序先看序
     2.研究目录页，对这本书的基本架构做概括性的理解。
     3.如果书中有索引，也要检阅一下
     找出重要的词汇，并看看引用这个茨木的某几页内文。很可能这几页就是本书的关键点——关系到作者意图与态度的新方法。
     4.有书衣的新书，读一下出版者的介绍
     5.开始挑几个看来跟主题嘻嘻相关的篇章来看
     6.把书打开，东翻翻，西翻翻，念个一两段，连续读个几页，但不要太多。
     留意主要论点的讯号，将自己想成是一个侦探，在寻找一本书的主题或思想的线索。

     检视阅读会让你高兴的发现：节省了更多时间，掌握了更多重点。
**** 检视阅读二：粗浅的阅读
     头一次面对一本难度的书的时候，从头到尾先读一遍，碰到不懂得地方不要停下来查询或思索。
     只注意你能理解的部分，不要为一些没法立即了解的东西而停顿。

     之所以阅读难懂的书很困难，是因为我们大多数人所受的教育，都说是要去注意那些我们不懂得地方。

     国富论中说了一些大原则：关于成本中包含的薪水，租金，利润与利息种种因素，市场在定价中的角色，
     垄断专卖的害处，自由贸易的理由等等。这些只有在通读一遍之后，才能掌握。
**** 阅读的速度
     应该是依照读物的性质与复杂程度，而让你用不同的速度来阅读。

     要了解译本难度的书，其间的障碍，飞一般所谓胜利或心理障碍所能比拟甚或涵盖的。
     之所以会如此是因为：阅读者不懂得运用心智的力量来做这件事。
**** 逗留与倒退
     我们的头脑是个进人的工具，可以在”一瞥“之间掌握住一个句子或段落——只要眼睛能提供足够的资讯。
     （我认为我们之所以会逗留或者倒退到起点是因为，我们太在意个别字，词的含义，而往往在搞清楚了个别字，词的含义
     之后，整个句子，段落的意思却忘记了，导致不得不从头读起。我在看有些生字很多的英文书籍时就会这样。）

**** 理解的问题
     略读一些事实的举证，阐述，而重点在于理解那些表现出深远含义的词汇。
**** 检视阅读的摘要
     更好的秘方是：在阅读一本书的时候，慢不该漫道不值得，快不该快到有损于满足与理解。

     在第一次阅读译本难度的书时，不要企图了解每一个字句。这是检视阅读最最重要的一个规则，也是基本概念。
*** 第五章 做一个有自我要求的读者
    如果你阅读的目标是获得利益——不论是心灵或精神上的成长——你旧的保持清醒。
**** 主动阅读的基础
     一个阅读者必须对自己提出四个基本问题。

     你在阅读时要提出问题——并且在阅读的过程中，你自己必须尝试去回答这些问题。
     1.整体来说，这本书到底在谈些什么？
     你一定要想办法找出这本书的主题，作者如何依次发展这个主题，如何逐步从核心主题分解出从属的议题。
     （这本书在谈我们应该如何主动阅读，运用阅读的艺术，以达到增进自我理解力和个人提升的目的。）
     2.作者细部说了什么，怎么说的？
     你一定要想办法找出主要的想法，声明与论点。这些组合成作者想要传达的特殊讯息。
     （作者细部说了阅读的4个层次，每个层次的作用，如何练习这个层次的阅读。）
     3.这本书说的有道理吗？是全部由道理，还是部分有道理？
     （这本书说的非常要道理）
     4.这本书跟你有什么关系？
     （这本书肯定跟我有大大的关系，因为我就是希望与提升自己的阅读技巧，以达到更高效，更好的阅读，
     大大增进自己的理解能力，以达到自我教育和自我境界提升的目的。）

     任何一种超越基础阅读的阅读层次，核心就在你要努力提出问题（然后尽你所能的找出答案）。这是绝对不可或忘的原则。

     你必须能够以自己的判断来掌握这本书的真题或者部分道理与意义，才算真正完成了阅读。
     在阅读过程中，你要记得去不断提出问题，并尝试自己解答这些问题。要养成这样的习惯。
**** 如何让一本书真正属于你自己
     俗话说：”你必须读出言外之意，才会有更大的收获。“
     此外，我们也鼓励你”写出言外之意“。不这么做，就难以达到最有效的阅读的境界。

     要正在完全有用一本书，必须把这本书变成你自己的一部分才行，而要让你成为书的一本书最好的办法——
     书成为你的一部分和你成为书的一部分是一回事——就是要去写下来。

     将你的感想写下来，能帮助你记住作者的思想。

**** 做笔记的方式：
     1.画底线————在主要的重点，或重要又有力量的句子下划线
     2.在画底线的外栏再加一道线或者花括号————把你画线的部分再强调一遍。
     3.在空白处做重点符号，比如星号————要慎用，只用来强调书中十来个最重要的声明或段落即可。
     4.在空白处编号————作者的某个论点发展处一连串的重要陈述是，可以顺序编号。
     5.在空白处记下其他的页码————强调作者在书中其他部分也有过同样的论点，或相关的要点。
     这样做能让散步全书的想法统一集中起来。
     6.将关键字或句子圈出来
     7.在书页的空白处做笔记————这样可以帮你回想，你也可以用来提问题，或者抒发一些联想到的知识，感悟。
**** 三种做笔记的方法
     在监视阅读中，要回答三个问题：
     1.这是什么样的一本书
     2.整本书在谈的是什么？
     3.作者是接着怎样的整体架构，来发展他的观点或陈述他对这个主题的理解。

     你应该在目录页或者书页来做一下笔记，并将这些问题的答案写下来。
     这些笔记主要的重点是全书的架构，而不是内容————至少不是细节。因此我们称之为：结构笔记。

     监视阅读，不对这本书的立论精确与否，有道理与否下结论，而只是记下作者的观点，我们成为：概念笔记。

     更高层次的笔记方法是：针对异常讨论情境的笔记————由许多作者共同参与的，由你来组织的情景讨论会。这样的称为：辩证笔记。
     就一个单一的主题，把所有作者相关的陈述和疑问全都列出来。

**** 培养阅读的习惯
     （这段强烈建议多次阅读。）
     所谓艺术或技巧，只属于那个能养成习惯，而且能依照规则来运作的人。这也是艺术家或任何领域的工匠与众不同之处。
     要养成习惯，除了不断的运作练习之外，别无他人，这也是从实际去做中学习到如何去做的道理。
     （如果你不去做，你用不不知道如何去做；你不知道如何去做，也就不会实际去做。）

     我们谈到一个有技能的人时，并不是在说他知道该如何去做那件事，而是他已经养成了去做那件事的习惯了。
     当然，对于规则是否了解的足够清楚，是能不能有用技能的关键。
     如果你不知道规则是什么，就根本不可能照规则来行事了。

     严格来说，对艺术家或雕塑家而言，时尚并没有最终的，不可打破的规则。
     （做一个打破规则的人）
**** 由许多规则中培养一个习惯
     阅读就像滑雪一样，做的很好的时候，像一个专家一样，滑雪跟阅读一样都是很优美又和谐的一种活动。

     滑雪的重点在不该讲所有的动作分开来想，而是要连贯在一起，平滑而稳定的转动。
     换句话说，帮你一定要学会忘掉那些分开的步骤，才能表现出整体的动作。但是，为了要忘掉这些单一的动作，
     一开始你必须先分别学会每一个单一的动作。只有这样，你才能将所有的动作链接起来，变成一个优秀的滑雪高手。

     阅读就跟滑雪一样，除非你对每一个步骤都很熟练之后，你才能将所有不同的步骤连接起来，变成一个复杂却和谐的动作。
     这是学校一种复杂技巧的基本知识。一个人只要学校过一种复杂的技巧，就会对一项新技巧开始的复杂过程不以为惧。

** 第二篇 层次三：分析阅读
*** 第六章 一本书的分类
**** 书籍分类的重要性
     规则一：你一定要知道自己在读的是哪一类书，而且要越早知道越好。
     最好早在你开始阅读之前就先知道。这要用到监事阅读的方法。

     任何一本书，如果主要的内容是由一些观点，理论，假设，推断所组成，并且主要目的是在传达知识，那么就是一本论说性的书。
**** 从一本书的书名中你能学到什么
     显然，作者认为，让读者知道它在写的是哪一类的书是很重要的。这也是为什么他会花那么多精神，
     不怕麻烦的在前言中做说明，通常也是这想要让他的说明————至少副标题————是让人能理解的。
**** 实用性VS理论性作品
     实用是与某种有效的做法有关，而理论所关注的却是去明白或了解某件事。

     明智的行动就是来自至少。

     有些书或有些老师，支队他们要传达的知识本身感兴趣。
     而其他的人的兴趣则在：哪些知识能帮忙解决实际的生活问题，他们也传递知识，但强调知识的实际应用。

     要让知识变得使用，就要有操作的规则。我们一定要超越”知道这是怎么一回事“，到明白”如果我们想做些什么，应该怎么利用它“。

     康德的《纯粹理性批判》找来读一读。

     首先，你要学习去怀疑一切。
**** 理论性作品的分类
     照传统的分发，理论性的作品会被分类为历史，科学和哲学等等。

     历史的本质就是口述的故事，是发生在过去特定时间，特定地点的时间。但是经历过时代的不同的历史家的演变。

     科学寻求的是定律或通则。

     哲学比较像科学，不像历史，追求的是一般的真理。
     如果一本理论的书所强调的内容，超乎你日常，理性，正常生活的经验，那就是科学的书，否则就是哲学的书。
     哲学家提出的事实或者观察，不会超越一般人的生活经验。

     缺少有某些非常重要的问题，一个懂得如何利用人类共通经验来思考的人，可以坐在摇椅上就想出解决的方案。

     历史，科学或哲学课，老师会用不同的方式来讲课，他使用的词句，讨论的方式，提出的问题，期望学生做出的答案，
     都会表现出他隶属的是哪个学科。
     （针对不同的形态，使用不同的方式）
*** 第七章 透视一本书
**** 结构与规划：叙述整本书的大意
    每一本书的封面之下都有一套自己的骨架。作为一个分析阅读的读者，你的责任就是要找出这个骨架。
    （我们之所以要找出书籍骨架，是因为这样能帮助我们更好的理清知识的脉络，将核心的东西内化。
    这样我们在以后回想，调用知识的时候就能够顺着脉络寻找）

    知道掌握一本书的架构是绝对需要的，任何一本指的读的书，都会有一个整体性和组织架构。
    （并不完全只是书籍的这样，任何稳固，有价值的事物都会有自己的整体性和组织架构，大到包括一个公司，小到一个人的日程事务。）

    分析阅读的第二个规则：使用一个单一的句子，或最多几句话（一小段字）来叙述整本书的内容。
    （这就是将书读薄了，然后内化成一句核心，规则，观念。）

    分析阅读的第三个规则：
    将书中重要篇章列出来，说明它们是如何按照顺序组成一个整体的架构。
    （这个过程不仅能帮助你阅读，更能帮助你写作。整个过程是：我们将书的整体切割开来，就重避轻，然后在将它们按照顺序组成起来。
    这样你就知道，如何分解，并重新组织，架构你的整本书，整个知识体系，逻辑架构。）

    人类所知的物质，或人类的产品中，没有一样是绝对简单的。所有的东西都是复杂的组合体。而且它们的各个组成部分是有机的。

    可读性最高的作品是作者达到了建筑学上最完整的整体架构。最好的书都有最睿智的架构。
    （可以看见，写出一部好的作品和搭建一个好的大型程序的软件架构是一样的道理。）

    譬如柏拉图说的，舞台使年轻人腐败堕落，或是早期教会里的神父所说的，戏剧是肉体和魔鬼的诱惑。
    （这点不太明白，但是看看现在的年轻人喜欢看的好莱坞大片，和香港的金瓶梅之XXX，可见一斑，都是获取一种感官上的刺激）
***** 驾驭复杂的内容：为一本书拟大纲
    第三个规则要求我们将一本书最重要的部分照次序与关系，列举出来。就像是哥哥部分自成一个整体，各有各的整体性与复杂性。

   规则三的公式：
   将一本书不断切分成更加小的却有机的整体，我们以《如何阅读一本书》举例说明：
   本书分成了4个部分（4篇），
   第一部分讲述了阅读的层次问题，
   第二部分讲述了分析阅读，
   第三部分讲述了阅读不同种类书籍的方法，
   第四部分讲述了我们为什么要阅读，阅读能够带给我们什么益处

   第一部分又分成了4个部分（章），
   一之一讲述了阅读的不同类型，为资讯，为理解，以及阅读的实质就是学习。
   一之二讲述了阅读的4个不同的层次，每个层次间不同的区别与联系；
   一之三讲述了基础阅读，也就是会看书识字；
   一之四讲述了检视阅读，怎么样去做，以及为什么要做检视阅读；
   一之五讲述了为了更好的阅读效果要做一个主动型的会习惯性提出4个问题的读者；

   后面的以此类推。。。

   除非你遵循规则三——要求你说明组成整体的各个部分——否则就没有办法有效地运用规则而——要求你作全书的重点摘要。
***** 阅读与写作的互惠技巧
      写作和阅读是一体两面的事，就像教书与被教一样，目的都是为了让读者或学生找出重点，掌握整体的架构。

      对一本书来说，血肉跟骨架是一样重要的。书，真的就跟人或动物是一模一样的。血肉，就是为纲要所做的进一步详细解释。
      血肉，为全书增添了必要的空间与深度。
      （单纯只是有骨架是不行的，必须要形成一个有机整体，然后发挥某些功能，比如一个人，骨肉之间是要相互依附的）

      这两个规则不但可以用来阅读一整本论说性的书，也可以用来阅读其中某个特别重要的部分。
      （这里运用的方法就是分解与递归。）

***** 发现作者的意图
      分析阅读的第四个规则：找出作者要问的问题。或者要解决的问题。
      （这本书要解决的问题就是：如何阅读一本书，如何从较低的层次进化到较高的阅读层次，
      如何通过阅读来做研究，解决问题，提升自我心智的成长。）

      以上就是分析阅读的第一个阶段。
*** 第八章 与作者找出共通的语义
    第一个规则，找出共通的词义。

    在任何一个成功的商业谈判中，双方找出共同的词义，就是达成共识，通常是最后一个阶段。

*** 第九章 判断作者的主旨
*** 第十章 公正的评判一本书
*** 第十一章 赞同或反对作者
*** 辅助阅读
** 第三章 阅读不同读物的方法
*** 第十三章 如何阅读实用型的书
*** 第十四章 如何阅读想象文学
*** 第十五章 阅读故事，戏剧与诗的一些建议
*** 第十六章 如何阅读历史书
*** 第十七章 如何阅读科学与数学
*** 第十八章 如何阅读哲学书
*** 第十九章 如何阅读社会科学
** 第四篇 阅读的最终目标
*** 第二十章 层次四：主题阅读
*** 第二十一章 阅读与心智的成长
*** 附录一 建议阅读书目
*** 附录二 四中层次阅读的练习与测验
** 其他感想
   阅读也可以用来上网
   阅读整个是研究问题，解决问题的方法。
