* 交友征婚启示
** 自我介绍
   我是宋鑫，生于1989，家乡湖北武汉，农村长大，目前居住于深圳。
   2012年毕业于长江大学计算机科学与技术专业，现在中集电商做软件架构师。
   家庭温馨和睦，父母都是通情达理之人。家中还有一个妹妹。
   身高178cm， 长相见图。

   本人兴趣爱好广泛，
   热爱思考，喜欢看书，目前看的少了，开始直接观察，思考，实践。
   平时喜欢做点笔记，写点文章，扩展下思维和点子，想法。
   本人无微博，不微信，无聊时会刷下知乎。

   喜欢独自旅行，摄影，如果你想找个"自己家"会摄影的男朋友，那就对了。
   热爱听音乐，杂食性动物，近期在考虑是否烧个耳放，对流行音乐，各种X星无感。
   玩过魔兽世界，打过Dota，都是被人抱大腿的。
   之前还打过一段时间德州扑克，炒过3年股票。
   目前几乎什么游戏都不玩，平时就看书，游泳，去公司加班。
   之前，还三三五五的和朋友，同学吃饭，打球，唱K，爬山，次数多了就没劲，不刺激。

   本人性格：
   为人真诚，做事有原则，足够锐意，不太会说话，有点慢热，思想独立自由。
   对他人足够包容，但是感情上传统守旧。
** 说说我这个人
   先来说收我这个人，思维异于常人，这可能是那段投机的时间对我的影响，
   不过，自己也不觉得如何不好，只是对大众说的很多东西，观点，不敢苟同。

   心地善良，人品真诚，只是我这人说话从不顾忌他人感受，
   所以有时候，可能一句话会把你气得半死，因此强者才能与我为伍。

   我这人慢热，不太会哄女的开心，也没那个闲情，功夫。
   要知道，时间宝贵。
   更加不会追女人，认为2个人最重要情投意合，其他的没什么意思。

   本人传统守旧，所以希望另外一半最好是大家闺秀，或者小家碧玉。
** 心中的她
   1.善良
   2.不做作
   3.性格或温婉，或俏皮，但要能干
   4..长相至少要顺眼，身材高挑，带点肉的最好，年龄比我小
   5.内心要强大，最少能抗住我不时的口出狂言，甚至能反驳，PK的最好

   第三：千万不能做，一做就死，所以把你那嘟嘟的嘴唇和猫嘴的头像，
   还有各种不知道是几次元的东西收一收，你们难道不知道这都是非常明显的性暗示。
   如果有不懂的可以问我，我解释给你听。
   第四：
