* 发现 收藏 分享 讨论 创造
  整个社区就是包含一个高质量的，精英团队的分享，讨论社区。
  整个流程，或者说初衷是：每个人在有限的一生，能够接触到的东西都是有限的。
  然后我们将自己有限接触到的，有价值的东西共享出来，然后让用户二次打分，

  搜索引擎的问题在：我们只有在遇到一个问题之后，才会进行相应的寻找解决方案，解决问题。
  而如果有这个网站的话，我们就能看到所有自己感兴趣的东西了。
  而且这个完全是一种人工的评价，推荐系统，因此更加进准，更加匹配。
  这个系统最核心的是广播价值，交付价值。
  互联网有太多好东西，但是被堙没了，我们需要把它们挖出来，除了互联网，还有很多古典书籍，音乐，电影等等。
  感觉这个就是和我的价值观，和我本人喜好的东西匹配啊。

  整个应用的缺点可能是没新内容产生，小众的东西？不对啊，智能推荐这是每个人都需要的，但是针对的是中产，精英啊。
  这个应用完全是反潮流而动，像微博，抖音，微信等，是适合大众的娱乐，我们就是追求实力，追求XX的人。
  用户必须要有准入门槛。后期可能也不打算放开。（原来所有这些都来源于我每次听音乐等遇到非常好听的东西，没人分享。）
  还有一个非常重要的是：最后落足与一个创造社区，比如用户产生的文章，图片等东西会推荐给所有人。

  我这个网站不做热点，不做流行，只做精华，就像古典音乐，经典文学作品类似的东西。
** 分享
   将所有好东西，高价值的信息的东西进行聚合。用户产生，大家评价（当然这里有相应的权重，算法）
   在网上或者哪里看到一篇文章，经历某些事情，你就可以马上进行实时进行分享，然后有chrome插件，可以进行 *收藏* 。
   不对，chrome插件可以喜欢，评分，收藏，分享。
   然后其他用户进行二次打分
** 推荐
   根据你喜欢的文章，喜欢的图片，电影，甚至物品，零食等等进行用户画像，如果你喜欢了某篇文章，可能会推荐给你某部电影。
   或者说，当你想玩游戏，想看电影的时候，直接来这里，系统会运用大数据的方式，给你推荐相关喜欢的东西。
   还有就是，根据你喜欢的东西，给你推荐相似的人，然后可以相互关注，关注后，能看到他喜欢，收藏，分享的东西等等。
   然后还能像github那样搞一个在线聊天室，进行陌生人的相互聊天。（聊天室是一个较重要得功能。）

   还能像他提问，我们倾向于帮助和我们类似的人。
** 用户体验
   从哪里入口？
   评论系统必须做的非常的好，最好类似github的issues这种，可以写长文，也能写短文，最后也是通过算法进行一个排序。
   最关键的是，分享高价值的东西，比如文章，然后有一个非常好的讨论系统（讨论，评论机制必须重新设计）。
   让用户产生数据，分享，让用户来评价，用户来消费，就是一个自我供给的系统，自我进化，循环的系统。

   然后，先分类别，根据传播介质，文字，图片，视频，声音等。
   文字里面分词句，文章，小说等。
   之后再根据业务类别分，比如创业，比如it，比如设计等等。
   然后下面在是有标签，但是每个东西的标签不能超过3个。

   得分越高，停留的时间越高，然后还有各种排序，得分，时间，最后回复等等。
   可能会搞些活动，比如回到大型机时代等等。
*** 形式和入口点
    入口点的话，我想到的就是类似hack news的东西，标题，url，剪切一段或者总结一段文章核心的东西，加上一段评论。

** 技术实现
   首先政治，色情等这些信息必须得进行过滤（关键字，内容评判等）。
   再次对垃圾评论机制考虑，再就是用户权限，权重的设计。比如来的早的，比如贡献多的人，比如获得赞多的人，他们的权重会高些。

** 推广运营
   这块感觉是重点啊，到处发帖?

** 人的要素
   人物画像，性格分析，人生规划，职场规划，指导，缺点等等。
   我们是由我们拥有的，喜欢的，讨厌的，经历的东西所定义。
