* 索罗斯语录
过去四十年，乔治·索罗斯旗下的量子基金获利高达396亿美元，称他为史上最成功的一位对冲基金经理也不为过。
他为什么能长期保持佳绩？有什么成功的秘诀？投资者可以从他身上学到什么？他的成功是否完全不可复制，只是因为他拥有难得一遇的天赋和机遇？和巴菲特一样，多年来，说起索罗斯的辉煌战绩总少不了提到这些问题。
本月12日是索罗斯84岁的寿诞。《爱尔兰时报》借此机会再次回顾索罗斯的投资经历和相关报道介绍，华尔街见闻从中归纳了以下索罗斯的招牌绝技：
     · 卖空
永远不要靠市场走高获利，索罗斯早就是卖空的高手，卖空就是要押注市场会下跌。上世纪70年代，全球股市大多低迷，市场中性策略帮助索罗斯逆市狂赚，十年里回报率超过4000%。
索罗斯最为人所知的莫过于1992年9月狙击英镑。这场做空大战预计让索罗斯收获了10亿美元，也让世人永远记住了这个“打垮”英国央行的金融大鳄。
本世纪金融危机导致全球经济恶化，大多数投资者损失惨重，此前已宣布退休的索罗斯在2007年重新坐镇量子基金，当年的回报率就达到32%。
近几年日本央行大力推行货币宽松，索罗斯也没错过日元贬值的机会。去年，索罗斯旗下基金做空日元预计斩获盈利10亿美元。
本周华尔街见闻文章提到，递交监管机构文件显示，截至今年第二季度末，索罗斯旗下基金管理的标普500空仓占比飙升至16.65%，前一个季度比例只有2.96%。这是索罗斯豪赌美股崩盘的迹象。这次索罗斯会不会又押对宝？让我们拭目以待。
     · 逆势而上，出手谨慎
索罗斯愿意和市场共识观点对着干，所以常被视为逆向投资者。他本人也说过，反潮流而行之有快感。
但他同样承认，自己逆向投资非常谨慎小心，因为那么做可能就被市场走势无情地踩在脚下。
而且索罗斯认为，大多数时候，趋势是好朋友。在他执笔的《走在股市曲线前面的人：索罗斯》（Soros on Soros: Staying Ahead of the Curve）一书中，有这样的句子：
只有在趋势有变的转折点出现时，追随趋势的人才会受伤。
     · 明知有泡沫也要买入
索罗斯不但会谨慎地和趋势对着干，有时也乐于加入其中，即使是经济角度看并不可取的趋势，也跟风买入。
2009年，索罗斯说过：
我看到在形成泡沫，还会冲上去买，火上浇油。那可不是脑子发昏不理智。
黄金就是近年的好例子。2009年，金价猛涨40%。第二年年初，索罗斯称黄金是“终极资产泡沫”。很多评论家认为，索罗斯这么评价说明他认为金价要跌了。
可实际上，在金价涨到大约每盎司1200美元时，索罗斯还在买黄金。这也不难理解，因为只要及时出手，在泡沫时期买入也可以大赚一笔。
索罗斯也确实是这么做的，2011年初，他抛售了持有的大部分黄金，那时距离金价在突破每盎司1900美元见顶后泡沫破灭还有大约六个月。
     · 反射性
索罗斯认为，驱动有效市场的不是理性的投资者，而是易错性和反射性这两大同时存在的力量。
具体来说，市场可以影响投资者期待的事件。不能把市场情绪和经济基本面分隔来看，因为市场情绪其实能形成和改变经济基本面。
看涨的情绪可以推动市场价格上涨，涨价又会产生财富效应，促使消费者愿意增加开支。
反之亦然。负面的情绪同样最终会影响消费。投资者的看法影响事件，事件反过来影响投资者的看法。这种投资者与市场的相互影响就是索罗斯所说的反射性。
他说，观念与现实之间双向的反射关系最初可以自我强化，自然而然地越来越强，最终会变成自我毁灭的过程，也就是从繁荣到泡沫破灭。
     · 动物直觉
索罗斯的儿子罗伯特透露，影响他父亲交易的因素不只是反射性。他说：
“你知道，他改变对市场的态度或者其他任何改变都是因为背痛在折磨他。和别的什么理由都没关系。如果他感觉背部痉挛，那就是提前警告的信号。”
索罗斯承认很依赖这种“动物直觉”，说突然疼痛往往是自己的投资组合出了问题的信号。
所以，他的决策其实是理论和直觉共同的产物。
     · 大手笔押注
Stanley Druckenmiller上世纪90年代曾为索罗斯管理资金。这位基金经理在1992年就提出了做空英镑的点子。可那时索罗斯不同意，说要稳扎稳打建仓。
用索罗斯的话说，如果赢面对你有利，你必须来一笔大的，“命中要害”。
Druckenmiller说，他向索罗斯学到了很多东西，其中最有意义的一点是，对错都不重要，关键是弄错的时候你损失了多少，判断正确的时候又赚了多少。
Druckenmiller还说，用大量杠杆获利需要勇气。在索罗斯看来，只要押对了，赚多少都不嫌多。
     · 承认错误
2008年，索罗斯说过：“我富有只是因为我知道自己什么时候出了错。”他还说，承认错误让他在市场中幸免于难。
这方面的例子也有一些，比如1987年的黑色星期一、1998年投资俄罗斯损失数十亿美元、2000年3月互联网泡沫。
最近的一次重大损失发生在2008年，那年3月贝尔斯登的股票以每股2美元价格被摩根大通收购。而之前索罗斯投资贝尔斯登的买入价是每股54美元。
不过，这些打击都没能真正击倒索罗斯，他每次都很快东山再起。
Druckenmiller这样评价索罗斯：
“他不在乎交易成败。他是我见过最善于挽回损失的人，是那种可以轻易走出困境的人。”
索罗斯的哲学思想无疑对他这种韧性有帮助。他说：
“对别人来说，犯错可耻。对我来说，认识自己的错误是值得骄傲的。只要我们认识到，人类的理解不可能无可挑剔，那犯错就没不算羞耻之事，没能纠正错误才是该羞愧的。”
     · 无法效仿
如果学习巴菲特的长期价值投资方式，一些投资者可能取得不错的成绩。但普通投资者要是想模仿索罗斯投资，那只能落得失败收场。
不管是卖空，还是泡沫时买入、大规模押注，都不是符合常规的做法。
索罗斯堪称超级投机者，他思想灵活，对市场的态度变化也快，他对市场时机的把握是由平生市场历练而来。
私募巨头黑石的副董事长Byron Wien是索罗斯的朋友。索罗斯曾经问Wien，明明有些日子做了工作也是无用功，为什么每天都要工作，难道有什么特别的用意？
Wien回答他：
“乔治，你我有个不同的地方，你知道哪天工作是做有用功，我不知道。”
