* 五年程序员生涯
2012年6月毕业，到今年2017年6月，就是工作，毕业整整五年了。回过头来，发现自己走了很多弯路，甚至可以说是坑。

### 大学期间 ###
高考的失利，随便报了一个够分数线的二本院校。大学期间，完全是自暴自弃，但是还有魔兽世界，DOTA天天打。四年期间，挂科无数，
临到毕业还要交钱去补考，考足学分，换取一张文凭。

后来发现这张文凭是找工作的必要条件，而非充分条件。在实习期间，深感一无所知，面临毕业找工作的恐惧，在坑爹的亲戚介绍工作失败后，
在楼梯间痛哭流涕，求着家里人给报了培训班。

辛苦的几个月培训后，虽然对JAVA编程还一知半解，但是一般的面试题都能够回答了，不会的也能背下来了。跟着老师做了几个之前培训被做烂了的项目，
面试时相对于其他一无所知的毕业生，优势还是明显的。后来有几个offer都普普通通，刚开始撒都不懂，就选薪水最高的。武汉给的offer最高的3000RMB/M。
最后选择了中国安防。

### 工作期间 ###

第一家，中国安防，这是一家非常大的类国企氛围的民营企业，各方面都非常正规。一去，我们就进行6个月的封闭式岗前培训，期间，食宿方面非常满意，
生态农场的豆浆甜的让我现在还很怀恋。也认识了很多有趣的同学，度过了一段青春飞扬的日子。
但这个公司太闲了，根本就没有一个称得上是项目的项目。最初接触的金蝶ERP二次开发，真TM痛苦，代码撒的写的乱七八糟，全部封装到jar里面去了，定义暴露
出来的接口也非常的烂，反正最后这个项目不了了之，我们那个软件集成部门都被干掉了。我们几个新人被划分到另外的一个部门去了，我们这群累赘不怎么受待见。

在这段工作期间，也没有好好学习，当初培训学习JAVA，完全是为了找个饭碗，对编程谈不上说热爱。后来实在被逼的没办法，就开始复习，投简历，最后找到一家公司，
薪水给的够多6K（当时对我这种拿着3900工资，不会撒东西的人，感到好多啊。）当时，对选择工作什么的，或者说工作是怎么一回事都稀里糊涂的。临走时，最后一个
月的工资还给我扣了好多，我真RTM，本来就没多少工资的。这事提醒我，做撒都要好聚好散，搞好上级，同事间关系，不会有害。

第二家，是一个主要做短信方面服务的公司，维护这一个非常古旧的短信系统，主要是提供给东南亚市场用的，里面的代码75%以上都是打印异常信息，我实在看的头疼。
再说让我直接从整个项目开始，我都无法直接入手，也可能是因为实在是自己不学无术，一无所知，实在是无法完成自己分内的工作。在被上级XX姐说过几句之后，我提出了离职。

那段时间还开始接触了股票，现在我还不知道投机到底是一个害人不浅的东西，还是一个能让人财务自由的路径。反正那段时间就是辞职后在租的出租屋里面炒股，当看着积蓄
越来越少，股票不断亏损，一直隐瞒家里，自己的情况，自己也一直在考虑是不是要考虑转行，因为自己对程序开发实在一无所知，并且谈不上兴趣，一点自信都没有。
后面想去做销售，但是发现投的简历大多没回音，有面试邀约的公司都破破烂烂，实在让人无法接受。然后来年，生活费没了，股票也亏的差不多了，就又开始找工作了。

第三家，是优购科技，后面外包出去成立了新公司云盛海宏，这个真是让人恶心到家了，特别是个B叫魏海金的人，别人员工想走，各种陪笑脸，拉着不让走，就像妓院里的老鸨一样。
还有就是工作期间我就发现自己薪水被大大压低，妈的，5500，比我上家公司还低，但是没办法，谁叫自己大半年不工作，面试，别人问起来，一问三不知。
怪也只能怪自己。妈个逼，有个和我一年毕业的卵子，居然拿10000，一个月，大多，我问了下，也有7000，RTMB的，人穷被人欺。资本家剥削的本质。
后来实在忍受不了，天天翻来覆去的修改需求了，而且明显都不合逻辑，非常脑残的业务需求都被他们搞出来了。就一个转运单什么的被反复改来改去。
一怒之下，愤而辞职，并且要求赔偿一个月工资，简直是折磨人。
辞职后，再次将希望寄托到炒股上，股票，投机成为我获取生活资料的一种手段和方式。那段时间每天起来就是吃完饭就去南山图书馆看《Reminiscences of stock operator》，那段时间交易
的确大有进步，但是投机这个行业就是只有交易水平到了一定的水平线后，才能开始盈利，不管你在这个水平线之下进步多块，进步多少，没到水平线之上，是不可能赚到钱的。
而且当时本金也非常小，根本连赚到平均每日的吃喝都不够。后来，又和之前一样，实在没办法，就又开始找工作。

第四家，宁远科技，这是家刚起来的互联网企业，做移动医疗的，当时也是找了很多公司，刚好这家开的薪水还行，面试也通过了，就签了offer了。实在是没有办法，已经没有吃饭的钱了。
下个月的房贷都不知道在哪里。这家公司刚开始还不错，领导没给我分配撒工作，就是让

回首五年工作经历，真的是不堪回首啊，

这么些年，尝试过炒股，打德州，写作，销售等方式赚钱，无一不是痛苦失败收场，现在唯一还未放弃的是交易，但是精力，身体，金钱消耗实在太大了。目前是想
