* 如何成为一名产品经理
 准备学习点产品的知识，如何学？
    继续深练技术？底子不好，难；
    综合取胜；

   我到现在这个水平了，必须要换一种更高效率，更高级的学习方法了。
   先不要急着看书，我们先来定义一些东西，什么是产品？
   和产品相关的一些核心概念。乔布斯，肯定是没看人人都是产品经理的，
   但是老乔搞产品的功底比别人强很多啊。

** 开动脑筋，直接开干
   现在用什么新的方式来学习了？如果不知道新的方式，那么原来老的方式有什么优劣了？

   如何成为一名产品经理
*** 老的旧的学习方式
    1.看书，先搞本《人人都是产品经理》
    2.上知乎，百度，谷歌等搜索答案
    3.然后按照他人写的教程，方法，看书，看视频，一步步打怪升级；
    4.去一个小破公司混产品经理经验，当产品经理助手；
    5.在一个或跳槽去另一个，几个公司，刷满10年产品经理经验，就认为
    自动成为产品经理高手，大神。。

    错！应该使用下面的神之方式：
    创造，也就是干，Do It的方式。

    *达到目的。*
    先问自己要做一个满足何种需求的，什么样的产品。
    先有需求（本质是问题，矛盾），后有产品（解决问题，矛盾的答案，方案）

    所以，就一搞一个公众号，个人网站等的方式，因为这也是产品。
    然后就会遇到很多让自己困惑的东西（问题），然后就以解决问题为导向，直达目的
    的去干事情。

    为什么我的网站没人访问？
    0.没有迎合大众口味去写东西？
    1.因为百度没收录吗？
    2.因为访问太慢？
    3.因为没添加友链？
    。。。。。

    还有很多，不断的排除，直到问题的症结所在。整个过程中，直到最终把握到问题的实质所在。

    不可能看完书再开始做产品，学习，这样效率太低。
    边做边学，查资料，解决问题。

    他们那么多问题，其实本质是没搞清楚什么是问题，事物的矛盾本质所在。
    你的目的是什么？要解决的问题是什么？

** 资料再抄
   专业能力、核心竞争力，你说老板有什么核心竞争力——成败论英雄，能把事情办成就是牛逼，什么能力手段能用的，都上，但这样注定难有专业能力的积累。

   职业化环境下，产品经理由于不具备独立决策的基础，个人意志难以彰显，同时受限于公司业务/组织历史包袱，精力更多消耗在产品/用户关注点以外的领域。说穿了，所谓产品经理，对于核心业务/产品，有多少有话语权呢？

   我在bat，pm5年，从助理，到高级，到专家，产品/业务跨过不少。技术专业出身，决定走产品路线不是因为混不下去，而是觉得技术相对被动务于实践，希望：a.向前走，琢磨用户行业，如何做业务、如何做用户，可以看更多。b.磨练价值弹性的沟通协作等通用能力，而非埋头苦练价值相对确定性的技术

   心里有认定：互联网行业，看懂趋势/公司/产品的内在，比搞得如何实现重要的多的多。小则可以选对公司找下家，赚点科技股票钱，大则有发力自起炉灶的基础。

** 参考资料和扩展阅读
   [][]
