* 财富与稀缺性
  1. 人：很多人，绝大多数想要的
     当前非常想要的，未来非常想要的。
     可能并不是非常想要的，只是一种迫切需要的幻觉
  2. 物：稀缺的
     之所以稀缺，还是因为需求的量远远大于产出供给的量。
     比如达芬奇的油画，手稿一般只有一幅，但是假设需求的人不那么多，就不会那么稀缺，那么贵。
     但是假设达芬奇没有名气？比如假设梵高死后一直都没被人发现？
     那么他的油画就不值钱。之所以之前是因为有很多人（有钱的，有权的）认可他画作的价值。
     因为他的确达到了非常高的技艺水平。

     事物在发展变化之中，所以有些不稀缺的东西会变得稀缺，比如：农村宅基地。
     国家以法律，行政（权力）的手段来收取土地，不准私人拥有，所以导致本来不稀缺的东西
     也变得稀缺。
** 个人的稀缺性
   作为一个程序员，市场上并不稀缺我这种水平的程序员，甚至更高水平的程序员。
   所以，我作为一个程序员完全没稀缺性，而且很多项目并不需要很好的代码，很稳定的架构。

   问自己的稀缺性，从两方面出发：
   1. 绝大多数人都想要的
   2. 我有或者我属于有的一小部分人中，而绝大多数人没有的

   还要结合人的功能，个人的功能来思考。
   所有人都会吃，会喝，会拉，会睡觉，会。。
   我们首先从视觉，眼睛，“看”来分析：
   有人是千里眼，这在一个村落里面只是比别人看的更多，看的更远。
   但是假设在远古打猎时代，或者春秋战国时代，早早就能看到猎物，敌人，
   那么这个人借助于"千里眼"肯定能够过的不错。

   但是如果穿越到现代社会，买一个5块钱的"望远镜"就能"替换"掉"千里眼"，效果会更好。
   这个人就失业了，很可能被“权力”者扯个理由抄家了。

   人之所以聪明是能够发明比自身“强大数倍，甚至成千上万倍”的工具。
   现在的汽车能够跑的比人快百倍完全不是问题，更快的还有飞机，火箭。

   人发明工具，就是为了消灭掉这种“稀缺性”。因为人不想被束缚，如果“千里眼”生重病了，
   敌人得知后，来个偷袭，可能这个依赖“千里眼”的部落就这么被干掉了。

   有人是透视眼，平时也就偷窥下村姑不穿衣服是撒样，但是如果用透视眼去赌场，
   那简直就是无往不利的利器，靠赌博就能过上非常好的生活了。

   所以，稀缺性要结合“使用场景”，就像千里马如果去拉煤车，搞不定还比蠢马更不耐操，
   但是千里马如果配将军，英雄，成为坐骑，那身价，待遇又是大大不同，也就是生活很好。

   *所以，你相对于别人的优势是什么？并且这项能力被很多人需要？*
   不一定非得单项能力，跨界组合之后的能力也可以。
   所以，要么是单项练到天下无双的地步（但是像刘翔这种跨栏的，天下无双，但是未必
   很好，特别是体育生涯结束之后，因为这种能力不被绝大部分人需要，体育竞技只是
   国家交流，文化等需要。）

   其次最好是两项技能结合，比如技术+写作，技术+炒股等之类的。


   我们再将事情往前推进，先跳过一步。
   假设我知道了自己的单项优势或者组合优势之后，我该怎么办？
   在这里还有一个非常关键的是： *影响力*
   也就是很多人需要的东西，他们知道去哪里获取。
   比如千里眼，很可能是将军的一个谋士推荐给将军的，所以这个千里眼的人必须扩大自己的影响力，
   让别人知道他有这一项能力。

   有些人天生就附带某些稀缺性，比如四大美人，出生长相注定了，靠“美貌”就能过上组尊贵的生活。

   我的稀缺性在哪里了？
   首先要看看1. *我会哪些东西？* ；2. *绝大部分人非常需要哪些东西？*
   我会看，但是双眼近视，属于劣势，近视的人这么多。
   我会闻，但是没有多灵敏，即使灵敏，肯定赶不上狗的鼻子。
   （狗的鼻子这么灵敏，猫会抓老鼠，所有这些都是上天赋予的，或者后天形成的生存本领？）
   即使这么强大的本领，也大多没撒用，现在都有专门的工具，狗和猫大多用来做“宠物”。

   这里涉及到非常重要的一点： *“人的价值观取向”* 。




   我们学习十几年，也不外乎是学习一门他人需要的技能，找一份工作。
   为什么要努力？
   因为别人在用iphone X的时候，你在用小米；
   别人在高档餐厅优雅的吃大餐的时候，你蹲在路边吃盒饭。

   当下的问题是什么？
