* 远程工作
** 草稿
   当时我认为中国最吸引我的团队就是彩程（出品过 Tower.im 和 Zhiren.com）。而且我已经提前一年就开始了解他们了。结果就是顺利的加入了这个团队。

   所以远程团队对开发者的要求一般都是老手、多面手。如果你观察过国内远程团队对技术栈的选择，会发现大部分都只招聘「全栈工程师」，比如 Rails 全栈或者 JS 全栈。只招前端或后端的也有，但大部分是外包。

   我还记得彩程面试我的时候，虽然对我的定位是主前端的工程师，但是依然会问我关于需求分析、产品设计、后端开发、开源项目、画图软件和自驱动力相关的问题。
   因为远程团队希望把需求跟你讲清楚之后，你一个人就能完成大部分分析、设计和开发工作（当然还会有一个人 review 你的所有工作）。

   1. 最重要的是培养自己的自律，或者是主观能动性。

你需要让这个团队相信你很自律，或者主观能动性很高。换句话说就是你不会在工作的时候浑水摸鱼。

那么如何做到这一点呢？那就是提供证据或者养成习惯，比如

你是某个开源项目的核心贡献者之一，而且你是自发贡献代码的。

你坚持健身或跑步已经五年了。

你在公司里主导过一些项目的立项、开发和维护。

你用代码解决了实际生活中的问题。

等等。只要能证明你不是一个混吃等死的码农，而是一个有追求的程序员的事迹都可以说出来。

参加课程或者专业大会也是一样的。我来给你算一道最简单的数学题，假设你一小时赚 30 美金，然后这个收费 300 刀的课程可以让你的生产力提高 5%，那么也就一个半课程你就回本了。而且在接下去的三年里，你就可以多赚 8000 美金。参加像 WordCamps 或者 PressNomics 这样的会议使得我去年无论是在经营 WordPress（译者注：一种使用 PHP 语言开发的博客平台）主题的商业项目还是写博客上，都实现了十倍的增长。


** 精
我发现我开始有一股很强的冲动，想找一个至少一半以上的人都比我厉害的团队，做一些我没做过、做不来的事情。

我整理的列表中，影音资料里面有一些访谈非常棒，建议听一听，尤其是 teahour 里面的。

从早上一睁眼就无时无刻不在思考项目上的问题, 我的修改是不是让代码变得更好了? 这个地方如何抽取? 为什么先写测试会帮助我做出更好的设计? 为什么预计到变化这么大, 依然坚持重构而不是重写?....

1. What have you done yesterday?
2. What will you work on today?
3. Is there anything block you?

正巧那段时间第一届 RubyConf China 要在上海举行。我当几乎不假思索的就定了票，而且内心有一种说不出的兴奋，这种感觉犹如一个职业选手要去参加WCG一般，让人兴奋不已，我一直想看看中国其他Ruby玩家到底是如何玩的，每天是怎么训练的, 于是找老板请三天假去上海参加这次Rubyconf.
变得更优秀，我必须要和这些优秀的人一起工作
