* 2017年的工作
  起名为工作（job）灵感来自于大数据，先有job，然后分解为任务（task）。
  首先审慎的定出一年的大方针，一个大方面的工作。
  然后分解到每个月应该做哪些工作，再到每个星期，每天的任务task。
  所以的准则就只有一条：
  *最重要最紧急的安排在最先完成。*

** 技术
*** SQL
    SQL原理
    SQL必知必会
*** JS
    先学习JS在学HTML,CSS
    读2本JS的书籍，但是这个和目前工作不太好契合啊。
*** HTML CSS
*** 架构
    看2本架构方面的书籍，特别是传统的企业系统架构。
*** Linux
*** 补充
    所以，你看MapReduce其实不在我的范围之内。
    还有什么网站SEO，写作，将网站排名搞到前面，这些都不在啊。
** 商业
*** 创业
    公开课，如何创业
    2本创业书籍
*** 合伙人
    找到2到3个合伙人，认识10个投资人。
** 产品
*** 比较分析产品
    邮箱，浏览器，云笔记，招聘网站
*** 书籍
    读2本产品有关书籍
*** 写东西
    做能够复用的模块，用户模块，权限模块，日志模块，
* 2017年
  大方针：狂打技术基础。操作系统，算法与数据结构，数据库，网络。
  这么多，我还TM平时看几本其他的，商业等的杂书。按重要性排个序：
  1.操作系统 CSAPP，毫无疑问读这个数，还要去看一本关于汇编的书。
  这个上班时间不能看，（我们被时间，空间所限制）

  2.数据库，学好数据库，开始设计，编码一些可复用的模块，用户，权限，日志等。
  这个上班时间可以看，也可以干。
  数据库原理，SQL必知必会，SQL Paper。

  3.算法与数据结构。今年还剩5个月，能搞完这3个吗？
  搞一个就搞精通，但是这个是反复的过程，蛋疼。
** 2017年8月 放假CSAPP 上班数据库
   主要搞数据库，重点在：原理，索引，核心概念。
   不要去看中文的，有依赖心理，而且英文水平一直上不去。
*** DONE 1.SQL Paper
    CLOSED: [2017-08-01 周二 16:08]
    :LOGBOOK:
    - State "DONE"       from "TODO"       [2017-08-01 周二 16:08]
    :END:
    A Relational Model of Data for Large Shared Data Banks
    读了一遍，最后几页直接跳过，妈的，太难懂了。内容说的是在DB出生之前，
    其他数据的组织形式的一些问题。
*** TODO 2.数据库原理

*** TODO 3.数据库索引
*** TODO 4.SQL必知必会

** 2017年9月 放假CSAPP 上班模块编写

** 2017年10月
** 2017年11月
** 2017年12月
