* Hunting a Job
** 规划
   将找工作整体作为一个项目进行规划：
   1.首先过滤出符合要求的招聘岗位
   2.之后看岗位的招聘要求共性的东西，列出来
   3.制定时间安排来完成复习，学习来掌握这些东西
   4.估计，验证制定安排的有效性（这可能需要在完成1，2个安排之后，通过反馈来判断）
   5.当完成所有复习之后，开始准备面试
   6.面试需要准备什么了？1.简历，2,穿着礼仪3面试策略，注意；4谈薪资；5。上班

   在这整个项目的进展过程中，肯定会遇到问题，此时，我们就需要停下来，
   问自己问题，追究到问题所在，
   然后再来考虑如何解决这个问题。

** Draft
   了解NIO,AIO,BIO工作原理
   熟悉MySQL, Oracle分库分表原则和设计,熟悉MyCat等数据库中间件.
   熟悉分布式技术（包括存储、缓存、消息系统等）优先
   精通Java EE相关的主流开源框架，能了解到它的原理和机制

   jvm本来我TM还想看书的，但是一看，都TM是浪费时间。
   *动手*
   直接从open jdk官网开始看起。然后找个jvm相关知识点查质料，动手，学习。
   JB看书一章章，简直浪费生命。

   What you are asked in an interview depends on variables such as:
   How much experience you have
   What your technical background is
   What positions you are interviewing for
   Which companies you are interviewing with
   Luck
** review plan
*** design-pattern
    102 patterns in 10days?i can't plan,because i don't do it before. so i need practice one tomorrow.

*** jvm
**** GC
**** class load
*** database and mysql
**** database read the book
**** mysql read offical document
*** network
**** http
**** udp
**** rpc
**** protocol and protocol design

*** memory management
*** frameworks
**** mybatis 1D 2017.12.13
     1. what is orm
     2. mybatis vs others
     3. mybatis most ask question stackoverflow
     4.

*** spring
**** AOP
**** IOC
**** spring cloud
**** spring boot
*** concurrent
*** kafka
*** zipkin 1D
*** micro-service 1D
     熟悉微服务架构，熟悉dubbo的使用和实现原理，熟悉服务治理的思想，熟悉dubbo服务治理的方式和实现
*** cache
*** distributing and cluster
**** distributing lock and transaction
**** cluster communication,failover,high avalibility,leader election
     redis cluster,kafka cluster,zookeeper cluster
     communication,failover,high avalibity,election,
**** redis cluster 1D
     https://redis.io/topics/cluster-tutorial
     https://redis.io/topics/cluster-spec
** 2019年1月
   去github上或者其他地方找内推
*** 内推微信群
    深圳的有
    众安 丁盛
    今日头条 王鹏举
    小米 小豆丁
    大疆 刘明明
    shoppe 刘详裕
    顺丰 changle0331@163.com
    微众银行 alexcai@webank.com
    YAI-后台开发高级工程师(web系统架构师)
    ZZT-后台开发工程师

** 面试复习
*** 陆金所的

1、 精通Java Core/数据结构及算法/J2EE/Struts 2/WebWork 2
    /JSP/Servlet/Java TCP/IP Socket/Ajax/JavaScript/Xml等WEB系统开发技术；
2、 精通SQLSERVER/MYSQL等数据库，熟练编写存储过程；
3、 精通在Linux系统下的应用环境部署及性能优化；
4、 熟悉jvm重点考虑
5、 具备较强的面向对象系统分析、系统设计经验；精通面向对象分析设计，熟悉设计模式
积极主动，能承受高度工作压力，具有良好的信息收集能力、归纳思维能力、团队协作意识强。


群体性的行为比大盘指数更有效，昨天所有次新都熄火，今天早盘芭田股份开板到跌停，
主力对于时机的把握是非常准确的，还好昨天出了爱朋股份，所有那些小技巧在大势面前都不值一提，
阳光电源错过了十几个点，错过就错过，大盘不好，不参与这是原则性的问题。
但是东方通信了？所以也要看看情况的，大盘块触底时，搞，比较安全，大盘经过一轮上涨之后，
开始要跌了，这时最危险。

力量主要通过反对者进行表达，一根阳线和一根阴线都说明不了什么问题，
问题是阳线以后的阴线和阴线以后的阳线


让我进场的是理由，让我出场的还是理由；
市场是没有方向的，没必要去猜它的方向，猜方向就会养成先入为主的思想，跟着会养成了死扛的思想，你只要学会在支撑阻力位上开平仓就行了。
** 再次找工作，苦，一切为了交易
*** 计划安排
    先将简历完善，关键是离职的那段时间如何写？或者直接写个商城项目，然后github上面找一个复习一下。
***
