* 给职场新人的几条建议
** 草稿
   入是为了出，如果出不来，就不能从外部看待事物了，就永远看不清楚。

   做对事，跟对人，如何发展，升职，加薪。
   去小公司还是大公司，如何混？

   首先练好一项本领，找到志同道合的人，组建团队，创业。
   不对。

   在听取任何人的意见之前，或者说，再给其他人意见之前，最好是对他人能够有比较全面，深刻的理解。
   不然牛头不对马嘴，活马当驴医（大概就是要针对下药），这里我给的几条建议都是具有普适性的，但是却缺乏针对性，
   大家学习，使用前，先请对号入座。

   职场就是江湖，先有规矩，按照规矩办事。
   首先是各种礼仪，邮件称谓，和上级沟通等等之类的。
   第二，学习各种高效的工作工具，流程等，时间管理。

   第三，搞好人际关系。

   跳槽，升职，加薪。
   如何才能升职，如何加薪等。跳槽。

   职场的本质，。。耸人听闻。学历，起点，无法背负过去。。

   工资，存钱，投资自己。

   安逸的工作。最事就一口气做完。

   如何学习，保持学习。

   最后，虽然建议都在这，之前的很多人也写过，但是路还是得自己走，事情还是得靠自己去经历，
   纸上得来终觉浅，绝知此事要躬行
   即使有人停机群了这些意见，他也不知道如何去做，如何设定目标，因为没有痛的领悟。
** 正文
   首先恭喜你顺利大学毕业，不管你是否变成了猪一样懒惰，愚蠢的废材，你还是成功的拿到大学的毕业证，学位证。
   虽然这只是两张纸片，但是却是花费你宝贵4年时光，加上至少10W左右的学费，生活费换来的。

   其次，再次恭喜你顺利找到一份还算满意的工作，要知道中国每年的大学生都是好几百万人，这还不包括专科，职高。
   而这些毕业生里面有相当一部分，废话有点多啊。
*** 职场规则
    有人的地方就有江湖，身在江湖，就要按照江湖的规矩来，正所谓：盗亦有道。
    职场讲究一个“混”字，怎么混？如何混？这应该就是你想要知道的东西。

    马哥比，从新写。
*** 高效
*** 重构你的学习方式，并保持终生学习
    职场里面的学习方式和校园里面的完全不同。在校园里面，你只需要当个好学生，牢记并理解老师讲解的知识，会做题，能考高分就行了。
    在职场里面，不是。在职场要学习做人，做事。先做人，后做事，也就是说要搞好关系，最少不能得罪人，除非你不打算在这干了。
    得罪人后，不管你是管别人，还是和别人一起做事，人家三天两头恶心你一下，搞你一下，你都会苦不堪言。明枪易躲暗箭难防啊。
    所以，你得重构你的学习方式，不能再用以前那套填鸭教育，工具人的那套方式了。

    学习，最先是要学会 *如何观察* ，所谓的“察言观色”就是观察。观察别人是如何做事，如何处理事情，如何和同事，客户打交道。
    其次就是学习 *如何思考* ，就是在上一步观察得到的结果上，多问为什么？为什么别人要这样做，不那样做；为什么老板安排他去做，不安排我去做；等等，诸如此类。
    建议学学5W1H，如何提问等工具方法。
    思考得到自己的结论之后，再反复推敲一下，然后和事情的最终结果比对一下，看看是否有出入，出入在哪里，问题在哪里。这样的话，你的思维更深入，以后遇到事情，就能直接得到想要的结果了。
    进一步，就是学习 *如何解决问题* ，

    能够解决别人解决不了的问题，这就为你带来了声誉，这是比工资更宝贵的东西。首先别人信任你，其次别人依赖你，再来你得到了巨大的成就感。
    这种声誉扩散出去，就能得到机会，而且是非常好的，主动提供的机会。
    最后一步是，学习 如何提出问题，到这个地步，我相信你在公司应该是有头有脸，至少是领导级的人物了。
*** 人际
*** 升职

*** 加薪
*** 本质
*** 跟对人，做对事
    经常看到有人就到底是跟对人重要，还是做对事重要争论，我记得我在第一家公司还参加过这题的辩论赛。
    其实这两者根本不矛盾，错误的人不可能做对的事情，除非是愚者千虑的一得。同样对的人很少会做错的事情，
    不然他就不会是一个对的人了，正是他之前做的那些正确的事情才造就了他在别人眼中是一个对的人。

    如果在

*** 最后
