* 德鲁克学会管理自己笔记
你首先要对自己有深刻的认识——不仅清楚自己的优点和缺点，也知道自己是怎样学习新知识和与别人共事的，并且还明白自己的价值观是什么、自己又能在哪些方面做出最大贡献。
因为只有当所有工作都从自己的长处着眼，你才能真正做到卓尔不群。

历史上的伟人——拿破仑、达芬奇、莫扎特——都很善于自我管理。
要发现自己的长处，唯一途径就是回馈分析法（feedback analysis）
每当做出重要决定或采取重要行动时，你都可以事先记录下自己对结果的预期。9到 12个月后，再将实际结果与自己的预期比较。我本人采用这种方法已有15到20年了，而每次使用都有意外的收获。
回馈分析法使他们的信徒养成了一种始终注重实际表现和结果的习惯，
我们只要持之以恒地运用这个简单的方法，就能在较短的时间内（可能两三年），发现自己的长处——这是你需要知道的最重要的事情。在采用这种方法之后，你就能知道，自己正在做（或没有做）的哪些事情会让你的长处无法发挥出来。
第三，发现任何由于恃才傲物而造成的偏见和无知，并且加以克服。

另外一点也同样重要——纠正你的不良习惯。所谓不良习惯，是指那些会影响你的工作成效和工作表现的事情。
对于知识工作者来说，“我的工作方式是怎样的？”可能比“我的长处是什么？”这个问题更加重要。
没有几个听者型的人可以通过努力变成合格的读者型——不管是主动还是被动的努力，反之亦然。

所有的学校都遵循这样的办学思路：只有一种正确的学习方式，而且人人都得遵从。但是，对学习方式跟别人不大一样的学生来说，被迫按学校教的方式来学习就是地狱。实际上，学习大概有六七种不同的方式。

他总是提出政策性问题，在每一个问题上提出三种不同观点。但他很少请这帮同事发表意见或提出问题，他只需要听众听他讲话。这就是他的学习方式。

根据自己是如何学习的，来调整自己的行为。

我属于阅读型，思考型，辨认别人错误认知的学习，现在体悟到实践才是学习的最好方式。
我喜欢单枪匹马，能与别人合作好，但又前提是：别人不是笨蛋。

我在怎样的关系下与他人共事？
没撒关系，就这样。

我如何才能取得成果——是作为决策者还是作为顾问？
很明显，作为决策者。

我是在压力下表现出色，还是适应一种按部就班、可预测的工作环境？
很明显，现在做的都不是我喜欢的事情，甚至是非常厌恶的事情。
所以在压力下，时间紧迫下，我肯定做不好。但是也无需按部就班，可预测。
条件，时间等差不多的情况下，就行了。

不要试图改变自我，因为这样你不大可能成功。但是，你应该努力改进你的工作方式。

*我的价值观是什么 ？*


如果一个组织的价值体系不为自己所接受或者与自己的价值观不相容，人们就会备感沮丧，工作效力低下。
价值观是并且应该是最终的试金石

使得一个人能够坦然接受一个机会、一个邀请或一项任务。“是的，我将做这件事。但是，我将按照我自己的特点，采取这样的方式来做这件事，进行这样的组织安排，这样来处理当中所牵涉的关系。这是我在这个时间范围内应该会取得的成果，因为这就是我。”

我想做什么？

当前形势的要求是什么？鉴于我的长处、我的工作方式以及我的价值观，我怎样才能对需要完成的任务做出最大贡献？最后，必须取得什么结果才能产生重要影响？
把眼光放得太远是不大可能的——甚至不是特别有效。
我在哪些方面能取得将在今后一年半内见效的结果？如何取得这样的结果？
确定了要实现的结果之后，接着就可以制订行动方针：做什么，从何处着手，如何开始，目标是什么，在多长时间内完成。

老板既不是组织结构图上的一个头衔，也不是一个“职能”。他们是有个性的人，他们有权以自己最得心应手的方式来工作。与他们共事的人有责任观察他们，了解他们的工作方式，并做出相应的自我调整，去适应老板最有效的工作方式。事实上，这就是“管理”上司的秘诀。

提高效力的第一个秘诀是了解跟你合作和你要依赖的人，以利用他们的长处、工作方式和价值观。工作关系应当既以工作为基础，也以人为基础。

发展第二兴趣（而且是趁早发展）还有一个原因：任何人都不能指望在生活或工作中很长时间都不遭遇严重挫折。

在一个崇尚成功的社会里，拥有各种选择变得越来越重要。从历史上来看，却没有“成功”一说。绝大多数人只期望坚守“适当的位置”。唯一的流动性是向下的流动性。

实际上，自我管理需要每一个知识工作者在思想和行动上都要成为自己的首席执行官。更进一步来看，这样的转变——从一切听从别人吩咐的体力劳动者到不得不自我管理的知识工作者——也使得社会结构发生了深刻变化。
