* 5年工作经验程序员的中年危机
  前段时间，“华为清退34岁以上程序员”，“中兴程序员跳楼”等事件炒的沸沸扬扬，
  身为一名程序员，我的内心也深感戚戚焉。本着好奇的心态，想看看国外程序员是否也有中年危机。
  咨询下Google：Programmer Midlife Crisis就看到了这篇很好的问答，收获颇多，特地翻译下。
** 问题：4到5年工作经验的程序员是否会遭遇中年危机？
   我已经做了4年全职的C#编程，在过去的4年里，我给一些中小型公司打工，大多都是做
   “网站”，“广告代理”类的，特别是那些卖软件给那些小的创业公司的工程。

   我主要是做“业务软件”方面的开发，使用一些高级语言（带垃圾回收的）。
   我的总体体验是：我完成的哪些工作可以做的更加专业些。

   很多事情都以非常不正确的方式完成，主要原因归结于成本因素。
   人们都想要立刻得到某些东西，但是只付非常少的钱。

   我经常思考如果我能给更大的公司打工，或者一个更适合程序员的公司，
   或者某些地方拥有相应的金钱和时间，真在的创建某些事情，有一个长期团队，并且更加可维护。
   我或许会更加的享受我的职业生涯。在我4年职业生涯中，重来没有一个导师指导过我。

   我是个通过大量的写博客，用Google来自学的程序员，而不是像我获取IT学士学位那样。

   我也经常观察到另外一个问题，在我的工作环境中，许多所谓的“高级”程序员并不具有相应的高级技能。
   他们之所以“高级”仅仅是因为他们做了很长时间的程序员，但是他们写的代码，做出的决定，
   完全全部都是垃圾。他们不愿去学习，他们不愿变得更好，他们只是为了工资，然后去做别人告诉他们
   行得通的，而且我们绝大多数都想这样。

   或许这就是为什么他们现在在这里的原因。或许这就是为什么他们现在就是这样。
   但是我不想成为他们那样，我想变得更好。
   我现在已经进入一种以后不再做程序员的精神状态。
   我开始思考，或许其他的地方有些更好的事情等着我去完成。
   我读的博客阅读，我试验的“最佳实践”越多，我就越感觉我已经从“我的现实”漂走。
   但是我不是一个伟大的程序员，否则我
   我不认为我应该是现在这个样子。
   我认为4到5年是一个台阶，阶段，可以明智的向职业生涯迈出前景的一步，
   或者踏出你现在所在的地方的一步。

   我仅仅想知道其他的人会说些什么，关于上面我提到的，
   或者你是否体验到相同的情况在你过去的编程职业生涯，并且你是如何处理的。谢谢。
** 回答：
*** 回答一 195票
    你提了一个非常有意思的问题。我全心全意的赞同你。我得到过相同的观察结论。

    我已经全职编程工作很多年了。我观察到的是，在那儿，
    优秀程序员的数量，
    热爱他们工作，并且以质量和热情完成工作的伟大开发者，几近于0 。

    我或许仅仅只遇到过一位能教我一些东西得人。
    绝大部分我所知道的都是通过自己，读书，逛论坛，在论坛提问，搜索相关的想法。

    然后我并不后悔。

    在工作环境中能够学习的方式经常，都是被限制的。
    你不能启动项目。你
    你也不设计，不提升，不重构，不思考架构，你仅仅只是编码，将事物拼装起来。
    这就是绝大多数软件商家的工作方式。
    你不仅仅学不到任何东西，你更可能会学到错误的东西，如何不会开发软件。
    在我周围，我不断的看到可怕的事情，所有那些你已经听到的反模式（anti-pattern）。
    更糟糕的是，我自己都被迫去做这些。

    我不知道这些事情是如何发生的，但是我以某种程度方法设置了一个输入屏障。
    我保持开放，聆听，并且一旦在我的研究中看到某种自我提升的可能性，或者采取
    并且一旦看到某种自我提升的可能性，我就开始研究，并且采取某些技术或主意。

    我曾经长时间在一个糟糕的很赶的项目中，但是我自己没接受到任何坏的技术。

    我马上就能理解到，如果你想从编程中获得满足感，那么就忘掉工作，拥有你自己的个人项目。
    你可以运用你所有的热爱，热情和知识去正确的做事情，以高品质的层次。
    你将学到非常多的东西，无数的东西，你将永远不会面对的挑战，
    当你拼装那些讨厌的团体事物。

    我仅仅只为薪水工作，但是通过自己的个人项目获得满足感。

    我完全不能明白的一件事是：当今这种情况是否有可能。
    软件开发行业成熟了很多。有好的也有坏的经历。有许多成功的项目，也有大量失败的。
    有长期项目的经历，。。。。
    这儿有许多的研究成果和写就的书籍。编程珠玑，代码大全，任运生化，设计心理学等等，
    为什么除了我们，程序员外，没有任何人读过他们？
    是否有可能，在IT行业工作20年的开发者和管理者重来没有时间去读它们，或者其他的方法学书籍？
    它们已写就， 但是几乎不可能被阅读，那些最需要这些良药的人。

    除了职业发展方面，我还注意到

    你发现很难卖出你的只是，经验，对宇宙的理解给任何人。这些东西不需要。
    需要的是

    廉价的人们被使用，被滥用，然后被扔掉，因此下一个循环开始。
    项目
*** 回答二 70票
    Jeff Atwood在Coding Horror博客上发表了一篇关于此事的文章，可能会很有趣。
    作为一个软件开发者的部分工作描述就是享受你的工作。否则，它将会变成一个非常讨厌和累赘的职业。

    事实上，你不停的寻找改善你工作的方法，不断的获取新事物的信息，
    并且最佳实践表明你实际上很享受你的工作。所以，我给你的建议是：开始重新寻找一份新工作。

    然后，我并不认为，为一家大公司工作就一定能改善工作的环境。
    我认为对软件开发者最好的公司是那种小中型的公司，里面的人们喜爱他们所做的一切。
    最好的办法是去寻找，并确认这些公司，然后做出决定。
    尝试并且确信这家新公司是值得加入的。
*** 回答三 50票
    首先，一个大的警告：如果你做了10年开发（像我这样），除了开发，你其他事情都做不好。
    所以，如果你想做一些其他的事情，全新的事情，赶快去做，否则就来不及了并且你永远
    不能做好任何其他的事情了。

    仅仅只是分享一下我的个人观点：我是一个自我驱动的人，完全自学。
    我已经自学了C，C#，Amiga C开发，Windows，COM，Delphi，PHP，Cinema4D，
    现在在学Blender和Python。我几乎一致都是独自工作。这是我目前遇到的最大问题了。
    小小公司都努力存活，你就是他们努力让公司存活中的一员。
    这事压力非常大，但是也非常值得。你做的越多，学的越快，并且是很多新东西。
    你制造产品更快（即使你经常无法合理并适当的完成工作）。不管怎样，反正很多压力。
    与此相反，大公司几乎总能存活，但是问题出在人身上：太多的人了。
    就是丛林，但是更糟糕，没有什么是清晰的：如果和你一起工作的人们感到你比他们好，
    他们会经最大努力，不去帮你往上走，而是攻击你。
    因为他们对自己的职业生涯感到害怕。这就是法国的情况（其他国家我不清楚）。

    长话短说：尝试找一个中等规模的公司，在哪儿你感到这是属于你的地方。
    无论你编码了多长时间，无论你工作了多久，
    当某一天你坐进你的汽车，准备去工作时，你会想“去工作我很开心“，那一天就会找到属于你的地方。

    这不是4到5年的问题或者别的什么。

    NB：“我很开心去工作”和“我很开心去工作因为我将做这个或者那个”或者“我很开心去工作，因为我将
    学到这个或者那个”，它们之间有巨大的差异。
    如果你认为“因为我将做这个或者那个”那将表明“这个和那个”总有一天会结束，
    再此之后你将都不会开心了。这是我12年的编程经验。并且我是资深工程师，报酬丰厚。
    但是我确实意识到20到25岁的年轻人比我思考的更快。他们仅仅只是缺乏我的经验，
    所以我承认我可以帮助他们做事情，并且他们做的更快，但是我帮助他们变得更好。（
    当你开始编程开发时，永远不会发生。）

    为我不太好的英文感到抱歉，别再犹豫了，将我的发帖改的更加英文范吧。
*** 回答四 36票
*** 回答五 29票
