* 成为一个自由职业者
  首先，继续像这样工作下去这个选项已经被我完全咔嚓，断头铡了。
  其次，创业需要巨大的资源投入，暂时还不具备相应的实力。
  作为一个freelancer，虽然赚的不多，但是完全能够自给自足，但是问题是：
  涌入这个市场的人肯定会欲来越多，这种竞争，肯定是类似淘宝，porkerstart上的完全竞争，
  对个人要求很大，最好能团队作战。

  工作最大的弊端就是去哪里都是搬砖，完全没有任何积累，到了34被干掉，就只能上天台。
  做freelancer和创业类似，但是不需要那么多的长时间投入和资源，但是我觉得也不容易。

  首先要做的是打造自己的个人品牌，说简单点就是：哪方面非常牛逼，哪方面的专家，
  人家一遇到问题，或者提到某件事情，首先想到的就是你，而不是别人。

  首先是搞相关的资料，然后学习，最好是能抱团，加入各种QQ群，微信群，社区等等。
  英语能力要提升起来，写作说服别人的能力也要提高。
  做freelancer的核心，关键是：能够接到较好的活。
  刚开始的时候只能从接一些别人不要的烂活开始。（从头开始）

  抱团的好处太多了。一方面能做些别人搞不完的活，一方面能够学习，得到在自由职业方面的指点。

  效率，时间，重用，收入肯定是和现在工作差不多的，做得好的很可能比现在多个50%，
  做的差的，刚开始一个月5,6K的收入肯定是有的。最少，每天上下班的公交时间免了，
  不怕被34了。全球的成本都在降低，一定要让自己往更高端的人工智能，区块链等领域走。
** 我想了很多
   首先，upwork之类的注定只能是低端行业的低端人群竞争，无法长远发展。
   关键词：一处制作，到处使用；能量，捕捉能量；借助外部势力；

   所以要学习：政治，经济。观察国内外大势。
   要么影响世界，要么顺应世界影响的趋势。大局观。要么创造机会，要么等待机会，要么借助机会。
   如果我早就知道中国热钱流入，城市人口集中，那么投资房地产就是很明显的了。
   如果我知道ofo和摩拜单车大战，那么去做自行车就是很明显的了。
   房地产，股票，比特币，这些事物都不是“我”可能发明的，但是它们具有巨大的能量，
   人人都在讨论，人人都在参与，顺应到了这个趋势的话，就能赚大钱。

   一份制作，到处使用。麦当劳，沃尔玛，房地产，股票，书籍，发明，创业，商品（iphone等）
   这些巨大的财富来源都符合这一特征。
   股票，是同样一份到达赚钱水平的能力，心性后，到处的资金都能使用，增加更多的资金就能赚更多的钱。
   麦当劳，一个地方是这样做，另外一个地方也是这样做，一个城市到处都是麦当劳，肯德基。标准化，流程化。
   房地产，


   如果真要做，就要选好之后，做这些事情。判断是否是这些事情，就要用到他们的相同特征。
   比较，求同，求异，统一的方法论。判断之后，是的就能开干，然后干的步伐：
   居然是和这个事物的特性的另外一点起步：就是一份制作，在一个地方，大获成功之后，再推广到其他地方。
   这些居然都是统一的。（学习思考，看看有没那些被低估的书籍）

   你看看Facebook，俞敏洪，麦当劳等等，都是如此，一个校园，一个学生，一个地方获得成功之后，
   大批量的推广开来，通过减少整个运营边际成本，获得利润的X倍增长。
   再往前回溯，就是这些事物必然有核心的东西，适应了时代潮流大的发展趋势。（这里开始思维有点不太灵了）

   俞敏洪，书教的好，顺应了出国留学的热潮。
   麦当劳，味道不错，速度快，顺应了工作族的，城市的快速生活节奏。
   Facebook，人人都不需要任何技术就拥有了一个网上的个人主页。虚荣心，社交等。

   *精通Kafka后写一本Kafka的电子书，然后售卖。*

   现在最热的是什么，能力的聚集处是什么？
   人工智能，区块链，APP，微信公众号，


   一大部分人群的需求痛点，它们遇到的问题，改善它们的生活，

   理论上来说，我能很轻松的解决每个月赚6000块的问题。
   为什么要限定成每个月6000块了，每个月赚6万不行？一年赚7万2不行？每个小时赚200块不行？
   不要给太多限定条件。
   赚钱，赚谁的钱，用什么赚钱？
   资本论里面写着有：生产的3要素，不是3。
   土地（我们无法摆脱空间的束缚），劳动力（苦力，牲口，机器），
   资本（购买生产所需的一切要素，土地，劳动力，机器，技术，管理等）
   也就是说：从状态A到状态B之间有时间缝隙，间隔，需要用资本来衔接。
   技术（程序员，生产技术，制造技术，工程技术工程师）
   经济信息（如何做出）
   经济管理（管理人员，CEO等）

   除此之外的信息成本，信息差，投机倒买倒卖，
   我没有金钱资本，土地也没有（家里宅基地被收走，城市住的鸽子笼），
   有技术但是不是多么牛逼的技术，是能够被市场上明码标价的技术（可改进），
   管理（我能管理，做出决策，但是没有信用背书，没有过去的成绩，成就来证明），
   倒买倒卖在信息透明的情况下，几乎不可能，或者时间缝隙很短，赚到的钱不够初始化的成本。
   中国的资本现在到处泛滥，所以会有泡沫。

   擦，我发现劳动力也包括脑力劳动者。
