* 以后

  最最重要的一点是如何赚钱。

  首先是1800，然后是5200，然后是1W，OK，可以了，哈哈。

  第一个1800估计是最难的，

  必须要搞清楚整个金钱是如何流动的，然后看你在哪一环，有哪些东西。
  看看国富论，资本论。

  如果是接外包，如何搞？成本太高了，当初说是写博客赚钱，投机赚钱，
  产品赚钱，出售技能赚钱，

  如果是去摄影楼里面兼职什么的，这就和打工没撒区别了。
  但是根据黑天鹅里面的，什么平均斯坦，极度斯坦的理论，要么平均赚，
  要么大赚。都想大赚，但是怕熬不过最穷的时候啊。

  其实就是一个长期和短期的问题，都要兼顾，而且长期喝短期通常都是矛盾的。

  博客这个CUT，定位不对。


  刚才大脑里面电光石火，之所以赚钱难，是因为钱是需要带来更多钱的，这个才符合金钱的属性，本质。
  也就是说，给你100块钱，你最少要带来120,110块钱，这样钱才能流通过你。
  而，你看看，想想穷人为嘛穷？或者那些搬砖的人，赚钱困难？
  因为给他们100块钱，他们只会存起来。永远不会让100块钱变成110块钱。
  所以金钱讨厌他们，不会流向他们，所以他们就会永远贫穷。

  所以钱赚钱是最简单，最容易，最符合钱的本质的。

  所以如果我要赚钱的话，就要让钱都流过我这里，就像银行是最富有的。

  金钱具有虹吸效应，必须要接近源头。
  交易，
  经济，
  禅
  编程。

  为什么互联网创富？节约社会活动成本，将人注意力这种资源进行了转换。



  所以有人也说了，财富不过只是暂时挂名在你名下


  关键是如何生存下来。


  每天的时间安排要严格计划一下，如果执行不了，就重新找工作去上班吧。
  好累。

  算下时间。

  早上7点起，7点半前洗漱，早餐完毕。

  7点半到9点15点，2个小时，看书

  9点30点到12点，2个半小时，图书馆，干活。

  12点30，吃完中饭，午休，
  13点到21:30 图书馆干活，8个半小时，其中1个小时锻炼，1个小时休息，6个小时

  一天是8个半小时。


  总共是14W左右，满打满算，只有一年时间，12个月。

  第一个月，30天，完成红绿之书，边炒股，炒期货。
  第二个月，

  关键是通过自己，能做什么，完成每个月赚5200，每天赚200的任务。

  但是即使赚到了又怎么样了？和打工不是一样，没什么区别？
  如果我要做，我就要做到最顶尖，最牛逼的。世界第一，俯视众生。

  所以，如果是德州扑克，我不去打的话，一样没钱赚，所以还是会占用我的时间。
  我要的是自由，所以先的用时间去赚金钱，然后用金钱去赚金钱，赚时间。这样，我就既有钱，又有时间了。
** 时间工作安排
*** 7月25~8月20日
    15天，上班期间，将红绿之书写完。
    这个安排，规划什么的，最好能够细化到每天。太宽，太泛不好。

    其次就是：培养设计的意识，如何设计一个东西。
    培养设计的意识之后，就是产品的意识，已经产品之后的用户，商业模式等等。

    最好能开个淘宝店？推广个人博客等等之类的实际操作下。
    对，可以应聘个什么店主？拿钱，还能学东西。
** 财务支出计划
** 每日时间安排
   21:30上床
   21:30~22:30 打坐一小时
   22:30~05:30 睡觉
   05:30~06:30 打坐一小时（是先洗漱走动下再打坐还是直接打坐？）
   06:30~06:45 洗漱，（不对，应该还要先运动下）

   07:00~08:00 早上运动和晚上运动区别，还要留个15分钟到处逛一下，看看新闻，github
   08:00~09:00 看书学习一小时
   09:00~10:00 看盘一小时
   10:00~12:00 干活两小时
   12:15~12:45 中饭，溜达
   12:45~13:30 午休

   13:30~14:30 学习一小时
   14:30~15:00 干活一个半小时
   15:00~16:00 复盘一小时（这个时候复盘效果最好啊）


   21:00~21:30 洗澡

   16~21这之间有5个小时了。打德州2小时？90分钟？
   放弃德州，全面学习互联网整条产业链上的东西，最核心关键的是：设计。商业逻辑，产品。

   每天打坐2小时，看盘2小时，学习2小时，休息7小时加午休0.5小时，
   每天干活2+1.5+3？6.5个小时？
   他妈的的，完全不对，最关键的是：你要弄清楚辞职之后最关键要做的是什么？
   必须得学会放弃，才能获得，比如放弃德州，放弃股票。必须得搞个点，然后爆破。

   不行，这个里面任务切换太多，效率估计提升不起来啊。
   时间偏差在15分钟以内的都能接受。
