* 关于程序员赚钱这件事儿

  任何商业行为，无外乎2个端点，一个是如何提高盈利，另外一个是如何缩减成本。
  就连你自身或家庭的财务管理也是同理，如何开源，如何节流。

  如何盈利这个问题会比较困难，就是如何开展一种新的商业模式或者商务活动，让消费者主动掏钱。
  那么我们来想想，如何缩减成本？

  你现在工作效率比别人高，那么产出就比别人多，但是拿的工资和别人差不多，相对于公司来说就是节约了成本，得益获利的是公司。
  但是究其本质，提高盈利和生产效率也有同样关系，比如社会上要求无穷多的功能，每开发一个功能，给X元钱，那么效率高的程序员，盈利就多。

  寻找社会需求的东西，匮乏的东西。
  公司设计到一个商业流程运作的过程，大致可认为是业务流程，以及牵扯进业务流程的人员，设备等。

  黑客与画家中说到一种，一次生产，到处使用，这是互联网产品的性质，但是也是肯德基，沃尔玛的模式。
  可以找到相关的生产活动是此种模式的，但是如何和别人竞争了？

  我也可以网上卖书，卖耳机等等，优势了？还是成本，和盈利（用户体验，用户数就是提高基数，提高盈利）

  找一个竞争小的区域，先成长壮大，但是有吗？你的生活经验太少，接触的时间，空间太小，难。
  压缩成本，其实本质是降低整个社会运行的成本，提高了社会对资源的使用效率。
  压缩成本是简单的，但是很多行业已经被压缩到利润极低，无法在压缩了，再压缩就倒闭或者已经回归到业界平均利润水平了。

  所以还是提高生产率，扩大用户基数，才是正途。压缩利润看似简单，其实是防守，不归路。
  帮别人节约，节约时间，节约出错机会，减少糟糕用户体验，这个也是可以产生价值的，但是如何运转，让别人付费？

  还是要从自身的经历，优势等出发啊，卖机械键盘？卖耳机？
  手机周边的产品（手机壳，自拍杆，手机镜头，手机贴膜等），BAT相关的产品，

  5W1H
  WHO：赚谁的钱？为什么是你能赚钱，而不是他们？
  谁的钱最好赚？（目标群体），让客户爽了，自然就容易掏钱出来了。如何爽，黄赌毒。
  为什么是你？你能什么提供独家的信息，新闻，价值？

  WHEN：什么时候赚钱？2018年如何赚钱？
  当前时间的热点是什么？BAT，微信公众号，熊掌号，

  WHAT：做什么赚钱？
  把机械键盘研究一番做机械键盘？还是写文章导流到网站卖机械键盘？

  WHERE：在哪里赚钱？赚那个地方的人的钱？
  互联网上赚钱还是实体店赚钱？赚中国人的钱还是外国人的钱？
  互联网竞争更激烈，但是体量，想象空间更大。外国人需要接触。

  WHY：为什么做这个能赚到钱？为什么是你能赚到钱，而不是他们？


  HOW：如何赚？
  写VPS相关的文章，写PorkerStar相关的文章，写机械键盘相关的文章，然后导流到自己店铺，赚钱。
  帮人搭建VPS，VPN？网上充斥那么多文章，如果保证你的访问量最大？ *精益求精，做到更好*

  所以，你还是必须得有独到的东西，深刻的东西，有价值的东西。有很多人需求的东西，还是一个厚积薄发的过程。
  不管是写程序，还是投机做期货，还是怎么的，只要某一方面很牛逼，很顶尖，独一无二，稀缺，那么来钱不是问题。

  你看看缠中说禅的博客就是，无论格局，视野，思维等等都是出类拔萃，非常牛逼的，虽然看懂得人没几个，但是也不妨碍他们进来膜拜一下，沾点仙气。
  最好的情况是将自己的理想，努力进程等，和这个过程联系起来。
  比如我准备听进天下最牛逼的音乐，然后做相应的歌曲集合，并写相应的评论，文章，那么这个就是独一无二的。
  比如我玩净各种音响器材，就能对每种评头论足，但是玩净器材的人很明显不会考虑赚钱一世啊。
  比如古人读书牛逼的，写字牛逼的，那也是一字千金，一诗千金啊。 *不对，这个过程可以是持续渐进，不断迭代的*
  ，同样也是可以包装成一个产品，然后进行出售的。 *关键点在唯一性，稀缺性* ，如果有同样一个也这么玩的人，你就要考虑 *竞争优势了。*

  有人轻松就4K多个粉丝？比如刚网上看到的分享电音的，这就是见多识广。
  有了粉丝后就考虑如何转化了，比如推荐听电音最棒的耳机；将电音制作成光碟，U盘等贩卖；和Bar，Club合作等。
  这个过程中，最主要是：思考，尝试，减小失败成本。
  对，还有个思维模式，我没粉丝，但是可以买别人的粉丝，或者和别人合作，分成。最关键是你的有一方面非常牛逼的技能啊。
  *或者这样：认识非常牛逼的人，然后借助，帮助他，使得他的技能能够变现啊。* 这个牛逼的思维想法和上面有类似之处，但是更加强大啊。
  想想刘邦，正是如此，他就是让那些非常牛逼的人，给平台，帮助他们将自己的技能变现了？一展平生所学，尽显胸中抱负。
  *所以要多结交朋友，多认识一些牛逼的人啊。*

  要学会“借”。很多人打工，不断往上爬，然后做出成绩，就是借助别人的平台来展现自己，等有名气，人脉之后，自立门口。

  那么我现在最想要做的是什么了？
  看净所有书？

  搞一个推荐股票书籍的页面，然后挂上广告？或者直接转到自己小店？关键是如何上量。基础，数量。
  最关键的是问问：你有什么？你有什么独一无二的经历，经验？
  还有个邪恶例子就是某人阅女无数，可以写写相关的东西。


  我现在大概知道如何包装一个产品并将它商业化了。
  搞一个学习交易时看到的好文章，好帖子，好书，好书评，好视频等，好电影，搞在一起。
  然后让人打赏，等流量高了之后，主动找人拉广告。

  关键是有人打赏吗？不对，问题的关键是：用户，流量。用户多了，流量多了，就有价值。
  可以这么搞，每个IP有免费的阅读数量，过了之后，就需要付费？感觉有点不太人道啊。

  即使没有任何受益，我在这个过程中，也是学到了更多的交易知识的啊。
  做这事我有什么损失？对，还可以引流卖电子书，纸质书的。还可以卖视频等。
  后面在搞一个房地产买卖的研究。

  刚才看了这个5W1H思维又扩散了点。
  做什么赚钱？赚钱的人都在做什么？有钱人都在做什么？大家都在做什么？微信公众号，你去做有什么优势？

  where：赚钱的人都在哪里？有钱人的人都在哪里？大家都在哪里？做些什么？

  when：赚钱的这事什么时候开始？什么时候结束？现在进入是不是晚了？你是什么时候知道的？
