* 到底究竟该如何止盈
  昨天晚上在2993止盈，平仓掉了豆粕1809的空单，同时反手在2992开多。
  之后就在2973止损出局。今天早上一看，豆粕1809价格收盘在2948左右，最低价曾达到2932，

  空单少掉了2992-2948=42的利润，反手还导致止损20个点，来去就是62个点，620块啊。
  真TM够郁闷的，不过仔细想想，问题还是出在我想的不够透彻。

  最近在读利物莫，如果我平空是对的，那么我就应该翻多。而且幽灵法则中指示：当放量的时候止盈，
  利物莫也说过：当市场有足够的吸纳能力，充分的流动性，就应该抓住机会兑现账面利润。

  所以我当时就在2993那个暴跌放量的15分钟内，止盈出局了。并且认为平空是对的，
  那么翻多也是对的，就在2973设定止损，2992买入做多，后面被大止损，而且发现
  后续的暴跌放出更大的量。而且在这个过程中，我还YY，主力肯定是针对3114以下20到30个
  点的止损盘进行打压，吸盘，毫无疑问达到目的，那么就会开始反向拉升，回补过大空头敞口头寸。

  我当时是这么在手机上写的：
  狂砸一波，不计价格的卖出，到最后只有很少的单子是已很低的价格卖出去的，
  然后就通过最后的少量成交价和引发的止损盘，知道达到了洗掉止损盘的目的，
  然后立刻反手，回补掉过多的空头头寸的敞口风险。
  主力在拉升行动前要把散户洗掉，不断的使用利物莫的手法，拉高卖出，低位买回，
  然后探知到各个价位的买盘，等手中筹码积累的差不多了，一口气狂砸下去，打穿阻挡，
  引发止损平仓盘，然后反手买回平掉空头头寸。
  通过最后几单的成交价，买盘的稀薄，知道自己已经达到目的。
  然后第二次再来试探前低，砸穿，看看是否放量，没有，就表明止损盘干净了。

  *现在来看上面我写的这段话，明显属于意淫。*
  对市场的杂念太多，定不住，容易出问题，自以为是的小聪明。
** 问自己几个问题
   到底该如何止盈？那先问问你交易的原则是什么？
   我交易的原则就是尽可能长时间的持有盈利的头寸，真所谓放飞利润，让利润奔跑。
   但是该如何放飞？我之前的操作经常就是死拿着盈利的单子，直到利润回吐一大半。
   我认为触发了以下几个标准之一，才考虑止盈：
   1. 持有空头盈利单，当多头力量暂时强过空头力量
   2. 价格突破20日MA
   3. 走势陷入震荡，无法再创新低
   止盈平仓这个东西还真是不好搞。

   那平空就应该翻多吗？或者就只是让你单纯的买入做多，你会在这个位置开仓吗？
   肯定不会，看看豆粕1809的走势，暴跌，5日线以下。
   如果我要做多，最少要等到下跌趋势企稳，其次等到空头力量无法将价格打压下5日MA，
   也就是多头力量非常强的时候再做多，与此同时一直观察空头的力量，而不是单单看多头的。

   *而平空翻多，平多翻空这种和单纯的做多，做空是不一样的。*
   *只有在走势出了问题，也就是上涨的趋势出问题，我们才平空翻多，反之同理。*

   所以我豆粕止盈出的问题在于：应该继续等待，等多头力量强过空头，或者等空头无法再创新低，
   或者空头走势无法延续走成了震荡，这才考虑平空。
   *与此同时，非常重要的一点：不要在15分钟级别上去看这看那。注意操作的级别，始终要是同一级别。*
** 开仓的问题
   今天早上试探了下，在3685放空螺纹钢，但是通过头寸很明显的感觉到多头势力为尽，相同价格平仓出来了。
   这说明多空在僵持。多头力量不强，空头力量也不强。

   后续我观察了下，不论是豆粕1809还是螺纹1810，下跌开始的标志都是非常明显的，都是经过二次确认的。
   这时，我突然反省，感悟到，原来我一致追求开空单在最高点。可笑啊，可笑。
   现在05-17 10:30这时的趋势，情形是最不明朗的。

   趋势，趋势就是非常流畅的走势啊。越流畅，力度越大的越好。现在不明朗进去很可能两面挨耳光。
   但是，我后续又想，如果在豆粕1809，螺纹钢1810，趋势确定时，那么已经价格走了一定距离了，如果再次反抽怎么办？
   这里就涉及到趋势的特性：连续。就是说，如果在下跌趋势中我卖出，那么价格就应该继续连续运动，如果没有连续运动，
   那么

   3216 3729，500个点，5000块，2手的话，可以再3516再加一单。

   *二次确认*
   *趋势的连续性，连续性的走势才是趋势*
