* K线有杀气整理
  任何一个交易方法表面上看起来可能很简单，执行下去就可以了，但事实上并非如此，
  它包含很多交易者独特的属性在里面，他的知识结构，他的习惯，他的性格，他在交易中所经历的很多事情，这些都是交易的一部分。
  那么，即使我告诉你一个方法，我用起来可能赚钱，但你用它做单就会稳定亏损，
  因为很多在我看来是常识或者习惯的东西，而你不具备，我们的经历和认知是完全不一样的。
  所以，构筑交易体系的工作只有靠自己。


  问：请问楼主怎样一步步地构建属于自己的规则？这过程中应该注意什么？
  答：学会每天总结交易的得失，收盘后根据交易明细总结，“失败的单子为什么失败，怎么处理才能付出最小的代价，成功的单子为什么成功，如何处理才能利益最大化”等等，
  学会写交易日记，把这些总结文字记录下来，一定要文字记录下来，不是想明白就算了，
  以后没事经常翻看自己的总结，成功的一部分可以复制，错误的事情不能一而再再而三的犯，坚持半年，你就知道了。
  这是一个自我专业化训练的过程。

  对于交易这种特殊的职业来说，要成为一名合格的交易者，必须有专业化严格的训练，养成良好的交易习惯，培养一流的执行力，但是并没有什么外力来帮助你，一切只能靠自己。
  很多人其实很努力，但就我所见到的来说，大部分人的力都没有使在关键点上，所以同样的错误总是在上演，缺乏严谨的、专业化的、残酷的自我训练过程。

  交易市场之所以难，就在于随机的不确定因素太多了，任何东西都可能是错的也可能是对的，但是很多朋友学习的过程本身没有一个严谨的训练计划，整个探索过程也变成了随机。

  随机中的随机是什么？混沌！所以很多朋友做了几年后除了身心疲惫外，其它感觉和刚入市时没有太多区别，因为你没有利用好这个过程中那些失败的和成功的经历，发生过的事情没有给你烙上印。

  问楼主：怎么把盈利单拿的足够长啊？
  答：不要离开你的整个交易体系去单独讨论盈利单持有的长短问题，任何事情走到极端了都不会有好结果，
  你必须分清楚，你追求是哪种级别的行情，你的目标和底线是什么，举个投机岛上现实的例子：zhnfem她持有盈利单的底线和目标都非常清晰。

  交易中的任何事情，只有介于最终目标和底线之间才是最安全的。

  问：请问目标如何设定？
  答：明确你操作的品种，明确你追求的行情级别，明确你要抓到的盈利幅度，不要奢望大小通吃，设定目标和底线，你交易的全部内容就是把你的头寸置于目标与底线之间。

  问：止损位的判断本人有一定的心得，但是止盈位的预测却不得要领？请教lz是怎么判断的？日内是否只做一个方向？
  答：大部分时候，止损和止盈本身是捆绑在一起的，不能完全分离来谈论，打开你自己的行情走势图，问自己，你的交易是希望抓到那种大波段，还是几个点的小波动。
  明白了你的目标，你就知道怎么去计划自己的交易，不要指望大小通杀，那是根本不懂交易的人告诉你的最销魂的自杀方式。

  问：对期货人最大的帮助就是不要做期货 这是一种99死一生的游戏！！！！！！！！！
  答：既然都已经进来了，就已经不存在诱导与否，每个人都在追求终极目标，如果连最起码的幻想都失去了，就不能称之为交易者。

  触及止损无条件离场，超过止损更要不择手段离场。

  你缺乏良好的交易习惯，很多习惯是残酷的自我折磨训练出来的，没有它法。

  交易是对称的"是什么意思?
  答：对称是指市场制造的波动归宿将是0，行情向上和向下走的动因是一样的，按照这样思维，任何信号的开平都只适合特定的时刻，一旦时间足够长，最后的资金的最好结局就是保本。

  交易中的很多问题很难用“是”或者“不是”来做结论，交易本身不是科学，不是可以通过数学能计算出来的，很多时候甚至自相矛盾。
  我前面说过，置侧是第一目标，就是首先把自己置身于浮盈的一侧，然后再去考虑自己的目标，目标的选取可以参照你的资金收益率，也可以根据历史行情。

  一般认为我们是在交易某个合约，其实不然，这个合约只是一个靶，我们真正在交易的是“机会”这个品种，
  在这个市场里，大小机会无时不在无处不在，你不可能都去交易，那样的成本和风险不是一个人能承受的，
  在交易之前，你必须明确哪种“机会品种”是自己的追求，基于策略的收益/风险比去参与。
  大部分人都是被乱石砸死的，因为他根本没明白哪种情况对于自己是安全的哪种情况对于自己是不安全的。

  有些东西你没有经历那个过程是永远不会感悟到的。

  做任何级别的行情我都只通过1分K线来选择机会，至于以后的走势，我更多依赖头寸给我的信息。

  如果你违反一次规则，你做100个俯卧撑，你能做到吗？残酷的手段很多，但在交易中很多基本的自律都难做好，我很怀疑你会不会去做这些看起来“没有用”的事情

  有时候为了灌输某些意识的东西，我们需要借助肢体动作，而不仅仅是坐在电脑前想，这就是为什么军人总在做一些外人看起来毫无意义的行为，
  这些行为其实本身价值并不大，每天都做那些规范动作看起来跟军人的作用无关，但这些基本的动作会诠释很多意识上的东西。

  开仓之前我会关注K线，开完仓后我可以完全不看行情软件，我只关注头寸

  但我认为最关键是就是处理那些在成本区域附近的单子，很直接向两侧运动的单子可以完全依赖策略来对付。

  更残酷的是单臂引体吊半个小时。

  所谓心态在欲望面前不堪一击，所以你必须依赖一套规则，就像类似于法律的契约一样，约束你的行为，但在交易中，遵守这种契约与否完全取决于你的自律，不像法律束于它律行为，这是最难的。
所以除了有一流的执行力外，还必须对你的规则有强大的信仰，潜意识的敬畏。

问：楼主，你认为你的方法可以复制吗？
答：任何人的交易都是独一无二的，经验永远无法复制，但基本的原则可以借鉴。

答：你还在沉迷于行情之中，在我看来，没有人能看对未来的走势。
行情是由我们这样的若干人在电脑终端输入的数据对冲产生的，没有人能预知那么多电脑前的人下一秒会输入什么样的参数进去。
基本面和技术分析在很多时候只是在给你做心理支撑，对的时候你可以说你的分析是多么精确，错的时候你也可以找无数个理由来否认之前的分析，其实并没有多少人真正了解这些分析到底和最后的走势有多少关联，50%？10%？80%？不知道。
这些东西是那些本身不做交易的理论分析师研究的结果，它是对于历史行情的研究的出来的，这些研究者本身是不会依靠交易吃饭的，但随机的魅力在于毫无轨迹可循，你只能用自己的头寸去“赌”。
当有一天你认为那些经典书籍和理论一直误导自己的时候，你才开始真正走向通向交易者的道路。
如果你执着于成为一名伟大的交易理论分析师，整天阅读那些理论能让你在应对面试官的时候口若悬河，或者文笔不错的朋友，可以尝试写一部经典的交易玄幻小说，我想很有市场。
这就是交易！

答：交易是从开仓开始，但盈利与否是从开仓以后才开始，没有人知道哪个点开仓是正确或者错误的，没有人知道。不要花太多时间在开仓上，实际上任何时候开仓都不是问题，只要你能处理好开仓之后的单子。
事实上，我们在开仓的时候受很多主观因素的影响，如果交易的时间长了，也可以称之为经验。

答：为什么一定要用单边和震荡来约束自己？
说点废话！
我个人不太喜欢讨论，我也不认为在交易的问题上互相讨论会带来什么建设性的东西，本贴里我只是在阐述自己在交易上的一些感悟，无关对错。
交易是一件“独来独往”的事情，试图让持有不同理念的交易者通过讨论而达到互相接受是一件不可能的事情，某种意义上说，交易策略并不会越辩越明，而是越辩越糊涂，一致性交易并不仅是对交易中处理单子的要求，也是对交易风格的要求。
交易理念的追求不存在对错优劣之分，更多是一种意识上的信仰，信仰的不仅是它的优点，它的缺陷你也必须接受，即使很多跟我截然不一样的交易策略我也没有资格否认，它依然可能是成功的，事实上，试图把每种交易风格的优点融合起来建立一套完美的交易计划是一件愚蠢的事情，因此，我没兴趣去和别人讨论以追求交易的更高境界。
但即便如此，我也乐见不同交易风格的人在本贴里表达各自不同的交易理念和策略，我乐于做一名旁观者，但很遗憾，目前我看到更多一些低俗言语的互相诋毁，没有任何值得思考的语句，通过这样的方式来达自己的异见总让人觉得缺乏品位。
我不是来拯救你的，也无需向你证明什么，如果你认为我的回复能触动你的某些交易神经，我倍感荣幸；如果我的言语让你感觉不舒服，我毫无歉意，因为，浏览本贴与否的权力在于你，没有人强迫你。
我是这么认为的，至于你如何感受并不是我所关心的。

问：您认为您能够盈利的最可能的原因是什么？
答：我认为“自己非常明确地知道哪些是自己做不到并能严格限制自己不去做”是我能盈利的最大原因，我很庆幸自己不是一个完美追求者。

答：单纯谈执行力比较空洞，缺乏执行力来自几个层面，交易策略有问题，缺乏对交易策略的信仰，以及性格的问题。

我只会获取那种自己策略范围内的机会，所以行情不会左右我。
不要过于受K线走势的误导，你应该专注于自己持有头寸的浮动盈亏的变化。

2、开仓和持仓对行情的依赖和干扰是完全不一样的，交易久了你会明白的，这一点也是很多模拟和实盘完全不一样的地方。
客观上，经验在某种程度上帮你开仓，而不是闭着眼睛开仓。
事实上任何标准化的开仓条件发生之后，行情向两个方向走的概率很难明确。

问：你的这句开仓之前的盈亏比，是不是带有预测性质？
答：没有，只是策略预期，也就是通过策略来界定属于自己的机会，所有不满足策略的都不是自己的机会。

问：总结了一些问题，想问问，不知道是否方便回答。谢谢！
1、按照我的理解，你的结算单中，应该分为四个部分：(A)几个点的止损单（开仓后发现与行情走向不对），(B)1到2个点的止盈单（开仓后略有浮盈即回撤），(C)五个点以上的止盈单（开仓后行情即狂奔，然后一定回撤后止盈），(D)因为意外情况，如秒杀行情或隔夜跳空行情，导致的十几个点以上的止损单。请问，是否是这样？或者是别的情况吗？能否透露下根据你实践下来A/B/C/D之间的比例？
2、因为股指期货和商品期货在交易时间不是完全一致的，所以股指的变动可能在商品的盘中带来开盘/收盘几分钟的跳空突变行情，这种情况有什么好的方法处理？依靠浮盈对头寸进行拨备？但是这样是否要求高了点？因为隔夜和周末持仓需要有浮盈保护可以理解，但是上午和中午两次休息，是否也有必要有浮盈？
3、“持有仓位，直到市场证明你是错的”和“在给定的时间内，如果市场没有证明你是对的，就平仓走人”两种思路比较，从实践上看，哪种更可取一些？
4、怎么预估自己的资金能够做哪些品种？是否按满仓能够做多少手来算？
5、从实践来看，持有多少仓位算重，多少算轻？还是没有固定标准，只看当前浮盈能否拨备现有的头寸？
6、交易期间是否你一直坐在电脑面前？还是偶尔走开让自动止损代劳一会儿？我感觉自动止损经常会亏的更多。
7、你是否认为期货价格的绝对高低是不重要的，现货价格对期货价格也没有参考价值？为什么？价格包含一切？还是因为我们其实只是对价格进行交易，其它的因素关联性无法判定，还不如不知道？
8、你是倾向于在激烈变动的行情中开仓，还是在平静的行情中开仓？平仓呢？
9、因为谁也不能预测行情，那么为了避免遇上极端情况，好像只好采用小止损和小回撤即平仓的策略，怎么样才能顶过回撤，把盈利的单子拿的长一点。有什么技巧吗？
10、一天的损失到了什么程度你会停手不做？如果一天的盈利赔光了，你会停手吗？
11、一天的交易量多少算正常？多少算过量？
12、如何防备大针戳止损的情况？
答：1、没统计过。
2、任何时候都不能把自己置于被动之下，如果你认为上下午存在跳空可能，那么没有盈利保护的单子就不要保留。
3、大部分时候，如果市场证明错了，那已经处于伤筋动骨的时候了。任何交易都应该跟一定的周期绑定。
4、没有量化的答案
5、没有量化的答案，这跟你交易中很多环节关联，所做的一切都是让你尽可能安全的前提下去盈利。
6、不需要无时无刻盯着走势。
7、除了你交易的合约，其它毫无关系，我是这么认为的，但我不否认相反的策略。
8、我很少在激烈的走势时进场。
9、除了不断优化的策略外，你还需要点运气，有时候你即使做到极致也并不一定能成功，这就是交易。
10、这个问题回答过很多次。
11、没有答案。
12、按照自己的策略执行，至于它是意外还是必然，抑或只是假象，无需关心

1、你的量化分析是基于大量客观存在的数据，静态的数据在测试下本身就是自我对称的，而交易是动态的，因为客观分析的前提是你的对手盘和市场也是客观的，这本身就是对称游戏，但你深入交易市场的时候不是这样的，你的对手盘被行情左右着。
2、你的分析并没有加上一些类似于交易经验的因素，而这些在交易中客观上有不可忽略的作用，尽管我不知道它的价值具体有多大。

答: 1、一致性保护很多方面，比如策略的一致性，执行的一致性等等。举个最简单的例子，比如你的交易的止盈是100点，而你做的第一笔到达了20点就反转回到成本价，你失去了20个浮盈，第二笔交易，有了20点的浮盈，你基于上一笔的判断平仓，但这一笔行情却到了200点。在这个过程中，你被行情左右损失了规则的一致性，因为你的上一笔交易的规则止盈是100点，如果这一笔按规则做，你总共获利100点，而失去了规则你结果只赚了20点。一致性的东西包含很多意思，它是基于概率的要求，只有同样条件下的事件，概率才有一致性。
2、亏损是交易的一部分，每个人交易者都必须习惯这一点，无需原因，你所能做的就是将亏损控制在自己可以承受的范围。


因为在没有外力而完全借助自律的作用下，大部分人是做不到自我残酷训练的，因为你即使违反了也遭受不到外力的惩罚，你最多懊悔一下，我想，这也是为什么大部分人注定了和成功无缘的原因，无论在哪个行业亦如此。
