* 对势力的理解
** 字本意
   “执”意为“在高原上滚球丸”。“执”与“力”联合起来表示“高原上的球丸具有往低地滚动的力”

   和权力联系很紧密，势家（有权势的豪家大族）;失势（失去权势）；权势（权柄和势力）；势子（趋炎附势的人）；势利（权势和利益）；势任（掌握权势的重要职位）；势利场（争权夺利的地方）
   又如：声势（声威和气势）；势耀（势力威望）；势倾人主（威风势力压倒了皇帝）；势派（气势；气派

   形势；情势
   又如：势促（形势所迫）；势面（世面）；势穷力屈（形势窘迫，力量衰竭）；大势所趋；守势；势胜（形势优越）

   又如：装腔作势，造势，借势，顺势，逆势，
   势均力敌，势不可挡，因势利导，
   表现出来的情况，样子：姿势。气势。山势。局势。虚张声势

   势必：按事物的发展推测必须会导致(某种结果)
   形势就像劈竹子。形容节节胜利,毫无阻碍
   权力，趋势，物理中的力场势，
** 势的词语
   势利，势力，势能，趋势，
** 成语
** 句子
** 书中引用
   《势》
   龙既是阳中之阴，也是阴中之阳。龙体永不竭尽地变化着，因此体现了以交替产生连续性的最佳例子。
   中国人以“交龙”这个双重形象来表现并且说明这种由永远在变化的龙体所代表的交替力量
   龙变化不息，它时显时隐，时飞时潜，因为“形其不可得而制”，龙因此被视为神圣的。
   龙从来没有固定的形状，因此显得奇异而且永远充满诱惑力，龙绝对不可能被控制，龙象征无止尽的超越。
** 哲学概念
   道生之，德畜之，物形之，势成之
   一方面，在相关词语后面加上“势”字，通常可以表示静态的或稳恒行进的事物的演变趋向
   另一方面，势又指某种影响力

   势字的义项源自于土墩斜面所给人的倾向感，以及这种斜面对“圆球”的加速作用。在某种意义上，环境就是各种斜面或曲面（包括直立面、水平面）的组合。推动或影响事态运行的因素有施动者所施加的“力”，也有事态环境中各种“斜面”所形成的“势”……细加考量，可以确定：势可以理解为用以表征事态演变特征的“加速度”，以及产生这种“加速度”的影响力。

系统内在的张力或外界的影响力是产生“加速度”的原因，它们对逆势而行者起着阻遏、阻止或改变行进方向的作用，对顺势而行者则起到加大运动速率的作用。它们造成行为处境的安稳与险恶的分化，改变行进过程的难易程度，


该势态所决定的难以被个别参与者所左右的演变趋势，即为事态局面的大势。
通过各种方法营造一种有利于预期的事态演变的趋势、大势，称之为谋势、集势、蓄势或造势。
凭借业已具备的趋势而推进，则称之为借势、乘势、顺势、任势……

孙子兵法·势篇》的“求之于势，不责于人”的说法，其精髓就在于通过事态的动力学分析来谋取目标的实现，而不是简单地责成于事态局面的某一参与者。

只有兼顾到事物目前的状态及其演变的“加速度”，才能对事态作全面的述说。古书中时常可见的“势使之然也”的论断

取势：“势”是大的发展趋势和各级政策导向，具体说就是市场形式和政府政策。
“势”往往无形，却具有方向，顺势而上则事半功倍，逆势而动则事倍功半。

“道为术之灵，术为道之体；以道统术，以术得道”；

取势：善战者谋其势而利导之
“取势”就是顺应潮流、顺应内外环境，顺势而上；
“取势”最重要。“势”按照现在的说法就是内外因影响下而形成的一个环境。
势又往往和时联系在一起，这就是时势。
企业应该顺应大环境，顺势而上，这个环境包括外部环境和企业内部环境


所谓取势，明道，优术：手段是术，人与品是道，大环境是势。
财富因势而生，会为道而停留。术面前，财富永远只是过客

无论多么卑微与渺小，都永远把自己置身在历史潮流中，
先做人，去追随并承担，再聚财，去分享和帮助。

很多时候，我们只是赚的一个大趋势的钱。有了这种谦卑而清醒的认知，你才不会偶有所得而志得意满，得意忘形
多数人之所以只是凡人，是因为他永远不会把自己的思考方式和行为方式上升到一个与历史趋势哪怕略微挂钩的高度，
而是甘于做一个完全无关历史的局外“小人”：蝇营苟且，自得其乐，与家国无涉，与族群无涉，与责任无涉。

取势而后借道。财富因势而生，为道而停留（厚德载物）

你的财富、你的成就、你的事业不会大于你的格局。一个境界低的人讲不出高远的话，一个没有使命感的人做不出有责任的行为。

随喜，赞赏，容人，助人，习人之长，补己所短，以做大做强自己，这是正道。挑刺，诋毁，自以为是，冷嘲热讽，这是歪道，一种恶习，它反映的是你的虚弱与不自信，你的不思进取与消极懈怠。

根本性影响的是什么：取国势，走正道，拿你该拿的。

看到比萨斜塔大家有没有感觉它要倒下的感觉？
这就是势！势就是方向，顺畅运行流动的方向，给人意像造成连续的想象空间。
连续呼应，力量，

整个市场，本质上，是一群乌合之众。
头羊，也就是意见领袖的决策，是引导市场走法的关键
现在板块想要有延续性，必须是游资和公募达成共识才可以。

这里有且只有题材符合国策指导（游资炒作），叠加板块低pe的属性（公募抬轿）。

才能形成合力。

没有形成合力之前，就是极速轮动模式。

3本黄金的书
golden f=fetters，黄金镣铐：金本位与大萧条
与天为敌，The Power of Gold
TheDeath of Money

趋势研究的是众人的走向、天地的走向。

众人的走向有4个基本观察维度：政治、经济；文化、科技。

从底往上依次是：文化（公众心理密码）、经济、政治。

文化是众人心理集合的公约特征，是人之世俗性的体现。

经济是物质的丰寡权利和匀极情势的动态分布图，人世所有中阶竞争的故事主线大都在此。

政治的内核是权力的分布地图、人世高阶纷争的焦点。

科技是天人交会的人世神迹，放在趋势四维度的最上面。

天地是第五维度。
势有变与不变！势不只是趋势之势；

趋势（或曰“情势、态势”）最大特点是“变”动不居！

人性之势、万物内在的运行规律之势——这两种势，几乎永恒不变。

以“政治经济文化科技天地”五大维度观之，每个维度中都有变与不变的东西。

** 势与能相互转化
与势相违，或寻不到势，必不可行！

项目可行，但是否可投，就不再看势，而是看“能”

有势而无能，就不能投，甚至宁可拿同样的项目另找人去做。

势与能之间是对立统一的关系。

——势本身即蕴含能，所谓势能：“势即是能”；

——有能才能借势成势，此时“能就是势”
有势且有能，有可能成事”

——为什么只说有可能，而不说一定？

还有运！

虽有势也有能，但运不济——事也难成。

很多事成，未见得在事先认知上已明势，只是恰巧点子踩准了——这就是运数造化。

然而『运』最不可控，只有保持赤子之心，多行善事；

其余但听天意，无须强求
