* 螺纹钢日记
   为什么我昨晚在3695开空螺纹钢，而又立马平了？
   因为我进去的当场就感受到了多头力量未尽，而且不对就错，立马就平仓出来了。
   但是很明显这导致了后来的错误，就是没有给多空，趋势一定的折腾空间。
   我太偏执的渴望，期待开仓在完全正确的点上，也就是一买就涨，一卖就跌。

   妈个逼，昨天晚上挂的条件单忘记取消，在3704点平掉了在3216的螺纹空单。

   05-16 14:35 现在螺纹应该怎么操作了？
   现在的心理状态很容易亏钱。现在局势还是不太明朗？

   05-18 11:00
   妈的，交易之前没有做好计划，第二，陷入了短期15分钟的涨跌，而没有使用限价挂单。
   第三，追杀卖出，3632的价格，我曹，不太好，不过后续应该是会在反抽时候继续加仓。

   最主要的错误是陷入了短期的追踪杀跌，15分钟的涨跌，盯盘盯得太死了。
   投机最重要的是抓住一波主要趋势，而抓住趋势是什么？就是你拥有筹码啊。
   在趋势中一直持有筹码，头寸啊。不是怕止损啊。看好的机会要重仓。

   首先我能做8手螺纹钢，如果我在3705空掉2手，现在就最少赚了1400啊。
   20点的止损，那么也是3730出局，前期最高点了。
   3705空2手，3685再空2手，为嘛？因为3705已经有了200的盈利，可以用来做止损。

   还有非常多做的不好的地方，主要是纠结于短期的涨跌，迷失在短线15分钟里面了。
   而其实本不需要关注这么多东西，而且短期的追涨杀跌，我禁不住诱惑开仓，让整个都变形了。


   05-23 为什么螺纹钢居然是最强的？
   郑煤，焦炭，焦煤都跌了4个点，螺纹钢才1.5个点。而且还错过了郑煤的行情。

   06-06 14:20
   早上想到了一个思维非常正确的点，就是可以使用假设，然后反向推理的方式，可以认为是幽灵法则一的衍生使用。
   比如拿螺纹1810来说，前面刚破3733的最高点，价格最高到3778，收盘3734。
   我们可以这样来假设：假设整个走势是一个多头的向上真突破，而真突破应该是怎么样个走势了？
   肯定是有个稍微下探，然后收盘价不会在3730以下，这种弱势形态最多维持3天，之后就应该开始暴涨。
   因为如果是真突破的话，后续的涨势就应该非常的猛，对这个应该没有异议吧？因为真突破解放了上边的套牢盘，
   空头也被打爆，打止损了，上方卖压很小，空头会去寻找下一个关键的阻挡点开空去了，所以应该是多头的天下，
   多头该表现了。但是目前的情况却不是这种情况，但是也不是做空的时机，非常模糊不清。目前看，多头稍占优势，
   但是持续性，力度都不行。
   现在是多头没涨，但是空头也打压不下去，还在5日均线以上，空头不给力，不知道为什么？

   还有就是3天法则，也是一个非常有用，概率非常大的工具。比如要开空之前，等待多头走势完了，再等3天。
   关键点突破后，等3天。

   刚看了下螺纹，很明显现在是错误的，一定要等待止损位置出局吗？刚刚已经以亏损1个点的成本代价，出局了。
   为什么？因为意识到自己错了。因为螺纹现在多头的表现还是这么强势，不到放空的时机。
   但是郑煤的空单有盈利，走势符合预期，继续持有。

   14:40 现在再看一下，妈的，牛逼，果然是对的，跑得快。
   那么现在郑煤的走势也需要好好观察了。

   现在很多情况下能做到对的，但是为什么不是做的多头赚钱了？因为螺纹钢区间有限？月线看跌？
   妈的，搞不懂。如果按照我那个朋友的操法

   所以，放空要等一方力竭，不然很容易被大止损，就是不断的错错错。最好是多空双方力量能够有个明确对比。
   妈的，期货主力都TMB的非常邪恶啊，刚最高到3788了，成交量巨大，很明显是很多止损盘被打掉了。
   打完之后，就开始跌了。今天非常关键的是： *观察螺纹1810的收盘价*

   06-07
   早上又想到了一个非常微妙的东西，就是如果按照你的挂单价格成交了的话，很可能走势会不对，为什么？
   因为假如我开空，那么走势如果是正确的话，就应该非常疲软，能够成交的价格就会非常低。
   而你开空，以一个期待反弹，较高的价格挂单，所以应该很难成交。
   真是诡异，如果走势是正确的，那么你挂的单子很难成交。

   第二个：最后再说一遍，不要把盈利的单子搞成亏损，即使你被扫了，然后立马下跌，也要保证盈利的单子
   有微弱的利润出局。而且那种被扫马上下跌的情况不太可能发生，即使发生，那也只能说明是你自己的开单时机不够成熟。

   今天郑煤很明显的突破前期月K的最高点643，最高价格达到645，而现在价格是635左右，
   非常关键的一个节点，今天看收盘价，是否站上643吧。

   苹果的开仓太冲动了，导致现在又亏损了600多块钱，今天早上螺纹钢2手止损亏400，
   郑煤本来赚了块2000，最后亏损600出场，妈的隔壁啊。郑煤是最心痛的了。狗日的，被大出来的时候完全是懵逼了。
   螺纹钢昨天晚上觉得非常不爽，狗日的个狗逼主力，很明显的疲软走势，还是狂拉，把空头拉爆了。
   我这个3820的点，是根据前期的阻挡推测出来的，而且的确是非常不爽，觉得我就是应该搞他一下，大不了送出去400块。

   今早一共亏出去1600块，这1600块钱中，600块钱是手贱，情绪太冲动（妈个逼，我真想日死主力），
   郑煤被大止损后，赚2000到亏600，狗日地，螺纹钢是非常不爽，而且觉得应该按照我的判断，月线级别是空头，该搞，该日。
   其实仔细想想，可以不亏？首先来说郑煤，按照走势预期来看，在15分钟线上不正常的情况下，就应该可以微利止盈出局。
   螺纹钢也应该是，也是个个逼啊，TMD的，（主力就是各种呼风唤雨，无法无天的）。

   破而后立，不破不立，好好TMB的想一想，为什么要破？我RTMB的，现在我想到的原因就是要达到多空换手。
   不然狗日的主力空头也是主力多头，没法倒货，没法制造陷阱坑傻逼散户，也打不掉空头散户的止损单，
   然后让走势流畅的走下去。

   很多时候，开单盈利了，但是我一般只对了一小段时间，后面就错了。市场真是不可预测。你不可能永远对。
   你只需要应对错误的时候，你甚至不一定非得在错误后正确，你仅仅只需要不是错误就好。
** 2018年7月10日
   在3876空一手，我有时候觉得很奇怪，为嘛明知道趋势无敌，短期趋势看涨，我TM却还是喜欢空。
   仔细思考了一下，是想证明你们都是傻逼，老子天下第一，哈哈哈。

   虽然现在的确是大概知道走势是个什么情况，但是还是有问题。
   我的走势出错理论是这样的：在一个时间周期内，不断上涨，直到走势出现问题，然后空头力量比多头强，
   并且多头反弹力量较弱，这时在反弹的时候开空单。

   但是非常要小心，谨防走势的再次不对。也就是空头向下突破很短期的平台，但是后续又涨回来了。
   其实这种小技巧估计会很害人啊。

   最好的开仓机会不应该是：多头反弹力度越来越低，一直在5日线下运行，然后开空单吗？
   现在即使符合我上面的走势出错理论，但是空头依然很弱，或者说多头的力量还没退却，这时开空单，非常不好，
   很容易造成强力的反弹啊。

   投机只需要会一招就行：趋势无敌。
   然后用大止损来提高容错，用走势出错理论来确定进场点。我个人觉得一力降十巧，大智若愚，
   也就是宽止损相比这些走势出错理论，具体的法，术要来的强的多。今天观察三联虹普得来的。

   那么就是2招：趋势无敌，宽止损。

   之前的那个撒：万达影业，还是什么的，根本不符合我上面这个走势出错理论啊。
   完全就是一个跌停板突破短中期平台，第二天开始一线板。

   所以问题是：如何确认趋势，和区分趋势无敌时的假突破，还有趋势反转时的真突破？
   以上涨为例，假突破前是盘整？向下假突破。趋势反转时是二次探顶，向上假突破？但是苹果也会这样啊。

   观察突破后的多头走势？万达影业是一线板啊。
   看向上假突破后的下跌力度？貌似这个东西，只能靠经验？

   投机整个说白了，就是欺诈与反欺诈啊。你想想你自己有时候是多么容易被骗。
   欺骗就要利用到你人性的劣根性和弱点。所以投机就是反人性的。这个逻辑说得通。

   三联虹普了？怎么看？明天是跌还是涨？
   创业板能走出独立行情吗？

   趋势无敌，但是任何不讨论，不限定时间周期的都是耍流氓。最牛逼的还是时间啊。

** 做的不好的
   其实有非常多做的不好的，主要是手法不够娴熟，心理不够强大，最主要的还是心理问题。
   1. 没有在3705上挂单卖出
   2. 即使如此，卖出也应该贴合在5日均线卖出，会比我现在靠15分钟短线上杀进导致拉低的均价好的多
   3. 心理依然不够成熟，一方面不停的盯着15分钟线不断的看盘，另外一方面今天5月24日居然不停的安慰自己，
      说没事的，反弹没事的。自我麻痹。有事没事，我都决定不了，也安慰不了。
      *市场发生了，给出的事实，我只能面对，只能尊重，只能在当时采取对自己最有利，最明智的处理。其他的都改变不了，我只能控制我自己。*

      而这种自我催眠有什么用了？甚至非常有害吧？
** 更大的规律及法则
  今天早上（5月24日）又想到了，如果期货投机，就像我现在想的，感悟到的这样的情况，那么那些搞了十几年，几十年的老油条，
  为什么会爆仓倒闭，跳楼自杀？难道是水平不够，心理素质不好，心态出问题，风控做的不够？我估计都不是。

  我想到的词汇有2个：九死一生，九胜一败。想到了项梁为什么会兵败被杀？因为胜仗打多了，人骄傲了。
  一骄傲，最大的风险，不利因素大多来源于自身，这时就是最危险，最脆弱的时候，因为强大的自己成了最强大的敌人。
  而且这种骄傲的弱点能够被别人更加扩大，利用。
  所以，项梁就败了一次，一次就死了。没得翻身余地。
  我又想，那人能不能不骄傲了？这是不可能的，人即使不骄傲，但是盈满则亏，月盈则蚀，这是万事万物发展的必然规律。
  阴极阳生，阳极阴生，九死一生，九生一死，这是必然的。所以，急流勇退之人才是真的大智慧，大气量啊。
