* 期货品种关联性相关性联动性
** 相关性
   所谓相关，要么具有替代性，要么具有互补性，要么属于产业链上下游，还有一种具有统计上的相关性。
*** 1、替代关系
    A.豆油、棕油、菜油
    B.豆粕、菜粕
    C.天然橡胶、合成橡胶(国外有合成胶的期货)
    D.焦炭、焦煤
    E.黄金、白银
    F.铜、铝
    G.聚乙烯(L)、聚丙烯(PP)、聚氯乙烯(PVC)
*** 2、互补关系
    A.铁矿、焦炭、焦煤、硅铁、锰硅
*** 3、上下游产业链
    A.大豆=豆油+豆粕，菜籽=菜油+菜粕
    B.原油=燃料油+天然气+润滑油+石脑油+沥青+各种副产品
    C.铁矿+焦炭+焦煤=螺纹钢D.玉米=玉米淀粉
*** 4.统计相关
    A.股指与工业品，的正相关，这波股指飙升之前相关性强，飙升后各自走行情，一天一地；
    B.工业品与工业品间，的正相关，比如铜与原油与橡胶，都受宏观经济形势影响；
    C.同个产区的不同产品，的正相关，比如，北美都生产棉花白糖，都受自然灾害影响；
    D.美元与黄金，甚至美元与全球大宗商品，的负相关。
** 豆类
   大豆和美豆的关联性很高，但是关联性最高的是豆粕和豆粉。
** 塑料
   L的走势比较独立，主要看成交量，一般成交持仓上去才有行情，也就是游资指导行情。



　　PVC因为中国主要原料是电石，比用石油便宜很多，所以和原油没有多少关联性，主要要看地产指数，上证指数。



　　PTA和原油没有任何关联性。为什么呢？从产业链来说，PTA是用原油生产出来的，怎么可能没有关联？这是因为生产PTA所用的石脑油是副产品！！！不是石化企业的收入的主要来源。

    当汽油，柴油的消费旺盛，石化企业加工原油多，利润丰厚。原油消耗的多，价格上涨，但是加工所产生的副产品石脑油供应会更多，反而产生利空。反正，分解原油利润下降，生产量减少，原油价格下跌，但是副产品石脑油反而供应短缺，利多。现在明白了吧，以后千万不要看原油做PTA了，错的很离谱。

    据郑交所得报告，PTA和上证指数的关联性在80%左右
    PTA在中国一直是供应多，库存高，
    PTA的主要利空就是下游聚酯消费不旺。而PTA的主要利多是石脑油供应的短缺，开工率的下降，下游聚酯需求旺盛
** 白糖
   白糖是投机盘
   中国的庄要在白糖上圈钱，不能使局面无法控制。广西那边中国糖其实被垄断的，消息也是垄断的，90%以上的糖在珠江期货，长城伟业做套保，其实糖就是他们的后花园。

    糖这个品种其实就是一个投机的盘子，他符合了2条最基本的条件：1、产量少。这里是相比其他大宗商品说的，庄可以轻松控盘。2、不是民生主要商品，国家干涉力度小。
** 焦炭，铁矿，螺纹钢
   这两个品种的供给和需求看，中国都是最大的生产和消费国，和外部关系不大。
   主要受国内政策，比如基础设施建设的影响。当经济低迷时，国内消费总是无法拉动经济
   （如果你要问为什么？这就要分析中国国情：钱都在富人手上，富人只能拉动奢侈品消费经济，
   普通百姓没钱，怎么消费？），所以政府为了拉动经济，都是用投资，什么是最好的投资？
   基础设施建设，高速公路，桥梁，政府大楼，产业园区，等等，都需要钢铁，也就需要焦炭了。
   所以这两个品种受国内国内宏观经济的影响很大，一个政策就可以使趋势反转。
   例如，2012年9月初的城市轨道基础设施建设，让连续跌停的螺纹刚和焦炭反转直接涨停；
   又如，2012年12月初的城镇化政策，让螺纹钢和焦炭趋势反转连续上攻。
** 有色金属
   黄金，白银，铜，锌，铝，这些有色金属价格和外盘联系非常紧密。
   原因很简单：如果价格相差太大，很容易套利，提着几十公斤黄金飞美国不需要多少时间。
** 期货品种和生活
*** 上海期货交易所
　　铜、铝、锌：电费、房价、汽车销量等
　　燃料油：交通工具
　　橡胶：轮胎
　　黄金：年前是黄金需求旺季，年底结婚的人多。
*** 大连商品期货交易所
　　大豆：用于压榨，产生豆粕、豆油
　　豆粕：猪肉价格
　　豆油：家庭、餐饮行业
　　玉米：主要用于生产加工饲料
　　棕榈油：同豆油
　　塑料（L和PVC）：塑料管道、农村的薄膜等
*** 郑州商品交易所
　　白糖：甜品（如中秋节前，是白糖消费已个小旺季）、夏季的饮料等，还有糖果厂等
　　小麦：粮食价格
　　早籼稻：粮食
　　菜油：同豆油
　　PTA：涤纶的原料，主要用于纺织行业。
　　棉花：衣服
*** 中金所
　　沪深300股指期货：我国宏观的经济环境。
