* 总结
  前几天，棉花1901的亏损，终于是让我看明白了。不是开仓的方法问题，而是开仓的时机，火候问题。
  然后结合PTA的走势，验证了一点：期货的技术流和股票是一样的。以股票来看待的话，清晰的多。
  而且以后都在招商证券上看，在另外的软件上下单。


  最近两天表现的非常棒！
  首先一点，看到期货PAT暴涨，我就联系到了股市里面PAT相关的股票最近应该也不错。
  然后百度PTA相关股票，看了看，还真的的确不错。从所有化工板块里面选出了荣盛石化，的确走势是非常好的，
  周五的时候克制住了，必须要等到收盘后才采取决定，当时就准备买入的。终于还是克制住了自己，主要是那天被打怕了。
  刚跌停前割掉了先锋新材，然后买入风华高科，刚买入，TM的当场就吃了个跌停。我曹，一天吃2个跌停，心情郁闷的要死，
  虽然仓位小，但是这个完全就是抽我的2大耳刮子号码？作为一代股神，一天吃2个跌停，我曹，还那么准。所有自选股里面就这2个跌停了。

  第二天看反弹无力，风华高科割了。当然这股后续还是会有表现机会。

  这个地方的犯错就在于：还没二次探底，看到一根大阳线5%以上涨幅，就一头扎进去，活该亏钱。
  没看空头的反应，这个短期低没二次验证。（底部二次验证，头部二次确认？）还有就是以后做的话，肯定是要等回调站稳5日均线在搞的。

  然后今天星期一，本来都已经入金2W到股票账户了，但是坚持的原则是：大盘没企稳，不搞。即使放过了荣盛石化这只股票，没赚到也算了。
  早盘荣盛石化最多涨了块4个点啊，当时真是差点没克制住。然后后面好了，盘中又TM跌停了，真是够准的。
  买撒，撒跌停啊。

  然后还有个问题是：我推荐的三联虹普和荣盛石化给我一个同事，我同事居然告诉我他另外一个朋友，也推荐三联虹普和荣盛石化给他，
  两只股一模一样，这TM的也太巧合了吧。A股几千只股票勒，这让我意识到一个非常大的问题：很有可能我被捕捉了。
  你看看今天的三联虹普和荣盛石化，三联虹普是跌停，荣盛石化是跌了8个点以上，刚推荐什么股，就什么股票暴跌。
  我的自选股里面，这两个跌的最多，最狠。

  当然，三联虹普的走势完全在我意料当中，而且后续的走势我也清楚的很。简直，感觉现在自己就是主力肚子里的蛔虫，
  当然，如果走势不按照我的预期来，也没什么问题，最终还是要落到操作上。

  但是现在的问题是，既然我知道三联虹普，荣盛石化，我那同事的朋友也知道三联虹普和荣盛石化，那么我们2个人知道，其他肯定还有另外的人知道。
  那操盘的主力肯定也是知道的，既然主力知道我知道，那么主力就能采取针对我的措施，所以我就能够被主力捕杀了。
  所以今天三联虹普就跌停，我非常想买的荣盛石化就早盘线拉高诱多，然后盘中杀跌，跌停引发恐慌，吸货。

  所以那天买入风华高科的时候，一买就跌停是一样的。主力也是知道了我咋想的，我的动向，所以就故意这么搞的。
  然后就是在之前的新城控股也是如此，知道很多人是用20日线做止损，止盈，就将收盘价格维持在20MA上，然后第二天杀跌停。
  还有的TM更恶心了，直接60日线上开始跌停板，我曹，跑都跑不了。


  郑煤的走势，就像我之前推测的那样，在附近这个点位，开始暴力反弹了，还好我TM没空，还是多看，多观察，少动手。
  很明显郑煤不应该介入，做空，先看看反弹的力度，现在你看到了。做多，不应该在底部做多，虽然现在的确如我预料的开始反弹。
  但是假设如果在我预测的点位后继续下跌了。
  而且显然郑煤不值得搞，值得搞的都是最强的。现在市场中，多头值得搞排名：甲醇>PTA>PP>沥青>PVC，所以，我又搞了最弱的？
  妈的，做多最弱的最危险了，要等待时机做最强的。之前那次PTA和棉花直接从涨停到跌停。而且其他的黑色系，都没跌停，第二天创新高。


  郑棉也如我预期的再走啊，可惜追高了。我悟出拿点之后，时候来看，的确是介入的时机不对。
  还有就是还是犯了错，追高了，没看到下跌就开始行动了。


  现在用招商证券看期货行情，将期货当做股票来看，真的是太清晰了。

  很多时候，你入场了，然后被打止损了，不是你方向错了，而是你时机错了。这个要结合趋势的力度一想就非常清楚了。

  棉花1901现在肯定还不是搞的时候，今天的走势也验证了这一点和我的猜测。
