* 最近的投机笔记整理
** 如何加仓？
   将每一次加仓看做单独的买入或者卖出？
   3705开2单空，3730止损，跌破15分钟上的最低3636，等反抽，在3653附近加仓。
   为什么？
   （其实我现在不完全是开仓，加仓的问题，而是没有紧紧跟随市场。比如螺纹的操作，
   知道现在空头走势不对，那么就应该平空翻多。但是固执，固守认为月K的空头趋势，而有钱不去赚。）
   3705~3653最少有50个点的利润，在3653开空，止损最多20个点，也就是3673止损。
   如果发生了，加仓的那笔交易立马止损出局，这个时候还是不赢不亏，但是第一手马上准备跑路。
   第一手不可能止损，不用等到3705就可以跑路。这样无论加仓是多少比，出局时的止损亏损都是固定的。
   1. 为什么要等破3636？
       因为这是15分钟上的关键点，破了，表明的确如我所想。
   2. 等破了这个关键点后才考虑加第二单，为什么？
      因为如果不破的话，走势很有可能只是在3636到3705之间的震荡。
   3. 破了之后才有足够的利润来抗止损，抗反向波动。
      而且即使都被止损我最多亏损也就是初始化时的第一笔单子的止损。

  我们所有的决策都是基于不确定来做的，甚至有很大可能性失败。如何在即使是失败，也将损失最小化，
  控制在一定范围之内，这就是我们要做的。好好想想，如何在以不确定性为前提下做决定吧！
  开仓，平仓，加仓等，都是以此为基础。

  利用人的贪婪和恐惧和技术指标来达到操控。为什么持有的时间越长亏损越多？因为买在最高点，卖在最低点。

  2018年5月22日 20:30
  豆粕创了新低，但是走势没有延续，可以认为下跌趋势出了点问题。空单可以选择止盈平仓，
  也可以选择继续在看看，因为多头没破5日均线。
  还有就是止盈的原则也是要结合到周期的。

  最难的就是不同周期的级别，毛刺，贪婪，恐惧，支撑，阻挡等。

  思维中有个非常重大的错误：总认为有某些事情是一定的，总想等反弹加仓，
  这个TM的是不是和想等回调后买入一样愚蠢？你怎么知道一定会反弹，一定会回调？
  我们要做的是：回调时，我们也有足够的止损，利润去抗，去对冲掉，不会危及到本金。
  我等待螺纹钢跌破小平台后再加仓，但是你怎么知道跌破后不是一去不复返？
  我这思维中居然有很多假定一定会发生的事情？？！！而我自己还不知道！

  为什么错过了郑煤的行情？
  为什么螺纹钢跌的没有郑煤猛？
  哦，我其实很早就大概知道了，螺纹钢因为没破，不是涨势出问题后下跌。

  急性转换是非常难的。
  3620设置止损，预计亏损在1600，加上回吐利润4500，不到一天的时间。
  又要重新开始，这次最大的问题是：价位的问题。还反了一个错误，将盈利的单子拿成亏损。
  主要是加仓后均价拉的太低。

  胆子太小。
  交易原则：不要让自己陷入被动的处境。

  市场中的每一天都是全新，无止境的战斗。
  25日
  原来市场走势就是这么神奇，螺纹1810收盘低于之前的小平台。

  现在思维中有个非常错误的想法：
  一定要捕捉到转折点。错错错，大错特错。一定要跟随市场。转折点来了，就接受它，应对它。
  还有就是这转折点，就像之前的支撑多，阻挡空，如果认为这就是转折点，在这种情况下：
  趋势都是非常纠结的，甚至不应该称之为趋势。趋势的特点之一就是：非常流畅。
  所以，开仓一定要等破而后立。但是做多会简单的多。

  什么时候趋势不对？空单时，多头比空头强就是不对的。
  所以，反推，开空单时，空头比多头强才是对的，或者说：等到空头比对头强，在开始开空单。

  既然知道了是破而后立，那么就等待关键的突破，然后再15分钟线上观察，然后开空？
  错错错，这个上面的思维还是左侧预测的思维，右侧追随而不要左侧预测。
*** 等待的思维和跟随的思维
    我之前有个非常大的错误就是：等待上涨结束后的盘整买入，这往往是错误的，风险很大的。
    趋势一旦停止，说明走势除了问题。
    所以应该在上涨途中直接上车，不要等回调，等盘整之后再买入。
    如果发生了回调，盘整，那么说明上涨趋势出了问题。

    非常关键的一点：通过视觉和感受，一定要分出多空双方的强弱，力度。要等待多头力竭，
    在开始开空单。
    （你看，我上面的这个想法又犯错了，还在左侧等待，而不是右侧跟随，等出现多头力竭，空头强大，
    再去右侧进行跟随，面对，而不是一直在左侧等待。利物莫当年的等待是等待空头力量弱到不会回调。
    我这里的等待是：面对市场的多头趋势，不去拥抱做多，等着多头转换成空头，再去开空。多空都赚钱，好吗。）

    Trend Following
    如何区分trend，如何following，这就是投机的精髓。
    也就是等待空方发难，然后看多头表现，然后再开始行动。
    大多数人是左侧预测思维，右侧跟随交易。

** 你为什么做多？
   赶紧会涨。你现在问我，我也会说感觉会涨，但本质是：感觉多头的力量比空头强，而且空头现在非常弱，
   连5日均线都打压不下去，我不会被洗出去。

   现在还不到放空的时机，螺纹钢多头还在赋予王康，而且局势还不太明朗，价格也没到很容易设置止损的位置，
   最关键的是空头还没发难，多头还没展现出力竭的样子。

   目前的操作，很多地方还不完善。

   其实开仓之后的走势就能立刻告知这次开仓对不对，而不用等待反弹。
   比如郑煤开空单后，下跌很扭捏，不流畅，那么大概率开仓有问题。就如良风有幸说的：“
   回踩60天线后的上涨应该是非常猛烈的。”如果不猛烈那么就是有问题的。

   同理，18年6月8日晚上的郑煤就非常符合上面说的这点。
   假突破前期历史高点643，然后盘了一日，第二日之后就开始猛烈下跌了。
   妈的，我的问题就是止损设置的太紧了。

   苹果的操作是追随，跟随市场，螺纹，郑煤的操作是预测市场。
   可以一直不停的假设，然后看走势，然后印证对对对，对，错，对。
