* 韬客帖子总结
** 我的外汇感悟
   格言 1：每一次下单你都可能会输，所以止损是最基本重要的生存第一步韬客外汇论坛* A5 Z# L' F( l
   实战心得 1：欧元20-30个点止损，英磅30-50个点止损，因为超出这个数，你的入场点肯定不好"

   格言 2：市场具有随机和规律二个方面，你只能赚到规律的钱韬客外汇论坛0 {- v' m; V7 Y4 g+ v4 C: B& R/ r- L
   实战心得 2：不需要系统、公式、指标等等，只盯价格的波动，经验和直觉告诉你怎么走就怎么做

   格言 3：最重要的投机技术是趋势方法，市场所有的走势无非是驱动和调整的反复交替www.talkforex.com( )) e* t, y% U- l
   实战心得 3：下单前必须明白自己可能处于趋势的某个阶段或某种状态中，这直接决定了你后续操作，比如止损、加码、平仓、清盘，推到重来等交易决策

   格言  4：最难处理是趋势或波浪的级别问题,所以操盘经验,那是相当重要汇,汇市,外币,汇率,炒汇,保证金,美元,日元,英镑,欧元,网上外汇书店2 q! P" l- T2 [# {8 o: S3 d$ u
   实战心得 4：多年前我就明白各种投机道理，现在仍然觉得每年都有进步，各种行情见多了，操盘功力随之增强，没有人可以随随便便成功，有新手总想弄个系统、指标就能成功,近乎白日做梦，痴人说梦话

   格言 5：止损象呼吸一样自然，顺势象流水一样简单
   实战感悟 5：如果在流畅的趋势行情中赚不到钱，那你就很难赚到钱，长时间地持牢赢利单，意味着可能是顺势单，相反，则可能是逆势单，最完美的分析，都不如孩子般眼睛看到的趋势方向。很多时候，我们是放弃了简单判断，却使用了复杂的分析，结果离真实越来越远外汇
** 终于将2万美金变成了200万美金
   人是有梦想的，
   像保罗.都铎.琼斯学习。

   情绪就是一根火柴，
可以点亮一切，
也可以烧毁一切，
成败皆情绪。

说起来简单，做起来步步小心。
判定趋势，逐步加码。
利润跑起来，快速止损。
最重要的，就是承认错误，处理损失的速度。

只有当这成为一个习惯深入骨髓的时候，
才会取得成功。

只有抛弃微波动
关注主趋势
交易才会更悠然自得。
大部分品种大部分时间都在做无效的窄幅波动，
如果陷入到这种区域，
那么当主趋势到来的时候，
你会茫然失措。
我们所有的一切努力就是在关键点跟上主趋势，
占好自己的位置

市场充满神奇，
周五重要数据公布之前，
市场逆着波动，
在数据公布临近当天，
市场收回失地，
处于一个新的临界位置。
市场在困难真的来到面前时，总是迎难而上，上涨
在这之前，是在担忧困难中度过，下跌。
交易中数据的学问。

市场总是提前走的，意外很少。

越大的时间框架，所呈现的阻力和支撑越重要，
在大的时间框架内，寻找4小时介入关键点。
交易频率不是自己决定的，
是市场给的
严格遵循交易系统给出的机会
因为进场的点位肯定是关键点，
严进场点，
止损点设定当然就不难了。
如果止损设定让你很困难，
那么你的进场就有问题。

兄好，
通过这些年的交易来看，
技术不是最重要哦
做杠杆盘
最重要的资金管理了，
可以说是情绪管理
和科学的根据交易品种的风险报酬比、波动极端值、目标值来决定仓位大小能力
对错不重要，
因为有无条件止损。
只有不愿意接受损失的人，才那么看重对错。

要想活下来，止损能力是关键。
只要活的久，就能在市场学到更多的东西，
才能成功。

既然说到技术，
我的优势在于波浪思维和价格波动结构的分析
别的，大家几乎都有一样吧。
当然，要稳定赚钱，
一种技术就够了
你说的突破建仓，break，就很好，胜率很高，保持一致性的执行，就很棒了。

兄好，
各个品种杠杆倍数不一样哦。
没有一次性下单这种想法哦。
都是根据机会的大小和预期风险和目标，
分次加码。
先有市场现实，在此基础上拟定市场未来情节，逐步通过投注验证自己的想法。
除了一些硬性的交易原则外，
下单是动态的，变化的。
随行就市。

通过看回帖，很多朋友对交易时间框架，交易频率，止损空间，一次下单多少，
貌似都倾向于定死。
其实，不然，这些都是活的，不是僵硬的。
根据机会、你愿意承受的风险和预期利润的大小，
来做决策的，每个人都不一样。
每个人的性格不一样，时间框架也不一样。
你只需要交易你舒服的时间框架就好，没有优劣之分。
关键是在这个时间框架内，保持执行的一致性 。

唯一是死的，就是设定止损价，无条件止损。
坚决止损，不要尝试移动止损位，即使侥幸对了，下次也逃不过的，市场自会惩罚那些自以为聪明的人。
只有快速成功处理错误的人，才能赢得生机和辉煌。

另一个，就是坚持自己的交易系统，有信号就执行，有利润，没有卖出信号，就坚守。
交易什么最难，止损难，坚持一个有盈利的仓位难。

有正确的理念没用，只有转化为正确的交易习惯，融化到一个投机手的血液里，才能成功。
多次割肉和多次坚守之后，将迎来不一样的交易层次，因为割肉和坚守对你来说理所当然，很舒服的一件事情。

看错永远都不会让你失败，
失败的是自己的贪念和情绪化，
仓位过重，不止损(论坛提示:跟单有风险)。
在这场生死存亡战中，跟止损一样重要的， 是耐心。
耐心等待关键点。



看法是次要的，
关键是应变。
纠错和坚守的弹性把握。
有一个合理的仓位，这些处理起来就容易了，
否则难以做到客观化，什么都棘手了。


不客气。
赢的关键不在使用的工具
更在于忍耐力。
投机的指标越简单越好。
一般也就趋势线和均线就好了。
对波浪结构理论有所掌握，可以开放你的思维和格局。
有时间可以看看艾略特波浪理论。
这个理论不是叫你数浪，而是培养这种波浪思维方式。


投机到后来，真是说无可说。
对于老鸟来说，都是多余。
就是看和干，
认错，再来，强势回归。
控制好回撤，稳定积分。
切忌想一招毙命，一夜暴富。
一场持久的存亡战，活得久才能活的好。

有朋友问什么书籍好，
Livermore的书就足够了。
其余的还真没觉得什么好。
幽灵的礼物简化就是3句话。
做杠杆盘的，这些技术类书籍还没什么大用，
关键是修心吧。

书籍看过不下100本吧，
现在脑子里几乎记不住特别有震撼力的经验和教训。
因为就归结于那两句，截断亏损，让利润奔跑。
而这个完全是个人交易习惯、心态和境界的问题了。
久战了，就知道这是一切了。
说起来容易，做起来难。
至于交易系统，只要50%成功率就足以了。
后面就是一致性执行问题了。

不同的人占据的位置
以不同的时间周期看，
看的方向是不同的。
风险回报比合适，止损容易设定，
对于我来说，就足够了。


耐心和格局最为重要，
至于那个关键点偶尔犯错也很正常，
有个好的止损位置就够了。
时间会给出答案。
赢家未必每笔都会赢，也未必每次都能判断正确。
我想我总是会过早进场的错误，看到了钱，未必就是我的，需要更耐心点。
但是我不贪婪，仓位和止损合理让我能坚持的更久，也能在合适的位置逃离一笔失败的交易。


q3出来后，无论是我放空的指数期货还是铜、黄金，都没有出现对称中的升幅。
我的投机更多的基于各品种指数本身的结构，而非完全基于当前的信息刺激和惯性涨升动能。
小的结构和格局，总会服从于更大的结构。
至少到目前为止，我还持续掌握着自己的位置优势。
黄金击破我当初设定的1775止损位，
对于我来说一点都不意外；
前面首次构筑头部的时候从1790区域推动开跌，之前横了5天；
后面两次都反弹都切到了这个区域，这次再去扫这个区域，也很正常，
对于空方来说，这是个极限位置，放空是自然选择，如果继续沿着这个方向上被突破，
那么就是结构方向的错误了，也是自己彻底认输的位置，否则前面几次的空单，
都是方向上的试错单子而已。当然还是心急了点。


抛开真假不谈，交割单根本无助于学习，因为谁比市场更聪明，能比市场走出来的事实更能证明你的对错了。
同样的市场，同样的时刻，每个人想的都不同， 仓量，能忍受的风险，能持长的时间都是不同的。
还有多少次的试错单。说看交割单学习，其实就是笑话。

耐心等待吧。
设好止损。
在阻力附近，先看空。
被击穿再说

不是做超短哦。
做方向波段。
所以不累的。
选择一个流畅不纠结的市场。
观点也不用老变，无需时时做判断。
所以的努力是为了抓住一个波段转折点。
持续跟随加仓。
其余都是在观察，试错。

这个位置在技术趋势上来说处于一个混沌位置，
开仓比较困难。
先不谈方向，
止损难以设定，除非超短。

一个好的进场点，止损一定要轻松设定。
这是一个安全阀，也是一个关键点的标志。
不想被市场强奸，就先戴上安全套，这样就会存活很久的，
当我们成为老鸟的时候，赚钱就容易了。

现在应该是你做减法的时候了，
除去繁杂，力求简单。
开悟到执行有好长的一段路要走，
有的人走十年，有的人几个月。
无论是短线还是更长的时间框架，
都要立足于既有的趋势粘性，
然则，就要反赌趋势极端。
从更大的局去看微观的波动，
这样胜算就很大。

投机是生活中的一部分，
与人斗，更是与己斗，修身的过程。
我也做股票，一部分精力花在这上面。
做外汇，我前面说过，更多的是做策略和格局，适当运用杠杆和仓位控制。
舍小求大。
多大的胸襟，多大的浪，多大的盈利。
想要赚的多，我们有时候也要承受的多。
得失与影随行，看怎么权衡了。

格局就是一个更大的时间框架上的空间位置。


   永远把自己处于一个无欲无求的状态，不要被环境中的各种杂音干扰。
   不要给自己任何目标，设置任何任务，自己就是宇宙中的一粒尘埃，谦卑，平凡。
   看过坛子里太多的帖子，有从500美金做到19.1万的，然后又开一个帖子，重新做，结果这哥们被一片崇拜之声搞晕了，心态变了，账户爆仓，人也消失了
   还有一个女汇友，账户做的不错，还差几十美金就整数了，结果给自己制定了了一个到达整数之后就换一无敌伞（佳能5d3，数码相机），结果导致心态变化，操作走形，资金回撤

   所以，不要关心你的资金，不要有任何目标，顺着自己最自然的状态，认真的，完美的完成你的每一个操作，就这么简单。
   看淡一切后，1850万美金，和1850美金还有区别吗?
   佛家讲的好，人为什么会迷失自己，因为一切相皆是虚像，人由虚像生妄念，由妄念生分别心，由分别心生执着，所以，放下执着，分别，妄念，你就能看透一切，得到开悟，得到智慧

   你就是一个平凡的操作者。
** 我系统的胜率
   我好想从来没仔细想过啊，认为每次开仓都必须正确？
** 拒绝下树的猪
如果你还在把大把时间浪费在研究开仓这个问题上，那你就纯粹是一个分不清轻重的SB，记住是SB，不是BS。

这样说不等于老子否认开仓的重要性，而是想告诉你，行情是无序变化的，很多时候的行情是人的情绪化产物，永远没有一个可以一直用下去的“信号”来指引你未来行情怎么走，永远没有。如果你不是特别弱智，或者不是特别懒惰，你可以统计分析一下过去的行情，要分析足够长的时间，同样的“信号”之后涨跌在概率上没有明显的差异。

这并不是说无法提高开仓胜率，可以，但这个是日积月累的，当你遇到过的行情足够多的时候，你会知道很多时候在那些时候进入风险比较小，但这些东西完全不可量化，因为它包含了太多经验性的东西。

炒个鱼香肉丝，同样量化的方案，一个优秀的厨师和一个菜鸟厨师炒出来的味道是完全不一样的，天差地别。。。。。。因为有很多东西是经验的积累，无法量化的。

老子说这么多的意思是告诉你，如果你打算玩好交易，把时间用在有用的地方。


我就搞不懂，随便一个垃圾策略，只要不是非常白痴的策略，坚持下去，想亏钱都难，不信你用模拟账户测试一下，但是为什么有那么多SB天天亏钱呢？


我来告诉你们怎么靠期货赚钱，别瞎鸡巴折腾，也别相信什么技术，就一个赌字，重赌，赌那种超级大行情，赔率很高的那种。

你回望了一下历史行情，任何一波大级别的走势你最开始都绝对有一定的认识，只是你没有坚持下来吧了。


关于交易，我们首先承认一个既定的客观事实：那就是无论做什么样的交易，无论长线短线还是长短结合，最终盈利的都是少数。

只有完全承认这一条你才知道去纠结做长线还是短线是多么浪费时间，自己喜欢怎么做就怎么做，刻意地改变自己习惯的交易方式除了带来不愉快外，不会给你的盈利能力增加一丝一好的帮助。

关于指标，那是扯淡的，它就是在价格的基础上加权计算出来的，无论均线还是什么线，他本身没有客观上的方向指引，按照概率来说，在同样的心态面前，向两个方向发生的概率不会差太多的。

关于止损和止盈，很多人追求小止损，但记住行情无论往哪个方向走都不是一蹴而就的，它需要一个空间来运行，包括回调空间，所以你的止损一定要留出足够的空间让行情运行，彻底封闭空间一侧的人跟猪一样蠢。

关于技术分析，我跟你说没用，但你不会相信的，几年前我也不相信，问题是我真的无法说服你不去相信他，因为不客气地说我们站在不同的高度。


期货新手和耗了几年的老油条的区别在于：新手认为一切可以确定，而老油条认为在投机市场没有一样东西是靠谱的。

如果你和一个刚入市的人说期货就是在赌，他会潜意识鄙视你的，因为他认为自己在从事一项伟大的事业，跟赌无关，当你熬了几年后你才明白期货就是在赌。

你看那些炒房赚钱有几个搞过技术分析？天天在那里搞技术分析的整天唧唧歪歪房地产要蹦，都说了几年了。

实战者和嘴盘的最大区别，就是后者相信技术分析是可以预知市场的。

做期货也如此，看准了就豪赌。。。。。

没在这市场痛苦地熬上一两年黑暗时日，没稳定操作手法之前，就想以小博大，想稳定抢钱，想着翻翻的美梦，你让我们这里在这个市场混了几年的老油条情何以甚，都这么好赚钱，那谁还去工厂三班倒，去背晒修铁路。。。。。。心态放平，先能不暴仓慢慢来，能赚点钱了，再考虑加大仓位大搞也不迟，做投机最不缺的就是机会了。

当一切完美时可能是假的，当漏洞百出时却可能是真的———这个世界就是这么奇怪，而大部分人总是缺乏自己的思考，活该成为垫背的。



我一直相信：做期货的大部分人都是SB，在投机岛上大部分人用行动证明了我这个观点。

那个艾XX，一开始我就说过不是好鸟，事实证明了这一点 ，那些粉丝毫无选择的是追寻，他们用行动证明了他们是SB，印证了我的观点。

而现在，又有一帮家伙忘记了自己的本业，一切的追着帖子骂，大交易时间的到处去寻找人家的漏洞证据来证明人家是多么假，犯得着么？浪费那么多精力在口水上，你们证明了你们跟之前那帮粉丝一样SB。

在投机市场，没有绝对的正确和错误，没有真和假，不要试图去追求绝对真理。

在这个市场，一切赚钱的手段都是欺骗。。。。。。。这就是投机的本质。



不要再拿“期货大部分亏钱”这样的调子来蛊惑人心了
你进入这个市场不正是因为这个吗？不正是因为绝大部分人亏钱才有利润可图吗？如果90%的人去赚10%的人钱有个鸟的意思，反过来才有趣，不是么？



你也许认为我疯狂 就像我认为你太过平常
如果多一次选择 你想变成谁?
不，这不是选择，而是对自己的怀疑。
我能经得住多大诋毁就能担得起多少赞美，如果忍耐算是坚强，我选择抵抗。
如果妥协算是努力，我选择争取，如果未来才会精彩，我也绝不放弃现在。
你也许认为我疯狂，就像我认为你太过平常，我的真实会为我证明自己。
做期货的人，不跟随


大家似乎历来不欣赏我这种做派，而喜欢中庸、四平八稳.
但是期货这个而行业，需要那种特性独立的才能成功。


所有棋局都是公开的，有人之所以将其归结为阴谋是因为没有看懂--------  行情亦如此


我相信大部分散户都是SB，而大家又用事实证明了这一点。这就是我这样的人在期货市场赚钱的根本所在，尽管你可能不喜欢我！


最误导人的一句话，可悲的是很多人还当着真理--------“要做事先学会做人”
这句话不知道误导了多少人。
无论中外，看看以前和现在的那些成功人士，有几个是人品的好的？正好相反。
** 投机岛论坛good888的帖子
止损就1-2个点，或者打平出局
有了在普通行情保证不亏的胜率，就可以不断地用0成本试探去抓大点的波段，大点的行
没有这些小手段
在抓到大鱼之前的回撤，就能把人消灭掉

投机的精髓，就是寻找一个大幅波动的行情，或者在研究怎么在已经大幅波动的行情中获利拎着你的止损，刀山敢上，火海敢闯
** 四年卧薪尝胆的回报，100w达成！刷新了韬客暴利的纪录
   在确认趋势之前，我也不敢随意重仓，只是到后来趋势确认了，我才敢放手一搏。

澳元空单我不仅仅是重仓，而且中间回调反抽加仓位置精准也是令我相当自得。

英镑这一波，我最早在1.647一带就布局了100手的重仓狙击，事实证明我的计算也是相当精确。

看书看书看书，看盘看盘看盘，每天一般都是1点睡觉，期间还挂警报以免突发事件，天天不间断，除非手里没有单子，虽然没有亲笔画K线，但是看盘时间绝对超过每天12小时。

日常是这样：早上起来，先看一下美盘尾盘的走势，看看有没有遗漏的，然后上午刷和讯等国内的外汇分析师等等的博客，11点准备下午欧盘盘前准备，13点预备，有时候欧盘的单子已经出击，15点收到订阅的免费国外分析报告，别小瞧，有的确实不错，dailyfx的去翻翻，反正不花钱，16-17点看数据，晚饭后，着手美盘前准备，看美盘前分析报告，基本上确定今晚的作战计划，20：30后，基本数据都出来了，走势也基本确定，23点，如果没逆转，就可以安心了，0-2点，通常是对付重磅的FOMC会议之类的，必看。


   谢谢捧场，这次确实有运气的成分，后期悟透了交易的真谛，能坚定持仓是扩大战果的原因。全部都是手动下单。

我的交易风格是比较激进，但我是重仓紧止损，可以说是玩精准狙击的一套，入场时间不定，这也是没办法，主要看是否已经符合入场原则，而且有时候，会选择在一些比较容易逆转的时段入场，比如说美盘23点的时候，而且做空也是需要计算日期，我会选择测算的变盘日特别专注盯盘。一般是看日图决定强弱，然后用H4来选择大概入场点位，最后按M5 M15入场，止损一般是高一级时间框架下的止损。

有时候会挂警报，比如说澳元反弹到某个价位，就自动提醒我，然后我就会看形态是否符合做空的条件，如果感觉比较合适，就会入场。

不敢，之前因为出门没看盘，结果被迫砍了100手多单，亏损4W+，你应该也看到了。我当时因为对美加把握不大，所以特别犹豫纠结，最后看到回踩了200日均线，然后通过我自己的货币联动理论判断，所有商品货币都崩了，加元不可能独善其身，崩盘是迟早的事情，所以就重仓紧止损博了一把，结果运气不错，所以技术面和基本面结合起来，分析操作都事倍功半。


今天的震荡行情，对日内交易是一种煎熬，我上午稍微有点急躁，太早入场被扫，后来下午沉住气，耐心试探趋势的方向，晚上在德拉基讲话后，重新重仓做空欧元英镑和澳元，现在欧元英镑空单已经大获全胜，澳元也是命不久矣，顺手还多了点美加，就等明天非农爆发了。

大神过奖了，现在资金量慢慢在稳步增长，只要市场走势符合自己的预期，就放手一搏，利润爆发式增长，如果发现走势不符预期，那么肯定是哪里有问题，这时候冷静仔细分析和观察，该止损就止损，尽量不要介入自己看不清的行情走势。

目前来看，我基本上盈利的一单可以抵过3个亏损的单子，算是对交易有了自己的心得体会，等年底看看能否把交易理念系统的总结一下，以助广大汇友一臂之力。

1.楼主起步资金是多少？平台的杠杆是多少？看楼主的图片，没有看到最初的资金就开始交易了，后来入金的都看到了，中间有断续
起步就是1w左右，期间有被损一些，后来断断续续补回到1.5w

2.楼主的止损是如何设置？市场很多情况下都是来回的扫损，如何避免
止损一般是50点以内，来回扫就是说明市场还没有一致的方向，应该改为震荡交易，直到出现一致，比如说这次德拉基讲话。


楼主过去4年爆过多少仓？没有经历过爆仓的刺痛教训是无法达到今天的成绩的！

总共爆过3次比较大的，2w左右，总共亏损应该有人民币60w左右，还好家底比较厚。
** 选来选去还是来talk吧，这几年感悟讲一下，还有现如今国内外汇散户的不良风气
    快做父亲了，突然有了些责任感之类的东西。所以特意注册的账号上来做一点点贡献吧。06年刚毕业到北京接触的外汇，毫无疑问是跟一个骗子学习的（当年骗子横行，哥全赶上了），前前后后交了几万块钱学费，技术指标学到不少，想赚钱绝对say no 。mini账户亏了一个又一个数不清了当年都是250美金开户的，后来顺势去了北京一个叫印尼富汇的公司，这是我接触第一家外汇公司（其实就是一ib租了一办公室而已，但当年觉得自己特nb已经走上了社会主义康庄大道，聊天都是一天赚几万美金巴拉巴拉的）结果就不用提了，然后去了上海搞私人团队巴拉巴拉的结果也不用说了。但为什么人都喜欢说叫拼搏呢，什么样的人有什么样的命，你必须去拼才能拼到自己的命。我在北京已经进了国企，自己辞职去的上海这就是拼。拼到后来有幸结识了一个外汇券商在招交易员（为什么说有幸，因为这些券商是不公开招聘的，不信你可以查一下。都是熟人介绍一般都是高资历的。这个券商名字就不说了反正下面ib早全国铺开了还是国内桥接商总代理），有基础的我很顺利进入这个机构一直到现在。从一个整天满嘴指标的毛头小子，到成为成熟的大叔交易员，到现在在currensee也算有一席之地。（不用让我拿证据我也不会拿，我只想做一点点贡献不求大部分人的认同）！
   好了前面废话这么多就是简述下这一行业的不容易，相信有心人自能学到东西。现在进入主题。再废话一句，（07年我上过所以知道一些草根阶层活动范围，这次有这个想法之后又回过头了解了一下，个人比较看好talk所以来这里了）
   进入正题，这么多年我接触的形形色色外汇交易员（都是顶尖交易员）没几十个也差不多了，券商优势就在这里门路多，但还是有相当一部分是通过后台从散户中挑选的精英。还来过几个外国人，是大老板从朋友那里找来的（刚来时候闹一笑话，我正对着我的8屏亮瞎眼工作平台做眼保健操时候突然大老板领进来，说来介绍一下这位是eric我英文名，这位是什么什么忘了我英语太差，然后帅哥过来给我握手并且说Howdoyoudo。我一时语塞心想我的回答必须酷一点啊给大老板张张面儿，结果直接回答一句YEAH！几个人当时表情就冻住了，我这话唠的毛病改不了了又跑题）总之接触这么多对各种交易方式都有了解。当然最后这些人也都被时间所淘汰，其实不是时间后面我会说到。喝口水一会继续


   当我有这个想法之后回过头看了一下散户们聚集的几个贴吧，发现风气依旧，依旧如06年我刚入行时一样，装神弄鬼者居多，讲到点上找到问题的太少。整个外汇风气都是在误导新人。深思之后发觉这是本能不是故意为之。大部分都在讨论某一个技术指标，更多是讨论某一个交易系统。
   迷信某一个交易系统，迷信某一个人某一段时间的交易记录，各种求师拜友，各种寻找捷径。这是其一
    其二，发帖子的人也多喜故弄玄虚，讲话都要引古论今，还喜欢说一些，真理大道理让人只能说，“哇太对了，讲的话太对了，谁谁谁真厉害”其实细细推敲就能发现不过是一些前人早总结过的废话空话。（实在人肯定有我这里只说大风气，请不要对号入座）
   其三，各种赚钱截图，有截图今天几个单子赚钱，有截图一段时间资金曲线的，还有交易记录的，悲痛的是，这些身后往往聚集着更多的膜拜者。我很负责人的说一句话这些记录都是可以造假的，即使有不造假的也说明不了哪怕一点点的问题，合格的交易员根本不看这些。

   因为学习外汇自然是从无知开始，自然要各种尝试，所以研究某一指标某一系统崇拜某人都是可以理解的。我也是过来人当年对骗子师傅那是五体投地。我今天是来为国内散户外汇氛围做一点点贡献，哪怕有一个人学到知识就值了。继续说
   我的建议，各种指标不必要全部了解到（不要钻牛角尖，全部的意思是强迫自己必须学某种指标）。看自己缘分有幸了解了某个指标就用某个指标，但是陷阱1绝对不要使用太多指标来构建系统，指标多了就好像精美的仪器，零件很多很容易出问题，经常自相矛盾，自相矛盾是可怕的，因为你很难发觉是系统出了问题，因为矛盾所以总有一个是对的，你就会想下一次使用对了就行，但是下一次自相矛盾还会这么想。新人学习外汇就像在漆黑大海里游泳找到陆地就活找不到就死，但是漆黑一片没有坐标不知道方向，我很负责告诉你，只根据自己缘分中的指标，关键是深入的复盘（复盘是重中之中，你要是告诉我你从不复盘，那请你趁早转行），这个深入是你要找到你所有能找到的历史盘进行研究，我当年研究时保存的excel文件达到700多m。你们可以对比一下就行。只要你用心深入那么技术上构建系统就不是问题。
    陷阱2不要研究别人的系统，不要想走捷径，必须自己深刻领悟深刻感受充满自信的指标信号才能构成你的系统。别人的只能是误导，因为你根本不了解。有人会说我拿别人的系统复盘就可以，哥哥这里不打口水仗，那么多年的检验直接告诉大家了，能听进去就是缘分。系统必须自己建造！
    陷阱3这是埋葬大部分优秀交易员的陷阱，一般散户都达不到踩这个陷阱的要求。这也是哥哥多年经验的积累精华都在这里能学到的尽量学吧，希望以后国内氛围可以更改。这个陷阱就是，去追求一个东西。比如追求胜率，追求投资回报率，追求风险比，巴拉巴拉。我接触那么多优秀交易员，之所以说是优秀因为他们已经有了自己的系统，而且一段时间内是可以稳健获利的，但是可惜毫无意外都在追求这些东西，我眼睁睁看着他们从辉煌到陨落，时间真是太奇妙了，外汇交易残酷就在这里，你的系统只要有一个缺点那么时间就会让这个缺点要了你的命。这部分可能比较笼统我尽量说细点

     这部分主题是告诉大家系统有一个短板，就要死。时间会证明一切。有人说我不怕短板我重仓赌博，呵呵赌博就不要提了，赌赢了还想继续赢，输了还想捞本巴拉巴拉总之就是系统不是这么来构建的，我先说上面的再说怎么构建。
   一般常见的就是追求胜率，追求投资回报率，追求风险比，胜率很容易理解一般追求胜率的单子都是赚几个点好一点的十几个点就走了，好打住，那么请问亏损时几个点走，这就是短板，如果也是几个点十几个点走那胜率肯定高不了，短板就在这里，亏损时容易抗单，甚至锁单。而且追求胜率的人往往都有一张表格，不信你问问。那我印象深刻的交易员为例，他来到公司后就在身后的墙上写下了满满的预期收益表（公司墙是可以写字的玻璃墙），几何倍数增长的，最后几栏已经达到比尔盖茨等级。几个月时间确实nb几乎都实现了每天的要求，可惜结果就是几个单子抗完回到起点，然后周而复始最后。。。
   追求投资回报率，短板就在这个几乎比较固定的投资回报率上，太死了必须到这个回报率才走，差1个点也不行，试问差1个点止盈最后却拿到止损的单子，对你心态会有什么样的打击。这个事短板，正视也好不正视也好他就存在
    风险比，每次都想最低风险获得最大回报，呵呵吧，同样的一个优秀交易员，真nb 50点止损拿了3个月赚了1000点以上，我们让他走他不走说要到1500点，后2个月反转，这一单赚了20点走的拿了半年，
短板没有具象的，哥哥这里只是举几个例子，每个人短板都不一样，但是道理相通，有这个缺点，时间就会让你完蛋。


说怎么样构建成熟的系统，就要说一句，玄乎的话了，兵无常什么水无常什么的。。。。真记不得了。以我为例吧，我的系统几乎可以解释所有行情，但是我做的行情只有那么几种信号，算了还真不能说我，以免有广告之嫌，说总体吧，很负责人的说这么多年经过时间考验成为合格交易员的人只有2个，然后我们有一个圈子都是各大机构的交易员也就不超过身上指头数（这里不继续爆料了）。总之系统一定不是短视的，是可以掌握一个货币对完整走势的（请和所谓趋势单分别开）这种掌握是大局上的掌握，一般都是多时段的，不要说你只看一个时段，那肯定是井底之蛙，比如你只看1h，但是4h已经碰到了一个千年顶，但是你根本不知道因为你不看4h，你还用1h做多单怎么可能赚钱。有人说我用1h做空行了吧，这次行了，时间会告诉你不行总有做反的时候，我们大老板管不住自己手，在欧元1.5几做的多就是典型只看一个时段的后果例子现在单子都不知道出来没有。
   总之就是想掌握大局就要多时段去看，其中还有很深奥的道理，我不具体说，一定要自己去领悟，我不希望让大家刚脱离一些陷阱又进入我的固定思路中。
   构建成熟系统有了大局还要有具体的信号，这个信号很简单是顺应你的分析的。但是重点是一定要进退有据，绝对不可以因为感觉要涨而做多反之亦然。为什么不可以我会告诉你还是因为时间，如果无理由仅仅凭感觉入场，那何来立足之本，一定要进退有据，进场有信号，离场也要有信号，这个信号时通过大量复盘自己复盘的来的，所以大家一定要努力，不要想走捷径不是自己的东西绝对用不好。
   以上就是成熟系统要有的东西，确实很简单，千万不要复杂。但是上面只是技术指标，你还可以结合基本面，我们有cnbc bbc nw的直播但是基本没用，我可以很负责的告诉大家，几乎所有的重大消息前，庄家都已经入场，我的信号会清楚显示出来，所以大家努力吧，不要总归结于这个消息太突然才导致的亏损，no，根源是你系统部完善。突发的基本面消息，不用担心，在技术上他往往体现为一根大影线。
   说了这么多还有一个重要组成，等我吃了饭再聊，一些优秀的交易员应该可以猜到是什么

  要成熟就一定是掌握全局的系统，如果你执着的追求某一个东西比如胜率回报率等等就会迷失了双眼，变的极端，变得只知其然不知所以然，这样自然会有短板。但是一个掌握全局的系统就不一样，一定要多时段来看来分析，但是多时段不是简简单单去用的，这里面的问题是要通过大量复盘来解决的，所以绝对不是一个简单的事情，不要想走捷径没有捷径，为什么说0和游戏永远是大多数人亏钱，不努力亏钱，努力了方向不对也亏钱，只有个别运气好的交易员才能走到最后。
  说了这么多接着上面的。构建系统只是成熟交易员的一小部分因素，最难的一道坎就是心态。很多人一直在瓶颈里就是这一环，因为很少有人提到，而且关键大家还都知道，一说心态很重要什么的，就会有人说我知道，但可惜一般这么说的都是不了解心态的。心态要我说就是最终BOSS，就是能否蜕变的关键。反思我这几年，好几次深度危机都是心态造成的，在我技术成型后（就是很少需要修改很少出现系统外的单子）有半年左右都处于不赚不亏得情况，神奇的是复盘就会发现都应该赚钱的却闹了这么一个结果。更极端的是在如此成熟的阶段也会出现心态失衡，心态太难以防范。很负责人的说去年我有3个月几乎没有一单赚钱，这3个月我每次亏损都分析，都严格查看是不是心态又失衡了，但是却发现没有失衡。各位知道到底什么原因吗。绝对想不到，当我一次和老婆吵架后，陷入极度冷静的阶段，我拿出交易记录把每一单都反复推敲，结果发现很无语tmd81%的亏损是心态失衡导致的。这个极端的例子就是告诉大家心魔这个东西，是多么的厉害，无时无刻不潜伏在你身边，关键你自己问自己有没有心态不好时，他还会蒙骗你说心态ok，其实心态早已失衡。心态失衡的具体表现我不多述，以免大家陷入固定思维。这一段的意思就是和心态的斗争，是伴随终身的，不要想一下战胜他，他就潜伏在你身边只要你有一点漏洞他就会趁虚而入，直到今天我都很害怕。
    好像前面没有提到不要迷信交易记录的问题，交易记录都是可以造假的，最简单的办法就是锁单，只解锁赚钱的单子这样交易报告将是完美的，但是未平仓单子确实巨亏。交易绩效表也是可以造假的，只需要多个账户反向操作就可以，甚至ps最简单。一般机构根本不看你的记录，人来了之后就是实盘交易6个月或更久，这是机构的优势，单子可以选择打出去还是不打出去，所以可以直接实盘交易。所以大家不要迷信交易记录，更不要相信暴力，我负责任的告诉你们成熟的交易员绩效是什么样的
    我的日风控是2%这个比例已经算高了，因为我系统很稳定。然后我们几个的长期交易记录基本上年绩效20%左右，一般都是一年中会有几个月亏损会有几个月赚的多几个月赚的少就这样的。不要想暴力几单翻翻什么的，那是不成熟的交易员的表现。但是我们是因为大账户所以如此操作
    我的个人账户基本日风控是用5%最早是20%所以翻翻也很容易，因为是小资金（偷偷告诉你们我开户就250哈哈）好了大概其就这么多了以后想到什么再补充吧，有问题我也会抽时间来看看，希望这个风气可以改变，那些华尔街同行早已进入ea时代，我们中国差太远了，大家一起加油吧，come on baby！！！


   怎么说呢，不管你信不信，我的系统显示了整个市场的一个逻辑关系，要反转要回调都是有道理的，有时候体现在次级有时候同周期

   根据你的系统来复盘，看看你系统什么情况赚钱什么情况亏钱，赚的时候多时段什么样，亏得时候什么样之类的
** 交易之道 献给还在挣扎中的兄弟们
   所以在这里你能学到什么呢？一些交易本质的知识而已，至于会否成为为你创造利润的工具，那还要看你是否能够深切的理解，并知行合一。
　　接下来说说交易之道
　　交易之道只有八个字：生存第一，赚大醅小！
　　理解了这八个字也就理解了交易的本质。
　　首先分析生存第一
　　进到这个市场都是为了要赚钱的，钱多到没边或者只是玩票性质的除外。
那么就要考虑一个持久发展的问题，如果你可以聪明到只是进来玩一次，赚了走人，
亏了也走人也可以不必关注生存这个问题。也就是说我们进到市场是来进行一场旷日持久的战役，
而不是打一次战斗，战役就不能着眼于一时一地的得失，只需要最后能够取得胜利即可。
此处可以参考孙子兵法中的“善战者不羞走、昔之善战者，先为不可胜，以待敌之可胜，不可胜在己，可胜在敌……”去多多的念叨，并且深切理解。


人不抗拒改变，但抗拒被改变！
　　每个人都守着一扇由内开启的门，别人怎么用力，怎么推你都不可能替你开门，改变的动力源泉来自每个人的内心。
　　思想观念指导你的行为，尽管可能你没意识到。行为日复一日的重复就会形成习惯，习惯是命运的关键点，习惯是你的奴隶，可以帮助你塑造自己，也可以成为你的主人，使你受习惯的驱使。多个习惯集中在你身上体现就会成为别人眼中的性格，而性格会决定你的命运。所以命运由我不由天，首先要有开放的胸怀，去接受，去包容，去思辨，以正根源，也就是观念。正观念之后其后的一切才可以顺理成章的出现，否则只是无源之水，放弃是迟早的事。


在我看来，交易你只需要记得四率就可以了，依次是：胜率、赔率、破产率、纪律。重要性由前到后依次加强。
现今社会最大的成就不是绚烂的物质和发达的科技，而是实现了把人都关在笼子里！思想的牢笼。绝大多数人都在用自己的肉体去实践着别人的思想！

大部分交易者追求高胜率的系统其实本能上是在追求安全感，追求确定性，人心是很害怕不确定性的，
所以希望自己能够看透明天，可现实是确定性永远不会出现，而不确定性是唯一真理。
唯变不变。只有你接受不确定性，安全感才会油然而生。承认吧，我们永远无法预知未来，
这个世界是非线性的，测不准的！所以，别再把精力浪费在追神和造神上了！

交易之道，生存第一。如果盈利和生存相抵触，请选择生存，否则自作孽，不可活。
** 且行且珍惜——第3~5年的时光
   欧美天图20年的行情
   从2012年9月到2015年3月，这是一段异常艰难的时光，因为所做的事情是“破”。打破已经成型的交易系统，打破已经养成的交易习惯，打破跟随自己三十多年的思维体系，重新认识并打破（甚至是打碎）自己。破比立更难的原因在于，“立”指向“得”，“破”指向“舍”。人天然的想要得到害怕失去，更不用说主动去舍，所以内心经历诸多煎熬，痛苦挣扎。

其中最难的是对思维方式的突破。需要在生活或交易中仔细观察，找到自己惯常的思维模式，分析解构这种思维方式下自己的行为模式，再去查找这种行为模式的弊端。打破自己虽然也很难，但主要难在开始，难在勇敢面对不再逃避的那个开始。而对思维方式的突破，难在过程，同时难在没有前路，没有教科书，没有老师，只能靠自己一点一点的去磨，去挖，去耗。在这个打破的过程中，各种东西轮番上阵折磨人。原本以为自己对市场已经有了一定的了解，结果发现这了解远远不够；原本以为自己心态很成熟，结果发现面对考验时仍然一塌糊涂；原本以为已经拥有了自己的交易理念，结果发现这理念在操作中反复被自己质疑；原本以为已经了解了足够多的交易技巧，结果发现各种技巧相互干扰无所适从。这就是自己这第3~5个交易年头里每天的常态，反复纠结，就像把稻草一遍遍从底部翻起堆上来沤粪的过程一样。操作也做的臭气熏天，糟透了，甚至不止一次感觉自己不会做交易了。



生活中大家都拥挤在这条被主流价值观框定好的路上，鲜有人有勇气执着的去走自己的路。
至少在我生活的阶层里，大家都是被框定束缚在某种标准下的笼子里。
这时候不从思维方式上做突破，任何举动都是困兽之举。
交易中想赢，就要让自己去接近去做怎样弄笼子这样的思维，至少要明白笼子存在并如何运行的机制。
窃以为，那些无法善始善终的技术分析流派的大师们，就是并没从根本上把自己从笼中解放。
交易做的就是自己对世界的看法，做的就是自己心灵的境界，不管自己是否意识到。

操作依然停留在想努力寻找好的进场时机，期待进场后的每一单都能盈利这样最初始的状态里。

截断亏损让盈利奔跑的理念指向“应该多把时间花在如何扩大获利与减少损失的技术上”，面对同一个交易机会，这种扩大获利减少损失的技术指向 头寸管理 的技术。
头寸管理的技术重要性是在分析行情技术重要性之上？至少两者应该结合？这里缺太多。
