* 棉花1901
  棉花涨了2%以后，我就觉得的确是符合我的预期在走。当时想挂单买入做多，价格是16950，挂了几次没买上。
  然后又盯了会盘，被每时每刻的行情勾引出了欲望，盘中开始了行动，犯了第一个错误。
  买单价格挂在17070，市价，追高了，这是第二个错。

  晚上的时候，还翻红了，内心一阵窃喜，最多的时候赚了100多个点，窃喜的我认为赚了就拿着。
  后面又亏回去了，睡觉前，价格刚好是成本价。当时不断拿手机看着，像个傻逼一样。

  晚上吓的睡不着觉，时不时爬起来看一下，看看是涨了还是跌了，过一会，又爬起来开一下，是涨了还是跌了。
  早上打开一看，亏了70个点。

  今天上班时，也是不时的看一看，希望反弹回去，立刻就卖掉，盘中最低跌到了16935，
  但是当时想的是我16950挂单的话，16935一样要拿着啊，但是我的仓位已经亏了很多了。
  当时的感觉非常难受。
  在后面，继续开始下挫，达到今日最低16750，也就是说，我最多的时候亏了1600多。
  当时的感觉就是完全被打蒙了，内心感到震撼，麻木，手足无措。

  但是即使我现在看这个，怎么看，都是明显的多头行情啊。（到底通过看出来很明显的东西是不是错的？）
  趋势无敌，但是涉及到具体的操作，加上期货的杠杆，完全没用啊。
  还是得有良好的开仓，占据优势的开仓点，如果刚开始就有盈利，入场前就设置好了能接受的止损点。

  其实还是操作上有问题，应该等回调之后再看是否介入。回调的幅度是否过大。
  但是这样就是正确的吗？有的可能在这里，直接15分钟级别回调后，继续上涨。
  等回调完成之后？你怎么知道回调什么时候完成？如果你都知道回调什么时候完成，那完成后直接买入不就行了？
  追高是错，震荡买入是错，徒手接飞刀也是错，回调后买入也是错，什么是对？

  即使我按照16950的价格买入，我现在依然是亏损，而且止损出局的位置非常接近下跌这波的最低点。
  我根本就玩不过嘛。！

  即使是股票中看到这个图形，我肯定是做多（如果多空必须要选择一项的话，其实股票这种图形我完全不会理，太弱，虽然是多头）

  要会选择对手。

  通过最近对三联虹普的观察，我越来越看清主力的意图和想法。还好我克制住了冲动，没有追高买入。
  这股很明显会有大动作，主力在不断的吸筹码，而且利用散户的冲动追高来更好的承接套牢盘，用更低的价格，成本吸货。
  而且非常强势，今天股票大跌，它还是翻红的，虽然后面收盘开始下跌，但是看出来有自己的计划。

  为什么对股票，我这么敏感了？但是对期货缺不行？
  股票很简单，大盘指数好了，找最猛的搞，在5日均线附近买入就行了。
  我这几趟股票的买卖，看得出来，行情非常的不好，反弹几乎可以忽略，除了那些跌出翔的有些游资拉几个无量涨停板，然后出部分货。
  但是看先锋新材，可能他们连自己都救不了，出不了货吧。

  股票的操作，最主要一点是：不要追高。其他并没有什么大问题。主要是要判断出当前市场的行情是什么样的。
** 不对，不是追高的问题，而是买入的时机的问题。
   你看看PTA最近的走势，看看焦炭最近的走势，买入之后第二天就涨，最多调整一天。
   期货的买入做多和股票是一样的，越是更高的价格越安全，等它跨过所有阻挡位再切入。
   比如棉花1901，我预计就是在17350左右会有巨幅震荡，加盘整，要等在这个附近走稳之后再入场。

   其实期货和股票是一样的。
   再来说说白糖1809，现在肯定不是介入的好时机。为什么？
   因为空头力量未尽，下跌调整还会到10日先以下，空头力量和涨势差不多凶猛。
   而且走势的形状还没扭转过来，再说，前面还有几个重要阻挡位置没突破了。
   需要用这几个重要的阻挡位来考察，校验下多头的力量。


   其实期货和股票是一样的。
   如果期货和股票是一样的，那么整个操作起来就很容易了。除了一点，带杠杆，心理考验更大。
   不抄底，不追高（其实不完全对），不接飞刀，不在支撑位买入，而在阻挡快要突破的位置买入。
   不在5日线以下买入，不在5日线以上卖出。

   如果真的是这样的话，再结合，下跌，盘整，上涨，调整等东西的话，那简直就是能抢钱啊。
   而且真如这样的话，在我这里，开仓就是非常重要的一点。
   开仓之后必然盈利，不盈利就砍掉。

   所有困惑一扫而空，谢谢良风有信的文章，而且文章中说的几个人的手法，段位排名，我都一清二楚。
   现在还有个突破大关就是：像最近PTA，能直接上去。然后回落加仓的。

   棉花被我扛了一个来回，不是我追高的问题，而是介入的时机问题，市场火候的问题。
   耐心，耐心的等待市场那个气氛，火候点的来临。这就是利物莫背水翻身一站采取的（策略，方式，手法？我觉得这些都不对，这需要极大的耐心，对市场极度的洞见和体悟。）

   破而后立买入是错误的；多头均线排列买入，也有那么点问题。最高点反向开仓？这个就是TM找死。
   走势不正确，反向开仓？这个貌似很好，但是会导致一个结果就是：总在寻找趋势的走势不正确点，会形成逆势的思维。并不太可取，但是利润也很大啊。
   最好的是顺应趋势的反向，在关键阻挡位开仓。

   投机还和炒菜非常接近，完全都是一个火候的问题。
   要到火候刚刚好的时候介入。火候这个东西也是用来渲染，酝酿气氛的，火候到了，就要开始杀猪了。


   OK，开仓的问题完全解决。我可能后续依然会错，但是开仓后不盈利，马上砍。
   只做多，等到趋势尾部行情不对，反手空。多了之后一直多。
   要最少以周作为自己的操作周期，不再盯盘，每日收盘必看，必复盘。

   今天有空，将凉风有信的文章再看看。
