* 趋势无敌
  *趋势无敌，* 所以最好的开仓机会是多头市场的向下突破，不破不立。具体操作就是等待下跌走势出问题，然后开仓买入。
  但是，何时止盈卖出了？比如螺纹钢，你趋势无敌，然后有一个月暴跌？死扛着？

  首先，确定趋势的方向，和 *趋势的级别* 。趋势的方向都会看，而且趋势的方向是受级别的限制的。
  比如你在周线看，是上涨趋势，月线看，却是下跌的趋势。
  所以趋势的级别是最重要的。
  *确定你操作的趋势级别。* 月线级别，就以周线走势出现问题为止盈点，开仓点。周线级别就以日线走势出问题为止盈点，开仓点。


  走势出问题：
  第一：一段不断上涨的趋势，到了一定阶段，会突破之前短期形成的阶段平台，然后巨幅下跌，
  短期阻挡平台在突破后变成支撑平台，但是没支撑住。
  然后，我们看看起涨点或者前一个支撑点，也就是平台突破前的支撑位，也没撑住。
  还有，很明显的空头的力度，强度比多头强。
  之后，还要看支撑点向下突破后的反弹，这个是非常重要的。反弹的确认。
  也就是说：如果反弹无力基本就能大概率确认上涨走势出问题了，但是还是要等到反弹结束之后的空头进攻，在开空单。

  何为力度，强度？空间除以时间得到速率，也即效率，就是强度。
  比方说，15分钟涨了30点的强度A，4个小时涨了60点的B，A时刻的强度强于B。
  强度是用来判断走势是否正常非常重要的一个指标。

  所以，走势出问题有4个特征来验证：
  1. 突破后，创新高，但没守住新高。阻挡的平台变支撑，支撑无效，没撑住
  2. 平台的前一个支撑被击穿，这时一般有反复，但击穿未确认
  3. 空头力度，强度开始比多头强
  4. 前一个支撑被击穿后，针对前高的反弹，刚开始就展现疲软无力，未创新高（或创新高后，尼玛跟强大的暴跌？）
     不对，如果再创新高了，那么这个再创新高的时候才是上述的最后一次向上假突破。

  所以，上涨趋势最后一次向上突破肯定是假突破。就好比每次在20天线获得支撑，肯定最后一次撑不住，
  不然就会是无限上涨了。验证了缠师那句：“买点是跌出来的，卖点是涨出来的”。

  这个成为了我开仓，止盈的依据。
  但是如果陷入短期的涨跌，掐头去尾，根本就剩不下多少肉。
  而且还有个陷阱就是：多头趋势，可以用此来洗盘。
  支撑撑不住，然后来根大阴线，暴跌，看似多头趋势完结（短期偏好），
  但实际破后不久，下跌趋势出问题，之后开始新一轮的长时间暴涨。而很多人被洗出去了。
** 开仓的错误，错误的开仓：
   不要在上涨途中开空单。
   不要在阻挡开仓，也不要在支撑开仓。涨会涨破，跌会跌穿。而且很多阻挡，支撑都是主力短期做出来的，
   迷惑大众的。要在下跌走势出问题时凯多，上涨走势出问题时开空。
   或者在空头无力打压下5日线，开多；多头反弹无力到5日县以上，开空。

   反弹开仓的精华在：同样也是，上涨走势出问题后开空，加仓。
   所谓反弹，只是说与当前交易级别，趋势周期级别，更小一级的反向运动。



   还好我今天关注了自己的手，不然又要剁了。2018-07-05 14:23
   但是打开一看，居然成交了。。

   看郑煤这个走势，好像我的理论还是有错误啊。螺纹现在怎么看？
** 思维非常大的问题，不看趋势，如果做空，为什么不空白糖？
