* 尼康说明书

** 快门 Shutter
   曝光了多长时间，曝光时间越短，对应的捕捉的运动物体帧数越少。
    使用速度和光圈的不同组合可以获得相同的曝光。是不是2个数字相乘？还有这个值是在所有条件下都是固定的？
    快门显示的数字是X，那么就是X分之一秒的时间曝光，比如快门显示1，就是一秒曝光。

    越长时间的曝光，曝光量越大，得到的照片很可能就是一片白。

    D90的快门区间在bulb~36’‘~4000，也就是说最快的快门是1/4000秒的曝光时间，最慢的快门是36秒的曝光时间。

    快门越快好像细节越多？
*** 安全快门
    手持拍摄不可低于1/50或安全快门。安全快门=1/焦距。比如85mm拍人像，快门不低于1/85。

** 光圈
   光圈越大，单位时间内进来的光越多，背景越模糊。
**** 景深
     即为对焦点前后清晰对焦的物体之间的距离。比如，人物P站在背景B前面，P和B距离100米，刚开始是小光圈，人物和背景都很清晰，
     也就是P和B都对焦清晰了，这时的景深就是100米；然后调大光圈，背景B开始变得模糊，但是任然有一段距离是清晰的，比如60米，那么景深就是60米。
     增加景深会突出背景和前景中的细节，因为都清晰对焦了。

     景深还收其他因素影响，如焦距和对焦距离。

     D90的光圈区间在F4.5到F29之间。

** ISO
   ISO越大，也就是感光越灵敏，那么不灵敏的区域就全部成了黑点点。
   滤网


** 曝光
    可以看取景器里面的那个+..0..-的曝光，在0的时候是最佳曝光，左边是过曝了，右边是曝光不足。

*** 长时间曝光
     M模式下的bulb和- -可用于对移动的灯光，星星，夜景或烟花进行长时间曝光拍摄。要使用三脚架。
     按住快门按钮，直到释放，完成曝光过程。
*** 测光
    测光方法决定了相机曝光的方式。
**** 3D彩色矩阵测光
     在大多数情况下推荐使用，自动和场景模式下相机自动选择此模式。
     相机对画面的广泛区域进行测光，并根据亮度的分布，色彩，距离以及构图，设定曝光以获得自然效果。
**** 中央重点测光
     相机对整个画面测光，但将最大比重分配给中央区域（8mm直径圈）。
     用于拍摄人像，是人像的经典测光方法。应该是近距离的人像特写，比如拍证件照，模特写真之类的。
     很显然的，人物的脸在画面的最中央，对于人物面部的细节，表情等展现更加细腻。
**** 点测光
     对3.5mm直径圈测光（约画面25%），关键这个点设置在哪里。
     确保即使与背景的亮度差异非常大时，也能正确曝光。

*** 曝光补偿
    用于 改变相机建议的曝光值，从而使照片更亮或更暗。
    与中央重点测光或点测光一起使用，效果最佳。
*** 闪光补偿
    用于更改相机建议的闪光量级别（闪光灯的亮度级别），以改变主要拍摄对象相对于背景的亮度。
    也就是说在夜景下，开启闪光灯，会增加拍摄人物的相对于背景的曝光量，亮度。
    增加单光亮使得人物更明亮，减少闪光量防止不需要的高光或反射。
*** 闪光包围BKT
    也就是多张连拍时候，可以设定曝光步进值，然后得到多张不同曝光程度的照片。

** 白平衡
   作用：确保色彩不受光源色彩的影响。大多数光源推荐使用自动白平衡。

   自动白平衡：色温范围是3500到8000
   白炽灯：色温3000
   直射阳光：色温5200
   闪光灯：色温5400
   阴天：色温6000
   阴影：色温8000
   K模式：可以选择色温
   D90的最大色温是在10000K，


*** 对焦与焦距

*** ISO感光度
    在数字上等同于胶片感光速度。ISO感光度越高，曝光时所需的光线越少，这样可以使用更高的快门和较小的光圈。
    想象一下整个过程，胶片更快的曝光的话，这样就是的胶片上有些区域无法得到充分的曝光，因此就会产生噪点。
    噪点也就是没有曝光成功的像素点。HI0.3到HI1的照片更容易产生噪点和色彩失真。


*** 屈光度？


** 四大模式

*** P 程序自动
    自动选择快门速度和光圈。
    然后调整光圈，会自动变动快门；调整快门，会自动变换光圈；但是2个的乘积不会变。这叫柔性程序。
*** S 快门优先
    高速快门定格动作
    低速快门通过模糊移动的物体表现动态效果
*** A 光圈优先自动
    调整光圈以柔化背景细节
    或增加景深是主要拍摄对象和背景位于焦距内

*** M 手动
    手动调整快门深度和光圈
    将快门设定为bulb或- -可实现长时间曝光。


** 场景模式
*** 人像
    柔化背景，突出人物（这个也就是加大景深，大光圈）
*** 风景
    保持风景中细节（也是调整光圈实现的）
*** 近摄
    为花朵，昆虫和细小物体特写
*** 运动
    定格运动中的物体（这个是快门优先，使用高速快门）
*** 夜间人像
    拍摄微暗背景下的人像（也就是晚上曝光不足的，应该是增加曝光补偿度实现）

** 调整
*** 快门调整
    先选择快门优先模式
    S或者M模式下，主指令拨盘
*** 光圈调整
    先选择光圈优先模式
    A或者M模式下，副指令拨盘

** 释放模式
   S 单张拍摄，每按一次快门释放按钮，相机拍摄一张照片。
   这个东西的作用也就是多张连拍，单张拍摄等作用。


** 构图
   当光线不足时，快门速度将降低，推荐使用三脚架。
   也就是说光线不足的情况下，快门速度必须降低，以获得更长时间的曝光量。
   使用三脚架的情况下，会更加平稳，也就是说在进行对焦的过程中，探测到的曝光量更准确？
   或者说在摇晃的过程中，机器无法准确的自动对焦，单位时间需要更多的曝光量。

   将拍摄对象置于对焦点上。


** 人像
   当人物距离背景较远或使用了元摄镜头时，背景细节江北柔滑以是构图更有层次感。
   原来如此，模糊柔滑背景是为了层次感。
   人物距离背景较远，这样就得到较大的景深？？？

** 风景
   风景模式下，内置闪光灯和自动对焦辅助照明灯会自动关闭。

** 近摄
   用于特写，微距镜头可以在极其近的距离内对焦。也就是取景器里面的物体很少，镜头要调成长枪。
   刚才实践了下，特写镜头因为要拍摄非常小的物体，也就是镜头要聚焦到一个非常小的区域，因此获得的曝光量非常的少，
   这是就需要用：1.低速快门；2.超大光圈，这样的话，细节才能完美展现。

   超大光圈的话，周围的东西会被模糊掉，但是中心突出了。

** 运动

   场景模式下，好像快门和光圈都调不了，

** 夜晚人像
   会开闪光灯，而且闪光灯是Auto-Slow，就是说需要很大的曝光量补偿。

** 对焦
*** 对焦模式
    1. AF-A
    自动选择，相机在拍静止的对象，就成AF-S，运动物体，就是AF-C
    2. AF-S
    单词伺服自动对焦
    3. AF-C
    连续伺服自动对角
*** 自动对焦不适用场景
    1. 拍摄对象与背景之间无对比度，差异很少，比如人物服装和背景色彩相同。
    2. 对焦点内包含亮度对比强烈的不同区域，就是说一部分在高光下，一部分在阴影下，特别是拍摄对象在阴影下。
    3. 对焦点内包含距离相机远近不同的物体，比如拍摄对象在笼子里。
    4. 背景物体比拍摄对象大，比如拍摄的人物背后有楼房，但是楼房又不作为背景，而是单独的物体，有明显的高亮区间区分。
    5. 拍摄对象由规则的集合团组成，比如百叶窗，摩天大楼。其实这个和无明显对比也差不多，因为对焦区域内核周边无对比。
    6. 拍色对象包含很多细节性景物，比如一篇花海的田地，或其他细小的物体，因为物体之间缺少亮度变化。




*** 自动对角辅助照明灯
    有效范围0.5到3.0m，需要焦距为24到200mm的镜头。
*** LV即时取景模式的对焦
    脸部优先
    相机自动检测并对焦与人物的脸部。

    宽区域
    适用于拍色风景和非人物

    标准区域
    精确对焦与画面中所选点。推荐用三脚架。
    也就是说标准区域会精确对焦画面中所选点，也就是说采光的区域，点位相对于宽区域会少，因此曝光量会少，所以用三脚架。
    但是很明显的是，这种模式，画质效果会更细腻，真实。
*** 对焦模式的不同
   人像，风景，夜晚人像，都是自动选择对焦点。
   特写模式是中央对焦点，其实也就是要让中间的物体突出。
   运动模式，是半按下快门进行连续对焦，跟踪中央对焦点上的拍摄对象

** 发挥D90极致性能


*** 拍摄注意事项
   拍摄对象要有对比。
   对焦点的拍摄对象不要包含高对比亮度
   光源要稳定
