* DSLR Digital Single Lens Reflex

** What
   DSLR uses a mirror mechanism to either reflect light from a camera lens to an optical viewfinder
   or let light fully pass onto the image sensor (which captures the image) .
   单反相机使用镜子的原理，通过反射镜头中的光线到取景器，让你看到你拍摄的东西。
   并且使光完全的传递到图像传感器上。

** How DSLR works
   就是所有的光线都是通过镜头进来的（景色物体上反射的光线），然后通过反光镜将景色
   反射到我们的取景器。

   反光镜在按下快门的瞬间会被弹起，让水平光线通过，这是快门也会打开，然后后面的
   图像传感器感光。快门会打开最够的时间直到传感器充分曝光。

*** 关键点
    快门打开的时间很显然就是快门速度，如果选择快门优先的话，这个打开的时间就固定了。
    如果要充分曝光的话，那么光圈要变大，也就是镜头的孔径要变大，让光更多的通过，
    这样的话，景深就会减小，也就是我们只能看清近距离的东西，远距离的东西看不清。
    也就是拍远距离的风景，细节会丢失，这时理论上来说可以通过调大ISO？

    最最关键的一点就是：还是曝光量少了。也就是摄影的最最基本原则是充分，完美曝光。

** 几种假设场景
   1. 室外，拍花卉
      时间肯定选早上或者晚上。静态物体，ISO尽量调低，突出细节，光照充分，为了有层次感，
      调大光圈，光圈优先。
      通过搞明白下面的焦距的问题，那么很显然，用短焦距，但是这样取景范围就变大了。
      所以我们应该走进花卉。

   2. 室内，篮球运动

      这里还有个问题？
      就是焦距，我们在单反上面构图，调整的那个东西。
      焦距影响的是什么了？1到2之间的距离，不对，是镜片到传感器的距离。
      短的焦距，有大的取景范围（就是能看到更大范围的东西）
      长焦距，小的取景范围，（这里并不是和远景，近景有关系）当然如果要
      拍远景风景（大取景），短焦距；远景的鸟，长焦距。
      不对，越短的焦距，很显然单位时间进来的光线更多，因为是从大取景里面采光的。
      所以远景的鸟这种抓拍，对相机的素质要求最高。

      光圈越大肯定越好。



** Tips
   1. 光照射到物体上，然后物体发射出的光进入到镜头。
   2. 短焦距>长焦距
