* 平凡之路
平凡之路

今天午睡的时候听到了这首歌，刚听还以为是个不出名的小乐队的成名歌曲，
但是听着听着，感受到歌曲中沸腾的热情和旋律。
问了播放歌曲的前台，原来歌名叫平凡之路，欣喜的居然还是朴树唱的。

从白桦林，那些花儿，生如夏花，我总觉得朴树是一个人在默默的唱歌。
在这个浮躁的世界没有几个人是在做着自己应该做的事情的。

“我曾经跨过山和大海，也穿过人山人海”
这是以后的事情了，我肯定会跨过更高的高山，拥抱更辽阔的海洋，去到更远的地方，仰望更深邃的星空，
去到你梦想的地方，一个人。
你就继续呆在原地吧，沉沦在过去和他美好的回忆中。


“我曾经拥有着一切，转眼都飘散如烟”
我曾经拥有一切，我拥有开心的每一天，我拥有优异的成就，我拥有好学生和乖孩子的标签，
拥有老师和家长，邻居的夸奖，我是绝大部分同龄人眼中羡慕的对象。但是这也只是曾经。

“我曾经毁掉了我的一切，只想永远的离开”
我曾经因为没有去到理想的高中，我以为我的一切都毁了，
我自暴自弃，到最后才发现是我自己毁了这一切。

“我曾经失落失望失掉所有方向”
可是我失去的这一切，是我自己抛弃的。要么最好，要么不要，这就是我。慢慢的
我失去了开心的每一天，失去了优异的成绩，老师和家长面对我只有叹气或者心事重重。
我痛恨所有人，我尽量不和任何人说话，我把一切的人和事都想的无比黑暗，是他们造成我这样的。

“我曾经以为我又拥有了一切，直到我知道那只是曾经”
我曾经以为我又拥有了一切，因为我爱上了一位姑娘。
因为我遇见了你，遇到了你的笑容。
我满心欢喜的爱着你，一如爱着才发觉的这美好的世界。
总有那么一个人曾经幸福的让你忘掉了梦想。
我就那么轻易的被一个笑容所拯救，而你却不知道。
即使我做了那么多，你只是一句：
“NOBODY CAN SAVE YOU”

我以为我说一句我爱你，你就不会走，
就像当初我以为说一句我有一点点喜欢你，
你就不会对我那么凶了，结果只是你的小小得意。
可是现在不一样了。

拼尽全力爱到最后还是回到了原点，我不知道。
对一个人我不知道应该是去爱，还是去恨，
我不知道。我只知道我累了，就这样吧。

“我曾经问遍整个世界”
我一直没有问过这个世界，我只是内心的不断问自己，“为什么？为什么要这样对我
难道我做的这一切都只是让你感到厌恶，每件你做的事都是我在乞求吗？
而你却感到我是在逼迫你，什么都没开始就已经成这样了。在你眼里，我到底算什么？
我视为比生命还珍贵的东西原来在有些人的眼中比狗屎还让人厌恶。
对，我就是一坨狗屎。即使是一坨狗屎我也要滋养一朵野花。
我不能像你那样沉浸在过去，等待一个人的拯救。
因为我不能像你那样的对待我自己。

我做了那么多，你只有一句他是狮子座。
我始终没有找到答案，我只是告诉自己那里有那么多的为什么了？
结果就是如此，没有为什么。
如果任何事情都有为什么，你还活着干嘛。

那天一个觉得不错，聊了一个多月的姑娘，突然来了一句：
“那都是过去的事情了，我只是想抹掉一段6年的感情。”
我内心波涛汹涌，但是只是回复了一句：“蛮好，最少还有6年的感情和回忆”
其实我心里想的下一句是，蛮好，最少要比我好，我的青春一无所有。

一个姑娘有多少个6年，还是在最珍贵的年华。20岁到40岁也就3个6年，
我不知道她能不能抹掉这段回忆，我不清楚，我也懒得去弄清楚。
不知道她是几年的感情和回忆，不过总以为自己可以拯救她，让她幸福。
我不知道自己是哪里来的狂妄和自信，现在发现是我的可笑。
我只知道，我只是想看到她的笑容，陪着她过每一天，逗她开心，即使平凡甚至平庸无聊的日子。
或许这些只是我的幻想吧，但是当时的我只是强烈的渴望着。
别的事情我不知道，，因为我很幼稚啊。
但是我知道有你的话，遇到一个问题，解决一个问题就好。

我不该写这些东西，我应该去做我的事情了，脚踏实地的工作，努力的敲代码。
不要沉浸在自己的过去和回忆中，要学会坚强，向前看。
