* 我为什么还在写博客
  在这么多年断断续续的折腾之后，再问现在这个问题，就有点严肃了。

  在有这个站点之前，我很早就开始写点什么了。可能是高中的时候，看韩2，郭4的文章看多了吧，
  也或许是受到新概念大赛获奖保送名牌的洗脑，自己变得成了个小文青。

  之前最初是在QQ空间写，后面去新浪博客写，中间还在百度空间写，都写过一段时间，
  但 *写作* 这件事一直没坚持下来。

** 建站
   QQ空间我TM就不说了，老子发的说说全部给屏蔽了，说是有敏感性词汇。
   想当初，哥读高中时，那就是一个诗人，一个哲人，发的哪些在现在看都有些深度，
   居然因为政治敏感原因，给老子屏蔽了。后面QQ空间完全不玩了。
   新浪名家太多，我写的东西完全不上档次，没流量，没访问太正常了。
   百度空间主要当时宣传的很，我也搞了一个试试。

   后面自己搞计算机专业的，在虚荣心的驱使下，自己也申请了个域名，搭了一个wordpress站点，
   但是大家都知道，玩wordpress的都不是写博客的，而是换主题的。
   三天两头的就换个主题，老是觉得别人的主题，刚刚换好，没过几天，发现又出来更漂亮的主题。
   反正就是折腾没停过，除了主题，还有各种插件神马的，反正就是折腾呗。

   文章没写几篇，主题已经换过几十个了，插件也全部都装上，发现还是没几个屌访问量，也没人留言
   ，后面慢慢的，连主题都懒得折腾了，很久都懒得上去搭理了。


   前段时间不经意在alexa看到自己网站排名居然是300多W，哥一下怒了，决定要将300W刷到100W
   以内，然后想了下：现在最火的是知乎，想要流量，去那里肯定有效。

   去知乎答题，那要选择一个擅长的话题，我这人就是撒都会一点，撒都不精。
   会炒股，会撸代码，会写作，会打德州，会摄影，会游泳，会。。。
   除了撸代码能持续赚钱外，其他的都不能。炒股这事，还真是靠天吃饭。
   （我一般不搞，要搞就大搞，往死里搞）
   最后选择了交易，发现中国散户真是多，怪不得股票这么容易赚钱。期货的难度，
   外汇的难度，真不是一个数量级。

   后面有折腾什么百度不收录，什么CDN加速，什么域名备案，什么搞友情链接。
   我TM心里想：去你妈个球，老子这么牛逼的人物不需要搞这些，你们爱看不看。

   最后心里真切的问：你为什么写博客？

   我心里一个震颤，这么多年折腾之后，现在问这个问题，是非常严肃的。

   *写博客是为了自己。*
   1.锻炼写作能力，本质是写作锻炼思维能力。
   2.记录自己的所学所思所得，传授给他人，一方面加深自己的理解，
   另一方面希望能给到他人一点点帮助。
   3.在互联网发出自己的声音，舆论自由是人人与生俱来的权利与义务，更是责任。
