* org-mode-summary
** 安装
   下载，解压到~.emacs.d/lisp目录下
   (add-to-list 'load-path "PATH_TO_WHERE_YOU_UNPACKED_ORGMODE/lisp")
** 激活
   将以下内容添加到.emacs中
   (require 'org)
   (define-key global-map "\C-cl" 'org-store-link)
   (define-key global-map "\C-ca" 'org-agenda)
   (setq org-log-done t)

** 快捷键
   C-c C-t 运行org-todo命令，然后可以有几个选项
   M-S-RET 运行org-insert-todo-heading
   C-c C-o 运行org-open-at-point 显示链接详情？
   C-c C-l 运行org-insert-link，添加链接地址
   C-c a t 进入全局TODO列表
   C-c C-s 运行org-schedule，选择deadline。
** 添加链接
   就是一组[]然后里面包着2组[]，前面是连接，后面是描述。先输入链接和描述，最后方括号。
   

** GTD
*** 全局TODO列表
    在emacs初始化文件中添加
    (setq org-agenda-files (list "~/org/work.org"
                             "~/org/school.org"
                             "~/org/home.org"))
    就会扫描这些文件中的TODOS项。
*** 计划任务
    
** 导出markdown
   C-c C-e m m 导出使用markdown语法的纯文本（但是我的没什么卵用啊）
   M-x package-install RET markdown-mode+ 安装markdown-mode
   (eval-after-load "org"
      '(require 'ox-md nil t))
      使用上面这个命令好像可以。
    尼玛，使用那个
** DONE test
   CLOSED: [2017-04-12 周三 15:54]
   :LOGBOOK:  
   - State "DONE"       from "TODO"       [2017-04-12 周三 15:54]
   :END:      
** DO
   

** Reference
[[http://orgmode.org/worg/org-tutorials/index.html][tutorials

]]
