* 办公室灯光布置
  fixture
  遇到任何问题前，先动用自己的大脑，常识来思考，而不是网上搜资料。

  最好的灯光环境肯定是类似自然光，比如上午的阳光，下午的太强烈，
  但是只要不是阳光直射，室内窗户边的光线也是非常棒的。
  到了晚上，太阳西沉，这时没有自然光了，而且街道两旁的各种霓虹灯照的人眼睛疼，
  特别是红色的，还有车灯远光灯，太亮太刺眼了。

  每天地铁的电梯上也是光线非常的差，很昏暗，但是又不是完全黑暗，就是光线分布
  非常不均匀，而且灯光照到铝合金等东西上面，形成高亮的反射光。

  所以太亮不好，要柔和，还有就是明暗对比度不能太高，不要有各种其他颜色的光，
  不要反射光，特别是那种聚点后反射出来的，光线分布要均匀。

  为什么自然光，太阳光这么好？
  我发现到现在，我才真的开始学会一点点如何思考。
  首先，太阳是一个超级巨大的球体，相较于地球来说，因此散发出去的光线
  到达地球是非常均匀的，其次太阳光线经过了这么久远的距离，还经过了紫外线层的过滤，
  光线非常柔和。
  另外一方面是我们经过几千年的生存进化，眼睛已经非常习惯了自然光线。
  这么好的自然光线，可能对于水中的娃娃鱼或者洞穴中的生物就非常刺眼了。

  所以，那么如何来布置办公室，家里的灯光配置，使得更加护眼？
  最好的假设情况是：所有的地方都布置上了点阵光源，每个光源亮度足够小
  这样的话，灯光分布足够均匀，亮度足够，并且非常柔和。

  多个光源明显比单个光源好，除非单个光源像太阳那样足够大，足够远。
  单个光源，为了保证亮度，必然瓦数很大，而且办公室，卧室很多角落，
  阻挡的地方照不到，比如我家现在的阳台。瓦数大，必然就很刺眼了。

  灯管明显比灯泡好，灯管照射的面积更大，发射出去的光源更均匀，更柔和。
  所以，我现在家里想改造的话，最好是买2个3W的灯管，肯定比1个6W的灯管效果好，

  还有就是放到距离较远的大功率灯管比放的较近的小功率灯管效果要好。


  灯泡是1瓦供应1平左右的   其他灯具是2-3瓦供应1平左右 亲您参考一下哦~
  我买的是灯管，
** 其他材料
   因为相比日光灯或ＬＥＤ光源，普通白炽的的功率更大
   人工照明应与天然采光结合设计
   宜采用荧光灯？
   无光泽装饰材料
   不要使用直射光和点光源。
   办公室的一般照明宜设计在工作区的两侧，采用灯管的时候，应该使灯管与视平线保持平行，不宜将灯具布置在工作位置的正前方。
   果然，要水平视线，如果是和水平视线垂直的话，灯光照射到屏幕上，会反射到眼睛里面。

灯光布局不仅要能满足用户在光照等级、眩光控制、色温、显色性、节能
6000K的冷光源给人视觉上清凉的感受，

在难于确定工作位置时，可选用发光面积大，亮度低的双向蝙蝠翼式配光灯具。

浪费这么多时间，看了这么多东西，其实撒有价值的都没有。

晚点在搞吧，哎，真难受。傻逼公司，无处不透露出傻逼。
** 看来还是得在后续的生活体验中，留意观察，看看哪些是好的灯光设计。
工作区需要高色温、高显色性的灯光，才能保证工作时的效率和准确度，完全可以照着办公场所用灯的参数去买。

具体说来，工作区的灯色温不能低于4000k，照着冷白光找准没错。
