* 思维导图总结
** 头脑风暴
   为什么要用思维导图？相对于我们做笔记有什么区别？思维导图的核心是什么？
   *思维导图的核心本质是什么？*
   我认为是

   如何画好思维导图？画了之后的思维导图如何用于学习？

   思维导图的工具有哪些，最好的是那个？
   什么是思维导图？
   我之前就大概看了下，
   Mind mapping is a highly effective way of getting information in and out of your brain.
   Mind mapping is a creative and logical means of note-taking and note-making that literally "maps out" your ideas.

   natural organizational structure，radiates from the center and use lines, symbols, words, color and images according to simple, brain-friendly concepts.

   主要是从大脑中取出东西，自然的结构，对应大脑自然的思维路径，方式，可以任意顺序的写下头脑中的idea
   是头脑思考的外部映射，用尽量少的词汇，

   先把这篇mindmap的文章搞完？不对，应该先


   多参考下手绘的图，多画曲线，使用这种破折线，，好了，等下来写篇文章就行了。
   5W1H
** 什么是思维导图？
   思维导图MindMap，就是将头脑中的想法，联想过程，思维逻辑处理过程，像画地图一样的画出来。
   但是实际结果是通过一个 *核心概念* 不断的发散思维，而思维的每一步又和前一步有联系。举个形象的比喻，
   就好比一颗思维的种子不断长大，扩展成为一颗大树的过程。

   思维导图是模拟，映射整个大脑自然的思维，推理，联想的过程路径。

   解决大脑容量有限，很难逆向回溯思考，
   大脑的思维过程很可能是跳跃性的，联想出来的东西，不完全连贯，可以使用思维导图的连线将他们组织起来，并补充相应的部分。
   还有时候可能会灵感迸发，这时最关键的就是记录：关键的几个字，印象，
   我们的思维也是发散性的，思维导图也模仿了这一点。
** 思维导图的核心本质是什么？
*** 背后理论
    科学家斯佩里研究实验证明，大脑的皮质活动越是融合在一起，每种皮质技能都会提高其他技能的表现。
    皮质技能包括：逻辑，节奏，线条，颜色，列表，白日梦，数字，想象力，单词，看全局等。
    使用MindMap不仅锻炼记忆和信息处理能力，还能综合使用所有皮质技能，使得思维更加清晰，结构化，有组织。

    一幅图包含了巨量的信息，并且更容易被大脑记忆，唤醒，图片识别理解调用的皮质技能也更多。
** 如何画思维导图？
   可以使用工具，也可以手绘。
*** 工具
    常见较好的工具有MindManager，XMind等等，但是使用这些工具的时候，需要考虑几个问题。
    1. 是否方便，
       大多数工具是需要先下载到本地的，而且开起后占用空间较大
    2. 是否支持多平台
       因为我们不可能在头脑灵感爆发时，却需要坐到电脑前，才能开始思维导图。
       最好能同时支持Windows，Mac，浏览器，IOS和安卓，因为你看你需要在手机上阅读或制作思维导图。
    3. 导入导出是否方便
       是否可以方便的导出到另外的MindMap工具中，导出到印象笔记，导出为图片，html等格式
    4. 收费
       大多数功能丰富的软件都不是免费的，虽然有基础免费版，但是干的事有限。
*** 手绘
    这里我个人推荐：手绘。完成之后再用手机拍照，保存到Dropbox或者七牛图床中。
    1. 方便
       只需要一张纸，一只铅笔，一个橡皮就能开始了
    2. 增强记忆
       在亲自动手，书写的过程中就加深了印象。
    3. 有趣，个性化，亲切
       有些绘画功底不错的人，画的思维导图很有意思，而且能彰显自己个性。
       看到思维导图的人也会觉得手绘的图片更加亲切，但是

       妈的，发现写的东西，官腔十足，而且很做做。
*** 画好的标准
    我个人认为没有绝对的标准，主要还是看是否适合自己，以及相应的取舍。
    1. 多图
       一图胜千言，图片易吸引注意力，易记忆，易唤醒。MindMap本身就是一个图。
    2. 关键字
       少写文字，多用关键字。如果遇到关键字，没有唤醒相关联的知识点，我们再翻看笔记。
    3. 结构自然
       多用曲线，随意组合，连接，但是必须要自然，符合大脑的思维过程。
    4. 多用色彩
       色彩会引发情绪，并能清晰的将不同知识点区分开
    5. 结构不深
       一个链条上，思维如果太深就会远离核心关键点，也不利于回忆。

** 思维导图的优缺点
   缺点的话，
   优点在上方已经说了，主要是帮助记忆，理清思路，复习，训练思维。
    1. 耗时

** 思维导图真的有效吗？
   是否有效，还是要看一段时间后的使用结果，还有投入的时间和产出比。
   如果有人讲思维导图当做学习绘画，当然对理解知识，发散思考没有帮助。
** 参考资料和扩展阅读
   [[http://www.mindmapping.com/theory-behind-mind-maps.php][MindMap Threory]]
   [[https://en.wikipedia.org/wiki/Mind_map][Mind map Wikipedia]]
