* 如何赚钱
  谈到赚钱，那么我们首先要做的就是建立正确的金钱观念，其次就是加深对金钱的认知和理解。
  很遗憾，因为中国文化社会发展的原因，大多数人都没有受过这方面的教育。
  几十年前的有钱人是会被打成右派，资本家的。
** 钱的本质
   钱代表的是什么？
   有钱了，你能够买别墅，买豪车，环游世界，甚至还能叫个网红？
   所以钱代表的是对物品的拥有权，对服务的使用权，钱代表的是：物品和服务，也就是劳动量。

   无论是体力劳动，脑力劳动，还是创新，都是一种不同形式的劳动。
** 赚钱这个行为过程
   赚钱这个过程简单来说就是：消费者通过金钱来交换生产者通过劳动生产的物品或
   提供的服务来达到满足自身的需求，欲望的过程。

   等价交换是万事万物，自然的法则。
   所以想要赚钱，先思考一下你能提供何种物品，何种服务，以供出售。
   即使你能提供某种物品，某种服务，但是市面上存在大量同质的商品或者服务，
   你能采取的措施只有一下几种：1. 要么价格比别人低；2. 要么质量比别人好；3. 要么有品牌。
   这3点其实本质上是相同的，都是节约了成本。
   价格低，性价比高，购买者承担的成本低；质量好使用的寿命长，平均单位时间内的成本低，
   有品牌，减少了购买者做决策所付出的时间和精力成本。

   但是即使你东西或者服务卖出去的，但是利润低，你一个人时间有限，只能糊口。
   如何赚大钱了？

   所以，如果要赚钱，一定要从这2个方面思考：节约成本，提高效率。
** 供需法则
   想赚大钱，先看个公式，盈利=利润x数量，所以要么单价利润高，要么走量，薄利多销。
   利润=价格-成本，成本可以压缩，但终究存在，价格却可以具有无限想象空间。

   价格是由什么决定的了？
   供需。

   需求多，供给少，价格高，需求更多，供给不变，价格更高；
   看看这个供给曲线，这个一个曲线课程解决很多问题，运用的奥妙只有经历才能体会。

   供给端：
   我的观点是：除了几样事物之外，供给端几乎能够敞开来供应，最多只是时间的问题。
   供给有限的有这么，这个观点不对。
*** 需求端：
    要么发现需求，要么制造需求。赚钱之所以对大多数人困难，是因为现有的需求已经得到饱和？
    我发现涉及到需求，和供给这2个本质的东西，我的观点很多都不对。

    需求得到满足？很多人北上广没房子，10万一平，你能将它降到5万吗？
    生活中充满了矛盾和困难，这些就是有价值的东西。


    写到这里，我发现自己对供需的理解还差好远了。


    所以想赚钱，首先你得有物可卖。可以是写的文章，小说，公众号，可以是跑腿，可以是淘宝开店铺，
    可以是投机（本质上来说是你执行了一种让市场更加高效运行的决策），可以接软件app外包（劳动服务），

    但是以上的东西都是我们平时在做的，也就是打工，但是赚钱，赚大钱，必须要有规模效应。
    同样是公众号，几百万粉丝的号和几十万，几万人的号，赚钱肯定有巨大差别，而且非常明显。
    记得之前听过的一句话就是行业1%的人年薪千万，10%的人年薪百万，20%的人5万，80%的人拿底薪。
    就是这个样。

    然后再来结合你自身的资源，优势，经验，等扥，结合起来看，将自己放到一个行业中，
    看你自己最适合赚取那个环节的利润。

** 赚钱你所在环节的利润
** 天时地利人和
   赚钱最好先考虑“天时地利人和”，这个会让你事半功倍，甚至即使你撒都不会，只要碰到了“大势”，
   或许就能大发横财，躺着赚钱。
*** 天时
    比如前几年的房地产，只要和房地产相关的行业，个人，简直都是“房地产得到，鸡犬升天”啊。
    即使是相关度最低的个人，只要你比别人早买一套房子，当然要是得地利的房子，北上广深，
    或人口多的二线城市。那你相当于是相对别人多赚了几百万啊。
    而且上车的人和没上车的人差距会随着时间越拉越大，恐怖的很。

    要赚钱其实是很容易的，炒股赚钱却是很难的。
*** 地利
    刚才说过北上广深的房子就是得地利，因为地理位置的稀缺性，优越性，
    当然即使就是在深圳，福田的房子比宝安的房子也有得了地利的道理。

    我现在准备尝试做外贸，深圳的电子加工厂很多，这个就是得了地利。
    还有些人，想淘宝卖农产品，他们当地农村有各种廉价的特产，这个也是得了地利啊。
*** 人和
    这个我想一般人都懂，做生意吗，买卖不成，仁义在。这就是人和，
    摆个摊，你得给城管大哥，巡逻的送根烟，打个招呼不是？？？

** 自身兴趣和长处优势，经验技能
   我的长处就是决策（或许以后能搞个互联网的产品，帮助别人决策）

   我的3个技能就是：投机，写作，编程。

   我的兴趣本身是创造，但是太懒（太懒也是一个问题啊）

   给自己2个月时间，然后来尝试做外贸。



** 关键字
   提升社会效率，节约社会成本，不然社会就如同一家公司倒闭
   我知道很多人像我一样为钱发愁，

   任何事情做好都是不容易的，我以前凭借一点小聪明获的成绩让我形成了
   一种一切对我来说都很容易的错觉。

   不用写的太好，要求太高，但是要经常写。

   写小说。
** 如何写作，驾驭文字
