* 个人高效的学习，工作习惯
** 目标
   在开始做一件事情之前，我会先设定一个目标。

** 分解目标，规划
   将一个大的目标分解成


早上去地铁的路上，我会想好今天要做什么。如果没有什么工作上的任务，我会想要学习些什么。
上了地铁之后，我会开始什么都不做，既不看手机，也不听音乐，也不会睁着眼发呆，我会闭幕养神，观察呼吸。

根据我这个归纳，可以看出，很多时间还没有高效的利用起来。比如去地铁的路上，（骑车，不要想东西），到公司的路上（浪费了）
到了公司之后，我会首先回顾一下昨天干了些什么，学习收获了些什么，并且记录下来，以备晨会。然后讲今天要做的事情列出来。
将重要紧急的事情放在前面，并标注，大写。如果工作任务不是很繁忙，我会利用上午的时间先学习一段时间。或者阅读一些资料性的东西。
因为上午的时候精神和状态最好。

工作以后我会将1.手机静音；2.将所有的社交软件都屏蔽掉，比如QQ得永远不提示消息除非他人@我；3.不会和别人长时间去讨论一件事情。

开始工作之后，我会要求自己在最短的时间以最快的速度完成，然后什么都不做，开始休息。而不会像部分人那样，做事拖拖拉拉，反正就是今天做完就行。
然后就是一种打酱油的态度对待工作，然后自己本身也成了永远的酱油，扶不上墙的的货色。

2. 在进行工作，我是程序员，比如做一个项目前，我会先思考一会，并且将思考的过程记录到印象笔记里面去。然后一边思考，一边反复看和回顾我思考的记录，
看是否有问题，或者不满意的地方。这个过程我会一直重复，直到我想明白了。然后会将整个过程梳理一边，边想边记。之后再开始工作。

3. 工作以后，我会尽量减少他人对我的干扰，也就是对他人的问答，我会嗯一声，事后再去问，你刚才说了什么。或者直接和他说，我很忙。
因为程序员的思路一旦打断，又需要交旧的时间回复过来，我记了笔记，就是为了迅速回到之前的思路。

拒绝无效沟通

如果他人不尊重我的时间，我也不会尊重他人。有些傻逼老是喜欢说多沟通，其实做的都是无效沟通。一个事情，聪明的人，你还没说完，他就知道你是什么意思了。
普通但认真的人，在你完整说完一边，他就知道你的意思了；普通但懒散的人，在你说2遍之后，就知道了；只有那种又懒又蠢还不动脑得人，才会在别人说了3遍以后
还不知道是什么意思。

我每隔一个小时，会去打一次水，然后上个厕所，然后在走廊转2圈，整个过程不会超过10分钟。
我从不在工作时看QQ，微信，邮件。当我起身开始休息一会之前，我会浏览一下QQ群的信息，微信的信息，还有邮件的信息。
除非提到我，或者和我有关，我一般都不看详情，也不去关心。

中午我一般都是最后一个热饭，吃完之后，我会在走廊走几圈，1是为了防止胀肚子；2.是为了便于消化；散步完之后，我会立马睡觉，什么都不做。

下午起来之后，我不会立马开电脑，因为对眼睛伤害太大。我会出去走动一下，活动下筋骨，然后让眼睛稍微适合下周遭环境，然后才开始开电脑。
开电脑之后，我不会立马工作，还是会先开始学习一下，阅读一下各种资料。

下午下班以后，我会将手头没完成的工作先完成，然后整理一下笔记，之后看一些和工作无关，或关系不大，想看却没时间看的东西。

晚上从公司到地铁，我会回顾下今天发生了写什么。有哪些东西没完成，对完成的标记（我现在用的org mode，我推荐你们也用下）
