* 赚大钱的逻辑：哪些说靠能力的人都快醒醒吧

其实在讲这个观点之前，我倒是想很花点时间跟大家谈谈，我们到底依赖什么来
赚钱这个话题？


其实我自己一直在反思这些年里的很多事情，突然发现所有的成功失败，很大程
度上都不是我自己个人能力决定的，而是很大程度上被大趋势给决定了，我很多
年前写了篇叫《我为什么看空中国股市》，里面我提到我自己为什么离开股市，
突然只是因为觉得我这个人能力不如别人，勤奋不如别人，运气不如别人，我凭
什么跟人在一个能力充分竞争市场上赚钱？我唯一盈利性的机会其实只有一个，
就是猪都会赚钱的时候，我才有赚钱的机会啊。也就是风口来的时候，例如06年，
例如09年，那时候，满大街都会听到谁赚了多少，赚了多少，于是我就能有机会
赚钱了，如果在一个不是普遍性的盈利市场上的时候，我发现赚钱一般都是辛苦
钱，也就是跟人比体力才能赚钱，花更多的时间，做更多的调研，那些都是辛苦
钱。而可悲的可能是竞争越充分的市场，你会更可悲的发现你即使很辛苦了，也
是不赚钱的。


后来衍生出去看很多问题，发现其实不单是股市，任何行业好像都是差不多，
2002年的时候，我们很多同学离开了中国去美国读书，都是名校啊，牛逼的一塌
糊涂的名校啊，我们这些垃圾被留在国内，十多年过去了，我们这些垃圾在国内
啥事情也没干，结婚生子，然后没事只能买房子，一套两套三四套，然后然后就
发现那些国外读了n年的书的同学们可能就比较悲催了，回国可能一套房子也买
不起，是我们能力强么，不是的，是因为我们赶上了好时候，中国大发展都格局
里，能力其实是不需要的，我们自己也很悲催的发现，回老家去，甚至不如那些
没考上大学的同学们，他们初中毕业、高中毕业就开始闯荡江湖，更早的接触社
会，更早的在外贸领域做业务，而你因为可能是大学毕业，选择也比较多，反倒
不如他们有更好的积累，尤其在过去十年赚钱最多房地产行业，一般比拼的其实
也是胆魄而非能力，我们东阳是建筑之乡，很多人很小就跟着走南闯北做工程，
然后在过去十年里，一个个都赚了很多钱，反观我们自诩名校毕业，其实是不如
他们的，当然现在趋势也在变化，互联网出现的格局里，房地产衰退之下，这个
趋势不同了，盈利逻辑也跟着变化了。


我前些日子碰到一个UT出来创业的小伙子，当年UT可能在全国招聘的为数不多的
本科生，他打败了无数的人终于挤进了UT，而那些被他打败的人，黯然的走进了
阿里的大门，彼时的阿里容纳了一帮乌合之众，很多都是职业技术学校毕业的学
生，名校几乎没有，十多年过去了，那个进了UT的天才，现在要出来创业了，那
些没办法只能去阿里的人，一个个身价过亿要给那些牛逼哄哄当年逼的他们无路
可走的牛人们投钱去了，能力决定一切么？好像还真不是。


前些日子，跟黄晓捷师兄谈话，他谈到他2001年在五道口读书的时候逃课去卖空
调，希望发家致富，结果卖了一年多，晒得黑黑的回学校，然后说了一句话，叫
辛苦不赚钱。跟我所思考的几乎是一致的，这简直就是句真理，这个世界上，赚
钱的事情，从来不是辛苦的事情。你们比辛苦，比的过那些富士康的工人么，比
得过农民伯伯么？但是他们比你更赚钱么？所以世界上，如果一个行业要靠比能
力来赚钱的时候，你会发现好像赚的只能是辛苦钱了。更苦逼的是甚至很多人还
赚不了辛苦钱，例如现在一堆苦逼的淘宝电商。


现在创业的人很多，我一直都跟大家说，创业有时候选择大方向很重要，因为赚
大钱和赚小钱说白了，其实都会很辛苦，都很艰难，你路边开一个小店铺要做成
赚钱，其实也不见得比做好一个国有企业要容易到哪里去，都不容易，但是同样
辛苦，结果是截然不同的，这个时候，大格局大趋势就显得非常重要，尽量去做
一些趋势性的机会的事情，市场整体向上的机会，只要做的稍微好点，总还是有
机会的，而有些行业，你在怎么做，其实都注定了最终的结果都不会好。我们做
投资的要去投资一个赚的是辛苦钱的时候，那就会发现我们赚取的只能是社会平
均回报率，于是我们到最后发现得出的结论其实也还是尽量淡化能力的重要性，
更多看中趋势性的投资机会，在大趋势性的格局里，在进行一定程度的铺量投资，
能力无法量化，很难确切的预测，而大趋势的视野还是有一定的逻辑可循。


周鸿祎有篇文章貌似是说，趋势之下无可抵挡，孙中山很多年前有句话叫，天下
大势，浩浩荡荡，顺之则昌，逆之则亡，意思就是任由你在牛逼，你也无法对抗
历史的潮流，这就是趋势的力量。但是问题来了，趋势到底是什么呢？


趋势是什么很难定义，我们其实看趋势这个东西吧，倒是有几个特征挺有意思，
第一个特征其实是趋势只有在将起未起的时候，才有意义，太早看到趋势其实毫
无意义，你会错过太多的东西。也是为什么很多聪明人都赚不到钱的原因，趋势
看到了最后就是虚无主义者，因为觉得这个也就这样那个也就那样，都没啥意思，
看的太远的人，其实挺适合做先知，当然也很容易成为先烈，看的太早的悲催案
例太多了，意义更是不大，哥白尼在中世纪就看到了地球不是宇宙中心，于是就
被火烧死了，太多太多聪明人死在了不在当下生活的故事里去，等好不容易撑到
风口来的时候，他已经先没了。


而如果，趋势都被人看到的时候，其实趋势的意义也就没量，当真理都被大家接
受的时候，真理就会沦落为常识，你已经没有任何机会和优势来成为一个布道者
了，在现实中也有挺多好玩的事情，前些日子听到一个农民说，政府让我们种葱，
我们就种蒜，政府让我们种蒜，我们就种葱。这个就是极为简单的朴素的趋势性
发现的案例。当趋势被所有的人都看到的时候，你其实只能回归到赚辛苦钱的逻
辑里去，记住辛苦钱往往不赚钱的真理吧。


在这个特征里，我们收获的东西是什么呢？是提前预判很重要，因为只有在人们
尚未发现，而你却提前发现，也提前动手了，那你或许能有先发性优势。这里挺
有意思的是很多人其实都能看到一些趋势性机会，但是能下手的人其实也不多，
看多做空，看空做多，甚至看而不做的人，其实都挺多，我们经常听很多人说，
当年我怎么怎么看对了，但是这种看对了，跟你有啥关系么，屁关系都没有，总
体来说，爱折腾的人，胜算更大，未来的创业很大程度上会比拼试错的次数和成
本的综合。尤其是趋势留的时间窗口越来越小的时候。


我感觉我自己算是在金融领域这几年稍微有些薄名很大程度上还是做了些预判的
吧，回头看两年来写的一系列金融文字，还是很大程度上预判来我国的金融经济
形势，也对一些企业做了整体性的判断，大体还是经得起推敲，实践也在不断的
验证一些当初的观点。


我2011年提出经济形势下行，金融去杠杆化即将开始的情况的观点，持有货币现
金是相对合理的理性选择，现在基本上也得到了验证，最近很多人都在提说企业
做好过冬的准备，其实现实的情况是，如果过去两三年前不提前准备好过冬，现
在大部分企业都已经半截子入土了，也就无法过冬了。尤其是杠杆很高的金融企
业，难度更大。一个普遍性的经济下滑趋势下，金融的整体性盈利格局是很难维
系的，整个逻辑链条其实是很简单清晰的，难度就在于你怎么判断经济下行的格
局，尤其是在2011年还不是很明显的市场情况下，乐观气氛浓厚的2011年里提通
货紧缩的确是不太容易让人接受的观点。


我自己对金融行业得简单理解就是金融很大程度上看天吃饭的行业，在普遍性不
赚钱的市场里，你金融机构要实现盈利，难度其实很大，这种典型看天吃饭得行
业得合理逻辑就是能赚钱得时候，狠狠得赚钱，不能赚钱得时候就回家休息，游
山玩水。不跟大趋势做对抗，当然不是说大趋势不好，你没有赚钱得机会，只是
这种机会会很辛苦，好汉不赚六月钱？火中取栗得事情玩他干什么呢？


我过去几年在四川一个高利贷培训班，我一直都是这个观点，很多学生都问我，
那我们怎么办呢？难道等死么。我其实不是很想的明白得是，为什么不做就是等
死，不干事情，难道就不能休息睡觉？为什么要每天把自己弄的累死才心满意足？
事实上，与其在家勤勤恳恳到处作风控放高利贷，不如跟着我游山玩水，骗吃骗
喝，这个花钱一年能花多少？


我承认，我的课程一直不太被人喜欢，因为这个世界做个说实话的人，向来都不
讨好，说实话尤其说难听的话的人，往往都挺可悲


当年袁绍官渡之战，谋士跟他说，不能打，不能打，一定败。袁绍不听非要打，
还把谋士关了起来，后来果然败了，别人就跟谋士说，主公败了，真该听你的话
啊，回来会感激你得。谋士就叹气说，不是的，如果主公胜了，一定会很高兴，
然后天天奚落我，骂我神棍，我还能活命，如果败了，他一定会觉得面子挂不住，
反倒把我给杀了。没多久就应验了，这个世界没人喜欢说真话，的确是有道理的。
不过好在我是自由身，这个也是互联网带来得好处，就是你喜欢听就听，不喜欢
听就不听，关我屁事。


好像扯的有点多，但是两年过去了，随着民间金融出事越来越多，其实基本可以
验证一个观点就是，我们过去维系金融体系蓬勃发展的市场性基础在坍塌，从过
去三十多年来看，维系我国信贷金融体系的基础其实是市场的企业一直是赚钱的，
我们八九十年代，企业能赚钱，无论你是摆地摊还是生产物品，都能赚不少钱，
2000年以后，生产可能本身不赚钱了，但是资产升值所赚取的利润甚至比单纯的
生产本身还赚钱，使得你过去的金融体系，无论是低利贷还是高利贷都可以被收
益覆盖，企业只要赚钱，金融机构你怎么玩，都不会出问题。


但是现在的市场的可怕之处在于谁都不赚钱，在一个整体不赚钱的市场里，金融
的逻辑则永远无法实现，企业赚了十块钱，还你三块钱愿意，但是总共赚个三块
钱给你两块，估计就心不甘情不愿了，如果亏钱了，要还你三块钱，基本就是跑
路的格局，所以谈金融困境很多时候首先要谈的问题是经济问题，都不是本身单
纯的金融问题，核心是你信贷供给无法解决企业是否盈利的问题，目前市场企业
为什么不赚钱很大程度上是因为整体性的产能过剩，这个问题恰恰是非金融命题
可以解答的，你放水也好，扶持也好，都无法消耗整体性的产能困境，这样的市
场里，去产能成为了必然的格局，去产能是成本很高，代价很大，而放松金融恰
恰不是去产能的逻辑，如何理解金融扶持呢？如同一桌子人嗷嗷待哺都快饿死了，
怎么办？现实的选择应该是饿死一部分人，然后给剩余的人支持，这样就能延续
下去，而金融放水是什么？放水就是如同来一场盛宴，给所有的人一起吃，然后
呢，强壮的和不强壮的，是都能吃一场饱饭了，但是结果呢？结果其实是一起死。
如此现实残酷，怎么选？不知道。


某地区政府呼吁救世，我跟他说，其实现在的救世其实说一场惩罚好人，保护坏
人的制度，是恶制度，为什么呢？许多规范经营的好企业，其实过去几年都挺安
分守己的，反倒是很多不安份的企业过去几年一直在扩杠杆，没节制的借钱，还
大打价格战，浙江很多企业一直以低于成本价格销售，目的并不是为了产品获得
利润，而是以此为基础向银行融资，进行其他领域的投资，他们的存在本来就让
那些安分守己的企业很难生存了，现在出现问题了，结果要去救他们了，那不是
扯淡是什么呢？坏人总是得不到惩罚，好人总是得不到保护的市场，最终就是大
家都一起变坏吧。


现实还有些好玩的逻辑，市场上生产企业不赚钱的时候，我们其实就会发现，市
场流动性会挺好的，为什么呢？因为很多企业因为生产不赚钱，不但不会借钱扩
大生产，反倒会挤压出很多钱出来，于是形成了今年二季度三季度的信贷规模下
降的情况，好人都不借钱了，因为借来的钱如果无法赚钱，好人为什么要借？那
么借钱的是什么人？是已经陷入困境的企业，流动性出现问题的企业，才需要借
钱维系流动性，避免不崩盘，而这部分企业，银行又不敢借钱，于是就出现了存
贷规模双降的情况，很现实的市场就是如此。


那么这份生产中流出来的钱去哪里呢？安分守纪的情况下，应该是趴着，但是现
实其实大部分的资金都不会安分守己，于是这部分钱，一部分成了游资，到处突
击，寻找投机性机会，美其名曰做金融。另外一部分，其实是去了互联网领域，
两个逻辑可能合一，互联网目前如此火热，恰恰反应的是整体产能过剩的情况下，
对渠道的依赖，互联网电商就是突出的表现，第二反应是钱无处可取，追逐目前
市场最大的热点，互联网，犹如黑暗中的灯塔，现实越残酷，灯塔就越是明亮，
然后大家飞蛾扑火。


今年创业市场非常火热，大量的vc成立，是个人都成为了投资人，都希望投资出
一个阿里巴巴，腾讯、百度等等，一边是实体的不景气，一边是创业氛围的浓厚，
形成了鲜明的对比，两个逻辑其实是相同的，实体越不好，资金就越挤入具备想
像力的行业中。这个逻辑其实暗含了一个很有意思的阳谋，就是政府鼓励和希望
市场上的钱都尽可能尽快的被消耗掉，这是一场消灭钱的运动，我们可以理解成
是金融去产能过剩的逻辑。想看这个逻辑的可以看我之前一篇文《只谈逻辑不谈
对错》，这里不多说了。


我们在回到趋势这个话题里去，趋势的背后其实反应很多问题，现在很多人都在
说阿里如何牛逼，如何牛逼，其实这个话题怎么说呢？在一个趋势起来的时候，
乘风而起其实难度并不如想象中大，在新兴领域并不需要太大大努力，就能较为
轻松的击败固有规则体系里的王者，苏宁曾经是线下的王者，当年股价也是及其
牛逼的，但是阿里打掉苏宁，我并不愿意认为是一个企业对一个企业的胜利，他
是一个时代对另外一个时代的胜利，每个时代里都有自己的王者，苏宁代表了互
联网未出现之前的渠道之王，而阿里则是互联网时代的王者，本质反应的其实是
人类走入了互联网时代，原先的生活作业方式时候对苏宁的依赖变得不再被需要。
这个时候，你会发现不是苏宁不努力，不牛逼，而是再牛逼也没用，你是很好很
好的，只是我也不需要了，这个是挺悲伤爱情故事。


事实上这种趋势性的颠覆市场上有过太多的案例，很多曾经在我们生命中如此重
要且认为永远都不会离开你的东西，其实发现一点点都在离去，这个观点其实用
在阿里、腾讯身上也上一样适用，你认为永远离不开的他们，也说不定很快会离
去。


想到苏宁，我突然想起了国美，很多年前黄光裕和陈晓之争，当时我写过两篇文
章骂陈晓，回头来看，我自己当评价是，我依然会骂陈晓，但是我却认同陈晓当
时的思路，黄光裕在牢里写信要求每年新增门店数量，认为这是核心竞争力，是
阻拦人家进入这个行业的高壁垒，门店越多，优势就预定先，很显然陈晓不认同
这个观点，他砍掉了很多的不盈利的门店，经营理念之争引发了他们两个的恶斗，
不去评价是非对错，单纯从结果来看，我们不得不说，其实黄光裕错了，在固有
规则和体系里，门店越多，优势越明显，但是人类进入了互联网时代的时候，发
现，门店越多，其实你是死的越快的，因为你做的再好再好，人们都不回来了，
都不需要你了。而当你认识清楚这个趋势的时候，你要掉头的时候，你发现你压
根无法回头，庞大的门店数量都是你的负担，而不是你的优势。你必须先自我革
命，让自己归零，才能跟人家一条起跑线上，但是人家会等你么？即使一条起跑
线了，你能保证你一定能在新规则下玩得过人家么？


这个就是可怕的趋势之争，不同纬度体系里的竞争是极其可怕的，压根不是单纯
和纯粹的能力之争了。互联网其实是个底层革命，改变很多的生产作业方式，从
而使得固有生产作业方式上的一系列王者的优势丧失。因为互联网这个技术，我
们被改变了很多，在很多行业都日益被互联网的今天，金融业不可避免受到波及，
但是事实上金融业由于是低频交易，他所受到的波及并不如对其他行业影响大，
但是又由于金融业的客单价高，这种变革带来的影响力却很大。


这里其实我想讲下互联网下，对金融业的几个趋势性的改变，我最近很关注众筹，
前几天跟红杉资本也谈到过这个话题，其实我想说互联网出现对早期投资的改变
是比较现实的，最大的特征就是互联网使得投资非专业化的趋势大幅度加强，怎
么理解呢？


原先的社会体系里，投资其实是很高大上的行业，投资人每天打高尔夫，住五星
级酒店，一堆人找他要钱，然后他给钱，感觉很爽，再过去那个年代里，钱是极
其重要的门槛，无论是投资还是创业，钱都是重要的门槛，你没个几千万在手，
做什么投资，其实几千万可能都不够，创业也是，阿里在十年前拿到了投资基本
上就可以把别的竞争对手给灭了，拿到钱和没拿到钱的竞争压根不再一个层面上。
所以投资人的高大上很大程度上是钱堆积出来的，他选了谁，谁可能就能快速成
长，远超越同行。


但是走到了今天两个明显变化，第一个是有钱人越来越多，越来越多的有钱人现
在都进入了投资领域，随便个土豪都能拿出个几千万做投资的时候，我们发现高
大上的投资已经彻底庸俗化了，而且原先被认为是专业性很强的行业其实被土豪
也冲击的七零八落的，专业机构估值个千八万的项目，土豪一进来就轻松把你击
垮，人家以亏了都无所谓的心态跟你玩，你很难玩的过他们，这种业余投资人的
出现，对专业化还是有一定要求的行业来说是很可怕的，而互联网的出现是进一
步加剧这个特征，互联网出现以后，让更多没什么钱的人凑在一起能量甚至超越
了土豪。这个逻辑，越来越会得到验证，而且趋势呈现加强的态度，大量屌丝拿
出无所谓亏得起的钱合投一些靠谱不靠谱的项目，然后拼了命的充当义务推广员
的作用，帮助项目快速成长，我们最终发现，以前一千个人想创业只有一百个人
能创业的时代过去了，现在一千个人想创业九百个人能创业了，为什么，因为市
场给了很多的办法给他钱，钱不是门槛的时候，市场越来越公平，能力竞争越来
越充分。


在早期投资格局里还采取传统基金的方式进行投资的逻辑，我个人感觉其实难度
挺大的，现在的投资是两头当孙子，拿钱时候当孙子，投资项目时候也当孙子，
我反正是不会去想做这种事情的，给人钱还看人脸色，这种钱不如不赚。


扯淡的有点多，我们再来谈谈，趋势的第二个特征是什么？是随机偶然不可测。
我们看到很多是因为技术的不可替代性，群体性特征的不可测性。使得技术是不
可琢磨的，而且群体性特征的兴起使得热点不断被改变，社会整体的无意识，你
很难把握未来趋势的机会在哪里。关于为什么社会整体的无意识，可以看我书章
节里大数据这个章节。这里不多说了。


我自己观察和发现，世界上能跟着趋势赚钱的是两类人，一类人是马云、黄晓捷
这样的人，他们天生具备敏锐的嗅觉，对于市场的理解很通透，而且执行力很强，
天生爱折腾，且够狠，对自己能狠下心来的人，都能成点事情，如果看准来方向，
能成大事。


还有一类人压根不存在所谓选择一说，他们中绝大多数人所谓跟着趋势赚钱，并
不是主动意识的结果，而是被动选择的结果，他们被社会的洪流抛向了不同的领
域，然后就是花落谁家是谁家的格局，有人成事，有人败事，无非是祖坟冒青烟
的结果罢了，94年被下岗的人，后来都能赚点小钱，而那些不下岗的员工，现在
估计得下岗了，02年进不了银行得人，去了房地产或者去了阿里，现在赚了大钱。
在过去的十多年里面，我们这个逻辑和趋势很明显，决定你是否赚大钱的逻辑，
不是选择，不是能力，而是运气，对，就是运气。我一直跟很多人说这个世界，
你赚小钱才是能力，赚大钱其实是靠命的，你努力勤奋，现在的社会，让你能过
比较好的生活，但是，并不是努力勤奋就能让你成为马云马化腾的，命格不再，
就别瞎想了。


其实我在台湾大学做演讲的时候提过一个叫中美教育比较的观点，我们发现美国
赚大钱的人都是名校毕业，至少考上了名校，美国要上名校，也是不容易的，都
是牛人，但是中国其实赚大钱的很少是名校毕业的，首富也只是杭州师范大学而
已，不是说这个学校不好，至少没有清华北大好，这个大家总是要认的吧。那么
这里说明的问题是什么呢？


是因为大爆发的年代里，越是底层越容易被抛向不一样的社会洪流，而不一样的
洪流，往往会有大机遇，很多人没得选择，更不会走固有的社会路径，也就更容
易被抛弃社会的大趋势之中去。我们过去十年的趋势性机会，不是互联网，互联
网其实是最近一两年的趋势，过去十年的趋势性机会其实是资产升值，大量的房
地产商在过去十年的盈利能力其实是极强的，只是趋势一旦逆转以后，互联网很
轻松的就击垮了这个固有的社会趋势，不是房地产不行，也不是互联网太牛逼，
而是社会趋势转化很快，在过去房地产是趋势的格局下，你会发现，我们曾经很
多年的首富五十强，都是房地产老板，还有曾经的煤老板，他们的出身都极低，
为什么呢？很多人其实到现在也没弄明白他们是怎么赚这个钱的，很多人都会把
自己都成功归结为能力的结果，事实上这个是最大的可悲，哪里有什么能力的结
果呢？你刚好在适合的年代碰巧做对了一件事情而已，然后以后就长期坚持这种
策略，坚持固有的逻辑去做事情的话，结果可能会死的很惨。


妹的，每次到了正题的时候，就会发现写不下去了，互联网改变社会的几个趋势，
其实几次演讲我都提过，互联网金融的趋势性机会到是没有怎么提，为什么呢？
是因为底层架构改变的过程中，金融业是随之改变的，小逻辑必然是服从大逻辑
的，所以看清楚互联网的趋势性变化，更有现实性意义。（来源：大家投，作者
佚名）
