* 侄女性：他有多爱你
前两天恋爱课程的学员，提了一个问题：
“他挺舍得给自己花钱的，我们俩共同的消费的也蛮贵的，比如吃饭什么的。我想想了觉得只要他参与享受的项目就不会那么抠门，他不参与的项目就不会那么大方。所以算不算不够爱我呢？”

对于恋爱中的女性，”他有多爱我“绝对是最常见的问题之一。有趣的是，关于她们对这个问题的看法，很大程度上反应了她们的价值观、情商，甚至可以说，能够在很大程度上预测出她们获得幸福的能力。所以我觉得有必要专门写篇文章，来讨论这个问题。

首先我们来看一下，到底如何判断一个人有多爱你呢？

常见的逻辑，是用“他有多重视”我，来评估“他有多爱我”。

那么又如何评判人的重视程度呢？

最基本的方法，莫过于看这个人的资源，尤其是宝贵的资源，例如金钱、时间、人脉，到底他们更愿意花在什么地方，来判断在这个人的心目中，不同人、事的重要性。还有就是他们愿意承担多大的风险。资本家为了200%的利润，可以冒砍头的风险。这证明例如对于他们的确是重要的。

所以，如果一个人既不愿意为你投入时间，也不愿意为你投入金钱，还不愿意为你承担风险，那么也就很难看出重视你的表现。大多数时候，也可以推断出他不重视你。

这里有种情况，例如在一些案例中，女方总觉得男方忙于工作赚钱，忽视自己。男方却很委屈：“我每天那么忙累，早出晚归，还不是为了多赚钱为了这个家。你还嫌这嫌那。”

在这个案例中，双方有比较大的分歧：


        * 对于“投入多少”的判断，男方认为自己每天很多时间是投入在关系上（赚钱为家），但女方未必认为如此

        * 对于事情重要性的认识，例如工作赚钱、两个人的交流互动，这些事情到底应该怎么去平衡

谈到重要性很多时候就会涉及到价值观，所谓价值观各位不要想象的那么高大上，我觉得价值观简单的说就是“关于事物重要性、优先级的认知。”

例 如男方认为“赚钱是重要的，我的时间要全放上去”，女方认为“我们要有比较多的情感交流，即使赚钱的时间少一些”，那么就出现了价值观的不一致。当然两个 人在一起，价值观完全一致也基本不可能。但如果大家没有对彼此的认知，能够达成共识，将时间和资源投入到能够满足关系中双方需求的地方，那么这段关系可能 就很不稳固。

对于想要长期关系的恋人，一个基本的沟通任务就是探讨彼此的价值观，发现差异，寻求共识。

例如前面的案例：

”他挺舍得给自己花钱的，我们俩共同的消费的也蛮贵的，比如吃饭什么的。我想想了觉得只要他参与享受的项目就不会那么抠门，他不参与的项目就不会那么大方。“

也 许有种可能性就是，那些男性参与的项目，本身对他来讲觉得”高价值“的，例如吃饭，吃了实在啊。反过来没有参与的项目，本身可能就反映了一种态度，就是觉 得不重要。例如女生买衣服，可能男生的价值观里，就是觉得“你不是已经很多衣服了吗，这么多钱浪费，还不如拿来去旅游。”

单纯这件事情，并不能反映出他一定是不重视对方，也许就是因为这种价值观差异，导致的消费态度。

大多数人容易不自觉的用自己的价值观去评判他人的想法。高情商的人的一个特征，就是会理解不同的人价值观会有差异，尽管自己未必会接受对方的观念，但是还是愿意去理解，并且愿意从对方的角度考虑行事。

上次在知乎上看到一个回答，说观察到自己的程序员男友，网上看到一款青釉键盘，非常喜欢但是价格太贵，好久都没有下手。然后她就买了下来。心态是”虽然不了解为什么一个键盘你会喜欢成这样，但是既然你喜欢，我就送给你让你开心。“

同样的，可能男生觉得”一个包包就几千几万块，一点实用价值都没有，简直宰人嘛“。但人家女生就是喜欢，喜欢这事情很多时候跟实用没啥关系。那么在自己力所能及的范围内，让对方开心，哪怕不符合自己的观念，这也是一种修养。

我的一位学员，跟女友谈了七年，最后女友提分手。原因是她好几次要求结婚，但男方家庭反对，然后男生一直犹豫。最后女生决定分手，然后男生求复合。但这时候女方已经在相亲准备嫁人。

女方会怎么想呢？家里有阻力你就不愿意结婚，明显是“重视程度不够”，不愿意付出代价。要真是想结婚，管父母怎么想，反正我这个婚结定了。这种态度才让对方觉得安心。

金钱和时间是最常见的资源，所以通常我们衡量重视程度，往往这两者是最常用标准。

不同的人拥有的金钱差异可以非常大，例如我们和Bill Gates，完全不是一个档次。但是时间呢，在永生或者大幅度拓展人类的技术之前，世界级的富豪未必和我们普通人能差到那里去。所以一个人层级越高，通常他会更倾向于珍惜自己的时间。

这就像普通学生，花2000块请女生吃饭，恐怕真的是重视的不得了；但反过来说事业有成的大忙人，可能花两万块也不是什么事，反过来愿意抽出时间来经常跟一个人聊天，反而是重视的表现 。

还有一种情况，就是尽管看上去两个人的时间花在了一起，但是往往是心不在焉的。例如一方在讲话，另外一方刷手机，完全没有在意。其实彼此之间的关系还是很平淡。

后 来我的总结是，其实相比时间，精力(能量）是一个更好的衡量标准。有些人打游戏的时候全神贯注，下来还念念不忘复盘；有些人一门心思要开创业公司，拿投资 人的钱；有些人想要做出伟大的产品.....反过来虽然有人天天上班貌似工作10小时，但他们的关注点根本不在这里。同样的，有些人看上去恋爱了几年，天 天在一起，但是通常把对方的话当耳边风，连对方想要什么都没有投入精力去了解过。而另外一些人，哪怕是初次见面，却能够全身心的去关心和了解对方。

前面讨论了如何判断对方的重视程度。

但问题又出来了，我们的主题是“他到底多爱你”，而爱和重视，并不是一回事。

当一个人对你有欲望的时候，也会重视。

很多女生说，男朋友在追求自己的时候，挺有热情挺花时间，自己说什么对方就听什么，要什么对方就给什么，觉得很被关心很受用。但是在一起了，突然发现对方就冷淡了。

这里一个常见的原因就是，也许对方一开始并不是有多少爱，而是有强烈的欲望。这种欲望可能是滚床单，也可能就像打游戏一样，本身”没达成的目标“，有新奇感挑战感愿意投入。一旦通关了，就没什么继续投入的兴趣了。

鉴于“爱和欲望”都会导致重视，要判断一个人多爱你，首先要能够区分这两者。

那么爱和欲望的差异在哪里呢？

爱的思想是”我想要你好“，欲望的思想是”我想要我好“。

在各种表白桥段中，一种常见类型就是：


        * 我爱你，见到你就很开心

        * 我爱你，没有你我简直朝思暮想，茶饭不思

        * 我爱你，有了你我就觉得有了世界

他们到底表达的是什么呢？其实是”我想要我好“，也就是自己的欲望。

我有学员，最近一心想和前男友复合。尝试跟前男友联系，了解到对方最近面临一些困扰。于是我建议她”从朋友的立场关心对方“，对方的反应比较冷淡（礼貌的谢谢），然后她就觉得很受伤，觉得对方不上路。

我问她：”你表达自己的关心，是因为你爱他呢，还是因为你的欲望？“
她说“我爱他啊”。
我问：”如果他不会选择你，你还会做这些事吗？“
她说不会。

那么我的理解是，她的动机还是欲望，想要在一起。如果是出于爱，出于”我希望你好“，那么无论是不是最后在一起，该关心的还是会关心。

我就跟他说：“反正我没有觉察到你多爱。多爱的话你会更关心他，而不是更关心你自己的欲望。”

当然在现实的恋爱关系中，爱和欲望往往是同时存在的，一个人因为欲望追求另外一个人，也是没什么问题的。但是：


        * 如果一个人因为欲望重视我们，我们会觉得这是合理的，但也不会为此感动

        * 如果一个人因为爱而重视我们，我们会觉得这是一件值得感动的事情

所以有女生说：”谁对我很重视啊，我有什么话就记住，然后帮我实现。“其实这件事情，我觉得单独来看，难以分辨到底是因为欲望，还是因为爱。

我建议自己的朋友，在选择长期伴侣时，首先要做的不是看对方对自己有多好，而是看对方对跟自己没有利益关系的人，是什么样的态度。

以我自己的经历，通过长期的公益项目认识的人，往往对他人有热情有爱心的比例更高。毕竟实实在在的付出自己的时间去帮助素不相识的人，就是重视的表现。而这些项目往往尽管也会涉及到现实的利益（例如拓展人际网络），但还是需要能够看出一个人为他人付出的意愿和能力。

刚才提到的想和前男友复合的学员，我们讨论下来，她很大的问题就是自私、缺乏爱心，老是希望得到。

我跟她说：”要愿意让别人爽，让别人开心，让别人更好。哪怕只是你周围的、没有利害关系的，甚至陌生人。”

例如去餐厅，经常夸夸服务员，让别人心情更好一点，也不要在意什么回报，这也是爱心的体现啊：“我想让你更开心一点”。其实这样做，通常你也能够得到更好的服务。当然本意上，不用追求回报。但人类的心理就是这样，别人让我更舒服，通常我才更愿意让别人舒服。

大家如果观察一下周围那些广受欢迎、喜欢的人，往往有共同点：他们把爱心、热情、关怀给了他人，自己却很少索取什么回报。反过来什么样的人我们不想打交道呢：自私的，付出3的价值就希望得到3、4、5的回报，甚至不付出就希望回报。

做人的一个基本原则，就是愿意无条件的让别人爽，这既是爱心的体现，也是做人的智慧。

和自私的人在一起，他们的好，总是希望你将来还的，还要带上利息。

另外一个角度，爱也是一种能力，例如如何了解他人的心理，如何关心得恰到好处，如何给别人有效的帮助，这些都是需要学习的。如果一个人仅仅是“我有欲望”的时候才去做事，那么他就失去了大多数的学习机会，能力的成长自然也受限。

好了，前面分享了关于如何判断”他到底多爱我“的思路。但是接下来也想跟大家讲，如果你在恋爱中，经常想的问题就是“他到底爱不爱我有多爱我“，其实这常常是一个信号，意味着你有更大的问题。

首先，经常困扰于”他到底爱不爱我“，往往反映了女性在关系中，缺乏安全感。

为什么这么说呢？


        * 如果女性对这段关系有信心，通常不会纠结于这个问题

        * 即使对于这段关系不看好，但是如果女性相信即使对方不爱自己，关系结束了，自己还是能够过得很好，也不会特别纠结

缺乏安全感，可以说是女性面临的头号恋爱问题。即使是在大多数人眼中看上去条件好、不愁人追的女生，在关系中往往也会有强烈的不安全感。

而 一旦缺乏安全感，她们常常会开始在恋人面前刷存在感。我的学员跟我说，她会拼命作，男朋友对她很好，但是经不过一作再作，开始疲惫抗拒，两个人的关系降 温。然后因为关系下降，不安全感更加强烈，变得更敏感猜疑，于是变本加厉，例如查消息记录、拼命逼婚。最后男方提出分手，她开始想要挽回，但为时已晚。

在 传统观念里，女性常常期待男性给自己带来安全感。但任何事情都是要付出代价的，如果你连基本的需求（安全感是基本需求）都要依赖于男性，那么独立也就无从 谈起。Freedom is not free, it's expensive. 归根结底，树立安全感应该是一个人自己的责任。

那么到底如何树立安全感呢？

首先你需要了解的是，缺乏安全感的根源，在于缺乏对自己的掌控，只能依赖他人。

在《高效能人士的7个习惯》中，作者指出一个人的成熟，分为三个阶段：

Level 1：依赖

在依赖阶段，一个人的思维以“你”为核心：你照顾我，为我的成败得失负责。

小孩就是在典型的依赖阶段，没有完整的法律权利，要有监护人通常是父母来照顾。出了问题，法律上也更多是强调监护人的责任。

依赖这件事情也表现在几个层面。

首先是人身层面上的依赖。例如小孩自己不能随意走动，要有父母或者其他人的监护。

在古代，女性和小孩一样，也是没有对自己人身的自主权的。在家从父，出家从夫。到了今天，法律上女性有了完整的人身自由，但现实中，在很多经济落后思想落后的地方，女性的人身自由，依然是难以得到充分保障的。

前几个月热议的山村最美女教师案例，就是一个极端情况的代表。被拐卖，没有人身的自由，而且周围的人甚至父母并不觉得“人身自由”是一个原则性的问题。尽管极端，但是以中国之大，很多地方的经济、思想依然可以说停留在古代，这种违法犯罪、限制人身自由的情况绝对不是个案。

当然更多的时候，并没有强制的外力限制人身自由，但是旧思想依然在中国有浓厚的基础。例如还是有不少人认为家庭暴力不是大问题，"老公教训一下老婆算什么呢"，默认男性对于女性身体的处置权。

在 这样一种环境中，对于女性在婚姻和家庭中的定位，通常是工具导向的：性工具、生育工具、养育工具、其它劳动工具。在经济超级落后例如很多偏远山区，这种思 想会赤裸裸的表达出来。而在其它地方，没有那么极端，女性有更多的自由度，但是“女性就是要相夫教子”这个中心思想，在今天恐怕依然是主流的婚姻观。衡量 女人的关键标准就是嫁的好不好、生了什么娃、娃养的怎么样。

第二个是经济上的依赖。

鲁迅在《挪拉出走之后》中谈到，一个新式的女子走出家庭，最后有两条路：堕落进了妓院，或者回到家庭。原因在于她们没有经济上的独立，因此即使看上去有了人身的选择，最后还是走回了老路。

Freedom is not free. 相反，自由常常是昂贵的。

郜老师这件事情，换个角度，假设她有经济能力在诸如北上广之类的地方过的很好，恐怕她对自己的事情的看法，又是另外的情况。而作为山区教师，吃财政的饭，讲话和做事自然也有很多限制。

所 以男女平权这件事情，发生的土壤往往是在文明程度高、经济发达、女性容易实现经济独立的地方产生。例如国内北上广，白领阶层的男女之间，大家的收入常常在 一个量级，你买得起的我也买的起，我买不起的常常你也买不起，谁怕谁呀。在这种情况下，女性择偶会更多的考虑自己的情感、价值观等精神层面的内容。

第三个是情感上的依赖。

前几天在知乎上看到一个问题：“三年的爱情分手了，他不爱了，而我该怎么办？怎么走出来？”

提问者的描述是：

" 跟男朋友是高中的同桌，在一起三年了去年十二月第一次听他说他不爱我了要分手，难过的要死。结果他后悔了三天后又回来找我，我马上就原谅他了，因为我真的 爱啊。但是从今年一月到四月无数次的分分合合。直到前几天他说他真的爱不上了，不要再逼他了。我心里也明白回不去了，可是就是很痛苦放不下，夜夜失眠也不 怎么想吃东西，可是还是忍不住每天联系他，然后听他说了各种狠话，这张嘴我听过极致的情话和对未来所有关于我的计划，如今却句句话刺在我心里，我甚至求他 再试一次不要分手，已经赌上了自尊。可是他的态度这次特别强硬。而我总抱着幻想觉得他还会回头，也总抱着回忆，夜夜失眠，爱情的最后，我成了自己最讨厌的 那种女孩，纠缠不清，没有自我，被人耻笑，可是三年啊，我要怎么抽离啊"

没有对方就不知道怎么过了，这是一种强烈的依赖。

在 言情小说、电视剧中，浪漫的爱情常常是一种“拯救式”的。灰姑娘跳了个舞丢了只鞋，然后王子就找上门来，从此两个人过上了幸福的生活。公主被陷害了沉睡 100年然后王子过来一吻，从此两个人过上了幸福的生活。女主人公长相平凡脾气暴躁但就是有集天下男性优点于一身的人瞎了眼拼命的倒追，然后…又是过上了 幸福的生活。

受到各种思潮潜移默化的影响，诸多女性的爱情观，依然是非常的被动，潜意识里常常期望有一个真命天子，带给自己幸福。却忘记了这是属于自己的责任。

但就像张学友的《情书》唱的：等待着别人给幸福的人，往往过的都不怎么幸福。

Level 2：独立

在依赖阶段，一个人的思维以“你”为核心：你照顾我，为我的成败得失负责。而在独立阶段，一个人的核心思维是“我”：我对自己负责，我有权选择。

一个人什么时候会进入独立的阶段呢？以我的观察，很多很多人一生，从思想上都没有走进这个阶段。

例如中国的父母，在催小孩结婚的时候经常用诸如“你都没结婚爸妈怎么开心得起来”之类的话。但这种语言本身就表明了他们的依赖性：一个人的快乐是自己的责任，而不应该是一定要别人做什么。

需要说明的是，很多人对独立的理解是选择的自主权“想做什么就做什么”，但却忽略了权利的另一面是责任：承担起属于自己的责任。

我认识一位女生，她和男朋友关系不好，觉得男朋友不懂她。例如选的餐厅不是自己喜欢的，讲话的对方不懂自己的言外之意。

因为她抱怨了几次，我就跟她说：“你可以跟他沟通啊，让他知道你的想法”。 她说：“为什么，爱我就应该要懂我啊”。

问题在于，人家现在也许的确不懂你。那怎么办呢？

她觉得“懂我就应该是你的事情，不是我的事情”。所以今天即使你不懂我，我不开心，我也不会去主动的改善状况，让我们的关系变得更好。

在糟糕的恋爱和婚姻关系里，很常见的一种情况就是双方或者至少有一方，遇到事情习惯性地会指责对方，觉得是对方的问题，但是“我没有错啊，我没有责任啊”。这种人常常停留在依赖的阶段，心理上没有断奶。进入关系中也容易问题不断。

Level 3：互赖

回顾前面的内容：在依赖阶段，一个人的思维以“你”为核心：你照顾我，为我的成败得失负责。而在独立阶段，一个人的核心思维是“我”：我对自己负责，我有权选择。

但人的成长，还有第三阶段：互赖。

互赖的核心是“我们”：我们共享目标；我们一起合作；我们深入沟通；我们融合彼此的智慧与能力，实现1+1>2的效果。

在《高效能人士的7个习惯》中说：


        * 依赖期的人，靠别人来实现愿望

        * 独立期的人，靠自己来实现愿望

        * 互赖期的人，群策群力实现最高成就

需要说明的是，互赖的基础是独立。就像打游戏组团，每个人都有出色的技能，自己也能玩的很开心。那么大家一起打怪才有基础。对于婚姻关系也是如此，一个人能够自立，自己也能够快乐幸福，懂得尊重他人的空间和独立，愿意承担责任，这样结成的联盟才容易碰撞出更大的火花。

在这个层次的人，除了本身的独立技能，在团队合作、沟通、人际关系这些方面的科技树会比较发达。

总结一下这3个层次：


        * Level 1：依赖

        * Level 2：独立

        * Level 3：互赖

各位可以注意的是，大多数人之所以缺乏安全感，是因为他们还在依赖阶段，无法独立掌握自己的情感、经济、命运。

但是很多在Level 1的女性，她们解决问题的中心思想，不是升级自己，成为一个独立的人。而是指望靠婚恋关系来解决自己缺失的部分：


        * 心情不好了，要找个男朋友哄我开心

        * 房价太贵买不起，找个老公

        * 工作不顺利，找个男人

她们简直把”找个男人“当成了解决自己问题的万能武器。先不说这种心态本身就让高质量的男性远离，即使遇到了，充满不安全感也是正常的事情。谁叫你人生中最大的姐问题，一定要依赖别人呢。

所以各位女性，在困扰于”他到底爱我吗有多爱我“这个问题的时候，请你首先评估一下自己，目前处在成长的哪个阶段？如果是阶段1，最大的问题并不是你眼前的男人，而是你自己的心态与能力。

理解了这三个层次，一个有趣的事情，是关于婚恋关系中的组合。

通常来讲，我们容易吸引到同一层次的人，所以我们先看看同层组合：

依赖-依赖：

典型的问题组合。双方都希望对方来解决问题，认为自己没有责任。在这样的婚恋关系中，尝尝伴随着频繁的争吵。既然对方没做好，指责当然是正确的事情了。

尽管双方都认为对方不好，但很多时候这种关系并不会解体，因为常常人们没有更好的选择，或者有不得已的因素，例如性、小孩、经济。

独立-独立：

低温关系，松散联合。在这样的关系里，大多数时候是各管各的，缺乏深入的沟通与合作。如果因为一些事情需要合作或者妥协，可能会出现比较大的争执。

互赖-互赖：

这样的组合容易产生高质量的关系，双方能够独立的做好自己，也理解合作、关系的重要性，愿意从对方的角度去考虑问题，达成双赢的结果。

这种组合的婚恋关系，常常是温暖、热情、快乐的。抗风险能力也更强。

那么不同层次的会不会组合到一起呢？

当 然有，但是，通常只会是“依赖-独立”、“独立-互赖”这两种情况，也就是双方差一个层级。而“依赖-互赖”这种组合，以我自己的经历，从来没有看到过比 较长期存在的。大概是一个人如果本身独立性强，又是非常好的team player，这样的人对于伙伴的要求也会非常高，对于不愿意承担自己的责任更谈不上作出出色的配合的人，很难容忍。

有句歌词叫做“我只有不停的要，要到你想逃”。在“依赖-独立”组合的关系中，独立型的人要处理一个很大的麻烦：就是管理对方的依赖性，避免成为对方的保姆，给自己争取到足够的空间。最重要么双方在某条线上达成均衡，要么走向散伙。

对于考虑长期严肃关系的女性，在思考“他有多爱我”这个问题之前，我觉得更重要的问题是“他在什么成熟度的层次上？”


        * 在依赖阶段的人，他们会让你代替他们去完成他们该做的事情，承担他们该承担的责任。心理上没断奶，还是个小孩。

        * 在独立阶段的人，还没有学会“有效沟通、团队合作”。

以我的经验，有这么三个看法：


        * 一个人是可以实现升级的，从依赖到独立、从独立到互赖（恋爱沟通课的目的也是旨在帮助大家的升级）

        * 大多数人一生中都没能实现从依赖到独立的完整升级，也就是整体停留在依赖阶段

        * 如果一个人自己不愿意改变，那么在一段关系中大多数人也没有能力推动他们升级

这意味着，在多数情况下，一个20多岁心理上还是处于依赖阶段的人，最大的可能是一生都处于这个阶段。

依赖阶段的人，最大的问题莫过于他们老是指望别人解决问题，很少想过提高自己，或者浅尝辄止。这种心态很要命，而且难以教育。而独立阶段的人通常给予他们自愿和帮助，进化到第三等级容易很多。

写到这里各位应该可以自然得出答案：最好是选择在“互赖”层次的伴侣，这样长期关系成功的可能性大很多。没错，当然要做到这一点，最好的就是女性自己也首先升级。毕竟就像查理芒格说的：要得到一件事物的最好办法，就是让自己配得上它。

当你在第三层次的时候，你会发现“他到底多爱我”这个问题，其实并没有那么重要了。

首先，按照吸引法则，通常你能够吸引到“互赖”层次的人。而这个层次的人，通常来讲他们有足够的资源和高质量选择，也知道自己想要什么。所以这样的人在关系中反而会更真实，做自己就好了，没有多少欺骗的必要性。

第二，在这个层次你会有更高的见识去认识不同的人，因此判断的准确性会高很多。

第三，你已经能够掌控好自己的情绪、经济、思想，也善于跟不同的人建立温暖、热情、亲密的关系。那么即使这个男人不那么爱你，你也不会觉得世界就塌下来了。

第四点，其实也是我觉得最重要的一点。鉴于这一点需要花比较多的篇幅解释，我放在了最后。

一个人的成熟，价值观的升级是超级重要的一块。

在价值观中，财富观是一个基本的组成部分。

什么是财富呢？简单的说，财富就是人们需要的东西。它又可以分为物质财富和精神财富。

例如手机，我们需要手机来和其它人沟通，这是一种物质财富；
莫扎特的音乐、金庸的小说、郭德纲的相声、牛顿运动定律、圣经，这些艺术、科学、宗教上的东西，是精神财富。

我们的生存和发展，是需要财富的。我们要吃饭、要听音乐、要学习知识......

很多人说需要钱，其实本质上我们需要的不是金钱，而是财富。

举个例子，如果你在撒哈拉沙漠里，荒无人烟。你身上有10亿美金，可能毫无用处。你现在需要的是水、食物、手机、骆驼或者其它交通工具。

金钱只是财富的中介物。

既然我们都需要财富，那么到底如何获得财富，这里面就有两种价值观了：创造财富 vs 分配财富。

先举个工作上的例子，假设你做销售。

你是想通过创造财富来赢得订单，还是通过分配财富赢得订单？这个决策会影响你的整个人生。

价格折扣是一种财富分配（在公司和客户间的分配）、回扣是一种财富分配（在公司、客户公司和受贿者之间的分配）。无论客户是否真正需要你的产品，都要强力推销是一种财富分配（客户的钱流到你们的钱包）。

大多数销售的失败是自然的结果，因为他们的技能几乎全是关于财富分配的（价格折扣、回扣、强力推销），不少客户待见很正常，不会做蛋糕就像分蛋糕的人多了去了，为什么就要选择你呢。

如果你通过给回扣、拼命打价格战赢得了订单，长远来看很可能是一件坏事。他让你忽略了更重要的事情：为客户创造价值，通过把蛋糕做大来得到更大的利益。

有趣的是，很多销售喜欢说“价格没有优惠怎么卖的出去呢？”，事实上这里面常常有情况就是，他们进入了“降价=>成交=>降价"的循环，精力完全没有放到客户价值创造上，所以最后他们说的的确是对的，因为没有任何的附加值，只能靠降价来吸引客户。

如果你是以”分配财富“为导向的，通常你会觉得赚到钱就可以啦，至于是怎么来的不是大问题；而如果你是“创造财富”导向的人，你会关注“我为客户社会创造了多少价值”，然后才是你的回报。

前 几年，很多人选择工作，喜欢选择公务员、教师等等，并不是因为他们觉得能够为社会创造多少价值，而是觉得”待遇好福利好有保障“，本质上就是冲着”财富分 配“去的。这种想法其实是愚蠢的，道理也很简单，从长期来看，整体来说，一个人如果没有价值创造能力，在社会上也很难得到高回报。在20岁的时候就关注” 我能得到多少“，完全是看错了点。

反过来，我们看互联网时代的顶级公司，往往他们成功的典型路径，是先为社会创造巨大的财富，然后获取回报。

例 如Google，Google的问世带来了人类获取信息和知识的革命，真的是做到了”信息随手可得“。但Google并没有收我们大多数人的钱，却已经为 整个人类社会创造了巨大的价值。然后才找到了它的商业模式。同样的大家可以看腾讯，对于我们大多数人而言，简直就是活雷锋嘛，让我们方便的跟家人、朋友、 同事交流，却不收一分钱。他们的回报，是建立在为社会创造巨大财富基础上的。

所以保罗·格雷汉姆，硅谷知名风险投资家，说一流的创业公司，一开始看起来很像是做公益。

我们之所以推崇创新型的公司，道理也很简单，建立在”为社会创造价值“基础上的企业，才能够推动社会进步，达成企业和社会的双赢。反过来如果每家公司、每个人都只是分配财富，那么人类社会也就完蛋了。

各位这里有没有意识到，前面的案例其实可以映射到恋爱领域。某种程度上，当我们想找恋爱对象的时候，也是销售和创业过程，我们要把自己给卖出去。

那么这里问题就来了。如果你看一下大多数女性对爱情的期望，常见的就是”我要找到一个好男人，他会疼我、爱我，哄我开心，照顾我一辈子。“

这就是典型的”分配财富“导向，消费一个”好男人“的爱。本质上，这跟找个男人，消费他的钱没什么大差异。

很 多时候，女性之所以关注”他到底多爱我“，其实就是在判断”我能从他这里得到多少回报“。这个问题当然可以关注，但是如果没有前面”我为他人创造了多少价 值“，这就像大多数公司和销售，老是关注”我能从客户身上赚多少钱“，收效甚微，因为”对方凭什么买单或者付高价呢“？

那些有吸引 力的人，往往是”创造财富“型的，他们带给我们的，可能是很多很多的爱、可能是很多很多的乐趣、可能是很多很多的鼓舞、可能是很多很多的实际利益。而且往 往他们是以接近于”公益“的方式做事情，很少要求回报。最简单的美女之所以受欢迎，本质上她们也是在做公益：提供观赏价值，显然这是很多人需要的。

所以与其操心”他到底有多爱我“，还不如操心下面一些问题：


        * 你能够带给别人很多乐趣吗

        * 你能够鼓舞激励他人吗

        * 你是一个非常好的听众吗？你愿意并且能够理解他人的内心世界吗？

        * 你有欣赏的眼光、会经常发现别人的优点，并且加以赞赏，让对方觉得备受认可飘飘然吗？

        * 你善于发现别人的困境

        * 你是否经常帮助他人取得成功、实现他们的目标和梦想

        * 你是多少人的坚定支持者、拉拉队员、后勤保障

总结一下问题就是：因为你的存在，这个世界变得更好了吗？你周围的人、甚至陌生的人他们的工作和生活更好了吗？然后才是你的恋人，因为你的存在他的人生变得更好了吗有多好？

如果其他人因为你的存在变得更好了，通常他们更容易选择你，无论是朋友关系、同事关系、客户关系还是恋爱关系。或者如果你觉得现在的恋人没法给你对等的价值，换一个也容易。很多人的问题就是“没得选”，没得选的根源还是自己缺乏价值。

不 要过于在意别人给了你多少爱，而是关注于为这个世界创造更多的关爱和乐趣。听上去像是宗教信仰，但其实也是人际关系的智慧。具体到恋爱关系，如果你喜欢一 个人，我觉得”他有多爱我“是不重要的，重要的是”我去爱他”。爱的行为更容易得到爱的回馈。当然你没法保证每次都会生效，但概率上来讲，一直这样做自然 会有结果。

另外，无条件的爱，其实做这件事情本身就是回报。“我爱你所以我愿意为你做这些事情，无论未来发生什么，我觉得都是值得 的”。当你有这样的心态，不再去计较对方给你的回报，整个人生会幸福很多。毕竟，幸福的关键在于关注那些你能掌控的（我能做什么、我如何变得更好），而不 要太在意你不能控制的（对方会多爱你）。

如果你的信仰是“终有一天我会等到一个好男人，他会爱我、照顾我、哄我开心、养我、给我安全感，陪伴我一生一世”，恕我直言，恐怕你的人生很难幸福，因为你把希望寄托在没法掌控的事情上，而且因为你只是在索取价值，很难得到他人和社会的支持。

但如果你的信仰是“人生的意义不仅仅是满足自己的欲望，也是为社会创造价值。我要去带给人们很多的爱、很多的乐趣，让他们因为我的存在变得更美好，创造这些价值的过程也是意义所在”。那么恭喜你，你踩准了赢得人心的方向。在这个方向走下去，会是全新的未来。

好了，写到这里，如果各位还是希望“分配到一个好男人，让他来爱我”，接下来的内容，也就不用读下去了，等待上天安排吧。但是如果你希望带给别人更多的价值，那么这里有很多很多问题，例如：


        * 如何管理好自己的情绪

        * 如何深入他人的内心世界，洞察他人的心理

        * 如何让与他人的互动变得有趣

        * 如何欣赏赞美激励他人

        * 如何帮助他人取得更大的成功

        * 如何关心他人，以对方想要的贴心的方式

        * 如何在面临冲突时有效处理

        * 如何既成就他人，又保持自我

        * 如何创造强烈的诱惑，引导别人主动选择你

人际关系可以说是影响人的最重要的能力之一，但是大多数人从来没有得到过专业的训练。

这是恋爱沟通课创建的动机：帮助人们成为聪明、热情、有趣、有爱的人，拥有无论是对同性还是异性的吸引力，为独立和幸福打下关系基础。如果以前各位困扰不知道“怎么做”的问题，那么今天这门课程已经给了提供了学习的机会。

但是我也可以坦率的说，今天本文读到这里的人，大多数会觉得我讲的东西是有道理的，但也不会真正去改变。毕竟提升自己，是需要花钱、花时间、花精力的，而期待他人，什么都不做想想就好了。是啊，说不定2块钱就中500万了呢？

其实就是本文前面讲的道理，你重视什么，要看你愿意花多少时间、金钱和心力。所以各位真正想成为更好的自己，持续创造出乐趣和幸福吗？我也不知道，你的选择会给你答案。
