* 苦逼的人到中年
这个话题在知乎有点冷门，按这个定义知乎上大部分人应该都是年轻人吧。
<br><br>咱们暂且说中年危机是一个人<b>从40开始，到接近60</b>这段时间吧。
早的，40岁开始，父母就开始有生病甚至去世的了，晚的，人到了60，父母身体
健康常需要关注。评论区有人问，难道不应该从30岁开始吗？我3x岁的时候也常
这么想过，现在到了45这个年龄，觉得3x岁，对大多数人来说，中年生活还没有
开始，多数人刚刚组建自己的小家庭没几年，孩子还小，多数的父母身体健康，
事业仍然处于上升期。<br><br>中年危机有两个层面，一个是自身成熟的问题，
一个是社会和家庭给你的重担造成的压力。度过中年危机并不难 ，要意识到，
<b>人人都会有这个难题，你并没有什么特殊的</b>。记住一句话：一切都会过
去。我也在不断地学习与自我提高，并不能，也不想用这么个帖子包治百病。对
于中年危机，我最大的体会是，中年危机像慢性病，不可能有什么灵丹妙药吃下
去就立即解决了，它更象每天跟随着你的慢性病，要学会每天和它和平相处。多
读一些关于心理类的文章与书籍。如果经济条件允许，可以考虑进行心理辅导。
<br><ul><li>我推荐大家读一本书《少有人走的路》，中译版质量很高，这本书
我看了几次目前仍只读了一半左右。因为它对我的指导意义很大，每次读几篇就
常常要放下琢磨些日子。读一读吧，你要的答案这本书里都有。</li><li>放松
一点自己，适当读读书，把生活节奏放慢点，要意识到自己只是普通的一个人。
人从青年到中年是一个从天上落到地上的过程。梁文道说：每个年轻人都以为自
己是能飞的，可是到了最后都还是在地上。</li><li>要认识到自己有所能，有
所不能。认清楚自己的能力之所在。中年也是放弃的艺术，人的精力有限，该放
弃的就放弃，别太争一兵一卒，因为如果如果说人生的成功，是一个综合的分数
的话，那么总分高才是你想要的答案，而不是在一门成绩上耗费大量精力。
</li><li>有机会参加几次朋友的亲人的葬礼，去医院陪陪床，都能让人迅速成
熟起来，度过中年危机期。经历让人成熟，看着一个人在你面前慢慢离去，人一
下子就成熟来了，因为一下子会认识到，人都是要自己走的，再多的荣辱与物质
金钱，在离开的时候，又有什么用呢？</li><li>建议看看锵锵三人行《生不如
死的朋友》这一期。反复看，反复看，反复看，因为终于有一次我看了以后，和
以前感觉不一样了，我就明白我初步度过中年危机期了。</li><li>考虑一下自
己走了一半的人生路，有那些是要安排好的，如果明天自己突然不在了，哪些是
今天你要安排的。说白了，到了中年危机的时候，你八成也40+了，就是离那一
头更近了，我们的时间要为自己过了，该安排的要安排了。</li><li>积极参加
体育锻炼，找到一个自己喜欢的运动并坚持下去。这一点对于中年危机调整心态
非常重要。一定要尽快开始一项适合自己并能坚持下去的体育运动。你一直锻炼，
一直锻炼就会慢慢感觉好起来，因为脑子里开始生产让你快乐的多巴胺。
</li><li>交几个知心朋友，异性的，同性的，死党那种。你睏了你累了，他/她
能接着你。你在他/她面前能做自己。我想一个人能意识到中年危机这个问题，
说明他已经思考很深了，别太在意是不是同性异性的朋友，关键要是那个对的朋
友。<br>这一点也很重要。对于走出中年危机很重要，再多的人背叛你，离开你，
对你不解，冷嘲热讽，不支持你，一想到总有个人会为你点赞，就会感觉好多了。
我喜欢Terry Prachett拍的纪录片《Choosing to Die》里面的一句台词Knowing
it's there, gives you strength。建议遇到中年危机的人都去看看这部片子，
很震撼。</li><li>尝试做一些简单的事情，比如和孩子玩玩，跟妈妈一起逛街，
或者这类能让自己很容易达成的目标，可以让自己迅速有一些成就感。有一些人，
中年了，有各种各样的危机，说白了，还是把自己看得太高，如果能踏实下来，
做一些小事，甚至养一盆花，人也就放松下来了。<br></li><li>人到中年，你
该享受点精致的，对人对物都如此。不一定每顿饭都吃撑，不一定每个人都好到
腻味，《迷失东京》里那样就很好。</li><li>可是，一切都还是要你自己做，
没有走出中年危机的灵丹妙药与一喝就好的心灵鸡汤，别人说的再多，也要你自
己走。要相信自己一定能走出来，因为其实别人也都走出来了，不是吗？
</li></ul> 慢慢你可能会开始觉得世俗意义上的成功慢慢变得不那么重要了，
怎么满足自己的好奇心，自己的愿望才更重要。你可能会关心我是谁，我从哪里
来这样的问题。到底我的家庭，父母，祖父母他们的一生是怎么度过的。那么你
知道，你已经度过中年危机了。
<br><br>---------------------------------------------------------------------------------------<br><b>
写了这个答案快一年了，我来陆续更新一下</b>。<br><ul><li>一个是我想谈谈
有一个自己酷爱的爱好对于中年危机的意义。我一直爱好无线电，从小学开始到
现在几十年了，乐此不疲。我们中年的生活，丰富多彩，但是也其实满枯燥的。
已经达到人生的某个制高点，可能往后面走都是平地，甚至是下坡路。那么怎么
样才能让我们在日复一日，一成不变的生活中添加点乐趣呢，那就靠一个爱好了。
有了这个爱好，集邮也好，跑步也好，什么也好，它可以让你专注其中，暂时忘
掉烦恼，实现自我，提高自尊(Self esteem)，让我们在中年过得更精彩一点。
昨天我矿坛看到一个无线电爱好者，自己设计制作了一台四次变频短波收音机。
那是一台非常精美的兼具设计美感与实用的收音机。为了这台收音机，他设计，
制作，调试了2个月时间，全身心投入。虽然，有一个爱好，并不能解决你中年
可以遇到的问题，但是他可以让你暂时放松下来，换一个角度看待问题，或者至
少别让自己紧绷的神经出现问题，明天继续前进。</li><li>还有我想谈一下身
体健康的重要性。中年人，有的开始生病了，性子急的也有先走的了，我的一个
朋友上个月犯了回轻微的心梗，索性没有大的问题。但是也提醒了圈子里的人，
这是身体在警告我们了。</li><li>中年危机很大一部分来自于我们每天的压力，
来自于家庭，工作，都是不得不做的责任，这种压力会日积月累把人压垮。每天
接送孩子上各种才艺班，每天买菜做饭，上班，开会毫无新鲜感，要面对老人。
中年人从某种程度上说是慢性病患者，短期之内没法治愈，你只能和它一起生存，
学会对付它的办法，保存自己的实力。</li><li><b>今年夏天，回去给我的舅舅
和父亲扫墓，站在那里，看躺着进来的，盒子里装着的，还有周围哭的。觉得自
己吧，浑身哪都舒服，看谁都是好人，纠结的事全不值得。
</b></li></ul><b>2016年以来</b><br><ul><li>过了45岁的生日，家庭重担似
乎一下子都涌了出来。我还在坚持跑步，从去年5月开始到现在，将近2000公里
的跑程，冬天不得不在室内跑。最近一两年来我迷上了跑步，今年在本地参加了
四次比赛，半程马拉松最好成绩是1小时51分。我的目标是希望参加本地明年的
全程马拉松。每个人开始跑步都有自己的原因，我跑步的时候，可以自己思考自
己孤独，我其实内心讨厌周围人叽里咕噜不停地说话。人就是这样，有了一个短
期而又明确的目标之后，其他的也跟着变得轻松了。<br></li><li>最近看了一
期《一席》，”老树画画：做一个梦“，非常推荐给有中年压力的人看看。
<br></li><li>你看我的回答是零散的，一条条的，可以看到中年的问题，是复
杂的，多方面的，难以用一句话说明白的。</li><li>今天，辛辛苦苦工作的结
果，无缘无故被领导数落了几句，下班路上和好友打电话，一句个不小心，被好
友指责抢白，逼得我道歉，多少有些心酸。中年就是这样，肩负家庭和单位的责
任，你不能抱怨，觉得累了也不一定能有人帮你，唯有默默穿上跑鞋去奔跑20公
里。</li><li>中年危机是为了责任，你的一切安排和计划都可能被打乱，每天
回家刚想加会儿班儿，大人喊，孩子叫。刚泡上壶茶想休息几分钟，丈母娘让你
去买糖尿病药。你只见单位新人一个个意气风发，精神抖擞仿佛世界都是他们的，
却不想和他们说，我二十年前也曾经光鲜。如果说年轻人背后较量的是进入社会
的起点和阶层，中年的你则是家庭和社会负担。<br>终于有几个星期你刚喘几口
气，单位一改组，或者项目一变动，你可能连工作都不保。眼瞅着离彻底退休还
有十几年，二十年，一定是要去找工作的，可社会是年轻人的社会，递上去看起
来丰富的简历，招聘的人却连连摇头，暗示你不要抱什么希望。我们能做的是让
自己负担轻一些，以便在今后的路上跑得更长远些。




他看见电视里的成功人士夸夸其谈知道那都是扯淡；他喝醉了，他记得回家的路，
成功学是扯淡的意思不是说成功学不能让人成功，而是说成功本来就是一种虚幻
的东西，一种社会毒品，未必值得追求。与其用酒精麻醉自己，不如清醒地面对
恐惧和痛苦。回避不一定躲得过，面对不一定最难过。
