* CoolShell博文摘录
  原始文章见:http://coolshell.cn/
  //二级标题是文章名，链接，等

** 我是怎么招聘程序员的
*** 最想知道：
    这个程序员的是否够聪明？
    这个程序员能否把事情搞定？
    这个程序员能和我的团队在一起工作吗？

    人个认为，团队的和谐是一切事情的前提。

*** 面试测重点
    沟通表达能力。
    应聘者能不能把一个事情讲清楚。如果这个人聪明的话，他就可以用最简单的语言把一个复杂的事情讲清楚。
    而且，这是一个好的程序员最基本的能力。而且，你可以在应聘者一边描述其经历的时候，你可以和应聘者有一些的良好的来来回回的交谈，这样就可以知道，他的沟通能力和沟通方式，从而了解他的性格，。

    角色和位置。
    也许他参与了一个很大的项目，但只是做了一个很简单的模块。所以，了解其在项目中的担任的角色和位置是非常必要的。
    当应聘者说到“我们”或者“大家”之类的词汇时，一定要向下细化和明确。

    做出的贡献和解决了什么的问题。
    这个很重要，通过了解这个，你可以知道面试者是否聪明，是否有能力解决问题，是否有好的技术底子。

    演示。
    如果可能，你可以让应聘者展示一些其写过的代码，做过的设计，或是直接给你看看他写的程序的演示。
    （从设计上，代码的风格，重用性，维护性上你可以了解很多很多）

    基础知识。
    了解该项目中应聘者使用的技术的一些基础知识，比如，通过整个过程，你可以问一些网络，语言，面象对象，
    系统的一些基础知识。基础知识是非常重要的，这直接关系到了他的能力。

    流程和工具。
    了解应聘者所熟悉的项目的流程（银弹，瀑布，敏捷，……），还有流程中的一些工件（如：需求文档，设计文档，
    测试方档等），以及在开发过程中使用的工具（内存测试，代码检查，BUG报告，版本维护，开发调试……）
    （关于程序员的基本技能，你可以参考——《程序员需要具备的基本技能》）

*** 观点
    重要的不是知识，重要的是其查找知识的能力。

    相信我，应聘的程序员十个人有八个人讲不清楚以前做的是什么。
    因为他们直接跳过了项目背景和要解决什么样的问题，而直接进入具体实现。

    了解一个人的过去，了解一个人做过的事情，比其会做什么更重要。
    了解一个人的性格，想法，思维和行为，比了解其技术技能更重要。
    技术技能固然很重要，但比其更重要的是这个人获取知识的能力，学习能力是在计算机这样变化飞快行业中必需具备的。
    是否可以进行培养，比掌握的技能更重要。
