* Jekyll SEO Tips,Github Pages Blog SEO优化技巧

** Google SEO Guide
   会使搜索引擎更容易抓取和索引您网站的内容

   充分利用基本元素。

   您应该将您优化的重心和出发点主要放在用户体验上 , 因为用户才
   是您网站内容的主要受众

*** 目录
    创建独特，准确的页面标题

    网站的每一个网页创建唯一的页面标题。
    避免使用像“Untitled”或者“New Page 1”这样的默认或者不清楚的标题

    使用简短的 , 但具描述性的标题标签
    避免在标题标签里堆砌不相关的关键词

    标题非常重要

    网页的描述元标签为Google和其他搜索引擎提供了关于这个网页的
总括性描述

对那些太短 , 太长或过分重复的描述元
标签做出提醒

描述元标签是非常重要的 , 因为Google可能会使用描述元标签来
生成您网页的摘要

避免在URL中使用奇怪的大写(大部分用户喜欢小写 , 而且小写也便于他们记忆)


网站的导航功能对于搜索引擎而言是非常重要的

除非您的网站只有
屈指可数的几个页面 , 否则您应该思考一下如何更好地将用户从您
的主页(根页面)带到有特定内容的页面。
这个真是我现在在做的。

重点：要搞的。
面包屑导航是指在网页顶端或者底部放置的一排内部链接 , 它使用
户可以方便地回到上一层结构中的网页或者根页面(

用户可能截取URL，比如想看全部的技术文章。。。

使用自定义404网页能有效地帮助用户回到网站中有效页面 , 这将大大提高用户体验。您的404网
页最好能提供回到您网站主页的链接以及到您网站中热门内容页面的链接。

提供高质量的、对用户有益的内容恐怕是本文中讨论的各种要素
里最重要的一部分

充分考虑到用户理解您的主题时可能存
在的差异性 , 向用户提供独特的、排他
性的内容
妈的，这点，最难做到。

*重点*
比如 , 一个资深棒球爱好者
可能会用[nlcs](全国棒球联盟冠军赛的缩写)作为搜索词 , 而一个
刚刚接触棒球的用户可能就会用一些更通俗的词汇来查询 , 比如[
棒球季后赛]。如果您在撰写您的内容时 , 预先考虑到这一点 , 通
过综合使用各种具有潜在搜索可能性的关键词 , 兼顾到不同用户的
搜索习惯 , 那么您将会收到更好的效果

Google AdWords提供了
一个很有用的关键词工具 , 这个工具能帮您发现和掌握关键词的变
化动向 , 并了解每一关键词的大致搜索量。同时 , 谷歌网站站长工
具向您提供了热门搜索查询功能 , 您可以通过这个功能了解您的网
站最常出现在哪些搜索查询触发的搜索结果中 , 以及哪些搜索查询
给您带来了最多的访问者

您可以考虑提供一些别的网站没有提供过的新的、有用的服务。您
还可以撰写一篇原创研究报告 , 一篇新的新闻采访或者某种能够发
挥您的独特用户群的优势的方式 , 来吸引更多的用户。其


所有的图片都可以拥有一个独一无
二的名字和“alt”属性 , 您可以对这两个特性加以利用

 如果您链向了某些被Google认为是垃圾的网站的话 , 那
么您自己网站的声誉也会受到影响。
所以要用nofollow元标签。

很多网站都围绕用户互动和交流 , 这使得那些有特定兴趣的用户找到相关的内容变得更加容易

在社区里接触和您的网站内容相关的网站
您很可能会发现有些网站的主题跟您的相似。与这样的网站建立沟通往往大有裨益。
避免：
与所有相关的网站滥发交换链接的请求
为了PageRank而不是流量从其他网站购买链接


*** URL
    使用连字符而非下划线，使用小写。


** 用户如何访问一个网站
 首先，你要思考， *用户是如何访问一个网站的？*
 1.搜索引擎展示了搜索关键字结果，而你的网站页面在其中
 2.在其他网站上有链接到你网站的链接（友链，转载的原文链接）
 3.觉得你的网站内容有价值的回头客。
 4.在其他社交网站上你的介绍，或者将自己写的东西分享到朋友圈

 1.这种的可能性很小，反正我自己大概试了下，根据文章的各种关键字在Google中进行搜索， 较好的文章排名也只是排在第3页。

 2.这种链接能够带来一定点击量，但是 *没有真实有效的阅读* ，也就是Google Analysis中的Bounce Rate会升高，Session Duration会降低。
 这里并不一定是你文章写的不好，可能是：美国人访问你的中国网站；别人不懂这些技术文章。所以，这里就要求我们对自己的文章进行进准投放。

3.这点，无论是放在那里都成立，也就是 *内容价值是网站的核心* ，创造并带给别人价值的任何事物都会受到欢迎。

4.这个可以带来非常多的流量，特别是现在的朋友圈，大家都是手机控，低头族。无事玩手机，但是有个问题是： *你的内容的可替代性太高。*
针对的用户人群不太对，真所谓“得屌丝者得天下”，而用Google的都是较高素质的人群。

** 互联网网站的整个生态链流程
其次，我们再来思考下， *整个互联网网站的生态链流程。* 也就是 *网页从产生到网页被消费的过程* 。
1.首先，我们精心写好一篇文章，然后将它发布到自己的网站上
2.等待被搜索引擎收录（除此之外，别无它法，因为浏览器，搜索引擎把持了流量入口），然后被用户搜索到
3.等待用户通过其他网站的推荐，点击网页的引用外链来访问

*所谓的SEO，最多只能影响第2步中的收录，以及搜索结果的展示。*

 我们先来说说SEO。

*** 被搜索引擎收录
作为一名程序员，其实这一步是非常透明，非常容易理解的。看似很高大上的收录，其实就是将你的网页，一个HTML文件存储起来。
但是不可能只是全部存储起来，必须要能被后续的查询给索引到。所以会将此页面进行切分，提前出网页的特征。

所以你网站内容的特征约是符合搜索关键字，就越有效。

而网站的特征是从何提取的了？
*标题Title，描述Description，文章内容Paragraph*
而且标题和描述还会作为SER（Search Engine Result）作为结果展示。
所以可见标题，描述的重要性。而网页的URL也会展示出来，所以URL的描述性也非常重要。
文章内容只是会用来匹配关键字，在结果中高亮展示前后文。
标题长度不超过55个字符，描述长度是80到160个字符，过短，过长都不好。
（提取网页特征，之前还有keyword，现在被google完全废弃了，但是建议还是加上。）

所以为了便于搜索引起的收录，HTML页面的质量，规范就非常重要。
1.页面不能太大，否则，不说用户体验不好，搜索引擎本身就不好读取，保存。
你可以想象搜索引擎是一个人，而网页是它的食物，如果食物太大，无法下咽，它当然不会吃到肚子里面（收录）

2.页面要符合html规范
还是以食物打比方，你的HTML页面就像一道菜，必须色香味俱全，盐和酱油什么的都要搭配好了。
它才会觉得好吃，才更加乐意去吃到肚子里面。这样你网站的收录量才会大。

3.页面的描述性
存起来都是为了以后查的，因此良好的页面描述性，页面的不同寻常就至关重要。
想象一样你的页面如同一本书一样被存在了一个图书馆里面，后面有人来查找一类主题的书籍，
那么如何让搜索引擎像图书管理系统一样的展示你的那本书了？ *就是你书的与众不同，明显的特征。*


4.页面元素
文字的很好，但是图片，flash，视频，这些富媒体，搜索引擎怎么处理了？
很显然，现在的搜索引擎还没有那么“人工智能”能够分析出你这张图片是针对什么内容的。
即使可以，这个计算量和资源消耗也是非常大的，再说互联网上每天这么多图片，搜索引擎不会去这么搞事情。

这只是图片，对于flash，视频这种就更加无能为力了，对于它们，其本质就是一个URL，搜索引擎也只认为是一个URL文本。
因此URL的描述性就很重要了，所以，使用具有描述性的URL。这个和我们写程序，使用有描述性的变量名是一致的。
而且给这些富媒体都补上alt属性吧，当URL失效了，没有人知道这什么，包括搜索引擎和访客。

描述性的重要再强调下，不管多么黑科技，最终都是要人来用的，描述性是给人看的（URL的显示），描述性也是给人用的（搜索匹配到描述性的结果）。

*** 搜索引擎结果展示
从搜索结果中，那些高亮的，黑体的字，我们就可以推断出，为什么google给我们这些结果。
很明显，以“数据库分库分表”为例，google首先会以全量匹配标题，找到了，直接返回。
然后将这个关键字拆分成“数据库”，“分库分表“来查询的，在标题中匹配到一项，或者两项的返回，
也有的可能在文章内容中匹配到，会在结果中高亮显示，并展示前后文。

如果几个网页，都符合相同条件，比如完全匹配，那么就会用到类似PageRank之类的东西，将权重高的排在前面。
你可以自己试着，多输入几次你网站的标题，刚开始完全输入，然后分成词输入，看看搜索结果的改变和效果。
这样你就知道了， *如何将标题起名为用户最可能搜索的*

在以“怎么打空气牌”为条件搜索，

再以“怎么诈唬”为条件进行搜索


如何留住客户，建立交流关系

** 其他补充
*** PageRank介绍
   PageRank是根据来自其他网页的链接衡量出此网页的重要性。

   主要的有以下2个维度的依据是：
   1.指向你网页的外链个数，也就是投票数。
   2.当前指向你网页的那个网站的PageRank。
   也就是质量和数量，核心想法就是越是重要的网站会被越多的引用。

*** 一些摘录
   只有完全匹配到关键字的的才会显示成黑体，所以好好想想，大多数人会怎么来搜索，用什么关键字来搜索。
   要让用户点击三次可以到达网站的任何一个页面。
   要增加高质量的外链，增加相关推荐（比如说我们经常见到右侧本站的最高阅读的排名列表），
   然后就是给每一个页面加上keyword和描述，并且对外链设置nofollow标签，避免spider爬着爬着就爬出去了（减少网站的跳出率）


 这篇文章想写写关于使用jekyll和github pages搭建的博客的SEO问题。
 不管是之前玩wordpress，还是现在的jekyll，经常看别人写的相关SEO文章，什么关键字啊，url优化啊等等。
 但是总是不得要领，因为你掌握的最多只是一些小技巧，而不是 *搜索引擎的工作原理，整个用户访问网站的生态链的流程。*

** 技术关键字
   试验，测试，现在我大概了解到Google的工作机制。

   首先是分词，然后是尽量进行全部匹配，最先最重要的是主题，其次是描述，然后是全文。
   如果刚好完全匹配到了，就会返回这条结果。

   如果同时有2个以上网站匹配到，就会算page rank之类的东西。

   如果没有全量匹配到，就会匹配部分关键字

   所以关键的是：想清楚，用户会以哪些关键字，关键词语来搜索。
   这样又进一步的要求你对使用Google很熟悉。

   而一些高端技巧，会的群体很少，所以，想网站流量什么的很容易。

   大小写不敏感，

   但是不一定和标题相关。

   比如有些高权志的网站，标题喊部分，页面有部分

140个字符，70个汉字不到。

*技术文章的一些关键词，简介，原理，机制，例子，等等。*
因为我的受众主要是中文的，但是又在使用google的搜索引擎，所以非常的不好，
要知道中国人口12亿啊。

github pages被百度收录，真TM烦。
Most search engines prefer an meta descriptions between 80 and 150 characters.

The description relevancy to webpage content is 0%. The description tag should match the content on your webpage.
也就是des中出现的东西，最好也在文章中出现。

搞好自己的技术，写点文章，提升自己，各行各业都有人才，就连SEO这么小的东西都有人这么牛逼。
写完吧，不搞这些J B东西了，烦，搞技术，多看几篇论文，多翻译下，解读下。
