* Google SEO Guide
   您应该将您优化的重心和出发点主要放在用户体验上 , 因为用户才是您网站内容的主要受众
** 目录
    创建独特，准确的页面标题

    网站的每一个网页创建唯一的页面标题。
    避免使用像“Untitled”或者“New Page 1”这样的默认或者不清楚的标题

    使用简短的 , 但具描述性的标题标签
    避免在标题标签里堆砌不相关的关键词

    标题非常重要

    网页的描述元标签为Google和其他搜索引擎提供了关于这个网页的
总括性描述

对那些太短 , 太长或过分重复的描述元
标签做出提醒

描述元标签是非常重要的 , 因为Google可能会使用描述元标签来
生成您网页的摘要

避免在URL中使用奇怪的大写(大部分用户喜欢小写 , 而且小写也便于他们记忆)


网站的导航功能对于搜索引擎而言是非常重要的

除非您的网站只有
屈指可数的几个页面 , 否则您应该思考一下如何更好地将用户从您
的主页(根页面)带到有特定内容的页面。
这个真是我现在在做的。

重点：要搞的。
面包屑导航是指在网页顶端或者底部放置的一排内部链接 , 它使用
户可以方便地回到上一层结构中的网页或者根页面(

用户可能截取URL，比如想看全部的技术文章。。。

使用自定义404网页能有效地帮助用户回到网站中有效页面 , 这将大大提高用户体验。您的404网
页最好能提供回到您网站主页的链接以及到您网站中热门内容页面的链接。

提供高质量的、对用户有益的内容恐怕是本文中讨论的各种要素
里最重要的一部分

充分考虑到用户理解您的主题时可能存
在的差异性 , 向用户提供独特的、排他
性的内容
妈的，这点，最难做到。

*重点*
比如 , 一个资深棒球爱好者
可能会用[nlcs](全国棒球联盟冠军赛的缩写)作为搜索词 , 而一个
刚刚接触棒球的用户可能就会用一些更通俗的词汇来查询 , 比如[
棒球季后赛]。如果您在撰写您的内容时 , 预先考虑到这一点 , 通
过综合使用各种具有潜在搜索可能性的关键词 , 兼顾到不同用户的
搜索习惯 , 那么您将会收到更好的效果

Google AdWords提供了
一个很有用的关键词工具 , 这个工具能帮您发现和掌握关键词的变
化动向 , 并了解每一关键词的大致搜索量。同时 , 谷歌网站站长工
具向您提供了热门搜索查询功能 , 您可以通过这个功能了解您的网
站最常出现在哪些搜索查询触发的搜索结果中 , 以及哪些搜索查询
给您带来了最多的访问者

您可以考虑提供一些别的网站没有提供过的新的、有用的服务。您
还可以撰写一篇原创研究报告 , 一篇新的新闻采访或者某种能够发
挥您的独特用户群的优势的方式 , 来吸引更多的用户。其


所有的图片都可以拥有一个独一无
二的名字和“alt”属性 , 您可以对这两个特性加以利用

 如果您链向了某些被Google认为是垃圾的网站的话 , 那
么您自己网站的声誉也会受到影响。
所以要用nofollow元标签。

很多网站都围绕用户互动和交流 , 这使得那些有特定兴趣的用户找到相关的内容变得更加容易

在社区里接触和您的网站内容相关的网站
您很可能会发现有些网站的主题跟您的相似。与这样的网站建立沟通往往大有裨益。
避免：
与所有相关的网站滥发交换链接的请求
为了PageRank而不是流量从其他网站购买链接
