* SWOT Summary
  strengths, weaknesses, opportunities, and threats

  a structured planning method that
  evaluates those four elements of an organization, project or business venture.


  It involves specifying the objectives of the business venture or project and identifying the internal and external factors that are favorable and unfavorable to achieve that objective

  First, decision-makers should consider whether the objective is attainable,

  Users of SWOT analysis must ask and answer questions that generate meaningful information

** 我的缺点
   自我管理，规划能力，设定目标，并分解项目，完成的能力。

** 我的优点

** 外部机遇

** 面临困境

** 问题
*** Strengths
    What do you do well?
    What are your unique skills?
    What expert or specialized knowledge do you have?
    What experience do you have?
    What do you do better than your competitors?
    Where are you most profitable in your business
*** Weaknesses
    In what areas do you need to improve?
    What resources do you lack?
    What parts of your business are not very profitable?
    Where do you need further education and/or experience?
    What costs you time and/or money?
*** Opportunities
    What are the business goals you are currently working towards?
    How can you do more for your existing customers or clients?
    How can you use technology to enhance your business?
    Are there new target audiences you have the potential to reach?
    Are there related products and services that provide an opportunity for your business?
*** Threats
    What obstacles do you face?
    What are the strengths of your biggest competitors?
    What are your competitors doing that you're not?
    What's going on in the economy?
    What's going on in the industry?
把资源和行动Focus在自己的强项和有最多机会的地方。
