* Share 分享

  创建一个最好物品分享的网站，可以包含一切东西。
  当然刚开始的时候，需要从具体的某个东西入手。

** 核心理念
   互联网的精神是：自由，开放，分享（开源精神）。
   我们作为一个人活在世界上，遇到美好的事物，总是想找人分享，而且我们也期待别人像我们一样
   非常的喜欢，享受这个事物，这样我们会得到深深的认同感，而且潜在的表示：
   我们是有品味的人。

   因此以人为本，充分发挥分享的精神，并且以粉丝经济作为驱动，以及商业化得动力。

** 思路
   刚开始做文本，图片，音频，视频等方面的分享。因为现在市面上的东西太烂了。
*** 文本
    比如分享好的文章，书籍等。

    图片，分享好的摄影作品，绘画作品等。

    音频，分享好的歌曲。


    也就是鉴赏力也是一种技能。互联网的趋势是越来越个性化，因为自由。
** 版权问题
   不提供下载，但是提供在线播放，和指定链接。但是我们的网站不存储任何有版权东西的复制品。

** 组织模式
   一般是两种模式：主要的是明星，粉丝的订阅关系，一种是好朋友的方式。
   订阅关系的话，都会被主动推送到粉丝哪里。（这样会大大减少粉丝的寻找时间，而且
   搜索引擎的部分功能完全被我们掐断了。）

   注册了的用户，都可以在此评论，然后可以和分享的人，互动。甚至，在这里，
   除了找到志同道合的朋友，也可以找到爱人，甚至知音。

   朋友的话，相互之间可以看到对方分享，推送的东西。而且相互之间可以私密分享，
   并且可以认识志同道合得朋友，和什么微信朋友圈完全不同。

** 商业模式
   有了粉丝，相当于你就是明星，是鉴赏家，就拥有了话语权。
   因此可以推荐好的商品，可以和淘宝等店铺合作，最好的方式我认为是自己搞一个
   分享精选的电商（我自己建立），然后和明星，鉴赏家们，分成。

   第二种，鉴赏力还可以做一个服装搭配师（因为他们本身也是鉴赏家）会给你搭配，
   选择更符号你自身的衣服，可以只提供服务，也可以买全套。高，中，低端都有。

   甚至，可以将搭配出来的服装整套出售。（好主意，但是买单的估计少）
   服装搭配特别适合程序员这种懒人，但是又有点穿衣品味和追求的人。

   再推广一点，任何一个领域都有专门的人给你指导。

   互联网，掌握话语权，就是掌握了制高地。

   第三种，可以对现在发行的唱片，电影做出评论，给歌迷，影迷做出参考。
   （但是这个商业模式）不好。

** 推广
   首先要吸引一批高素质，高修养的人群。这方面的东西是弱项。如果不一炮打响，
   很容易被中国人抄袭。

   对，以人为本，任何问题都可以围绕人来解决，也就是说：我不知道如何解决这个问题，
   但是肯定有人知道如何解决这个问题。

** 整个网站的运营流程
   网站的设计，组织模式，推广，商业盈利模式，公司人员的管理等等。
   我自己又有多少可以服人的东西？我这个人能听取意见，如果别人说的很对，我会感激。

** 研究
   还要研究下微博，知乎等的模式。
** 文艺

** 问题
   域名个卵都被别人注册了，找找关于分享的故事。
   感觉自身依然非常欠缺，很多问题需要解决。如果我去做一个军师，然后找个CEO？
   去他妈的，老子才不会被人当枪使。再说，即使有CEO，像乔布什找来的卖饮料的，
   他能懂我的理念？？

** 最大的几个问题
   网站的设计，前端。
   网站的推广。
   公司的人员管理。
   钱。
