* 2018天使黑客马拉松体验行
  这是一个非常匆忙，偶然的机会参与到2018年的天使黑客马拉松活动，非常赞，非常棒，水准很高的一次活动。
  让我打开眼界，增长见识，体验到了创客文化。

  周五晚上，下班前，又不知道周末该干嘛去，然后打开活动行，看到了这个活动。
  刚开始的时候、还对自己没自信，因为之前只是偶尔有了解到黑客马拉松大概是做什么的，但是具体流程，用户体验等等都没概念。
  还有就是对要做的东西，自己的技术水平有那么一点点不自信。感觉自身离黑客水平还差了很多。

  然后网上到处找资料，知乎看参加黑客马拉松是什么体验，然后就想着，最多最大得损失也就是60RMB吗，这点钱小意思。

  周六起来的完了点，本来可以赶地铁，但是怕迟到，而且这样不好，所以就直接打车过去了。目标地：南山科技寺。
  刚到了之后，先签到，领Tshirt，指引，介绍，工作人员非常的热情，过去一看，已经有非常多的人到场了。
  而且3322，聚成小圈子，在social，交谈，而我英语水平真的有点烂，没敢上去勾搭，然后就四处逛逛。
  感觉他们英语说的非常的溜，很多人都是从香港来的，而且大多数都是外国人，真是让我感到了国际范。
  我感觉自己这次酱油打大了，完全就是有一种深深的违和感，不过好在也没人关注我，每个人都非常友善。

  我知道科技寺是一个众创空间，然后里面灯光非常充足，有透明的玻璃墙隔起来的封闭办公室，也有会议室。
  然后整个空间是开放的，非常宽敞。



  后面陆陆续续来人了，看一哥们非常亲切，而且感觉应该是个中国人，过去就顺便勾搭上了，然后问了下他们有没组队，有队友之类的。
  然后后面我们2个人就组成一个队伍了。但是就我们两个人，后面到了组队环节，然后另外有落单的成员，然后我们一起组成了一个13人左右的队伍，
  开始临时性的讨论自己的idea，然后让大家来评断，讨论。最后确定了2个idea，然后分成了2组。

  我们这边虽然队伍分出来了，但是idea，决定做什么还没确定下来。
  一个妹子想做的是，通过技术的力量将一栋大楼附近的人流量，交通设施，情况，商场人流量等信息进行统计，然后在顾客购买大宗资产的时候进行参考。
  但是具体技术如何实现，暂时还没人清楚，因为通过人脸识别等并不太好实现，而且最关键的逻辑点在：如果你决定买一栋写字楼，你会参考这些信息就做决定吗？
  肯定是要通过亲自参观才能做出决定的，所以这个需求不够刚性，不够痛点，最多只能算作多出了参考资料，信息，可以进行过滤等。

  另一个人想做的是：房地产抖音。就是通过小视频的方式来介绍房子，然后进行销售。但是这个点子认为太过垂直，估计有趣度也不够，而且现有的企业，
  如链接，房多多等都能直接在房子介绍界面加个视频介绍就可以了。还有就是和VR看房有重合之处，可取代性并不大。

  我们最后决定做的是一个智能停车管理系统，用户场景是：周末晚上车主去商圈吃饭约会，但是到了后，却发现停车位爆满，非常难找。
  而且吃完饭，看完电影，出来找车非常难找。我们做的就是一个手机APP，统计收集各大商圈，小区的停车位信息，管理起来，然后通过GPS定位，
  当用户要出发到目标地点前，可以通过APP预定车位；也可以不预定，而直接查找当前位置附近的停车位，然后进行预订停车，道行等。
  而不用自己到处找车位。

  我们就从早上10点钟讨论到下午4点钟，才确定最终要做的idea。通过整个的辩论过程，交流过程中，我发现和学习到了非常多的东西。
  每个人都坚信自己的想法，注意，每个人都想要说服他人。有的比较固执，有的人无所谓，有的人在团队决策后就能非常好的配合团队。
  每个人的思维方式，出发点，考虑的东西都不一样。还有就是很多人考虑到太细的东西了，有的人甚至对你的想法专门挑刺，这些都是你必须去面对的。

  最关键的一点，绝大多数人在绝大多数时候都是想的多，说的多，争执，思考的多，而做的少。因此很难出成果，影响现实，而大家看的都是结果。
  我和另外一个人负责完善想法，原型制作，功能的技术实现等等，另外3个人负责PPT的制作。

  然后从早上到晚上10点钟，除了吃饭，上厕所，完全没有片刻休息，每个人都是饿了就吃水果，零食等，渴了就和矿泉水。
  不断的讨论，交流，一起确定方案，结果是否OK。

  然后晚上10点多，大体的原型都已经OK，PPT也还行，但是需要修改，然后我们一起过PPT,过原型，提意见，问问题，等等等等。
  整个过程给我的感觉就是：非常像一起打BOSS，每个人都在YY里面提自己的想法，考验，质疑别人的想法。
  时间一晃就过。

  整体过完之后，我们就一起去地铁回家了。
  因为整个讨论的时间耗时太长，因此决定不写代码了。我会后端，然后兼职前端的产品必须要花时间整原型。
  所以，我们就是一只没写一行代码参加黑客马拉松的队伍，太有意思了。
  而且不止我们，很多队伍都并没有后台，只是做了一些简单的原型，前端页面等等。
  不过都是第一次参加，抱着体验，打酱油，学习的心态过来的，所以也就不怎么有压力了。
  但是我看队友，还有其他参赛者的整个状态，都是非常认真，充满激情的。

  我们回去后，还有些团队在这里通宵写代码，做东西，因为很多人是香港过来的，或者新加坡过来的，
  而评审官们，组织者们都在小房间看世界杯了，有些参赛者也会休息时间看看，反正就是很随意啦。
** 第二天
   因为原型，PPT都已经大体做好，只需要修改，优化，所以大家第二天都是较晚的10点左右到了。
   然后相互之间交流一些展示环节，面试官可能会问到的问题，以及如何进行阐述，PPT得台词准备，背诵等等，
   一下就到中午12点了，简单吃点东西，在讨论一会，就到13点，需要提交APP，展示网址，代码，项目描述，队名，成员名等等。

   之后就是展示环节，来自五湖四海得，国际化有人，各种各样，各种创意的点子，虽然说不上天马行空，但是我觉得也非常不错了。
   所有队伍，只有我们这一只是纯粹的中国人队（没算香港），有印度的，有美国的，有香港的，有加拿大的，有学生，有老头，形形色色。
   大概说下几个参赛队伍的作品吧。
   有个队伍是做的大楼室内的VR展示，可以通过链接进行跳转等等；
   有个队伍是做的设计师产品的衍生品，比如设计了一个可爱的角色，通过平台就能产生自带可爱角色logo的杯子，T-shirt，绘画本等等一类的东西。
   有个队伍是做Nature box，就是旅游旺季，可以通过卡车拉来临时房屋，或者直接开房车类似的东西来做临时的租赁。
   有个队伍是做优惠吗的，有个队伍是做在线教育，将说中文的孩子和说英文的孩子连接起来，让他们一起学习。
   有个队伍是做大楼平面展示，定位的，就是说用户现在在大楼的那个具体地方可以精准的定位出来，然后进行道行，推荐食物等。
   有个队伍是根据你喜欢的餐馆，喜欢的单车还有距离，等来推荐房屋让你来买，或者来租的。
   还有个队伍是根据你的兴趣爱好，给你推荐室友的。
   还有个队伍是做AC转DC集中化管理，然后丢掉电源转换器的。


   整个评审过程也非常的有趣，主持人不得不说，非常能活跃气氛，而且本身也精力充沛的人。
   最后是由Nature box获得了一个奖项，根据喜好推荐房屋购买，出租的获得了2个奖项，并且获得了1万元的奖金。

   整个活动非常的cool，人的整体素质，友善度都非常的搞，很多人英语溜的不行，不过大多都是海龟。

   从这次活动中，我收获到了非常多的知识。

   这里的每一个人都仿佛被创业，创意，激情给点燃了。
