* 如何开始创业
** 头脑风暴
   创业的本质是商业，是赚钱，也就是：确定用户人群，愿意用真金白银去满足一种特定的需求。
   人群和需求就组成了市场，和竞争对手比拼就是商业竞争。如果要在商业竞争中取胜就必须得有优势：竞争优势，相对优势等。

   如果你要创业，就相当于是提供或者整合一部分资源，去满足特定市场的需求。其实除了需求，还有一种就是：提高了效率，生产率。
   创业刚开始很可能是自己一个人干，或者找1,2个亲人，朋友一起干，为撒？节约成本，没钱请人。
   所以你一个人，或者你周围人有什么才能，技能，稀缺资源了？如何拉这1,2个人入伙，让别人相信你了？

** 问题
*** 你会些什么，你有什么资源，你相对于其他人的优势是什么，什么是你独有的，而这些又是别人需要的，或者说别人需要的是你准备去学习的？
    那这个就要看你平时的时间花费，以及经常进行的活动是什么？就是你所在的时间和空间是什么？
    看书，炒股，上班编程搬砖，思考如何创业，
    你有哪方面的影响力，或者行业建树？

*** 为什么要创业？
    我这么牛逼，这么年轻，为什么又要给别人打工了？
*** 创业是怎么样的一件事？创业的本质是什么？

*** 创业的资源有哪些？
*** 一些点子
    如果要搞，肯定搞微信公总号，但是理论上来说别人都搞起了，很多东西都一下抢占满了，那我如何脱颖而出？？
    在说，真的搞

    我现在想到的有每周一篇读书笔记，每日盘后总结，后续有粉丝了就是炒股教程，如何读书，如何做笔记等教程。
    这个是什么？线上教育。

    看微小宝的数据分析：热门的东西有，时事政治，两性情感，冷笑话，明星
    *最好的方式是：钱也赚了，自己也提升了，别人也受益了。*
    如果没有考虑创业，我应该干嘛？我应该跳槽去一家新公司，然后用业余时间提升自己，
    首先是将自己的综合素质提升起来，阅读，做笔记，学习方式方法，高效率工作，掌握高效工具，沟通，演讲等。

    之后再考虑的就是：是创业还是投机？估计大概率是创业，为什么？因为我太牛逼了，而且我不想只做一个蒙头炒股赚钱的人。

    而我现在的问题是：妈逼的，找工作不顺，给不了钱也就算了，都是些什么垃圾公司，不稳定不说，钱也给不够，
    好多看似还行的公司，给老子简历都不通过，我曹。问题到底是谁的？是我的，还是公司的？

    其实，仔细来想，中国这么多人，本质是我的简历含金量不够，为什么我当初没有想到这些事情了？没有对这个规划了？
    所以现在就想选择创业和投机是一样的，要对未来规划。要对未来规划，要对每天规划，要对每年规划。

    妈的，死逼，我曹。提升基本素质，草TM的，每天上班。
    搜狗微信搜索
** 人生规划蓝图

** 办公司费用
   我个人来说所有的开销：
   代办公司（含刻章）：RMB 300
   建设银行开户预约费（含 U 盾、密码器）：RMB 100
   银行年费：RMB 100交通费：RMB 50
   法人一证通：RMB 50
   发票章：RMB 20
   针式打印机（开发票用）：RMB 700
   ------总计：RMB 1320
   如果公司没有财务就需要代理记账，我代理记帐花费是 2880/15个月。
   因此如果算上财务的费用总计就是 RMB 4200。
** 创业相关的源资
*** 书籍

*** 视频
    斯坦福创业课程：
    http://mooc.guokr.com/course/1636/How-to-Start-a-Startup/
** 如何开始创业
*** 为什么你还是个打工仔？
   李嘉诚说你为什么是个打工仔：为什么你一直是打工仔？因为你安于现状！因为你没有勇气，你天生胆小怕事不敢另择它路！
   所以你是打工仔！因为你没有勇往直前，没有超越自我的精神！所以，你该一直打工。

   如果我们不努力，就只有打工、受气、只有钱刚够花的窘态。
   当你放下面子赚钱的时候，说明你已经懂事了。当你用钱赚回面子的时候，说明你已经成功了。当你用面子可以赚钱的时候，说明你已经是人物了。
   当你还停留在那里喝酒、吹牛，啥也不懂还装懂，只爱所谓的面子的时候，说明你这辈子也就这样了……这是所有人走向成熟的必经之路！
*** 创业的思考
   想清楚创业的整个流程，然后的话，以终为始，我认为可以先锻炼营销的能力。
   创业的本质就是商业，商业就是买卖，赚取差价。（不对）
   创业的流程：点子->产品->销售给客户->赚取利润。

   点子->产品，执行力，相应的技能，
   产品阶段：涉及到产品设计，技术实现

   获得用户，获得用户的成本
** 创业的必备素质
   1. 知道人性的多面化
   2. 学会忍
   3. 锻炼人际关系，干推销员
   4. 看别人脸色，学嘴上功夫
   5. 市场洞察力，眼光

** 几件创业前值的做的事情
   1.  开创一个线上交流群体，组织聚会沙龙
   2.  开一个博客
   3.  设计推出一款APP
   4.  写一本电子书
   5.  在网上开班授课
** 点子
   做一个销量排行的网站？

   [[http://www.58cyjm.com/html/view/32194.shtml][创业前体验创业的四大实战环节]]

** 创业做什么，你有什么？
    在我看来第一次创业的人做什么并不重要，重要的是你有什么！有什么!youshenme!
     期间产生过很多所谓的idea。但当我把每个idea拿出来和同事朋友相关行业人群讨论后，由于无法说服自己而都被我自己放弃，直到最后一次的一个想法，是在和客户的不断接触中慢慢成形

     尤其在一个早期投资人（非知名）的帮助下，把一开始很宽泛的一个概念落实在了一个很小很细的点上，瞬间觉得脑洞大开。

     于是，我不断的修改不断的咨询，终于逻辑清晰，条目合理的把自己的最终想干的事情梳理了出来并作了一份BP
*** 我有什么？
    作为一个贫下中农，要什么没什么。这也正是我寒窗苦读十余载，换取一张进城打工的门票。
    作为一个打工仔，我所做的就是用：我的健康+我的时间+我的技能给资本家打工，换取每个月微薄的薪酬。
    （我有的：健康，时间，技能，这些都是最宝贵的东西啊，健康损坏了，时间浪费了，技能不值钱了，就被踢走，像垃圾一样扔掉。）

    我还有爸爸，妈妈，妹妹，可惜我爸不是王健林，也不是李刚。我妈也不是明星，董明珠，我妹也是苦逼打工仔一枚。


    人都被教傻逼了。

    最稀缺的：创造力，把握时机的能力，果敢，坚持，
** 创业的约束条件
   我必须得每个月交1W多的贷款，但是我现在可以每个月存钱，然后等我那个该的还的差不多了就能用这个存钱交房贷，就能有几个月空余时间了。
** 成功的创业公司
   Linkedin
   tripadvisor
   cisco
   conell university
** 失败的原因
   Google Top 20 Reasons statups fail

2004年起，王兴的小团队以平均两个月淘汰一个创业项目的节奏不断试错、摸索、总结经
他们先搞SNS，又搞输入法，两年折腾了差不多10个项目，都没什么起色，最后决定再回到SNS，专注在校园上。
淘房网进展也不是很顺利，花了很多钱去做广告，但效果并不好
** yc的书看到多少页
