* org-mode-summary
** 安装
   下载，解压到~.emacs.d/lisp目录下
   (add-to-list 'load-path "PATH_TO_WHERE_YOU_UNPACKED_ORGMODE/lisp")
** 激活
   将以下内容添加到.emacs中
   (require 'org)
   (define-key global-map "\C-cl" 'org-store-link)
   (define-key global-map "\C-ca" 'org-agenda)
   (setq org-log-done t)

** 快捷键
   C-c C-t 运行org-todo命令，然后可以有几个选项
   M-S-RET 运行org-insert-todo-heading
   C-c C-o 运行org-open-at-point 显示链接详情？
   C-c C-l 运行org-insert-link，添加链接地址
   C-c a t 进入全局TODO列表
   C-c C-s 运行org-schedule，选择deadline。
** 添加链接
   就是一组[]然后里面包着2组[]，前面是连接，后面是描述。先输入链接和描述，最后方括号。
   
** 代码块
    #+NAME: <name>
     #+BEGIN_SRC <language> <switches> <header arguments>
       <body>
     #+END_SRC

** GTD
*** 全局TODO列表
    在emacs初始化文件中添加
    (setq org-agenda-files (list "~/org/work.org"
                             "~/org/school.org"
                             "~/org/home.org"))
    就会扫描这些文件中的TODOS项。
*** 计划任务
    
** 导出markdown
   C-c C-e m m 导出使用markdown语法的纯文本（但是我的没什么卵用啊）
   M-x package-install RET markdown-mode+ 安装markdown-mode
   (eval-after-load "org"
      '(require 'ox-md nil t))
      使用上面这个命令好像可以。
    尼玛，使用那个
** DONE  test
   CLOSED: [2017-04-12 周三 15:54]
   :LOGBOOK:  
   - State "DONE"       from "TODO"       [2017-04-12 周三 15:54]
   :END:      
** DO
** 标签Tags                                                                     :test:
   标签可以使用字符，数字，下划线，@符号。
   必须以冒号开头，例如:work:urgent:。
   用org-tag-faces来使用特殊的样式
*** 标签继承                                                                    :nil:<SPC>: :test:a:
    1. 子标题会继承父标题的标签。*标题 :work:
    2. 可以在一个文件中定义标签，并引入。#+FILETAGS: :Peter:Boss:Secret:
    3. 使用org-tags-exclude-from-inheritance使指定的标签无法被继承；
       使用org-use-tag-inheritance禁用标签继承。
    4. 搜索时，子标题都会被展示出来，可以配置org-tags-match-list-sublevels，但不建议
    5. 配置org-use-tag-inheritance来自定义在agenda中的搜索匹配。
*** 配置标签
    C-c C-q 然后输入标签
    C-u C-c C-q 其他标签对齐本标签
    可以使用固定的标签列表，在org-tag-alist里面配置

** Links 链接
*** Internal links
    不像URL的就被认为是内部链接。例如 【【#my-custom-id】】会被链接到有
    my-custom-id属性的入口。id必须唯一。

    【【My Target】】或【【My Target】【Find my Target】】会在当前文件进行文字搜索。

    * STARTED [80%] 超链接
** 网址链接
   [[www.gnu.org/software/emacs/][Download and install Emacs]] 
** 文件链接
[[file:c:/windows/desktop.ini][桌面配置文件]]
** 内部链接
[[目录位置][返回目录]]
** TODO 其他链接

** 符号
   以 # 号后加一空格开始的行表示注释，文件导出时这些内容不被导出，上面第一行就是。
   以 #+ 符号开始的行用于设置文档参数或内容属性，比如文档的标题、作者，org-mode打开时文档的呈现状态等。
   用 [[]] 括起来的内容表示外部链接
   用 <<>> 括起来的内容表示文档的内部链接
   以 * 符号开始的行，表示该行为标题。
   标题内容前的 TODO 标记是待办任务的标记符号。
   标题行后面两个 : 符号间的内容表示标签（ TAG ）。
   标题行如果标题文本前有 COMMENT 标记表示该标题下的所有内容为注释。
   位于 #+BEGIN_XXX 和 #+END_XXX 之间的内容为特殊文档块，如代码块、例子、引用等。

** 进入Org模式
   有3种方式：
   打开后缀名为org的文件自动进入org-mode模式
   在init.el配置文件中设置某类文件的编辑模式为org，如txt类文件：
   (add-to-list 'auto-mode-alist '("\\.txt\\'" . org-mode))
   用Emacs打开文件后使用主模式选择命令（ M-x org-mode ）
   任意文件名，如果文件的第一个非空行包含： -*-org-*- ，用Emacs打开该文件后会自动使用org-mode模式。
   后面这种方式对于使用Emacs编辑程序文件尤其方便，无需改变文件的后缀名。
** 标题
   为使标题适应更广泛的应用（不仅仅是表明文档的结构层次），Org对其进行了较复杂的定义。它的完整语法为：
   STARS KEYWORD PRIORITY TITLE TAGS
   其中：
   STARS 即星号，这是一个标题唯一必要的内容，其他（包括标题名称）都可以省略。
   KEYRORD 为TODO关键词，大小写敏感。
   PRIORITY 为优先级选项，为#号加一个字符并用方括号括起来，如 [#A]
   TITLE 即为实际的标题文本
   TAGS 为标签。

   完整例子：
   ** TODO [#2] 优先级为2的待办事项                                                :@家庭作业:

** Reference
[[http://orgmode.org/worg/org-tutorials/index.html][tutorials

]]


** 高级搜索
   可以使用grep，awk，perl等命令工具。
   [[http://orgmode.org/worg/org-tutorials/advanced-searching.html#boolean-searches-by-default][Advanced searching]]

