* 设计心理学 笔记
  多年来一直研究人类思维，记忆和注意力，学习以及运动控制基本原理的我。

  不考虑，毫不在乎用户的需要。

  这些日用品问题听起来微不足道，但却能够影响你的心情。

  以人为本的产品设计程序。

  物品的外观为用户提供了正确操作所需要的关键线索（给用户提示）——
  知识不仅存储于人的头脑中，而且还存储于客观世界（物体本身）

  设计必须反映产品的核心功能，工作原理，可能的操作方法和反馈产品在某一特定时刻的运转状态。
  （Transparently！！！）

  设计实际是一个交流过程，设计人员必须深入了解其交流对象。
  （其实更本质应该是满足人的掌握欲，不过一切皆在掌握，是以人为本的精神）

  概念模型
  位置和操作方法应当存在自然，显而易见的关系，使用户一看就明白每一个控制器的功能。
  （这个类似接口的定义，看名字就明白功能）

  反馈。显示操作结果。在软件设计上就是，任何操作都要有明显的返回值。

  限制因素。要想使物品用起来方便，不出错，最好的方法是让物品不具备其他功能。
  （这个对应到软件设计的模块原则，单一功能）
  比如电池和记忆卡，要么只有一种对应的插入方式，要么怎么插都可以正常工作。

  设计实际是一个对表面上相互冲突的各种要求进行协调的过程。

  所有伟大的设计都是在艺术美，可靠性，安全性，易用性，成本和功能之间需求平衡与和谐。

  这些问题的答案应该在门的设计上找到，而无须用文字或符号加以说。

  设计中的一项重要原则：可视性。利用自然信号。

  用户操作意图和可能的操作方法之间必须匹配。

  没有把产品的各项新功能与用户已知的，有着相似名称的功能联系起来。

  人们已经开始研究物质心理学，这是一门研究物品预设用户的学问。
  预设用途是指物品被人们认为具有的性能及其实际上的性能，
  主要是指那些决定物品可以用来作何用途的基本性能。

  预设用途提供了操作上的明显线索。平板是用来推的，旋钮是用来转的，
  狭长的方孔是用来插东西的，球是用来抛掷或上下弹跳的。
  （存在决定用途）

  不要让用户借助任何的图解，标志和说明。

  12件不同功能，颜色和样式的文具用品。
  （功能，颜色，样式这些都是和谐的，和而为一的）

  大多数的物品都是由许多部件构成的。
  （原来有这么多细节，细心的观察，我们就能学会很多东西）

  设计的两个基本原则：1.提供搞一个好的概念模型；2.可视性。

  我们没有必要了解每件物品的物或化学原理，所需了解的就是控制器和操作结果之间的关系。

  心理模型：是指人们通过经验，训练和教导，对自己，他人，环境以及接触到的事物形成的模型。
  一个物品的心理模型大多产生于：人们对该物品可感知到的功能和可视结构进行解释的过程中。
  （这个不真是我现在理解很多启动命令的方式吗？这个是什么意思，那个是什么意思，它们是怎么交互，
  怎么相互起作用的。）

  厂商希望尽量降低成本，销售商希望产品能够吸引顾客。用户在商店采购时，会注重产品的价格，外观和品牌，
  但在加重使用这些产品时，则会更在乎产品的功能和操作。修理人员所关心的则是产品拆装，检查和维修的难易程度。

  （不同身份的人是站在不同角度考虑问题的，并且，为何同一个人在不同地理位置，环境，
  考虑问题的角度就会发生改变？而且通过他们考虑的东西，也可以推导出他们的利益所在）
  厂商希望成本降低，这样产品才能更有竞争力，因为进货成本价格。
  销售商当然是卖出去越多越好。用户注重价格，品牌好理解，但是为什么买时注重外观，
  在加却在乎功能和操作？


  心理学家对错误和错误观念飞车感兴趣，因为它们提供了有关人类思维组织和运转的重要线索。

  我们习惯对事物加以解释，这就形成了针对事物作用方式，事物发生过程和人类行为方式的概念模型，即心力模型。

  把自己的不幸归结于环境因素，把他人的不幸归结于性格因素，这是我们都认为很自然的。
  可是，当一切进展顺利时，人们就会归功于自己的优良素质和智慧。

  习得的无助感：多次经历失败，便陷入无助的状态，不敢再进行尝试。
  若是经常遇到这种情况，人们就会产生严重的心理障碍，发展到极限就会导致忧郁症。

  致使一个阶段的困难成了下一个阶段的学习障碍。后面就开始了恶性循环，
  下一次面临时候，你甚至不去尝试就放弃了。你认为自己没有能力做某事，结果真的做不了，于是陷入自我实现的预言之中。
  人们不知道如何正确的将胶片放入放映机，因为无法确定自己的操作与放映机工作程序之间的关系。
  以及各种控制键的功能和使用方法，也很难通过图像，声音，亮度和放映机的工作状态来明确是否成功。

  在匹配和反馈环节遇到困难。

  使用日常物品出现问题，大多是因为人们自己不明白自己的心理意图及解释与实际操作及外界状态之间的关系。

  107页 预设用途
