* 杠杆原理
我的目标就是学习理论，但是理论本身也是从现实生活中抽象出来的，所以要从身边的事情观察，分析，学习起来，
从身边的事件实践起来。

就是做什么？？？最少能养活自己先，
现在的关键点是：搞钱，找到支点，切入点，撬动杠杆，正向循环反馈闭环，
我今天想到那个抖音割韭菜赚钱的交人做微商的，本质是自身形成了一个正向循环，然后庞氏骗局发展下线，
让别人推着你走，这就形成了“势”，就是你做的一个“局”，所有的套路都莫过于此，只是在于“局”的大小，级别而已，股票同理。

然后我想到之前成功的事，做kafka技术分享，然后就做个网上的技术分享网站，专栏，但是别人为撒来你这个平台了？
所有人都为了利，你这平台必须要提供些什么，本质都是利益互换，所以你得有名气，有影响力，有号召力，
或者有独到见解，不然这个平台没用，

我现在的支点是什么？？？
炒股，编程，写作，思考。而且要搞懂这些，貌似还是写公众号，简单来说就是这几个技能怎么来撬动杠杆，用户，关注度，
技能22结合，甚至3个结合？炒股+编程=量化，写作+炒股=炒股公众号，编程+写作=编程教学，写作+思考=公众号，
写电子书？根据mvp先写一篇文章，得到反馈？关键现在互联网泛滥了，
炒股+编程+写作=量化交易写作，公众号，关键是怎么撬动杠杆啊，1个人到2个人到4个人到10个人到100个人，
支点，切入点，

正向反馈本质就是成功，杠杆撬动更多资源，本质是有更多更大的资源支配权，也就是权力，
比如高级别的管理就有很多权力，创业容易失败之类的，本质是消耗掉的资源远大于成功需要的资源，就失败了。
所以现在怎么做？？？？支点，切入点在哪里？？隔行如隔山，
龟兔赛跑，乌龟赢是必然的，因为它确定了唯一的一个目标。人生最怕的失去方向，没有目标，得过且过，
慢一点没关系，艰难困苦都不是问题，只要没死，坚持下去就有成功的那天。

支点，切入点，撬动资源，从身边思考：就是怎么去镬取资源，，，每个打工仔的时间，精力是有限的，
1.家庭
气力一心，共同目标，
2.事业
工作上的，同事，上级这些
3.朋友亲戚
穷人的亲戚怕你好，把你往下往回拉，和狗逼父母一样的。
哎，最本质的还是我们没有什么资产，资源啊，所以被称为穷人。
怪不得老子混的差，家庭上的，全部和老子作对，不断掏老子的钱，逼着老子去铤而走险，
事业工作上，完全不行，没人赏识，各种斗争，而且人际沟通，撕逼不会，
朋友亲戚，几乎没有。。。人脉本质也是杠杆，资源。技能，编程，炒股，唯一的资源，
怎么搞钱？？？看看身边暴富的，

减法聚焦，定点爆破，定位，大的方向：编程，边工作边炒股，2条路走，
分析事件，等待大的参与的机会，工作的时候搞好本职工作，但是中小公司恨不得一个人当3个人用，
比如jdlz，大公司了又全jb当螺丝钉，关键是这个职位我根本做不来，不善沟通交流，
最好是有门非常强的技能，端到端，能直接变现。这几年的买房暴富了，
借势取势，所有打工人的财富最终被收割，中产以下的，即使炒股赚了几十亿，这个国权力收割你，
全世界会被美国收割，反客为主，反向收割，是啊，亚洲金融危机，这个局，这个势更大，
关键是你要能驾驭的住，佛陀说的轮回真实不虚的，你要狭隘的认为佛陀会不断转世撒的当我没说，
以股票举例，就是不断的轮回，局势在扩大一点：全世界的经济，气候的轮回，文化意识形态的转变等等，
再更大的一个局势：太阳系，银河系，宇宙。。但本质是相同的，一沙一世界

做码农最关键的这些东西无法复用，不能变现，产生价值，不能直接兑现，没得进步，一直重复，玩你妈比。
而且狗鸡巴的还要面临激烈的巨大的竞争，算了，转安全，学术悟道，中国it全鸡巴是业务流程那套低端的东西，

我发现直接Google根本无法学习了解到什么，都太肤浅和局限性了。
所以学习的方式不对，我们还是直接来看图，看源头。
杠杆是物理学上阿基米德发明的一个概念，那句著名的名言“给我一个支点，我能翘起地球！”

看看这幅图有几个元素：
地球：你要翘起的目标
支点
阿基米德：使用杠杆的人
力臂：阻力臂动力臂
力：阻力动力
阻力x阻力臂=动力x动力臂=做的功，
所以做的功是不变的，恒定的。

杠杆原理给人的启发是：目前做不到，看似完全没任何办法解决的事情，通过时间的力臂，长期的努力就能做到。
因为目前当下的力量太小了。

用肉用弱

杠杆一般用在经济学上，比如炒股，炒期货，借贷等。
** 长到33岁，这些年做了什么？？
1.读书，读傻逼了，读了23年
2.听音乐
3.打游戏打了
