* Resume Tips
** Principles
   1. leave the recruiter seeing the obvious connection between WHAT you've done and HOW you can HELP their company.

   2. Does every single bullet or sentence contribute toward the recruiter think "We must meet this person?"
      也就是说搞清楚你先简历的目的，希望别人给你一次面试机会。那么就要让招聘者认为你适合这个岗位，并且适合他们公司，能
      做出贡献。也就是你的简历和他们的要求匹配度很高。

   3. put yourself in the shoes of a hiring manager or HR screener role.
      也就是突出你为前公司做了什么贡献，可以带给当前公司什么利益。

    4. use mini-storys.Tell us the problem,then what you didi to solve it,and give us the impact.
       使用小故事，告诉我们你遇到什么问题，然后你如何解决了，产生什么影响。problem-solution-impact。

** Negotiate Salary 薪水谈判
glassdoor.com, salary.com，salaryexpert.com

Impact is anything that truly matters to the company.
Too many people discuss what they did, but never tie it to impact, and as such, it carries little weight.

Then, after going through your impact articulation, follow with some positive comments about why you like working for the company and this manager. And then add this:

But there is one thing that is troubling me a bit. I feel that given my role and the impact I’m having, I am under-compensated. And I’d really like your help so that we can address this.

This opens the door to a non-threatening, collaborative discussion around compensation



** Reference
[[http://www.anthonysdesk.com/forget-everything-you-learned/][forget-everything-you-leared]]
