* 如何提高口才
第一点，最重要的就是思想。指的是你懂得些什么，你思维清不清晰，你脑子装了多少东西。举个例子，让你在某个领域内发表你的观点，让你对某件事情提出你的看法，如果你对这个领域一窍不通，如果你对这件事情闻所未闻，就算你说话再流利，就算你再有铜牙铁齿，你也说不出个什么来。所以我认为，懂得多，才说的多。我们要从各种途径学习更多的知识，了解更多的信息。

第二点，语言的组织。就是怎么把思想表达出去。有了思想，就要表达。怎么表达，我认为我们可以在平时没事干的时候，多想想你要说的话怎么讲。多听听人家怎么说，怎么表达；多朗读书本，听演讲，看视频。有好词好句的，有经典语录的，记下来，抄下来，有时间多点重复看看，多读读。

第三点，讲话的风格。讲话有速度快的，声音低沉的，富有节奏的，很爷们的，手舞足蹈的，等等。每个人都有不同的讲话风格，但同样的内容，甚至同样的句子，用不同的风格表达出来，效果不一样啊。所以这点，我认为培养一个良好的讲话风格是比较必要的。现在网络发达，我们很容易就能找到很多知名讲师的视频，我们可以适当的结合自身情况来模仿。也可以对比不同讲话风格，看哪个人说的话比较有感染力。

第四点，是坚持不懈。
如何快速提升口才
悬赏分：0 - 解决时间：2009-7-13 22:19
大家好 请问如何可以快速提好口才啊 我的口才实在不怎么样 大家有什么好建意吗
问题补充：
最好给上一些相关的学习资料 最好多点 呵呵~~~~
提问者： blueskyjiabin2 - 二级
最佳答案
无论做什么事情，好的口才会提高事情的成功率。但是，你首先也要明白，培养好的口才没有速成的方法，不可以两三天就让你成为一个有口才的人。

第一，下定决心学好自己的口才并为之付出努力，你坚定的决心也会让你看起来比较自信。你在心里一定要跟自己说，我要学好口才，一定要学好口才，学好口才才能让事情进行得更顺利。

第二，先充实自己，为口才做好铺垫。多看书，上网查资料，先让自己有知识了，才能跟别人聊得起来啊，如果别人一问你三不知，话题就无法进行下去了。你想想，有谁会不喜欢有文化的人？

第三，先倾听，后诉说。你去看一些名人演讲或者听一些口才好的人说话，看一下他们是如何表达自己的，吸取他们的优点，看到适合你的，就用在自己的身上。任何口才好的人会成功都是以模仿为主，然后再加上自己创新的东西，形成自己的一种风格的。

第四，诉说的时候一定要注意对方的反映，不要光是你一个人在说，别人都没有心思在听。你一定要保证你说的话是别人想听的，如果不是这样的话，就打住不要继续说下去。所以要学会观察别人的面部表情，来决定自己说话内容的长短，别自个在那里滔滔不绝地讲。

第五，在说话之前先考虑好了再说，别想到什么说什么。你在头脑里先组织一下语言，然后再通过嘴表达出来，不要等到说出来之后后悔了，那就来不及了。你一旦失言了，以后听众就没心思听你说话了。所以不要失言，才不会冷场。

其实，我自己本身也不是一个善于表达的人，我出来工作之后考虑到人际交往这些方面，我给自己提了这几个方案，很多人也同意我的观点，希望也能够适合你。最近我已经有所进步了，呵呵。


怎么样才可以提升自己的口才？
悬赏分：0 - 解决时间：2006-5-27 14:40

提问者： ∮铃铛 - 四级
最佳答案
2、怎样才能提高自己的口才呢？
我觉得应该从以下几个方面入手：
首先，口才是练出来的，不要羞怯，要知道每个人的资质都是差不多的，自己有怯场的心理，别人也会有同样的感受，要抓紧一切可以锻炼的机会来展示自己，给自己信心，相信自己既能够做得到也能够说得出，每一次的锻炼都会给自己开始下一次以莫大的勇气，再加上自己不断的总结和积累。长此以往，必然能够在以后的一切场合中自己脱颖而出，说出自己，证明自己。
其次，说话要有内容，才能够在社交场合及一些工作场合中吸引别人的倾听，你总要使别人在听你说话的过程中有一些收益或是产生共鸣，那么这样的说话才是成功的，而别人也才会乐意听你说话，与你交流。同理而言，一位好的说话者一定是一位特别擅长沟通的人，在自己说话的时候也要学会倾听他人的说话，俗话说：出门看天色，进门看脸色。因此在说话时更要学会看他人听你说话时的表情，以便适时的改变自己说话的内容、语气等等，说话时千万不要自说自话，这是最不成功的说话。
再次，说话要注意自己的节奏感，这一点是相当重要的。有些人在说话的时候语速相当快，就象在爆豆子一样，往往她自己说完以后，别人都没有反映过来她说的是什么。说话说得慢一些，声音响亮一些，你会发现，人们会更加注意的倾听你的说话，而且他们会感觉你所说的每一句话都是从内心深处说出来的，是经过你慎重考虑后才说出来的，人们会认为你在对自己说的话负责任。其实言语并不见得比写文章容易，文章写得不好来还可以修改，而一句话说出来了，要想修改是比较困难的。我们也常感觉到，即使同一个意思，甚至同一句话，会说话的人，能叫你眉飞色舞，不会说话的人，则叫你头昏脑胀。
最后，要跟会说话的人多学习，多去倾听别人的说话，西方有句谚语说：上帝之所以给人一个嘴巴两只耳朵，就是要人多听少说。多听，才是最有收获的，不断的丰富自己的内在知识，不断的去学习别人的长处，用一颗自信与谦和的心来面对自己的每一次社交与工作中的场合，即使自己做的不够好，只要努力，只要有真诚，相信你假以时日，一定能够成为一位说话和沟通的高手，为自己的事业和生活带来很多快乐！
3、卡耐基是怎样锻炼口才的！（一）
一 借鉴别人的经验

卡耐基的一生几乎都在致力于帮助人们克服谈话和演讲中畏惧和胆怯的心理，培养
勇气和信心。在“戴尔·卡耐基课程”开课之前，他曾作过一个调查，即让人们说说来
上课的原因，以及希望从这种口才演讲训练课中获得什么。调查的结果令人吃惊，大多
数人的中心愿望与基本需要都是基本一样的，他们是这样回答的：“当人们要我站起来
讲话时，我觉得很不自在，很害怕，使我不能清晰地思考，不能集中精力，不知道自己
要说的是什么。所以，我想获得自信，能泰然自若，当众站起并能随心所欲地思考，能
依逻辑次序归纳自己的思想，在公共场所或社交人士的面前侃侃而谈，富有哲理且又让
人信服。”
卡耐基认为，要达到这种效果，获得当众演讲的技巧，应当从以下几个方面入手训
练自己。
借别人的经验鼓起勇气。卡耐基认为，不论是处在任何情况、任状态之下，绝没有
哪种动物是天生的大众演说家。历史上有些时期，当众讲演是一门精致的艺术，必须谨
遵修辞法与优雅的演说方式，因而，要想做个天生的大众演说家那是极其困难的，是经
过坚苦努力才能达到的。现在我们却把当众演说看成一种扩大的交谈。以前那种说话、
动作俱佳的方式、如雷贯耳的声音已经永远过去。我们与人共进晚餐、在教堂中做礼拜，
或看电视、听收音机时，喜欢听到的是率直的言语，依常理而构思，专挚地和我们谈论
问题，而不是对着我们空空而谈。
当众演说不是一门闭锁的艺术，并不象许多学校的那样容易学到知识，必须经过多
年的美化声音，以及苦学修辞学多年以后才能成功。平常说话轻而易举，只要遵循一些
简单的规则就行。对于这一点，卡耐基有深刻的体验。1912年，他在纽约市青年基督协
会开始教授学生时，讲授那些低年级的方法，同他在密苏里州的华伦堡上大学时受教的
方式大同小异。但是他很快发现，把商界中的大人当成大学新生来教是一种很大的失误，
对演说家韦伯斯特、柏克匹特和欧康内尔等一味模仿也毫无裨益。因为学生们所需要的
并不是这些，而是在下回的商务会议里能有足够的勇气直起腰来，做一番明确、连贯的
报告。于是他就把教科书一古脑儿全抛掉，用一些简单的概念和那些学生互相交流和切
嗟，直到他们的报告词达意尽、深得人心为止。这一着果然奏效，因为此后他们一再回
来，还想学得更多。
在卡耐基的一生中，所收到的感谢信可以堆积如山。它们有的来自工业领袖们，有
的来自州长、国会议员、大学校长和娱乐圈中的名人们，有的来自家庭主妇、牧师、老
师、青年男女们，有的则来自各级主管人员、技术纯熟或生疏的劳工、工会会员、大学
生和商业妇女等。所有这些人都感到需要自信，需要有在公开场合中表达自己的能力，
好让别人接纳自己的意见。他们在达到目的之后，就满怀感激地抽空给卡耐基写信，以
表示谢意。
根特先生是费城一位成功的生意人，有一次下课以后，邀请卡耐基共进午餐。餐桌
上，他倾身向前说：“卡耐基先生，我曾避开各种聚会中说话的机会，但是如今我当选
为大学里董事会的主席，必须主持会议。你想，我在这半百之年，是否还可能学会当众
演说？”卡耐基说：“先生，你一定会成功的。”
三年以后，他们又在那个地方共进午餐。卡耐基提起从前的谈话，问他当初的预言
是否已经实现。他微微一笑，从口袋中拿出一本小小的红色笔记本，给卡耐基大师看他
往后数月里排定的演说日程表。“有能力作这些讲演，讲演时所获得的快乐，以及我对
社会能够提供额外的服务——这一切都是我一生当中最高兴的事。”他承认道。接着，
根特先生又得意洋洋的亮出王牌。他那教堂里的人，邀请英国首相前来费城，在一次宗
教会议上演说。英国首相很少到美国来，而负责介绍这位政治家的不是别人，正是根特
先生。就是这位先生，三年前还在这张桌边倾身问卡耐基，他是否有朝一日能够当众讲
话呢？他的演讲能力进步如此神速，在卡耐基看来，就同他的心理素质及自我认识的改
变密切相关。
有一位叫寇蒂斯的医生，是位热心的棒球迷，经常去看球员们练球。不久，他就和
球员成为好朋友，并被邀请参加一次为球队举行的宴会。
在侍者送上咖啡与糖果之后，有几位著名的宾客被请上台“说几名话”。突然之间，
在事先没有通知的情况下，他听到宴会主持人宣布说：“今晚有一位医学界的朋友在座，
我特别请寇蒂斯大夫上来向我们谈谈棒球队员的健康问题。”
他对这个问题是否有准备呢？当然有，而且可以说他是对这个问题准备最充分的人，
因为他是研究卫生保健的，已经行医三十余年。他可以坐在椅子里向坐在两旁的人侃侃
谈论这个问题，可以谈一整个晚上。但是，要他站起来讲这些问题，而且对象只是眼前
的一小部分人，那却是另外一个问题了。这个问题令他不知所措，他心跳的速度加快了
一倍，而他每一沉思，心脏就立即停止跳动。他一生中从未作过演讲，而他脑海中的记
忆，现在仿佛全长着翅膀飞走了。
他该怎么办呢？宴会上的人全在鼓掌，大家都望着他，他摇摇头，表示谢绝。但他
这样做反而引来了更热烈的掌声，纷纷要求他上台演讲。“寇蒂斯大夫！请讲！请讲！”
的呼声愈来愈大，也更坚决。
他处在极为悲怯的情况下。他知道，如果他站起来演讲一定会失败，他将无法讲出
完整的五、六个句子。因此，他站起身来，一句话也没说，转身背对着他的朋友，默默
地走了出去，深感难堪，更觉得是莫大的耻辱。
他回到布鲁克林的第一件事就是报名参加卡耐基的演讲训练课程。他不愿再度陷入
脸红及哑口无言的困境了。
象他这样的学生，是老师最高兴碰到的，因为他有极为迫切的需要。他希望拥有演
讲的能力，他对这项欲望毫无二心。能彻底地准备自己的讲稿，心甘情愿地加以练习，
从不漏掉训练课程中的任何一课。
通过努力练习，进步的速度令他自己都感到惊讶，并且超越了他最大的希望。在上
过最初的几节课后，他紧张的情绪消失了，信心愈来愈强。两个月后，他已成为班上的
明星演讲家，不久就开始接受邀请，前往各地演讲。他现在很喜欢演讲的感觉及那分欢
喜，以及所获得的荣誉，更高兴从演讲中结交到更多的朋友。纽约市共和党竞选委员会
的一名委员，在听过寇蒂斯大夫的一次演说之后，立即邀请他到全市各地为共和党发表
竞选演说。要是这位政治家知道，在一年以前他所要欣赏的这位演讲家曾经在羞愧与困
惑的情况下离开一个宴会，并且是因为他张口结舌，说不出话来，害怕面对观众，那么，
这位政治家一定会大吃一惊的。
要想获得自信心、勇气以及能力，以便在向人们发表谈话的同时能够冷静而清晰地
思考，这并不象大多数人所想象的那般困难。这就如同你打高尔夫球一样，任何人都可
以发展出他潜在的能力，只要他有想要如此做的充分欲望就行。
还有另外一个例子，一日，一个公司的董事长顾立区来到卡耐基的办公室。他对卡
耐基说：“我这一生每逢要说话时，没有一次不是惊惧万状的。身为董事长不能不主持
开会。董事们个个都已熟悉多年，大家围桌而坐时，我同他们对答如流，一点困难也没
有，然而一旦起身说话，我就会惊恐万状，一个字也说不出。这种情形已有多年。我不
相信你能帮得上忙。我的毛病太严重了，它由来太久。”
卡耐基说：“你既然认为我帮不上你的忙，干嘛还来找我？”
“只为了一个原因，”他答道。“我有个会计师，他处理我私人的帐目问题，他是
个羞怯的家伙。进自己的小办公室前，得先穿过我的办公室，好多年来，他一直都是蹑
手蹑脚地走过我的办公室，眼观地面，难得说一个字。不过最近，他改头换面了。如今
他走进办公室时，下颚抬起，眼里闪着一股光亮，而且还说：‘早安，顾立区先生。’
信心十足，神采奕奕。我吃惊于这种改变，就问他：‘你怎么现在变得不腼腆了？’他
于是告诉了我参加你的训练课程之事。我就是因为看见那个吓坏了的小人物身上的大改
变，才来找你的。”
卡耐基告诉顾立区先生，定期来上课，并照课程的要求做，不出几星期，就会喜欢
在听众面前讲话了。
“你要真是办得到，”顾立区说，“那我可就要成为全国最快乐的人之一了。”
顾立区先生果然来参加课程，并且进步神速。三个月后，卡耐基邀请他参加阿斯特
饭店舞厅里的三千人聚会，并谈谈自己在训练中所获得的收益。他很抱歉不能参加，因
为他事先已有约。但第二天他挂电话给卡耐基说：“我把约会取消了。
我准备去参加那个聚会，并为你而讲演，这是我欠你的。我要告诉听众这个训练给
我的帮助。我这么做，是希望借自己的故事来激励一些听众，让他们祛除残害他们生命
的恐惧。”
卡耐基说让他讲两分钟就行，结果对着三千人，他足足说了十多分钟。
类似的奇迹在卡耐基先生的演讲口才训练班上很多。许多人由于参加这项训练而改
变了自己的命运。其中，有好多人在自己的岗位上获得了远远超过自己所希望的擢升，
在商业上、事业上和社会上达于显赫的地位。也因为如此，卡耐基先生认为，在正确的
时刻，一场演说就足以使大功告成。因为在这样一场演说中，受训者就可以借助别人的
经验，克服不良心理，获得演讲的信心、勇气和技巧。

4、首先，口才是练出来的，不要羞怯，要知道每个人的资质都是差不多的，自己有怯场的心理，别人也会有同样的感受，要抓紧一切可以锻炼的机会来展示自己，给自己信心，相信自己既能够做得到也能够说得出，每一次的锻炼都会给自己开始下一次以莫大的勇气，再加上自己不断的总结和积累。长此以往，必然能够在以后的一切场合中自己脱颖而出，说出自己，证明自己。
其次，说话要有内容，才能够在社交场合及一些工作场合中吸引别人的倾听，你总要使别人在听你说话的过程中有一些收益或是产生共鸣，那么这样的说话才是成功的，而别人也才会乐意听你说话，与你交流。同理而言，一位好的说话者一定是一位特别擅长沟通的人，在自己说话的时候也要学会倾听他人的说话，俗话说：出门看天色，进门看脸色。因此在说话时更要学会看他人听你说话时的表情，以便适时的改变自己说话的内容、语气等等，说话时千万不要自说自话，这是最不成功的说话。
再次，说话要注意自己的节奏感，这一点是相当重要的。有些人在说话的时候语速相当快，就象在爆豆子一样，往往她自己说完以后，别人都没有反映过来她说的是什么。说话说得慢一些，声音响亮一些，你会发现，人们会更加注意的倾听你的说话，而且他们会感觉你所说的每一句话都是从内心深处说出来的，是经过你慎重考虑后才说出来的，人们会认为你在对自己说的话负责任。其实言语并不见得比写文章容易，文章写得不好来还可以修改，而一句话说出来了，要想修改是比较困难的。我们也常感觉到，即使同一个意思，甚至同一句话，会说话的人，能叫你眉飞色舞，不会说话的人，则叫你头昏脑胀。
最后，要跟会说话的人多学习，多去倾听别人的说话，西方有句谚语说：上帝之所以给人一个嘴巴两只耳朵，就是要人多听少说。多听，才是最有收获的，不断的丰富自己的内在知识，不断的去学习别人的长处，用一颗自信与谦和的心来面对自己的每一次社交与工作中的场合，即使自己做的不够好，只要努力，只要有真诚，相信你假以时日，一定能够成为一位说话和沟通的高手，为自己的事业和生活带来很多快乐！
5、自信、多练习、常说，
祝你成功，同时，以前有一个主持人为了练出标准的普通话，嘴里曾含过石子，效果不错，但本人没有试过，是校音的，你可以尝试一下。
祝你开心！！！

30天口才速成法

目标：锻炼最大胆的发言，锻炼最大声的说话，锻炼最流畅的演讲。
自我激励誓言：我一定要最大胆地发言，我一定要最大声地说话，我一定要最流畅地演讲。
目标实现时间：30天

一、积极心态训练（20分）
  1、自我暗示：每天清晨默念10遍“我一定要最大胆地发言，我一定要最大声地说话，我一定要最流畅地演讲。我一定行！今天一定是幸福快乐的一天！”（平常也自我暗示，默念或写出来，至少10遍。）（10分）
2、想象训练：至少5分钟想象自己在公众场合成功的演讲，想象自己成功。（5分）
3、至少5分钟在镜前学习微笑，展示自己的手势及形态。（5分）
二、口才锻炼（60分）
（一）每天至少10分钟深呼吸训练。（10分）
（二）抓住一切机会讲话，锻炼口才。（50分）
1、每天至少与5个人有意识地交流思想。（10分）
2、每天大声朗诵或大声讲至少5分钟。（10分）
3、每天训练自己“三分钟演讲”一次或“三分钟默讲”一次。（10分）
4、每天给亲人、同事至少讲一个故事或完整叙述一件事情。（10分）
5、注意讲话时的一些技巧。（10分）
A、讲话前，深吸一口气，平静心情，面带微笑，眼神交流一遍后，开始讲话。
B、勇敢地讲出第一句话，声音大一点，速度慢一点，说短句，语句中间不打岔。
C、当发现紧张卡壳时，停下来有意识地深吸口气，然后随着吐气讲出来。
D、如果表现不好，自我安慰：“刚才怎么又紧张了？没关系，继续平稳地讲”；同时，用感觉和行动上的自信战胜恐惧。
E、紧张时，可以做放松练习，深呼吸，或尽力握紧拳头，又迅速放松，连续10次。
三、辅助锻炼（20分）
1、每天至少20分钟阅读励志书籍或口才书籍，培养自己积极心态，学习一些技巧。（4分）
2、每天放声大笑10次，乐观面对生活，放松情绪。（4分）
3、训练接受他人的视线、目光，培养自信和观察能力。（4分）
4、培养微笑的习惯，要笑得灿烂、笑得真诚，锻炼亲和力。（4分）
5、学会检讨，每天总结得与失，写心得体会。每周要全面总结成效及不足，并确定下周的目标。（4分）
每天的反省记录：


口才并不是一种天赋的才能，它是靠刻苦训练得来的。古今中外历史上一切口若悬河、能言善辩的演讲家、雄辩家。他们无一不是靠刻苦训练而获得成功的。

美国前总统林肯为了练口才，徒步30英里，到一个法院去听律师们的辩护词，看他们如何论辩，如何做手势，他一边倾听，一边模仿。他听到那些云游八方的福音传教士挥舞手臂、声震长空的布道，回来后也学他们的样子。他曾对着树、树桩、成行的玉米练习口才。

日本前首相田中角荣，少年时曾患有口吃病，但他不被困难所吓倒。为了克服口吃，练就口才，他常常朗诵、慢读课文，为了准确发音，他对着镜子纠正嘴和舌根的部位，严肃认真，一丝不苟。

我国早期无产阶级革命家、演讲家肖楚女，更是靠平时的艰苦训练，练就了非凡的口才。肖楚女在重庆国立第二女子师范教书时，除了认真备课外，他每天天刚亮就跑到学校后面的山上，找一处僻静的地方，把一面镜子挂在树枝上，对着镜子开始练演讲，从镜子中观察自己的表情和动作，经过这样的刻苦训练，他掌握了高超的演讲艺术，他的教学水平也很快提高了。1926年，他年方30，就在毛泽东同志主办的广州农民运动讲习所工作，他的演讲至今受到世人的推崇。

我国著名的数学家华罗庚，不仅有超群的数学才华，而且也是一位不可多得的“辩才”。他从小就注意培养自己的口才，学习普通话，他还背了唐诗四五百首，以此来锻炼自己的“口舌”。

这些名人与伟人为我们训练口才树立了光荣的榜样，我们要想练就一副过硬的口才，就必须像他们那样，一丝不苟，刻苦训练，正如华罗庚先生在总结练“口才”的体会时说的：“勤能补拙是良训，一分辛苦一分才。”

练口才不仅要刻苦，还要掌握一定的方法。科学的方法可以使你事半功倍，加速你口才的形成。当然，根据每个人的学识、环境、年龄等等的不同，练口才的方法也会有所差异，但只要选择最适合自己的方法，加上持之以恒的刻苦训练，那么你就会在通向“口才家”的大道上迅速成长起来。

我们在此介绍几种符合同学们特点，简单、易行、见效的口才训练方法。

（1）         速读法

这里的“读”指的是朗读，是用嘴去读，而不是用眼去看，顾名思义，“速读”也就是快速的朗读。

这种训练方法的目的，是在于锻炼人口齿伶俐，语音准确，吐字清晰。

方法：找来一篇演讲辞或一篇文辞优美的散文。先拿来字典、词典把文章中不认识或弄不懂的字、词查出来，搞清楚，弄明白，然后开始朗读。一般开始朗读的时候速度较慢，逐次加快，一次比一次读得快，最后达到你所能达到的最快速度。

要求：读的过程中不要有停顿，发音要准确，吐字要清晰，要尽量达到发声完整。因为如果你不把每个字音都完整的发出来，那么，如果速度加快以后，就会让人听不清楚你在说些什么，快也就失去了快的意义。我们的快必须建立在吐字清楚、发音干净利落的基础上。我们都听过体育节目的解说专家宋世雄的解说，他的解说就很有“快”的功夫。宋世雄解说的“快”，是快而不乱，每个字，每个音都发得十分清楚、准确，没有含混不清的地方。我们希望达到的快也就是他的那种快，吐字清晰，发音准确，而不是为了快而快。

速读法的优点是不受时间、地点的约束，无论在何时、何地。只要手头有一篇文章就可以练习。而且还不受人员的限制，不需要别人的配合，一个人就可以独立完成。当然你也可以找一位同学听听你的速读练习，让他帮助挑你速读中出现的毛病。比如哪个字发音不够准确，那个地方吐字还不清晰，等等，这样就更有利于你有目的地进行纠正、学习。你还可以用录音机把你的速读录下来，然后自己听一听，从中找出不足，进行改进。如果有老师指导就更好了。

（2）         背诵法

同学们都背诵过课文。有诗歌、有散文、有小说。背诵的目的是各有不同的。有的是因为老师要求必须背诵，而不得不背，以完成老师交给的学习任务；也有的是为了记忆下某个名诗、名句，以此来丰富自己的文学素养。而我们提倡的背诵，主要的目的是在于锻炼我们的口才。

我们要求的背诵，并不仅仅要求你把某篇演讲辞、散文背下来就算完成了任务，我们要求的背诵，一是要“背”，二还要求“诵”。这种训练的目的有两个：一是培养记忆能力，二是培养口头表达能力。

记忆是练口才必不可少的一种素质。没有好的记忆力，要想培养出口才是不可能的。只有大脑中充分地积累了知识，你才可能张口即出，滔滔不绝。如果你大脑中是一片空白，那么你再伶牙俐齿，也无济无事。记忆与口才一样，它并不是一种天赋的才能，后天的锻炼对它同样起着至关重要的作用，“背”正是对这种能力的培养。

“诵”是对表达能力的一种训练。这里的“诵”也就是我们常说的“朗诵”。它要求在准确把握文章内容的基础上进行声情并茂的表达。

背诵法，不同于我们前面讲的速读法。速读法的着眼点在“快”上，而背诵法的着眼点在“准”上。也就是你背的演讲辞或文章一定要准确，不能有遗漏或错误的地方，而且在吐字、发音上也一定要准确无误。

其方法是：第一步，先选一篇自己喜欢的演讲辞、散文、诗歌；第二步，对选定的材料进行分析、理解，体会作者的思想感情。这是要花点工夫的，需要我们逐句逐段地进行分析，推敲每一个词句，从中感受作者的思想感情，并激发自己的感情；第三步，对所选的演讲辞、散文、诗歌等进行一些艺术处理，比如找出重音、划分停顿等，这些都有利于准确表达内容；第四步，在以上几步工作的基础上进行背诵。在背诵的过程中，也可分步进行。首先，进行“背”的训练。也就是先将文章背下来。在这个阶段不要求声情并茂。只要能达到熟练记忆就行。并在背的过程中，自己进一步领会作品的格调、节奏，为准确把握作品打下更坚实的基础。第二，是在背熟文章的基础上进行大声朗诵。将你背熟的演讲辞、散文、诗歌等大声地背诵出来，并随时注意发声的正确与否，而且要带有一定的感情。第三，是这个训练的最后一步，用饱满的情感，准确的语言、语调进行背诵。

这里的要求是准确无误地记忆文章，准确地表达作品的思想感情。比如，我们要背诵高尔基的《海燕》，我们首先就应明白，这是篇散文诗。它是在预报革命的风暴即将来临，讴歌的是海燕——无产阶级战士的形象。整篇散文诗都是热烈激亢的，表达了革命者不可遏止的憎爱分明。那么我们在朗诵《海燕》时就要抓住这个基调。当然仅仅抓住作品的基调还是不够的。我们还要对作品进行一些技巧上的处理，比如划分段落、确定重音、停顿等等。平平淡淡，没有波澜，没有起伏，一调到底的朗诵是不会成功的。有些人在背诵《海燕》时把握了它激昂奋进的基调，却没有注意朗诵技巧，开口就定在最高的音上，结果到了表达感情的最高点时，就只能是声嘶竭力。我们说这也是把握欠准确的缘故。如果对作者的思想感情发展的脉络有了准确的把握，那么就不会犯类似的错误了。

这个训练最好能有老师的指导，特别是在朗诵技巧上给些指导。如果没有这个条件，也可以找同学帮助，请同学听自己背诵，然后指出不足，使我们在改进时有所依据，这对练口才很有好处。

（3）         练声法

练声也就是练声音，练嗓子。在生活中，我们都喜欢听那些饱满圆润、悦耳动听的声音，而不愿听干瘪无力、沙哑干涩的声音。所以锻炼出一副好嗓子，练就一腔悦耳动听的声音，是我们必做的工作。

练声的方法是：第一步，练气。俗话说练声先练气，气息是人体发声的动力，就像汽车上的发动机一样，它是发声的基础。气息的大小对发声有着直接的关系。气不足，声音无力，用力过猛，又有损声带。所以我们练声，首先要学会用气。

吸气：吸气要深，小腹收缩，整个胸部要撑开，尽量把更多的气吸进去。我们可以体会一下，你闻到一股香味时的吸气法。注意吸气时不要提肩。

呼气：呼气时要慢慢地进行。要让气慢慢地呼出。因为我们在演讲、朗诵、论辩时，有时需要较长的气息，那么只有呼气慢而长，才能达到这个目的。呼气时可以把两齿基本合上。留一条小缝让气息慢慢地通过。

学习吸气与呼气的基本方法，你可以每天到室外、到公园去做这种练习，做深呼吸，天长日久定会见效。

第二步，练声。我们知道人类语言的声源是在声带上，也就是我们的声音是通过气流振动声带而发出来的。

在练发声以前先要做一些准备工作。先放松声带，用一些轻缓的气流振动它，让声带有点准备，发一些轻慢的声音，千万不要张口就大喊大叫，那只能对声带起破坏作用。这就像我们在做激烈运动之前，要做些准备动作一样，否则就容易使肌肉拉伤。

声带活动开了，我们还要在口腔上做一些准备活动。我们知道口腔是人的一个重要的共鸣器，声音的洪亮、圆润与否与口腔有着直接的联系，所以不要小看了口腔的作用。

口腔活动可以按以下方法进行：

第一，进行张闭口的练习，活动嚼肌，也就是面皮。这样等到练声时嚼肌运动起来就轻松自如了。

第二，挺软腭。这个方法可以用学鸭子叫“gāgā”声来体会。

人体还有一个重要的共鸣器，就是鼻腔。有人在发音时，只会在喉咙上使劲，根本就没有上胸腔、鼻腔这两个共鸣器、所以声音单薄，音色较差。练习用鼻腔的共鸣方法是，学习牛叫。但我们一定要注意，在平日说话时，如果只用鼻腔共鸣，那么也可能造成鼻音太重的结果。

我们还要注意，练声时，千万不要在早晨刚睡醒时就到室外去练习，那样会使声带受到损害。特别是室外与室内温差较大时，更不要张口就喊，那样，冷空气进入口腔后，会刺激声带。

第三，练习吐字。吐字似乎离发声远了些，其实二者是息息相关的。只有发音准确无误，清晰、圆润，吐字也才能“字正腔圆”。

我们在小学时，都学习过拼音，都知道每个字都是由一个音节组成的，而一个音节我们又可以把它分成字头、字腹、字尾三部分，这三部分从语音结构来分，大体上可以说是，字头就是我们说的声母，字腹就是我们说的韵母，字尾就是韵尾。

吐字发声时一定要咬住字头。有一句话叫“咬字千斤重，听者自动容”说的就是这个意思。所以我们在发音时，一定要紧紧咬住字头，这时嘴唇一定要有力，把发音的力量放在字头上，利用字头带响字腹与字尾。

字腹的发音一定要饱满、充实，口形要正确。发出的声音应该是立着的；而不是横着的，应该是圆的，而不是扁的。但是，如果处理的不好，就容易使发出的声音扁、塌、不圆润。

字尾，主要是归音。归音一定要到家，要完整。也就是不要念“半截子”字，要把音发完整。当然字尾也要能收住，不能把音拖得过长。

如果我们能按照以上的练习要求去做，那么你的吐字一定圆润、响亮，你的声音也就会变得悦耳动听了。

这里应多做一些这样的练习：

①深吸一口气。数数，看能数多少。

②跑20米左右，然后朗读一段课文，尽量避免喘气声。

③按字正腔圆的要求读下列成语：

英雄好汉 兵强马壮 争先恐后 光明磊落 深谋远虑

果实累累 五彩缤纷 心明眼亮 海市蜃楼 优柔寡断

源远流长 山清水秀

④读练口令

A．八面标兵奔北坡，炮兵并排北坡炮；

炮兵怕把标兵碰，标兵怕碰炮兵炮。

B．哥挎瓜筐过宽沟，赶快过沟看怪狗；

光看怪狗瓜筐扣，瓜滚筐空怪看狗。

C．洪小波和白小果，

拿着箩筐收萝卜。

洪小波收了一筐白萝卜，

白小果收了一筐红萝卜。

不知是洪小波收的白萝卜多，

还是白小果收的红萝卜多。

（4）         复述法

复述法简单地说，就是把别人的话重复地叙述一遍。这种方法在课堂上使用的较多。如老师让同学们看一段幻灯片，然后请同学复述幻灯片的情节或人物的对话。这种训练方法的目的，在于锻炼人的记忆力、反应力和语言的连贯性。

其方法是：选一段长短合适、有一定情节的文章。最好是小说或演讲辞中叙述性强的一段，然后请朗诵较好的同学进行朗读，最好能用录音机把它录下来，然后听一遍复述一遍，反复多次地进行。直到能完全把这个作品复述出来。复述的时候，你可把第一次复述的内容录下来，然后对比原文，看你能复述下多少，重复进行，看多少遍自己才能把全部的内容复述下来。这种练习绝不单单在于背诵，而在于锻炼语言的连贯性。如果能面对众人复述就更好了，它还可以锻炼你的胆量，克服紧张心理。

这要求我们在开始时，只要能把基本情节复述出来就可以，在记住原话的时候，可以用自己的话把意思复述出来；第二次复述时就要求不仅仅是复述情节，而且要求能复述一定的人物语言或描写语言；第三次复述时，就应基本准确地复述出人物的语言和基本的描写语言，逐次提高要求。在进行这种练习之前，最好能根据自己的实际情况和所选文章的情况，制定一个具体的要求。比如选了一段共有10句话的文章，那么第一次复述时就要把基本情节复述出来，并能把几个关键的句子复述出来；第二次就应该能复述出5～7个句子；第三次就应能复述8～10个句子。当然，速度进展得越快，也就说明你的语言连贯性和记忆力越强。

开始练习时，最好选择句子较短、内容活泼的材料进行，这样便于你把握、记忆、复述。随着训练的深入，你可以逐渐选一些句子较长，情节少的材料，进行练习。这样由易到难，循序渐进，效果会更好。

这种练习一定要有耐心与毅力。有的同学一开始就选用那些长句子、情节少的文章作为训练材料，结果常常是欲速则不达。这就像我们学走路一样，没学会走，就要学跑是一定要摔跤的。而且这个训练有时显得很繁琐、麻烦，甚至是枯燥乏味，这就需要我们要有耐心与毅力，要知难而进，勇于吃苦，不怕麻烦。没有耐心与毅力，那么你将注定是一事无成的。

（5）         模仿法

我们每个人从小就会模仿，模仿大人做事，模仿大人说话。其实模仿的过程也是一个学习的过程。我们小时候学说话是向爸爸、妈妈及周围的人学习，向周围的人模仿。那么我们练口才也可以利用模仿法，向这方面有专长的人模仿。这样天长日久，我们的口语表达能力就能得到提高。

其方法是：

①模仿专人。在生活中找一位口语表达能力强的人，请他讲几段最精彩的话，录下来，供你进行模仿。你也可以把你喜欢的、又适合你模仿的播音员、演员的声音录下来，然后进行模仿。

②专题模仿。几个好朋友在一起，请一个人先讲一段小故事、小幽默，然后大家轮流模仿，看谁模仿的最像。为了刺激积极性，也可以采用打分的形式，大家一起来评分，表扬模仿最成功的一位。这个方法简单易行，且有娱乐性。课上、课间、课后都可进行。只要有三四个人就能进行。所要注意的是，每个人讲的小故事、小幽默，一定要新鲜有趣，大家爱听爱学。而且在讲以前一定要进行一些准备，一定要讲准确、生动、形象，千万不要把一些错误的东西带去，否则模仿的人了跟着错了，害人害己。

③随时模仿。我们每天都听广播，看电视、电影，那么你就可以随时跟着播音员、演播员、演员进行模仿，注意他的声音、语调，他的神态、动作，边听边模仿，边看边模仿，天长日久，你的口语能力就得到了提高。而且会增加你的词汇，增长你的文学知识。

这里要求要尽量模仿得像，要从模仿对象的语气、语速、表情、动作等多方面进行模仿，并在模仿中有创造，力争在模仿中超过对方。

在进行这种练习时，一要注意选择适合自己的对象进行模仿。要选择那些对自己身心有好处的语言动作进行模仿，我们有些同学模仿力很强，可是在模仿时都不够严肃认真，专拣一些脏话进行模仿，久而久之，就形成了一种低级的趣味，我们反对这种模仿方法。

模仿法是一种简单易学、娱乐性强、见效快的方法，尤其适合我们这个年龄的同学们练习，希望大家能勤学苦练，早日见效。

（6）         描述法

小的时候我们都学过看图说话，描述法就类似于这种看图说话，只是我们要看的不仅仅是书本上的图，还有生活中的一些景、事、物、人，而且要求也比看图说话高一些。简单地说，描述法也就是把你看到的景、事、物、人用描述性的语言表达出来。

描述法可以说是比以上的几种训练法更进了一步。这里没有现成的演讲辞、散文、诗歌等做你的练习材料，而要求你自己去组织语言进行描述。所以描述法训练的主要目的就在于训练同学们的语言组织能力和语言的条理性。

无论是演讲、说话、论辩都需要有较强的组织语言的能力，没有这种能力也就不可能有一张悬河之口，组织语言的能力是口语表达能力的一项基本功。

其方法是一幅画或一个景物作为描述的对象。第一步，对要描述的对象进行观察。比如，我们所要描述的对象是“秋天的小湖边”，那么我们就要观察一下这个湖的周围都有些什么，有树？有假山？有凉亭？还有游人？并且树是什么样子，山是什么样子？凉亭在这湖光山色、树影的衬托下又是个什么样子，这秋天里的游人此时又该是一种什么心情呢？这一切都需要你用自己的眼睛去观察，用你的心去体验。只有有了这种观察，你的描述才有基础。第二步，描述。描述时一定要抓住景物的特点，要有顺序地进行描述。

其要求是，抓住特点进行描述。语言要清楚，明白，要有一定的文采。描述的千万不要成流水账，平平淡淡，一定要用描述性的语言，尽量生动些，活泼些。要讲点顺序，不要东一句，西一句，南一句，北一句的，描述出的东西，让人听了以后能知道你描述的到底是个什么景物。描述的时候允许有联想与想象。比如，你观察到秋天的湖边有一位白发苍苍的老爷爷，孤独地坐在斑驳陆离的树荫下，你就可能有一种联想，你可能想到了自己的爷爷，也可能想到这个老人的生活晚景，还可能想到“夕阳无限好，只是近黄昏”这个诗句……那么在描述的时候，你就可以把这一切都加进去，使你的描述更充实、生动。

（7）         角色扮演法

角色一词，我们也是从戏剧、电影中借用来的。是指演员扮演的戏剧或电影中的人物。我们这里的角色，与戏剧、电影中讲的角色，有着相同的意义。

角色扮演法，就是要我们学演员那样去演戏，去扮演作品中出现的不同的人物，当然这个扮演主要是在语言上的扮演。

其方法是：

①选一篇有情节、有人物的小说、戏剧为材料。

②对选定的材料进行分析，特别要分析人物的语言特点。

③根据作品中人物的多少，找同学，分别扮演不同的人物角色。比比看，谁最能准确地扮演自己的角色。

④也可一个人扮演多种角色，以此培养自己的语言适应力。

这种训练的目的，在于培养人的语言的适应性、个性，以及适当的表情、动作。

这种训练法要求“演”的成分很重，它有别于对朗诵的要求。它不仅要求声音洪亮，充满感情，停顿得当；还要求能绘声绘色、惟妙惟肖地把人物的性格表现出来，而且要配有一定的动作和表情。从这个角度看，这个训练是有一定的难度的。但只要我们朝着这个方向努力，那么我们就会成功。

（8）讲故事法

同学们或许都听过故事，但是不是都讲过故事呢？讲故事看起来很容易，要真讲起来就不那么容易了，常言说：“看花容易，绣花难”呀！听别人讲故事绘声绘色，很吸引人，有些朋友听起故事来甚至都可以忘了吃饭、睡觉，可是自己一讲起来，仿佛就不是那么回事了，干干巴巴，毫无吸引力。因此，讲故事也是一种才能，并不是人人都可以把故事讲好的。学习讲故事是练口才的一种好方法。

讲故事，可以训练人的多种能力。因为故事里面既有独白，又有人物对话，还有描述性的语言、叙述性的语言，所以讲故事可以训练人的多种口语能力。

这里的方法是：

①分析故事中的人物。故事的情节性是十分强的，而且故事的主题大都是通过人物的语言、行动表现出来的，所以我们在讲故事以前就要先研究人物的性格特征，以及人物之间的关系。比如，我们要讲《皇帝的新衣》这个童话故事，那么你就要分析其中的几个人物，以及他们的性格，然后把国王的愚蠢无知，骗子的狡诈阴险，大臣的阿谀奉承、不分是非，乃至小孩的天真无邪都用语言表现出来，这是一项十分艰巨的工作。

②掌握故事的语言特点。故事的语言不同于其他文学形式的语言，其最大的特点是口语性强、个性化强。所以当我们拿到一个材料的时候，不要马上就开始练习讲，而要先把材料改造一下，改成适合我们讲的故事。这个工作你可以请老师或爸爸、妈妈帮你做。

③反复练讲。对材料做了以上的分析、加工以后，我们就可以开始练讲。通过反复练讲达到对内容的熟悉。最后能使自己的感情与故事中人物的感情相隔合，做到惟妙惟肖地表现人物性格，语言生动形象。

另外，边练讲，还要边注意设计自己的表情、动作。看看你讲故事时的表情、动作是不是与你讲的内容相一致。

其要求是：①发音要准确、清楚。平舌音、翘舌音、四声都要清楚。最好能用普通话讲。②不要照本宣读。讲故事是不允许手里拿着故事书照着念的，那样就成了念故事了。讲故事要用自己的语言去讲?
