* 阅读专业书籍如何做笔记
阅读专业书籍怎么做读书笔记？【知乎】
作者： 杨程Ben

问题：

一般我自己的专业书籍就在书上做笔记
但是如果是借来的专业书籍，或者是电子版的专业书籍要怎么做笔记才好？
比如说曼昆的经济学，斯通普夫的西方哲学史，东北财经大学的中级财务会计
这类书的知识含量很多，如果光是阅读，很快就忘了很多，所以应该怎么写读书笔记才好

PS：请不要回答“读书笔记一般有批注、摘录、提纲、心得等几种...”这种在百度上一搜索就有很多这种类似的回答，太笼统概括了。
请具体到专业书籍该怎么做

谢谢

谢谢回复我问题的人，下面列出一些回复，及我的看法，方便后面的人看：
----关于 “ 拿个笔记本写下页数和速记标题”：我一般阅读散文小说这些类型的书籍会怎么做，先标记下令我感触很深的地方，在阅读完之后誊写出来，附上自己的感想。但是比如曼昆的经济学原理这本书吧，书中列举的案例我倒是可以写出自己的想法，经济学原理才十个我也可以抄，但是很多地方我觉得每一句每一页都很重要，都是我学要学的地方......又比如清华大学出版的Java6基础教程，什么java语言基础，流程控制语句，如果是要标记页数，我得从第一页标记到最后一页了。



答案：

不好意识，回答有些文不对题，你的问题并不是都是笔记，而是阅读的方法就不对。我的回复中包括一些阅读、笔记和其它内容。如果有其它问题，在留言。

阅读专业书籍最开始最基本的东西耐心，别想求快，多花些时间和精力把基础概念搞清楚，深入的进行理解，别在意别人的速度.

我自己阅读专业书籍的目的如果是为了学习和理解，不会只局限于一、二本，会花时间时间收集书单，然后做主题阅读。

对于阅读专业书籍，可以试试：

主题阅读
名词辞典
读书笔记 +思维导图
讲故事

1、名词辞典：初期最大的问题，对要把一些专业名词搞清楚，理解每个词是什么意识，不是书中的归纳试着用自己的话把对这个词的理解写下来，尽量通俗一点，随着你理解的加深，不断的修改。一些专业词汇的理解程度往往决定你阅读时的效果。

2、主题阅读：在这个时候，不要只读一本书，最好进行主题阅读，准备20、30本书籍，一起阅读。有些书可能很烂，但有时能把一个的概念讲解的不错。一本看不懂就换一本，对于重要的概念和观点会在不同的书籍中反复出现和阐述。

3、读书笔记+思维导图：
通过思维导图先大概划分出一个整体的框架，专业书可以按章做，先把每一章的重点总结出来。
针对某个细节，书中说可能会非常精彩，这时把书中的部分内容摘录做成读书笔记。
刚开始时是记录要点，在后期整理时会加上一些自己的想法和阅读时的心得。有时会单独把心得和想法做成单独的思维导图，把这些想法从新汇总、提练之后会非常有价值。

做思维导图时，如果书非常好，也有充分的时间会进行4、5遍的调整。

第一遍开始把书中所有的要点都做出来。
第二遍自己的理解对做出的思维导图要点做成整合和调整。
第三遍开始进行删减只保留对自己有用的部分。
第四遍把这个导图按照5W3H的方式从新做一个思维导图
第五遍把这本书的内容放到个人行业的知识树，进行补充和扩展。这个知识树通过阅读、实践和自己的反思积累而完成。

4、讲故事
有很多东西非常难以理解，这时可以试着把编故事来讲解这些概念，看你能把故事编得多好。
试着用传播你学到的东西，并把它跟现实连接起来，把你的心得写出来放在Blog上、做PPT、思维导图，

5、对于你上面提到的几本书：

曼昆的经济学原理跟《一堂经济课》一起阅读，先把经济学的一些基本概念了解清楚
斯通普夫的西方哲学史: 搞清楚，书中讲解了多少个流派，每个流派的特点是什么。如果实在看不明白，寻找每个流派的著作，继续深入阅读。推荐跟傅佩荣《哲学与人生》一起阅读。
中级财务会计：去看看《卖竹竿的小贩为什么不会倒?》、《饺子馆和高级餐厅，哪个更赚钱？》
清华大学出版的Java6基础教程 ：把语法看几遍，然后搭建一个Java编程环境，开始敲代码.在写代码的过程，慢慢就能理解，如果你光看书不动手，那你永远也学不会。

6、带着问题去阅读
或者带着问题去阅读，把遇到的问题写下来，一次准备个问题列表。

利用网络进行搜索，比如看看维基百科对于概念是如何理解的
花上几天时间去图书馆，大量而快速的翻书，看看哪本书能解决这个问题。只读跟这几个问题相关的部分，做笔记。

剩下的东西就是反复读，在不断重复时反复总结，坚持下去.
你认为书中所有的地方都是重点，那是你基本没有读明白，主次都没有分清。阅读的第一步就是先分清主次
