* 个人网站快速备案
  关键字：网站备案，快速，流程，注意事项
  描述：这篇文章将详述网站备案的各方面，总结个人经验，讲解个人网站如何快速备案
** 网站要不要备案
   网站到底要不要备案？这TM可是争论了好久的问题，身在天朝，无可奈何啊。
   我个人的结论是：除非玩票性质，一定要备案。
*** 不备案的好处
    1.省去不少麻烦
    在天朝办事，大家都心里清楚，不过现在有了阿里云好很多了。
    2.便宜的vps
    不备案，可以租用国外便宜的vps，各种硬件配置，网络流量完全秒杀国内
    3.自由
    这个不说了，要不怎么叫身在“墙外”了。网站内容，随你便，什么样类型的一般都行。
*** 不备案的缺点
    1.无法使用国内各种服务
    什么CDN还是小事，各种方便，好用的网络服务都用不了，连个微信小程序都要后端服务器要备案。
    2.国内用户访问慢
    本来大家都是中国人，你的站内容在怎么样，也是中文的吧？但是墙外很慢，JP的很多vps都被墙了。

    所以上面的这些，你自己掂量下吧。哎，不容易啊。
** 网站备案流程及个人网站如何快速备案
   1.购买阿里云万网虚拟主机
   买[[https://wanwang.aliyun.com/hosting/free?spm=5176.8060947.858673.gongxiangpuhui.16fc11faTwhXAj][共享普惠版]] ，第一年只要6元，续费50。
   2.备案
   点击阿里云右侧[[https://beian.aliyun.com/?spm=5176.8047873.765261.4.4dd8d51117SD3z][备案按钮]] ，然后仔细的填写，内容一定要详细，完整，不懂的打客服，速度相当快。
   填完后，是初审，只要1天，过了就打电话给客服催。
   初审后，买幕布，15元，然后照相。我深圳的，是广州过来的快递，第二天就到了。
   拍照，审核通过，就提交管局了。哈哈，我这个一次性过，只等了管局6天就搞定了，真是效率。
   3.去公安备案系统接入
   你以为这样就完了？too young，too simple。
   备案通过之后，还需要去[[http://www.beian.gov.cn/portal/index][公安备案系统接入]] 。又要进行各种身份验证了，提交完了慢慢等吧。
   公安备案接入注意事项，可以看这里： [[https://help.aliyun.com/knowledge_detail/36981.html?spm=0.0.0.0.BfWgTk][公安备案常见问题]] 。
   要注意的一点是：域名如果是国外，比如godday注册的，就需要先将域名迁入到阿里。
   具体如何操作，请知乎。坑爹的是，域名迁入过程中，需要[[https://domain.console.aliyun.com/?spm=5176.78016.342142.3.56cb490b2H508i#/infotemplate][个人信息模板]] ，尼玛，这个又要等至少3天啊。

*** 快速备案 结论
    所以，最快的方式是：
    *在备案的同时，1.将个人信息模板给验证了；2.将公安备案系统个人信息验证了；3.提前将域名转入到阿里；*
    我真不知道后续，还有没其他问题
** 网站备案注意事项
*** 网站名称
    *网站名称* ，这个一定要注意啊，特别特别的注意。下面我摘抄其他网站的内容：

**** 网站名称中绝对不可带有的字眼：
    论坛 博客 企业 科技  技术 炼钢  游戏 求职 招聘  广告 炒股 基金 股票 影视 网络音乐
    教育 搜索 引擎 银行  门户 购物  淘宝 商城 下载  交友 婚介 房产 联盟 学校 俱乐部
    支付 新闻 邮局 保险  医药 药物  投资 金融 推广  首页

**** 网站名称取名的一些技巧：
    名称最好取的不一样
    网站名称要清楚，要让管局能通过网站名称判断出网站的大概内容

**** 个人网站备案网站名称命名规则：
     1、个人网站备案名称必须与网站内容有关联性，不能包含：姓名、地名、成语，不能包含带有公司、组织性质的词语。
     2、个人网站名称请不要用纯数字或字母组成,不能包
     3、网站名称请使用4个以上汉字命名。
     4、请不要使用某某某个人空间、网站、网络、网址、爱好者、作品展示、工作室、平台、主页、热线、社团、导航；这样的格式
     5、网站名称中不要带有博客、论坛、在线、社区、交流等字样，若要带有此类信息，需提交前置审批文件（网站名称以“xxx的博客”等方式命名的，江苏、广东、重庆三省不需要进行前置审批）；
     6、个人网站名称不能使用成语；
     7、个人网站名称不能涉及封建迷信；不能涉及非法信息。
     8、个人网站名称也不能涉及论文、期刊等；

   最后，我自己的网站名称叫做：思维笔记网，你可以参考下。
*** 网站类别
    强烈建议不要选什么博客，个人空间之类的，选其他。
*** 备案电子验证标识和备案编号
    现在不用电子验证标示了，也就是备案电子证书。
    只需要在网站底部放上当前网站的备案编号，并添加url链接到：http://www.miitbeian.gov.cn。
*** 不要将域名解析到国外ip
    域名备案后，不要将域名全部解析到国外ip，有可能被撤销备案的。
