* 学习bootstrap
  项目在F:\bootstrap\node_modules\bootstrap

  要掌握node
  npm
  ruby等
  package managers like npm, Bower, RubyGems, and more.
  包管理，类似maven？

  sass compiler
** Intro FINISH
   include:
   file:Starter-Template.org
   use global box-sizing
   override it:
   .selector-for-some-widget {
       box-sizing: content-box;
   }

   learn slack and IRC free time
** 下载安装
  使用npm安装
  npm install bootstrap@4.0.0-beta
  需要一个package.json

** 图片
** 草稿
*** 重写bootstrap css样式最佳实践方法
    根据选择器的重量来重写，比如添加一个class之类的。
    1. 新建一个css文件，在bootstrap css后引用
    2. 在class中添加自己的class，

    100 points for IDs
    10 points for classes and pseudo-classes
    1 point for tag selectors and pseudo-elements

**** 参考资料和扩展阅读
     [[https://stackoverflow.com/questions/20721248/best-way-to-override-bootstrap-css][best way to override bootstrap css]]
     [[https://teamtreehouse.com/community/best-practices-to-customise-bootstrap-3-vanilla-css][Best practices to customise Bootstrap 3]]

** Components
*** Navbar
    BootStrap一定要学的非常熟，做好笔记，完整学习，
    需要.navbar和.navbar-expand达成响应模式。

    使用containers来限定快读。

    使用<nav>标签保证可达性，如果使用了<div>，添加role="navigation"来显示表明
    地标性的区域。

    collapse搞清楚，

    主要最初没弄懂的就是那个navbar-collapse这个，是说的，窗口过小，导航栏就会成为Button
    给隐藏起来，点击Button后才显示，

    Brand这个清楚，

    导航的条目居中，这些也清楚，先将float:left清楚掉，然后让text-align:center.
    Toggler就是隐藏后，那个导航栏条目是在左边还是右边的设置。
    大概就是这样，如果还有不懂就Google吧。

*** Breadcrumb 面包屑
     aria-label="breadcrumb"，就是一个可达性标签？
     不错，可以放在后面
     可以使用多个Nav标签。



** Content

** Layout
*** Container
    @media搞清楚，Grid搞清楚。


    将stackoverflow的问题搞成中文的？

** Image Done
** Text
