** 开仓
   到底该如何开仓还是没搞太清楚。是因为我在追求开仓的绝对正确性吗？（如果不是追求正确性，我开仓干吗？难道开仓之后等被打脸，等错误？）
   貌似还是我的思维错了。机会是市场给的，有机会就开仓，没机会就等待，不开仓。（机会？等待的是何种机会？要描述清楚）
   我的思维是左侧思维，也就是在左侧进行预测后开仓交易。
   理论上来说，我们应该是右侧思维，也就是等待市场给出信号，比如破而后立，走势不正确之后开仓。
   因为我们本身就应该是追随市场，追随趋势，是右侧交易者。而不是在左侧等待，去挨最后一刀。
   趋势追踪，trend following，这个追踪两个字太深奥，博大精深。
   怎么说？比如，现在我看到了郑煤1810破而后立，收盘反而在关键点之下，这时候就可以开仓。
   比如我在看到螺纹1810在关键支撑位没得到支撑，而第二天空头比多头还强势，这时候就可以开仓。
   最高点开仓？
   破而后立，反向开仓？
   走势不正确，反向开仓？
   多头无力，该涨不涨，理应看跌，开空？

   1. 最大亏损已确定，在可接受范围内，开仓。以前期最高点，最低点为止损点。开仓。
      问题在：遇到破而后立的情况，刚被打止损出局，下跌趋势开始。
      对心态打击非常的大，难以平稳情绪，如果在立马去追，又可能被反向打耳光，会在次级别反抽。
   2. 破而后立在开仓。
      等待前期最高点，最低点破掉之后，次级别回抽开仓。以新最高点，最低点为止损点，开仓。
      问题：不是每次都会破而后立。可能会错失掉趋势。这里有很大个错误就是假定：一定会破掉。
   3. 走势出问题，反向开仓
      比如螺纹1810，本来是个上涨趋势，但是在关键点上没有获得多头的支撑，所以之前刚启动的上涨，
      是一个多头陷阱，这是最好的反向开仓机会。而且第二天的空头力量展现的比多头强，继续加仓。
   4. 5日线以下开空，5日线以上开多
      价格站上5日线以上，以15分钟级别低点开多单，空单于此相反。
      我发现这个的好处非常的多，如果真的是下跌趋势，那么5日线破后，短期内肯定不会上破15分钟级别的。
      但是同样会有双头的反抽啊，就是过段时间后，在反弹创新高。有的甚至更恶心，多次上探高点。
      （没有理解这句话的实质）
   5. 多头力量强于空头力量，开多；空头力量强于多头力量，开空。
      当经过一轮下跌之后，破新低但是3日内趋势却没有延续继续下跌。而且立马有个大阳棒，
      可以认为多头力量强于空头力量，这时可以找时机在15分钟K线上开多。比如豆粕1809。
      （TM的不对，多头力量强于空头，也可能会有震荡，回调，应该是完全没空头力量开多。）
   6. 空头力量非常薄弱，甚至连5日线都打压不下去，开仓做多。
      很明显这是一个趋势不断强化的过程，做多的情况下非常适合这个形态。
      但是做空却不是，空头理论上来说都是开起暴跌模式，趋势延续过程中5日线都破不了。


   想想在一轮空头趋势中，如何加仓？
   那肯定是等每次反弹无力之后再开仓，如何判断这个反弹无力了？3天法则。
   暴力上涨之后，创新高之后的3天内可以看出端倪，蛛丝马迹。

   我现在是怎么想，都没想到一个非常好的开仓规则，描述，其实这样想的前提在：幻想每一次开仓都是对的。
   而实际情况是：每一次开仓几乎都是错的，都会被打止损，不打止损的话就会爆亏。

   开仓的几个原则：
   1. 不追高
   2. 不抄底
   3. 不接飞刀
   4. 不参与震荡
   5. 不在5日线以下做多，不在5日线以上做空
      但是他妈比的，今天郑棉1901就是在5日线以下跳空高开，大涨2,5个点以上啊啊啊啊。
      但是我现在回顾过去，也不知道是在那个点开仓啊啊啊。为毛要那么精确啊？因为这是带杠杆的啊。我曹。
      搞了这么久，我发现还是当初用调30日均线最方便了。回调到30日均线开仓，继续跌了，止损割掉。
      没破30日线，一直拿着，感觉是最简单，最省事的了。

      其实开仓点可以看日线，大概估计下就行，结合15分钟K线和止损就行了。
      如果15分钟K线加止损还是没能包容这次下跌，回调，那么就认为趋势有问题，没有符合我的预期的都是有问题的。

      5日线附近开仓。这个才是精髓，不一定非得5日线以上。但是要站上5日线以后，在考虑开仓做多。



   我写这个，反思到，我完全是靠感觉开仓。
