* 如何选股
  其实选股真的很简单，没有大多数人想的那么复杂和困难，大多数人对我这点估计都不相信。
  这里说说我的选股方法。

  其实选股这个东西就涉及到炒股的整个体系了。股票选好了，天天涨停板，完全不用担心什么卖的问题，也不用担惊受怕，只需要坐享云霄飞车的快感。
  最关键也最考验火候的就是对当前经济环境，货币情况有一个准确的大致了解，能估计下这次行情是个什么级别。
  这就是后续利物莫潜心研究的基本面和市场的基本逻辑。

  认为股市会有行情之后，有多大级别的行情，是牛市，还是反弹，还是震荡，这些后续的操作都会完全不同。
  确定了行情级别，就来动用自己的资金了，正所谓兵马未动粮草先行，根据级别的大小，动用不同的资金。
  这点非常关键，真正忍耐能够不出手，少出手，会空仓的，都是高手，特别是中国这个牛短熊长的市场。
  你要是听信了某报，某人说的4500点，牛市才开始，会是慢牛市的话，结局如何，你现在已经知道了。
  投机这行，最怕的就是亲信他人，时刻你都得有自己的脑子，盯紧自己的钱袋。

  知道了行情之后，我们先要来研究下指数，看看指数是否有相应的走势，是否有可能来一波行情。
  其实指数研究透彻了，还炒什么股票啊，股指期货搞起。

  指数研究好了，再来看板块，记住不是什么概念板块，活跃板块等，而是行业板块。
  选出走势良好，最近涨幅较大的板块，然后从板块中找出龙头股。
  何为龙头股，你可以认为是基本面最好的，也可以认为是涨势最好的。
  搞的话，就搞最强势的龙头股。

  这样就从基本经济-》大盘指数-》行业板块-》龙头个股，将股票选出来了。

  其实还有更加暴力，更加方便快捷的选股方法。
  那就是近2周，1月，涨幅最多的股票排行榜，然后从排行榜中找一个能保证自己上车的股票，
  然后看看此股所在的板块最近表现如何，这样就将股票选出来了。

  另外，在走出幻觉走向成熟中，万点绿中一点红，那种大盘个股，大幅杀跌时，不仅不跌，还微微收红的股票，
  就是好股票，这就是我15年选出怡亚通的原因，只可惜当时火候未到，没拿住。

  还有一种是针对弱势反弹行情的，不过能不做尽量不做吧。
  就是那种底部启动的股票，操作起来是这样搞，看那种底部启动快要涨停的，尾盘买入，第二天不涨停，或者亏损3个点以上，立马卖掉。
  这种方法应该也可以，不过属于那种怎么说了，有点像丐帮吧。
