* 大数据历史
** 核心概念
*** 大数据
    麦肯锡：
    大数据指的是规模超过现有数据库工具获取、存储、管理和分析能力的数据集，
    大数据的四个维度：
    数据集的规模（Volume）、数据流动的速度（Velocity）、数据类型的多少（Variety）和数据价值的大小（Value）
    亚马逊：
    超过单台计算机处理能力的数据量则为大数据
    WIKI：
    Big data is the term for a collection of data sets so large and complex that it becomes difficult to process
    using on-hand database management tools or traditional data processing applications.

** 技术栈
   Google的GFS和MapReduce
   Hadoop
   AMPLab和Spark
*** Hadoop
    早期的Hadoop，主要由两个核心组件构成：HDFS和MapReduce，
    其中HDFS是Google GFS的开源版本，MapReduce计算框架实现了由Google工程师提出的MapReduce编程模型
    还有一些围绕在Hadoop周围的开源项目，为完善大数据处理的全生命周期提供了必要的配套和补充。
    这些软件常用的有ZooKeeper、Hive、Pig、HBase、Storm、Kafka、Flume、Sqoop、Oozie、Mahout等

    YARN（Yet Another Resource Negotiator）
    YARN的出现是为了把计算框架与资源管理彻底分离开，解决Hadoop v1由此带来的扩展性差、单点故障
    和不能同时支持多种计算框架的问题。YARN对标的恰好就是Google的Borg系统。
*** Hadoop发展历程
    从2006年到2008年是Hadoop的诞生阶段
    从2008年到2010年是Hadoop的少年阶段。
    在互联网行业已经开始投入实际应用，应用集中在网页存储检索，日志处理和用户行为分析等方面。
    2009年，Yahoo!使用4000节点的机群运行Hadoop，支持广告系统和Web搜索的研究；
    Facebook使用600节点的机群运行 Hadoop，存储内部日志数据，支持其上的数据分析和机器学习；
    百度用Hadoop处理每周200TB的数据，进行搜索日志分析和网页数据挖掘工作。

    从2010年到2015年是Hadoop的青年阶段。
    在追求大数据处理能力的同时，也开始思考系统适配性和效率问题。
    互联网行业出现了大量数据分析类应用，比如支付宝的交易数据离线分析系统等；
    用Hadoop与生态系统中的其他软件一起构成更为复杂的应用系统，比如腾讯的广点通精准广告投放系统，电信运营商的基于用户画像的精准营销系统等。

    互联网应用和企业计算应用在需求、服务、研发和运维体系方面有本质的不同。
    互联网应用业务逻辑简单、服务于海量用户、非固定使用人群、系统的用户体验至上、持续交付、能够快速响应的专业运维；
    而企业计算应用业务逻辑复杂、有限数量用户、固定使用人群、系统更强调稳定可靠、版本交付、层级式的技术支持。

    传统的应用服务器、数据库服务器和存储服务器这样的典型三层架构受到极大的冲击。
    应用开发人员需要更深入的理解计算机系统结构，“程序” = “算法” + “数据结构”将逐渐演变成“程序” = “算法” + “数据结构” + “系统结构”。

    互联网服务强调用户体验，原本做不到实时的应用在向实时化靠拢，
    比如前端系统及业务日志从产生到收集入库的延迟从1到2天时间进化到10秒以内。
    传统企业无法忍受关系数据库动辄几十分钟的查询分析性能，纷纷求助于性价比更好的技术和产品。
    这些需求使大数据交互式查询分析、流式计算、内存计算成为业界研发和应用的新方向。

    就拿个性化推荐技术来说，目前已经开始从简单的商品推荐走向复杂的内容推荐。
    根据用户的特性与偏好，推荐内容的特征，以及当时的上下文数据（客户端设备类型、用户所处时空数据等），
    向特定用户提供个性化的内容推荐服务，内容包括商品（包括电商和零售）、广告、新闻和资讯等。
    在移动设备和移动互联网飞速发展的时代，个性化推荐将成为用户获取信息最直接的渠道之一。

    从数据中抽取隐含的信息或者知识，也就是价值挖掘，这方面的理论和技术还比较缺乏。
    一是缺乏成熟的数据挖掘建模方法和工具，经验对于挖掘出有价值信息的影响甚大，原始数据与隐含信息之间存在技术缺失，
    二是机器学习和深度学习技术面临应用问题。与大数据相结合，已经在诸如语音识别、图像识别、广告推荐和风险控制等场景中得以初步应用

** 计算模式
   不同的模式对时间敏感程度不同，批式计算模式、交互式计算模式、流计算模式、实时计算模式等

** 问题本质
   实际上，所谓大数据问题的本质应是数据的资产化和服务化，而挖掘数据的内在价值是研究大数据的最终目标。

** 起源于Google
   Google提出了一整套基于分布式并行集群方式的基础架构技术，利用软件的能力来处理集群中经常发生的节点失效问题。
   5个独立系统：
   分布式资源管理系统Borg
   Google文件系统（GFS）GFS是一个大型的分布式文件系统
   针对Google应用程序的特点提出的MapReduce 编程模式
   MapReduce通过“Map（映射）”和“Reduce（化简）”这样两个简单的概念来参加运算。用户只需要提供自己的Map 函数以及Reduce 函数就可以在集群上进行大规模的分布式数据处理
   与传统的分布式程序设计相比，MapReduce封装了并行处理、容错处理、本地化计算、负载均衡等细节

   分布式的锁机制Chubby
   Chubby是提供粗粒度锁服务的一个文件系统，它基于松耦合分布式文件系统，解决了分布式系统的一致性问题。

   大规模分布式数据库BigTable。
   关系数据库要求很强的一致性，很难将其扩展到很大的规模

** 论文
   Large-scale cluster management at Google with Borg
   https://pdos.csail.mit.edu/6.824/papers/borg.pdf
   SOSP：The Google File System
   https://static.googleusercontent.com/media/research.google.com/zh-CN//archive/gfs-sosp2003.pdf

   OSDI：MapReduce: Simplified Data Processing on Large Clusters
