* 做一个在线征婚交友的网站
** 草稿，思路
   首先，我自己设计，制作一个征婚交友的单页面。

   然后添加一个注册，登录，用户管理的功能，每个人都能自己生成此单页面。

   其实就是一个统一模板，然后填写信息，和模板合在一起，出页面。

   首页，就是注册，加展示会员信息，其他没有。
*** 3个角色
    我找女朋友，我找男朋友，我要做红娘。
   这里很关键的一个角色是：红娘。
** 痛点
   这些是后续需要解决的，其实方案很简单，实名制，实名认证好友关系。
   1. 骗子多
   2. 成本高
** 商业化
   后续考虑，
** 设计
   在设计之前，我们首先考虑要承载 *哪些功能* ，这些功能需要 *哪些信息* 。
   *最本质的东西是什么？*
   以最小的成本找到最合适（可比较）的对象。
   最小的成本包括：最短的时间，最少的金钱，最少的精力等。

   功能：
   1.

   信息：

** 参考
   核实女生信息，发布女生信息，然后让男生自行联系女生
   后续我们提高了核实女生信息的要求，尽量降低风险
   也提高了男生获取女生联系方式的门槛，尽量过滤一些没有诚意的男生。但仍然全部都是免费。

   男生希望发更多女生，希望能更方便地联系上女生，希望也公开发布男生（希望发男生的呼声其实喊了好几年）。
   潜水围观的女生也希望我们推送男生。已经发布信息的女生却要求能对发邮件的男生有所过滤，有些女生在参加面向对象后，收到的邮件非常多！以至于出现过，当天就要求撤下信息的女生。原因是邮件太多了，而且夹杂着各种不按照要求、仅仅是求认识的相亲邮件。

   相亲圈会核实部分资料，比起鱼龙混杂的相亲活动，这里相对更放心。
   学历、身高和年龄都有门槛，适合受过一定教育的单身年轻人。
   圈子比较私密，仅入圈的人可见。既能让更多人看到你，也不必完全公开。
   圈内公布自己的部分资料，相互可见。同时，支持按照城市、职业、兴趣爱好等搜索。

   入圈后可以报名参加搭伴公开相亲，
   我们认为被越多的单身异性知道和联系，脱单的概率越高。

   世纪佳缘，百合网和珍爱网

   觉得还是介绍靠谱，还是熟人靠谱些。
   不过哪里遇到骗子的几率都是一样~~大大滴高！
   未来属于陌陌和尚未出现的移动端APP
   不管怎样，所有的线上幻想最终都要转移到线下场景。

   世纪佳缘：在注册是填写的资料，最终会形成性格测试，还有征婚宣言，做的不错。

   https://www.zhihu.com/question/19969554
