* 需求就是问题 如何发现它
能够发现问题的人，一定是一个善于观察细节的人。
去年阿里的产品笔试题有一道是这样的：“说出生活中你认为体验不好的地方或者存在的问题，并说出自己的解决方案

这些都是问题，来源于身边，来源于生活，来源于产品
用户对产品的使用，其实也是一种消费行为，对用户消费心理的揣测可以帮助你更进一步接近用户的真实感受。
揣摩不如直接调查。

1.观察人们的行为
用户学习成本

除此之外，人性的“七宗罪”也可以很好的利用在发现需求这一环节上。例如，那些美女论坛，美女主播，晒事业线是利用了人性的色欲；一键下单，记住密码，多平台同步是利用了人性的懒惰；等级制度，vip特权，粉丝是利用人性的虚荣；团购，返现，抽奖是利用人性的贪婪等等
当这些需求被开发，被利用，人们只会高兴并且乐此不疲的接受他们，而不会遭到“反人类”的吐槽。
2.了解行业（流程逻辑）
3.降低某个目的的成本（时间，金钱）

多多关注国内外新的产品，
需求不能被创造，只能被发现？？

需求分析是互联网行业工作中最基本的能力。不只是产品经理，包括运营，市场，销售人员等都必须对需求有所了解，才能知道怎么去设计产品方案，运营用户，推广产品，最后把用户或流量转化成企业的收入。

使用场景
用户的问题
用户现有的解决方案，
可改进的方案

刚需，痛点，高频
抄创意，抄手法，抄套路

这个痛点是否可以转化成需求，还需要对这个痛点进行判断，有的人通过自身体验来判断，有的人通过数据分析，有的人通过用户调研，有的人通过拍脑袋判断，套路各异，花样很多。

[[http://www.woshipm.com/pmd/587068.html][需求分析01：如何发现用户需求？]]

http://www.woshipm.com/user-research/591064.html

如何梳理自己的想法，让想法变的清晰，可表达，易接受，

你要用你有限的资源尽快找到突破口和卖点，找到一个值得深耕的市场。
第一步要做的是，按照你们创业的想法用最快的方法做出一个非常粗糙的原型，

在初期用尽可能小的代价，发现产品的不足，错误和不足发现的越晚，改正的代价就越昂贵。
将自己作为苛刻的用户，看功能是否能接受。

第二步要做的是，找出具有创新意识愿意和你一起玩的几个非典型客户
这些客户是极其宝贵的，他们不仅会指出很多你没有考虑到的地方，帮你拓展思路，甚至会帮你打翻原有的设计！在这过程中你要注意观察这些极端客户的行为，不仅听他们说，还要琢磨他们为什么这么做。在这不基础上你可以发现很多新的需求，甚至产品的独到卖点，因为很多客户需求是客户自己都没有意识到的。


第三步，根据上面的需求分析，再反馈回来，做新的改进，并进一步完善产品
你下一步要做的是寻找更多客户验证需求，而不是debug。

第四步，这时可以寻找更广泛的友好测试用户群体，通过观察和倾听，了解更多的需求
们就曾经遇到过一个非常前瞻性的客户。他告诉我我们，我们提的方案他以前就考虑过，而他在用的竞争对手的方案有哪些缺点让他很痛苦——还有比这个更有价值的信息吗？

要尽早接触到客户，在产品还没有作出来的时候就要厚着脸皮见客户，和他讲你们的愿景和产品规划，谦虚地从他们那里学习，
讲到竞争对手，实际上他们是你最好的老师。他们已经做过一轮甚至几轮市场调查，用他们的产品前赴后继地趟出了一条血路。你一定要把市面上主要竞争对手的产品都拿来分析一下，把你自己放在用户的角度，看你能不能说服你自己，你的产品是有竞争力有卖点的。如果你自己都说服不了自己，那还是慎重考虑创业——别告诉我你没有竞争对手，客户没有替代方案！
