* 人才估值建模
** 草稿
   目前主要是针对技术人员的个人简历，进行评分，数字量化：
    1. 毕业院校，专业
    2. 公司，岗位，职责
    3. 项目经验，工作年限，负责项目，事务等。
    4. 开源贡献
    5. 个人作品
    6. 技能栈，及掌握程度
    7. 其他，比如一些籍贯，实习等。
    这个其实回到了我初衷的背面，不过这是第一步，会更加公平，透明。

    首先我们自己拿到一份简历之后，会看什么东西？重要的优先。
    基本情况：年龄（技术行业对年龄还是敏感），性别（男的肯定比女的有优势）
    学历：毕业院校，专业，文凭（本科，研究生等）
    工作情况：工作年限，什么公司，什么岗位，做过什么项目，担当什么职责。
    开源贡献：github活跃度，stackoverflow答题量等。
    技能栈：会哪些技术，掌握程度如何，哪些技术比较值钱，哪些技术不值钱。
    技能栈中的技术是否和项目中的匹配。

    能力：学习能力如何，沟通能力如何，写的这个简历水平如何。
    读书写作：读过多少技术方面的书籍，写过多少技术博客之类，还有影响力。

*** 处理流程
    想想整个的处理流程，首先用户在线填写一份简历，然后使用分词器等搞出关键字，
    然后针对各个维度进行分析。

** 维度评估系数
   系数，以1为标准，然后按照三六九等来分。超出爆表的，就是1.2等。
   北清复交 为1，还是1,0.99,0.9,0.85？刚开始就简单点：

   中国大学排名，然后按照排名切割，比如前10大高校是1，前20是0.9，
   然后有个模型，一直排到最后。
   按照ps的奖金模型，还是什么模型？我R，我发现很多东西都不是你学的东西。
   还有就是在搞一个完全陌生的东西的时候， *你会知道很多你不知道的。成长速度更快*
   *所以，先去干，后需要什么，学什么*
*** 学历维度
    985，211，一本，二本，三本，专科。。。
*** 技术栈维度
    技术评估维度，比如现在火热的spark，hadoop，kafka等，肯定比spring，mybatis要好，
    然后每个技术的掌握程度不同：了解，熟悉，熟练掌握，精通，commiter，甚至owner。

    这个还是比较好估的。
*** 公司维度
    在BAT，和普通公司的人肯定又不一样，这个估分怎么估？取平均值？
    还有即使都是BAT，曾经的岗位也不同。怎么评估？

    要用好平均值，不然差距太大，容易被骂傻逼。
*** 项目经验维度
    项目规模，项目持续时间，项目岗位（经理，架构，高级，初级开发，测试）
    然后每个技术做过的项目，上亿用户，上百万用户，几百人团队，几个人做的，。。
    这个也还行， *主要是调试参数么？？？让系统自己去调，这样就是人工智能了。*
    我看刚开始还是我自己人工调吧。
    这么少功能，简单的一个东西，要做出来，做好都不是那么容易的。

    项目里面模块也不同，有的人做CRMS，有的做算法，差距很大。
*** 表关系
    用户表，简历表（可能要用关联表）
