* 项目点子
  也就是一些自己想到的，想做的项目点子。还是得通过做东西学习，但是时间不太够啊。
** 虾米收藏音乐下载导出 废弃
** 人才估值，简历估值
   1. 简历估值
   2. 人才素质，特质，全方面估值
*** 研究拉钩，智联招聘等产品

** 做个自己用的爬虫机器人
   1. 可以得到感兴趣的动漫更新。
   2. 可以直接看感兴趣的网站的内容。
   3.
如何做一个爬虫

*** 研究今日头条等产品

看了上面几个项目点子，感觉爬虫是必不可少的技能项啊。

** 信息搜集
   给自己提一个需求，通过机器人将网站的最新文章拉下来，然后同步到我的手机阅读器上面。
   或者通过爬虫爬取精华文章，最热门的文章等。
** 决定
   现在想到的，最好的就是：个人知识搜索的东西了。
   也就是说做一个笔记，知识，网页，微信搜藏等的工具，
   然后进行联机，这样的好处是：

   0.对于自己的知识能够进行管理，整理
   1.不需要google这样的大工具，更加准确，而且资源效率更高
   2.可以组建一个强大的群体。

** 股票问答网
   好像可以搞
** 推荐网好像也可以搞
** 草稿
   首先从自身出发，从自己需要的功能，需求出发。

   比如我目前需要一个东西：取代掉书签。
   为什么？
   1.因为书签连接放进去就没用过，
   2.书签就是一个url，然后加上简单的备注信息
   3.url中的网页内容太多，我根本不需要那么多信息
   4.不是很好搜索，只能通过书签栏，搜索备注的信息

   观察市场上产品
   看看市场上是否有同类产品，比如pocket，剪藏等，是否满足需求

** 做一个征婚交友的网站
** 做一个组队开黑的网站
** 做一个大学生社交的网站
   file:2017-11-30-Dating-Profile-Website.org

** ComicGlass Server 【废弃】
   file://2018-03-14-Comic-Glass-Server.org

** 最热最火Hot
   将全网最热最火的东西聚集起来。
   最火的微博，最火的微信文章，最后的视频，图片等。

** 未完成的项目
   我应该来测试下绑定顶级域名有没撒问题，没有，搞定。
   之前有做过一个类似twitter的东西，还做过一个简历生成的东西。

   现在的问题是什么？网页该如何设计，

** 小说网站
   首先，我们下载下来的都是完整的单独的txt文件，然后找到其中的第几回，然后切割，组成相应的md文件。
   然后我们的URL定为：http://xx.com/jinyong/SDYXZ/1.html
   那么就是作家，作品名缩写，第几章，

   然后展览页，目录页就是： 大类/作者/作品名，点击之后就跳转到作品页面？

   主页提供搜索功能，xxxx，对啊，感觉可以做一个练练手啊。

   提供

   果然可以使用1万次加24小时阅读来规避。

*** 问题
    1. 根据文件名得到缩写，如射雕英雄传得到sdyxz
       https://www.kanunu8.com/wuxia/201102/1625/37041.html
       这个是努努的url感觉层级太深。

** 网赚项目
   1. 搭建小说网站（X）
   5. 搭建德州扑克资源站（这个应该可以，足够短平快）
      但是不适合上班做，适合放假，周末做。
   6. 求职简历聚合平台（这个不够短平快）
   7. 美女图片应用（这个也是不够短平快）
   8. 帮别人推广商品（必须有名气，有粉丝之后）
   9. 所有的网赚项目都进行尝试

   所以总的来说，应该是混成知乎大V，然后搞公众号，不停学习，做笔记。
   多答问题，增加公众号曝光度先。
   想想公众号的名字吧，
** 给页面做标注 这个有插件，但是用的人好像很少
