* Youtube下载工具开发
  首先是python的web框架，如何post form之类的example。
  然后后台调用youtube-dl下载，放到apache目录，多少分钟后删除。


  之后是如何推广？
** 工具里面重要的几个api
*** 下载指定格式
    youtube-dl -f best/mp4 Y6n5gdrvpvo
*** 获取url
    youtube-dl -g Y6n5gdrvpvo
*** 获取可下载列表
    youtube-dl -F Y6n5gdrvpvo
** 问题
   我发现在寻找bootstrap模板的时候涉及到用户的心理。

   功能1：直接黏贴一个url，得到界面，
*** 现在的问题是？？？
    1. 结果的布局有问题
    2. 为什么不直接用index.html渲染，还要用js来操作页面元素？

    逻辑流程有问题，原型有问题。
    第一，去掉前端显示url为null的情况，其他情况用search。
    null时候什么都不做， DONE
    第二，直接返回渲染的结果，最大也就网络传输的东西多一点，但是其实
    浏览器有缓存。影响不大。 DONE

    现在来解决排版的问题。

    我应该精通一种排版。


    OK，一个功能完成。
    现在来做搜索。
*** 搜索
    https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=25&q=%E5%A5%BD%E6%97%A5%E5%AD%90&key=AIzaSyASWhdK8_bAXBZVnCKthl4aXfzbAGNSCOQ

    https://www.googleapis.com/youtube/v3/videos?part=id%2C+snippet&id=Y6n5gdrvpvo&key=AIzaSyASWhdK8_bAXBZVnCKthl4aXfzbAGNSCOQ

    AIzaSyASWhdK8_bAXBZVnCKthl4aXfzbAGNSCOQ


    Y6n5gdrvpvo
    easy。

    现在要做的是？？？
    重点是搞出video和audio的url。

    现在有个问题就是太慢了。但是这是个致命的问题吗？不是，所以还是先功能吧。

    我这个分类是按照什么来分类？是关键东西吗？
    直接按照mp4,mp3,webem,3gp等就行了，感觉。

    后面如何组成对象？？
    应该单独用一个对象存储。

    格式，mp3,mp4等等
    xxp，240p等，
    url
    abr
    size
    如果你下载视频，肯定是下载质量最好的。

    那么音频了？
** 版权声明
   先来想想，怎么写版权

   使用本站服务默认表示认同本站的版权声明。

   所有解析出来的地址对应的音频，视频版权都归原作者，原网站所有，
   如果有任何

   请勿将下载后的音频，视频进行共享，复制，传播，或其他商业盈利性用途，
   但同时应遵守著作权法及其他相关法律的规定，不得侵犯原创者和相关权利人的合法权利。

   将音频，视频用做其他用途时，请征询原创者和相关权利人的许可。

   本站承诺服务器上不保存任何音频，视频等复制文件。
** SEO
   我这个东西的SEO
** 定位
   这个是非常重要的。还是把这个东西搞上去吧。
** 问题
   文章一行太长了，怎么弄？明显是缩小p的width，然后整体没有居中。


   先做一个支持很多网站的应用，然后在微信小程序里面加一个。
   然后搞个视频转换，gif，搞笑，恶俗的视频站，
** 搞笑网站
   搞笑视频，gif，图片，段子，相声等等。

   流量怎么办？盗链啊。
** 下载到vps并提供链接
   还是要放到这个项目的某个目录？先不要百度，想想。
