* 搭建一个小说网站
** 头脑风暴
   5W1H：WHAT,WHERE,WHEN,WHO,HOW
   要做一个什么样的东西，就是将书籍全部搬到网上去，可以在网上一章章的看书，比如类似algorithms这样，
   这个的核心需求是：需要在电脑边边看书，边学习，但是比看PDF要好，为嘛？
   1. 我们习惯了浏览网页
   2. 不需要下载，现在很多下载资源都没有了，看PDF还要相应的PDF软件，Google虽然可以直接打开，但是体验不好
   3. 网页更加开放
   4. 没有那种整本书的压迫感，一天只需要看一章，做一页的问题就行了


   我TM就是想搭建一个，而且我发现在搭建的过程学到了很多，并且即使这么简单的一个东西，我发现涉及到的东西远远超过我平时所学的。
   管它侵不侵权，我TM自己先练技术。

   1. 妈的，idea打开txt不能换行，但是用vim，记事本打开却能换行。
   2. md的换行规则和txt不一样，我还要重新搞

   用chrome直接打开可以换行，但是字体等很丑。
   这个自动换行是怎么实现的？<pre style="word-wrap: break-word; white-space: pre-wrap;">
   搞清楚HTML的这几个是撒含义。
   果然可以在上面直接加各种css属性，那么整个就简单了， *直接将txt转成html，但是依然要注意划分每章节。*

   上面有每个章节第一回，第一章之类的，所以可以搞定。

   java将pdf转txt，所有统一先转成txt？束口，就是将进入txt处理的东西，搞成一样的，在这个切面上截断，
   如果出了问题，那么也是在这个切面之前出的问题。

   但是整个网站该如何构建？其实就是树，

   ok，搞定，剩下的是将，比如射雕英雄传.txt按章节分成N个txt，然后和html合并成一个html文件。 DONE

   接下来就是构建整个网站，也就是树，定好URL，逻辑连接线路。 TODO
   把这个做了，蛋疼，就是目录页。还要添加上作品名字，作家名字，所属目录(WUXIA)，


   再接下来就是：写css样式，或者是将pdf，mobi等转txt， TODO

   再加一个就是：如何从百度网盘下载资料。TODO

   如何将一个域名解析到2个ip或者说一个固定ip负载均衡到2台机器上面。
   Github是有容量限制的，每个respository是1G。
   *我发现即使是这么简单的一个东西，都需要搞很多事情。*



   对，还要加上一章，下一章，
   我曹，对这个上一页，下一页，这个两边分别距离都搞不定，妈的。
** 现在还差什么？
   1. 一个主页
   2. 一个书籍目录介绍页
   3. 将所有文件转成html

   获取作品名，获取类别，获取作家名

   这个分段不像我想的那么容易啊。
   首页没想好有些什么？那就先搞目录吧

   如何判断一行非空字符串的前后是换行？来简化一下，不分章节，章节搞？
   现在要解决的最重要的问题是：分篇章，如何确定是章节的切割。

   为什么，JB这么简单的事情都搞不了？
   抹平差异，那么首先应该
是全部变成第一章这种，一个问题一个问题解决：
   1. 怎么保存为utf8
   2. 章节怎么切分？不切分行不行？太长了

   还有一种最笨最傻逼的方式，那就是自己读，读了，然后复制黏贴上去。
   妈的，为什么做这么简单的事情都这么多问题了？

   那么我们就这样做吧，能够切分的切分，不能切分的不切分，然后转HTML。


*** 奇思妙想
    可以做个开源的服务，任何人可以管理自己的电子书，通过程序转换成在线的html，然后就可以直接看了。
    还能添加搜索等功能，等等。
** 笔记
   pre表情是pre formatt文本。
   word-wrap:break-word是Allow long words to be able to break and wrap onto the next line:
   让很长的一个单词换行。
   white-space:pre-wrap
   有几种，主要是关注：是否保留空格，还是多个空格合并；是否换行，是必要时换行还是只有换行符才换行。

** 问题
*** 怎么将header和footer合并在一起？
    我先主要搞的是那种类似jekyll的组装形式，将header，footer，body等分开，怎么将他们合并在一起？
    本质上来说，其实还是写文件，就是用StringBuilder来搞，如果遇到一个<include header>这种就替换成header这个html里面的内容，

    css的命名怎么搞？不要喝html命名等重复就行，应该
    错误，我不应该这么搞，我最多也就3到4个不同的页面，完全可以直接复制黏贴，而不需要搞这么写模板语言，这大大增加了复杂度，
    而且让我的管理成本提高。

    评论最好自己写，然后和反馈之类的都保存到数据库中。
    *保持最简洁，这是设计原则。*

    因为很多东西都很少，所以直接用手动的就能解决。比如写死导航栏

    这个类也要重新搞下，应该是说有个txt处理类，有个HtmlRender类，有个PDF处理类，
    整个的过程是：
    给一个目录，然后判断是txt还是pdf，然后是pdf的先转成txt，然后调用txt处理类，
    处理完了，调用htmlRender类处理，（在htmlRender处理的时候，转章节html和目录html）

    然后还有作家作品页，整个网站作家页，然后保存category，并将category组成导航目录，
    但是其实应该手动写死。

    如果是txt，怎么处理？转换成chanpters？

    下午的重点是什么？ *那就是HTML页面的制作和百度网盘改如何下载。*

    还要了解广告联盟相关的东西，怎么搞？怎么转漏洞，去各种无效，自动点击。
    看来广告联盟这条路走不了。


    怎么每次都不能善始善终了？之前搞了太多一半的项目？

*** 格式 搞定
    草他大爷的，使用那撒搞了之后，全部成一行了。
    加上杠r杠n了，好多了，但是第一行的缩进没了。

    搞定了，他妈的，我想应该是这个StringBuilder的问题，就是那个delete(0,sb.length()-1)这个地方。
*** 中文数字转阿拉伯数字

*** 目录结构如何定？
    域名/作者/作品名/章节
*** 看小说的方式 （重点）
    1. 下载下来后观看
       下载什么样格式的了？txt，pdf，word等。
       为什么要下载了？为什么不直接网页上看了？
       下载下来之后就能在很多设备上看了，智能手机，kindle，mp4等。
       可以保存起来，如保存到网盘，自己电脑里面。
    每次打开之后直接到上次阅读的地方。
    可以传输，比如直接分享给朋友，

    下载的缺点：
    要找相应的资源；下载的速度可能很慢；
    下载下来的东西可能是错的，乱码的，有病毒的，不完整的。
    这些都要下载之后校对的，如果错了要重新找资源，同样也要再次校验。

    下载的文件格式：
    word的很少，不讨论，但是想想为撒，word的很少？因为word主要用于排版，办公的，
    而小说对于排版是不讲究的，只要每行不要太长，间距合适，段落清楚就行了。

    PDF和TXT的区别
     txt，关键点在通用，所有的都支持，但是很明显，除了最基本，简单的功能外，没有其他功能。

     PDF，有目录，可以打书签，可以做注释，甚至编辑，转换也可以，但是有些问题。
     还能幻灯片播放等，上下页，输入页号等。
     所以PDF很适合看书，就是平时那种用来学习的，做笔记的书籍。

     2. 网页直接观看
        无需下载，但是要打开网页，想想手机上打开网页浏览器的方式吧，多么麻烦，尴尬。
        每一章必须看完，这样下次比较好看下一章，如果没看完的话，下一次找起来就比较麻烦，
        除非此标签页一直开着。
        只能在电脑上看，但是一般在电脑前都是打游戏或者办公的。

     3. 手机直接观看
        手机直接看，有几种：1.自己下载电子书下来看；2.app书城里面看，但是可能要收费，
        再者资源太少，还要选择下载相应的App，比较麻烦。
     4. 不喜欢看，喜欢听（触感方式不同，看，听）



     直接下载下来看和网站上看，什么区别？看PDF，txt的和看网站上得撒区别？

    首先将网站整个设计好，必须要非常简洁，（不对，理论上来说应该是短平快，
    最快速度将网站搭建起来）

    *慢慢有一种产品的思维模式了。*
    几种文件格式的区别？

    不对，整个流程应该是：从百度网盘下载文件，解压缩，得到txt文件。
    在之后，通过程序得到N多md文件，使用jeklly自动生成静态的html文件，
*** 项目如何管理
    要学习了解一下项目管理的东西，主要是如何开始一个项目，项目的流程是什么，如何计划，分配工时等。
** 功能
   最好是提供阅读也提供阅读，下载，搜索的网站。

   然后添加一个页面，能够让人提交维权信息，自动删除。
   还有个就是能抓取网站的最新更新，然后同步过来，然后再24小时或者浏览1W次后自动删除。

   先搞几本金庸的武侠小说上去，
** 如何搞？
   内容现在已经有了，电子书，怎么搞成静态的html？
   还有很多其他信息，各种meta啊之类的，为什么一定要用jekyll的东西了？

   wordpress，
   没把问题想清楚，如果重新搞，要花多久？

   OK，可以了，就用Jekyll，自己比较熟悉，也是静态网站，wp还要搞数据库什么的。
*** 将txt文件转换成md文件

** 小说下载，在线观看站如何盈利？
   广告，

   mvn install:install-file -Dfile=PDFxStream.jar -DgroupId=com.snowtide -DartifactId=pdfxstream -Dversion=3.5.0 -Dpackaging=jar
