* 起名字服务
  从各大小说，网文，诗歌，等里面搞出人物名字，然后让人随机选，
   还可以给签名等。

   他妈的，这个感觉最有趣了，想想我都想笑啊

   名字来源，寓意，然后最好能配头像，签名。动态GIF等。
** 名字来源
   自己先在网上找
   1. 小说
   2. 神话，希腊，北欧神话
   3. 网文
   4. 各大已有的网站上的网友贡献的

   名字都要贴标签，比如狂拽酷等，犹豫，诗意等等。

** 用户交互
   用户交互的本质是让用户有参与感，荣誉感，自由感等等一系列的东西。
   以名字配名字
   显示下稀有程度，同名的人，也看了其他的姓名等。

   有几个选项框，让选择条件，然后点击按钮，生成姓名，然后可以分享出去。
   分享到微信，微博，QQ空间等等。
   名字的稀有度。
   以上帝之名，赐汝XX名字。
   莫某人又获得了什么名字。
*** 意见反馈
    这就是参与度之类的东西
** 具体实现
   1. 字数
      一字，两字，多字，用一个字来匹配名字
   2. 性别
      男女
   3. 类别
      武侠，言情等
   4. 标签
   5. 随机
   6. 以名匹配名字
   7. 以歌，图匹配名字？
   8. 从歌曲中获取名字
   9. 让网友自己提供
   10. 情侣名称，点击可以生成一男一女的
       类似什么南山南，北秋悲的。。
   用户绑定一下自己的社交账号，俅俅他。
*** 前端bootstrap，
*** 后端java，redis，mysql
    为什么要用redis，请求会很频繁吗？
    表结构，对象属性，
    还要学习下NLP的语义拆分。
**** 名字表
     名字代表撒意思，名字出自哪里，
     名字作为唯一键，
     名字还要统计下，比如某个名字，总共有多少人使用啊，哪里的IP之类的。
     是单独搞个域名还是用个人博客域名？这点不太清楚啊。
**** 标签表
     这是一个什么标签的名字，多少字的名字？
     select * from name where tag contains 两个字，狂拽酷

** 项目排期与任务分配规划
   第一期：只有名字，
   第二期：签名，solgan
   第三期：头像

*** 任务分配规划
    1. 先头脑风暴，多思考下，想象下用户场景
    2. 研究其他同类产品的优缺点
    3. 以最小可用化产品为目标，规划整个的路径，实现等。

    我发现就是做这么小的一个项目都要花非常多的时间，精力。
    但是却非常有趣，而且我自身一定要非常快的得到反馈，才能更好的改进。
** 推广
   1. SEO
   2. 去写论坛社区发帖子

** 盈利模式
   微信扫一下，一元钱？同理心，如果让你花一元钱来起个名字，你愿意吗？
   其实可以试试，他妈的谁知道了。打赏？
