* IDEA常见问题
4.读取不到config目录下配置文件
Edit Configurations–》Configuration–》Working directory，输入$MODULE_DIR$
或重新制定当前module所在路径
** 5.Idea中Maven怎么Debug
直接右键，Debug。
** 7.idea构建sbt项目(非常重要)
之前遇到的一个问题就是，IDEA一直自己下载sbt相关的依赖，jar包等。需要在这里配置。

-Dplay.version=2.4.11
-Dsbt.ivy.home=D:/sbt/.ivy2
-Dsbt.repository.config=D:/sbt/conf/repositories
** 8 .代码格式化
https://github.com/square/java-code-styles

** 9. 添加maven的编辑版本等
<properties>
  <maven.compiler.source>1.8</maven.compiler.source>
  <maven.compiler.target>1.8</maven.compiler.target>
</properties>

** 10.Gihub账号添加
直接在全局设置，DefaultSetting里面绑定账户和密码。
需要哪个skingit什么的？
** SVN集成
   idea和第三方的TortoiseSVN集成，有些问题，安装时需要勾选command，其次那个配置起来好像也有点问题

*** 方法：
    1. 下载sliksvn
    https://sliksvn.com/download/
    安装，配置环境变量（如果需要在CMD使用）

    2. idea中配置
    调出Settings->Version Control->Subversion->选择sliksvn所在目录。

    3. VCS->Enable Version Control Integration...->勾选Subversion，这样VCS的菜单会改变，
    所有SVN的操作这里都有。

*** 一些问题：
    之前的一些乌龟TouritSvn checkout下来的项目，在Idea中是无法比对的，需要重新在Idea中使用svn checkout下来并打开。

*** 参考资料
    http://www.cnblogs.com/yingsong/p/5097862.html

** idea构建maven多项目
   1. 新建空白标准的maven Project作为parent project，不要用Create from archetype。
   2. 创建Module，选择父依赖是parent project。

http://www.cnblogs.com/Brake/p/create_maven_multi_module_project_via_intellij_idea.html

** idea mybatis生成代码
   有两种方式，一种是直接使用插件，但是目前好像都下载不来。
   第二种是maven中添加maven依赖。
   1. 有个插件，先安装插件
   2. 在maven中添加
      <build>
  <finalName>xxx</finalName>
  <plugins>
    <plugin>
      <groupId>org.mybatis.generator</groupId>
      <artifactId>mybatis-generator-maven-plugin</artifactId>
      <version>1.3.2</version>
      <configuration>
        <verbose>true</verbose>
        <overwrite>true</overwrite>
      </configuration>
    </plugin>
  </plugins>
</build>

    *注意那个targetProject的值。写绝对路径？*

** 比较2个文件异同
  我曹，很强大啊，可以比对文件，文件夹，数据库对象。
  还能比较粘贴板和文件，
