计算机网络 谢希仁
15天看完，一天25页，但是这样算不太对。
一天应该要看90页。

先看第6，5，7章，重要的先看，麻痹的。
* 第1章 概述（理解）
网络是由若干节点和链接这些结点的链路组成。网络中的结点可以是计算机，集线器，交换机或路由器等。

网络和网络通过路由器链接形成互联网。

第一阶段是单个网络

第二阶段是三级结构的因特网。分为主干网，地区网和校园网。

第三阶段形成多层次ISP结构的因特网。

ISP Internet Service Provider 因特网服务提供商
NAP Network Access Point网络接入点

路由器 router是实现分组交换packet switching的关键，任务是转发收到的分组，这是网络核心部分最重要的功能。


电路交换：

建立链接（占用通信资源）-通话（一直占用）释放链接（归还资源，三个步骤的交换方式成为电路交换。然后电话于电话之间通过交换机来构成链接。
电路交换的一个重要特点就是通话的全部时间内，通话的两个用户始终占用端到端的通信资源。

分组交换采用存储转发技术，要发的整块数据成为报文，发送报文前，将教程报文切分一个个更小的等长数据段。然后在数据段前面加上必要的控制信息组成的头部（header），就构成了一个分组（packet）,也称为包、分组的头部称为包头。分组是在因特网传输的数据单元。首部非常重要，包含了诸如目的地址，原地址等信息，才能选择传输路径。

主机是用户进行信息处理的，并且和其他主机通过网络交换信息。

路有钱则是用来转发分组的，即进行分组交换的。路由器收到一个分组，先存储起来，检查头部，查找转发表，按照首部中的目的地址，找到合适的接口转发出去，把分组交给下一个路由器，直到达到最终的目的地。各个路由器之间必须经常彼此交换掌握的路由信息，一边创建和维持在路由器中的转发表，是的转发表能够在整个网络拓扑发送变化时及时更新。

采用存储转发的分组交换，实质上是采用了在数据通信的过程中断续或者动态分配传输宽带的策略。因为如果网络中的某些结点或者链路突然出故障，在个路与怄气中运行的路由选择协议能自动找到其他路径转发出去。因特网使用网状拓扑结构，提高可靠性和使用率。

网络性能的指标
1.速率
2.贷款

3.吞吐量
throughpu，单位时间内通过某网络的数数量
4.延时
发送时延是主机或者路由器发送数据帧所需要的时间，也就是从发送数据帧的第一个比特算起到最后一个比特发送完毕的时间
传播时延
是电磁波在信道中传播一定距离所话费的时间。
处理时延
排队时延


** 1.6
*** 1.6.2
    费用，质量，标准化，可靠性，可扩展和可升级性，易于管理和维护
** 1.7 网络体系结构
   *核心思想：分层。*
   分层将庞大而复杂的整体性问题，分解成若干较小的局部性问题。还可以复用。
   OSI网络是7层体系结构。
*** 1.7.2
    在网络中通行必须遵循一定的规则，规定了数据格式和同步问题。
    *网络协议：为进行网络中的数据交换而建立的规则，标准或约定，就是网络协议。*
    网络协议由3个要素组成：
    1.语法，数据与控制信息的结构或者格式
    2.语义，需要发出何种控制信息，完成何种动作，做出何种响应
    3.同步，事件实现顺序的详细说明

    分层的好处：
    1.各层之间是独立的
    通过接口调用服务，不需要知道复杂的具体实现；
    每层只实现独立的功能，处理较小不太复杂的问题，降低整体复杂度
    2.灵活性好
    接口服务关系不变，具体实现可变
    3.结构可分割
    像积木一样，各层都能分割开，采用最适合的技术实现。
    4.易于实现和维护
    只需要实现和维护特定层的功能，也即整体系统的子系统。
    5.促进标准化
    每层服务已明确说明。
    6.复用
    发送端几个高层会话能复一条用低层的连接，在接收端在进行高层会话奋勇。

    计算机网络的各层及其协议的集合，成为网络的体系结构。
*** 1.7.3
    OSI是7层；TCP/IP是4层；本书采用5层；
    *TCP/IP包含：应用层，运输层，网际层和网络接口层。*
    实质上讲，只有最上面3层（要精通）。
    图1-16

    本书的5层包括：
    1.应用层
    应用层协议有：HTTP,SMTP,FTP等。
    2.运输层（transport）
    运输层的任务：2个主机中进程之间的通信提供服务。
    运输层有复用和分用的功能。
    复用：多个应用层进程使用下面运输层服务，分用：运输层把收到信息交付给应用层。
    运输层协议有：
    传输控制协议TCP，面向连接，传输单位是报文段segment，可靠性交付
    用户数据报协议UDP，无连接，传输单位是datagram，用户数据报不保证可靠性，
    3.网络层
    网络层把运输层产生的报文段或用户数据报封装成分组或包packat，
    在TCP/IP体系中， *网络层使用IP协议* ，分组也称IP数据报。
    网络层还需要选择合适的路由。
    因特网的主要网络层协议是IP和多钟路由选择协议，因特网的网络层也叫网际层或者IP层。
    4.数据链路层
    链路：2个相邻节点之间，是点对点的，这称为链路，比如主机和路由器之间，2个路由器之间。
    2个主机之间的数据总数在一段一段的链路上传送的。
    数据链路层将网络层交下来的IP数据报组装车鞥帧（framing）。
    5.物理层
    传输单位比特，通过不同电压代表0和1。

    TCP/IP不一定是单指TCP和IP这两个具体协议，一般是互联网整个的TCP/IP协议族。
*** 1.7.5
    图1-21
* 第2章 物理层（了解）
** 数据通信
*** 2.2.1 模型

* 第3章 数据链路层（精通）
* 第4章 网层络（精通）
* 第5章 运输层（精通）
* 第6章 应用层（精通）
** 6.1 域名系统DNS
*** 6.1.1 概述
    之所以叫域名系统，是因为因特网中使用了许多的域（domain），域名结构中有很重要的点符号。
    在ARPANET时代，只有几百台计算机，使用一个文件，将主机名字和相应的IP地址对应起来，这就是HOST文件。
*** 6.1.2 域名结构
    mail.cctv.com
    mail三级域名；cctv二级域名；com顶级域名

    本地域名服务器：
    设置IP和DNS服务器的，那个地址就是设置的本地域名服务器地址。

    域名解析过程：
    要注意2点：
    PC作为DNS客户到本地域名服务器查询，没找到，本地域名服务器作为DNS客户，向根域名服务器查询，这是递归查询。
    根域名服务器告诉本地服务器去哪个顶级域名服务器查询，没找到，顶级域名服务器告诉本地服务器去哪个权限域名服务器查询，这是迭代。

    为提高DNS查询效率，减轻根域名服务器负荷，减少因特网上DNS查询报文数量，
    使用缓存机制，在大量域名服务器中保存最近查询过的域名以及从何处获得域名映射信息的记录。
** 6.2 文件传送协议FTP
   如何实现一个FTP？
*** 6.2.1 FTP概述
    FTP，File Transfer Protocol，有基于TCP的FTP和基于UDP的TFTP。
   不论是存取文件，还是修改文件，都只能先获得一个副本，然后在副本上操作，之后合并到原文件。
*** 6.2.2 FTP基本原理
    FTP服务器进程有2大部分：
    一个主进程，负责接收新的请求；
    若干从属进程，负责处理单个请求。

    FTP的客户和服务器之间要建立2个并行的TCP连接：控制连接和数据连接。
    网络文件系统NFS允许应用进程打开一个远地文件，并能在该文件的某个特定位置开始读写文件。
*** 6.2.3 TFTP
** 6.3 Telnet
   telnet是通过TCP连接注册到远程的另一台电脑上。
** 6.4 万维网WWW
   用户通过浏览器访问站点的过程，比如访问http://www.baidu.com/about.html
   1.浏览器分析，校验URL
   2.浏览器向DNS请求解析域名www.baidu.com的IP地址
   3.DNS返回域名对应的IP
   4.浏览器与服务器建立TCP连接，用上步获得的IP和80端口
   5.浏览器发送GET请求获取文件，GET /about.html
   6.服务器读取about.html文件成字节流，返回给浏览器
   7.浏览器接收字节流，组成about.html文件，然后用引擎渲染出html页面。
   8.释放TCP连接

   HTTP/1.0的缺点：每次请求一个文档就要两倍RTT的开销。
   一个RTT用于TCP，一个RTT用于请求和接收文档。

   HTTP/1.1使用了持续连接，也就是服务器发送响应后，并不马上释放掉连接，而是仍然保持一段时间内的可用性。也就是Keep-Alive参数。
*** 代理服务器
    代理服务器又称为万维网高速缓存，将最近的请求和响应暂存在本地磁盘。
    整个流程是：用户访问www.baidu.com/about.html，首先会经过代理服务器，
    看看是否刚才已经访问过，有缓存页面，有的话直接返回。
    优点：1.节省了大量带宽；2.减小服务器开销；3.降低延时。
*** HTTP报文结构
    图6-12
    HTTP报文主要由3部分组成
    1.开始行
    用于区分请求还是响应，在请求报文中的叫请求行（Request-line），
    在响应中叫状态行（Status-line）。CR和LF分别代表回车和换行。

    2.首部行
    用来说明浏览器，服务器或报文主体的一些信息。
    每行由键值对组成，以CRLF结束。最后必须要多一个CRLF来分开实体主体

    3.实体主体（entity body）
    应该就是HTTP Request POST请求的body和HTTP Response中的body？

    状态码
    都是三位数字，分为5大类，共33种。
    1xx 表示通知信息，如收到了，或正在处理
    2xx 表示成功
    3xx 表示重定向
    4xx 客户端的差错，比如资源找不到
    5xx 服务器差错，比如程序bug
*** 在服务器上保存用户信息
    HTTP是无状态的，但是能用Cookie保存用户信息。
    Cookie的工作原理和交互流程
    1.用户通过浏览器客户端访问网站W
    2.W为第一次访问的用户生成一个唯一的识别码ID，
    并在返回响应时，在首部字段中设置：Set-cookie:ID
    3.浏览器在收到响应后，就在它管理的Cookie文件中添加一行，
    网站名W和Set-cookie后的值ID，以对应起来。
    4.用户再次访问网站W，浏览器从Cookie文件中取出W对应的ID值，
    在HTTP请求的首部中添加：Cookie:ID。
    5.网站W的服务器端在接收到请求后，取出Cookie对应的ID值，
    然后根据ID查找到用户之前的保存信息，如浏览记录，购物车，用户名，密码等。
*** 6.4.4 万维网文档
    应增加一种机制，将浏览器发送的数据传送给后台应用程序，
    然后服务器能解释这个应用程序员的输出，并返回HTML文档给浏览器。

    这个就是CGI（common gateway interface）通用网关接口。
    CGI是一种标准，定义了动态文档应如何创建，输入数据应如何提供给后台程序，
    后台输出结果应如何使用。

    脚本指的是一个程序，它被解释程序而不是计算机的cpu来处理，解释。
    对一些有限功能的小程序是很合适的。
** 6.5 电子邮件
   MIME：通用因特网邮件扩展
** 6.6 DHCP动态主机配置协议
   连接到互联网的计算机需要配置以下协议：
   IP地址
   子网掩码
   默认路由器IP地址
   域名服务器IP地址
*** DHCP工作流程
   1.需要IP地址的主机启动，并向整个网络发送发现报文
   2.所有在此网络中的机器都会接受到，但是只有DHCP能响应
   3.DHCP服务器先查询此计算机的配置信息，找到就返回，没找到就从IP地址池中获取并分配一个。
** 6.7 SNMP简单网路管理协议

* 第7章 网络安全（理解）

* 第8章 因特网上的音频/视频服务（了解）
* 第9章 无线络网（了解）
* 第10章 下一代因特网（了解）
