* 招股说明书原来可以这么玩 笔记
  学习招股说明书是了解中国商业原生态最快速也最便捷的方式
  商业生态，风险因素以及资金投向

  风险因素没有讲，公司发展的前三大风险分别是什么

  男一号是“业务与技术”，男二号是“股东结构”，而女主角“风险因素”是他们心中永远的痛，
  他们之间的爱恨离愁的故事都被路人甲“财务会计信息”记录地清清楚楚

** LROE法则
   最后总结出阅读招股说明书的
   LROE 法则。L 是 Logic，代表的是逻辑思维；R 是 Risk，代表的是风险思维；O 是
   Operation，代表的是运营思维；E 是 Estimation，代表的是估值思维。

   这四点是招股说明书的共性，因此 LROE 法则是阅读招股说明书的心法

   如何解读封面的内容，如何分析企业家背景
对公司未来发展的影响等等

任何人都可以写
“招股说明书”，因为招股说明书只是一种描述事物的一种文体格式。
我们可以给
自己创业企业写“招股说明书”，也能给身边的社团写“招股说明书”，甚至能给某
位正在寻觅对象的朋友写“招股说明书”。

** 导言
*** what
    从招股说明书的定义来说，
股份有限公司的招股说明书是供社会公众了解发起人和将要设立公司的情况，说
明公司股份发行的有关事宜，指导公众购买公司股份的规范性文件。

他们把招股说明书作为认识商业原生态的资料，学习商业形态，
揣摩招股说明书不同使用者的心理，认识不同行业的特征。

反射原理，揣摩心理。

因此拟上市公司会在招股说明书里尽可能地美化自己，包装自己，尽量展示其优点，
尽量淡化其缺点，甚至掩盖自己的缺点。

对于那些把招股说明书作为认识商业原生态的资料的人而言，招股说明书就
是一个百宝箱，里面既有行业信息情况，又有公司的财务信息，还有公司发展历
程中各种重大事件的披露，并且还能通过招股说明书揣摩各路参与者的心态和意
图

拟上市
公司往往是相关细分行业中领头羊，基本上属于最高生产力的代表，因此通过它
的企业发展的重大事项不仅仅可以了解公司自己的发展脉络，甚至可以了解到相
关行业的发展脉络，比如中石油的发展史就是蕴含这中国石油工业的发展史，它
利润的衰退意味着行业发展放缓或者市场竞争变得激烈，它大规模的海外重组并
购，意味着中国石油工业开始国际化进程。另外，那些把招股说明书作为认识商
业原生态的资料的人还可以假设自己扮演着不同的角色，比如拟上市公司本身，
证券公司，投资人等，从不同的角度来揣摩各方的意图，比如站在拟上市公司的
角度来思考为什么它会把产品与技术这么写，再比如站在投资人的角度来思考面
对这样的财务数据我是否愿意投资这家公司，如果投资的话我愿意出多少钱持有
多少股票。
