* 100$Startup
Business, like traveling, is often improved by starting poor. You are forced to improvise, innovate, and stay close to reality. You can’t buy solutions,
so you have to create your own. Suddenly you have the first part of success—something of value. I got all this from  The $100 Startup , which is  full
of practical advice about inventing your own livelihood . I’ve done a handful of $100 startups myself, several of which I later sold.  Chris
Guillebeau knows what he is talking about. Listen to this book!

You can’t grow a thriving business on wishes and dreams. You need the kind of nuts-and-bolts wisdom that only comes from hard-earned
experience.

1.start today
2.deposit money tomorrow

 I watched what other people had done and tried to *reverse-engineer* their success.
reverse-engineer

making something and selling it
starting with a list of what I wanted to do

value is created when a person makes something useful and shares it with the world


 In fact, the more you understand how your skills and knowledge can be useful to others, the more your
odds of success will go up
