* 台湾东线
** 景点
  台北故宫博物馆，101大楼，七星潭，中正纪念堂，鹅銮鼻，清水断崖，太鲁阁公园，九份，
  阿里山，日月潭，海洋博物馆，清境农场，西子湾，花东纵谷，

  清水断崖运输：
  1.由花莲火车站搭往崇德方向的花莲客运，于崇德下车。
  2.搭北回线铁路，于和仁、崇德下车，可分抵清水断崖北、南端。
  七星潭交通
  1.在花莲火车站搭乘花莲客运105线班车，在七星潭站下车，车程约50分钟，下车步行约15分钟可到七星潭景区。
  花莲火车站发车时间：07:20、09:30、11:20、15:30；七星潭发车时间：08:10、10:20、12:10、17:10。
  七星潭风景区非常大，建议租车游览，平日100元新台币/天
** 路线
   台北（台铁）瑞芳（平溪线）九份（一日游中巴）花莲（一日游拼车）垦丁（拼车）高雄（台铁）台南（高铁）桃园
   单独一日游拼车：花东纵谷、垦丁。

*** 10.2号D1 台北 宿台北
    桃园到台北，巴士，1到1.5小时，NT110，计程车太贵，
    高铁要先到高铁桃园站，时间20分钟，但是做公交车要花时间。
    中正纪念堂，掐点观看礼兵换岗和降旗仪式

    住斯格加台湾, 台北, 中山區林森北路, 72號
*** 10.3号D2 瑞芳，九份 宿九份
    坐台铁，买平溪，深奥双支线一日游券，
    做小火车到最后一站菁桐，十分站人非常多。再从菁桐步行到平溪上车返回。

    赶回瑞芳火车站，到九份
*** 10.4号 D3 九份，苏花公路到花莲，宿花莲
*** 10.5 D4 花莲 宿花莲，花东纵谷一日游
    出站后问附近店铺的价格一般在150台币左右。如果坐大巴去七星潭和清水断崖的话一定会错过路边的美景，但说实话从花莲骑行到清水断崖距离不短，
*** 10.6 D5 花莲到垦丁，宿垦丁
*** 10.7 D6 垦丁 宿垦丁  垦丁一日游
    需要包车，第一站鹅銮鼻公园，第二站，最南点，第三站风吹沙（蛮漂亮）
    4菜加橘子冰，一共软民币100出头，新鲜三文鱼刺身厚片（30片）只要软民币40！
*** 10.8 D7 垦丁到高雄到台南 宿台南？
    高雄西子湾，西子湾捷运出口即是高雄旅游局主办的文化公车环游线路的起点，依次经过武德殿、打狗领事馆、代天宫、鼓山鱼市场、渔人码头、驳二艺术特区、历史博物馆。
    在高雄玩的话就租辆自行车（很便宜80NTS的样子）；去绿岛和和垦丁就租辆电动车（400~800NTS），绝对大大提升旅游品质。
    早上租车去旗津岛骑行，中午在岛上吃海鲜，下午逛一下驳二文创艺术园(类似于北京的798或者武汉的汉阳造)，傍晚看西子湾的夕阳，晚上在爱河边散散步喝喝咖啡，晚上住在85大楼（高雄的101，但住一晚的价格真的很便宜）。
*** 10.9 D8 回家
    台南（经高铁）→桃园机场
** 吃的
   1.台北
   铁蛋、阿给、郑记猪脚饭
   2.九份
   芋圆
   3.高雄
   旗津岛海鲜
   4.台南
   虾卷、棺材板、花枝煎、鱼头菜、黑豆豆花、豆奶鸡、鳝鱼意面、石斑鱼汤
   5.台东
   释迦
   6.垦丁
   莲雾、海鲜烩饭
   7.彰化
   肉圆、花枝羹、虾猴酥
** Tips
   钱：用华夏卡，取现
   通信：手机上网，桃园机场办理
   机票过关：拿台湾通行证+台湾签注，入台证，和机票确认单，过关。

   记得办个青壮卡，机场咨询台办理
   还有一个itaiwan的wifi审核，到机场继续审核
