* 如何订机票最划算
** 提前订机票
  提前53天最便宜
  起飞前的周二机票可能最便宜
  国内航班提前30~60天预定可能最便宜
  国际航班提前170天左右预定，也就是提前5到6个月。
  周四往周一返，可能是国际航空最便宜组合，比其他时间段要便宜20%。

  淡季的票很低，4、11月份是淡季

** 利用比价网站
   天巡网 - 廉价航空、国际机票、特价机票查询预订、Skyscanner中国
   https://www.tianxun.com/

   阿里旅行订机票最便宜，适合官网秒杀活动。
   时候为了更好的获取移动端用户，APP的价格会比网页版更便宜

** 一定看官网
   不看官网，很可能错过最优价格保障。最优价格保障也就是说，在第三方订票网站买的比官网便宜
   特价机票和优惠活动都会在航空公司官网第一时间放出来，这是其他代理网站所没有的。

   网站可以关注E旅行：机票 - E旅行网http://www.elvxing.net/jipiao.php
   此网站不仅会集中更新机票优惠活动，还能看到近一个月内此航线价格浮动

   最推荐拨打航空公司官网电话进行人工预定。
** 共享航班
   如果你确认出发时间和目的地，并知道自己最喜欢哪个航班，那么「共享航班」是个享受低价的好机会。

** 比价APP
   「即刻」APP的「航空优惠」、「航空物语精选」专栏，集中更新各大特价机票活动，记得打开推送提醒！
   机票全网比价」APP，可以同时比较携程、去哪儿、酷讯三大比价网站的价格，非常方便。

** 其他建议
   Easyjet有一种「灵活票价」（ Flexifares）允许你的出行时间4周的灵活度，而不需要额外付费。
   廉价航空保险太贵，自行购买更便宜。穷游网：【穷游网】旅游保险

** 会员日
   各大航空公司都有自己的会员日，这一天机票价格几乎能刷到全网最低。
   海南航空的会员日是每月8日；
   东方航空是每月18日；
   春秋航空是每月27日；
   南方航空是每月28日；
   国航是「每月同月数日」，即「1月1日，2月2日」，以此类推

** 航空公司
   亚航几乎是所有人在东南亚旅行中最常用的航空公司。从深圳、澳门、香港、广州、海口、杭州和天津出发，以吉隆坡和曼谷两地为主要中转地，
   春秋：国内最大的本土廉价航空公司

   我草，这两个站碉堡了：
   http://www.journey.ca/category/china/

   http://www.meethk.com/
