* 台湾东线计划
  台湾全部景点：
  台北故宫博物馆，101大楼，七星潭，中正纪念堂，鹅銮鼻，清水断崖，太鲁阁公园，九份，
  阿里山，日月潭，海洋博物馆，清境农场，西子湾，花东纵谷，

  清水断崖指的是苏花公路和仁至崇德之间，长约12公里的路段。
  大众运输：
  1.由花莲火车站搭往崇德方向的花莲客运，于崇德下车。
  2.搭北回线铁路，于和仁、崇德下车，可分抵清水断崖北、南端。


  七星潭是花莲县唯一的县级风景区，风景区范围从海边延伸到七星潭社区，邻近太鲁阁公园、东海岸和花东纵谷国家风景区，七星潭已成为花莲县内最佳的风景区
  1.在花莲火车站搭乘花莲客运105线班车，在七星潭站下车，车程约50分钟，下车步行约15分钟可到七星潭景区。花莲火车站发车时间：07:20、09:30、11:20、15:30；七星潭发车时间：08:10、10:20、12:10、17:10。
  七星潭风景区非常大，建议租车游览，平日100元新台币/天

** 路线
   台北（台铁）瑞芳（平溪线）九份（一日游中巴）花莲（一日游拼车）垦丁（拼车）高雄（台铁）台南（高铁）桃园
   单独一日游拼车：花东纵谷、垦丁。
   一日游统统淘宝搞定，8折台铁票和65折高铁早鸟票也由淘宝搞定，入台证提前1月拍蚂蜂窝特价，实惠，基本没什么周折。

*** D1 台北
   中正纪念堂，掐点观看礼兵换岗和降旗仪式
*** D2 瑞芳，九份
    坐台铁，买平溪，深奥双支线一日游券，
    做小火车到最后一站菁桐，十分站人非常多。再从菁桐步行到平溪上车返回。

    赶回瑞芳火车站，到九份
*** D3 九份，苏花公路

*** D4 花莲
    booking上订的美丽晨曦民宿
    因为带着娃，感觉去太鲁阁太累，所以此次选择了花东纵谷线——鲤鱼潭、云山水生态园、林田山、瑞穗牧场。
*** D5 花莲到垦丁

*** D6 垦丁
    需要包车，第一站鹅銮鼻公园，第二站，最南点，第三站风吹沙（蛮漂亮）
    4菜加橘子冰，一共软民币100出头，新鲜三文鱼刺身厚片（30片）只要软民币40！
    下一站，猫鼻头、核电站出海口、白沙湾海滩

*** D7 垦丁到高雄到台南
    高雄西子湾，西子湾捷运出口即是高雄旅游局主办的文化公车环游线路的起点，依次经过武德殿、打狗领事馆、代天宫、鼓山鱼市场、渔人码头、驳二艺术特区、历史博物馆，整条线路票价成人才30新台币

*** D8 回家
    台南（经高铁）→桃园机场
