* 贵州旅游攻略
** 必去景点
   我个人经验来说，必须要去小七孔和黄果树瀑布，特别是第二个景点下半段。
** 我的行程
*** DAY 1
    深圳高铁到广州，然后广州高铁到都匀。到了都匀之后，做高铁1路专线到都匀东汽车总站，
    做大巴从都匀到荔波，这个车最晚到18：30，每半个小时一班车。
*** DAY 2
    在美食街旁边等着拦车，到小七孔，30分钟（也可以去汽车站，但要走段路）。小七孔一般游玩5个小时。
    小七孔完了，可以去大七孔。但是我非常不建议去，因为门票50元，1个小时玩，一个小时返回，就完了。
    结束后，在下车的地方等车回都匀县城。这里推荐家吃饭的就是荔之味饭馆。
*** DAY 3
    去荔波县汽车站（只有一个），就是都匀坐车过来下的那个汽车站。坐大巴去凯里，要3，4个小时。
    然后凯里做大巴去西江。我住的是藏鼓人家，在山顶上，比较安静，但是要爬个小山头，个人感觉还好。

    西江千户苗寨就是黄昏时，华灯初上的那会非常漂亮，其他的一般般。商业气息，性质非常浓重，和凤凰
    古镇差不多，但是夜景，还有白天逛逛的感觉没凤凰漂亮。去过凤凰的，感觉可以不去西江了。

    强烈建议将西江换成荔波的茂兰，特别是喜欢山水大于所谓“古镇”的人。
*** DAY 4
    早上睡个好觉，看看西江的早晨，中午看个表演出来（我没看），然后坐大巴回凯里（就在售票点旁边）。
    然后凯里汽车站出门坐公汽去火车站，做火车去镇远。

    这里我也得说说，镇远也是"古镇"，有夜景，有青龙洞古建筑群，还有铁溪，舞阳河，高挂河。个人感觉的话，
    古镇都那样，反正我以后不怎么想去了。铁溪适合周末去走走，特意去不划算，舞阳河和高挂河应该不错，但是
    船票什么的蛮贵，而且要单独花一天时间游玩。所以，你们可以考虑下。
*** DAY 5
    上午游玩铁溪，4个小时，总共来回走路8公里（妹子们甚行），有一条比较漂亮的小溪，最后有个龙潭，不下雨
    的时候是漂亮的紫蓝色，下雨后，和小七孔一样的青绿色，没什么特别。
    反正我走了4，5公里后，看到龙潭，大呼上当。

    中午去汽车站，坐车到安顺。车票一定要记得提前预购，一定。因为票非常紧张。
    到安顺，我是住在火车站旁边的市西路的七天，服务不错，非常安静，旁边还有个7好馆湘菜，
    味道中规中矩，稍好一点。不过已经是这几天我吃到最可口的了。

*** DAY 6
    早上起来做公汽到安顺东部汽车站，半个多小时。做专列大巴到黄果树瀑布，45分钟。到黄果树瀑布，记得不要随便买东西，
    第一个景点完了后的上车点，有老太婆卖桑葚，尼玛，一个纸碗下面塞得全部是荷花叶。

    黄果树要记住的是第二个景点，也就是数生步后面到的高老庄，还有下半段景点，不要从卖水果和农副产品的一条街走出去了。
    要从里面商店横穿过去。下半段景点非常漂亮，特别是那条河。

    黄果树瀑布慢慢玩，早上10点到，晚上18点出去，然后坐车回安顺。
*** DAY 7
    安顺坐火车去织金县，不要做汽车，汽车要4个小时，火车就一个半小时。到了火车站，有车直接到织金洞，10块一人。
    织金县现在在修路，车程非常的不好，很颠簸。

    织金洞非常的大，也非常的壮观，可以看各种奇形怪状的钟乳石和柱子。记得最好穿2件裤子，一定要批件外套。
    里面阴寒之气不是一般般的，而且全程要走2.5到3个小时，2千多个台阶。

    游完之后，坐车会织金县，做大巴会贵阳，因为火车只有几班，最晚的一般18点多，倒数第二班13点多。
*** DAY 8
    可以赶着去花溪逛逛，或者不想赶就去黔灵山（距离高铁站较近），下午坐动车会广州，5个多小时，然后高铁到深圳。
