* 台湾游记
  关键字：台湾，游记，攻略，
  描述：

国庆八天假期过去了，这次去了台湾，现在来记点流水账。

我的行程是从深圳到香港做飞机到台湾，因为香港的机票非常便宜，接近内地深圳直飞机票的一半。
但是过关的时候，不得不说非常的坑爹，这也是我第一次通过机票过关，以前都是用港澳通行证，或者自助过关。

尼玛，排了N久的长队，到了检察员哪里，居然要我回去填一个过境单子，相当的坑爹啊，填完单子之后继续排队，
还好来的早，很快就拍到了。

有一点更肯爹的是：国庆期间，要提前3个小时接驳，所以最早的一班蛇口到香港国际机场的船不让做，没办法，提前到香港住了一晚。
花了老子500多，而且住宿是相当的差，你们以后顶住宿千万不要去青衣那边，临近港口，非常的吵。

首先是到的桃园机场，然后做大巴去的台北。不知道怎么说，反正遇到的都是非常坑爹的事情，我的iphone4s，中国电信定制机，无法办理台湾的手机号和网络。
好吧，8天，我就完全无网络的情况下，游台湾。

台北住的斯格加旅店，强烈推荐。就是找了我很久时间，从国宾大饭店下了后，到处问人，因为我没手机网络，无法google map等。
后面去7-11办理了那个台湾本地，所有网络畅通使用的那个卡。才知道什么很nice，很耐心的台湾人。

我办理的这个卡，需要各种身份证，手续等等，然后去操作那个机器激活，然后那个年纪应该蛮大的老太婆，就一直在哪里耐心的操作。
只要350台币，不到100人民币，这么耐心的操作我还是第一次见。

更牛逼的是，我这个卡后续还是不能用，因为她告诉我是要2个小时左右发激活短信过来的，然后我大晚上找到她们那家店，成功的办理了退款。
简直不敢相信，反正当时我想的就是能弄好就弄好，不能弄好，无法退款也没办法。

第二天一大早就去了，瑞芳（这个坑爹的行程，尼玛我都网上抄的，但是不得不说，台湾真没撒好玩的）。
先做捷运（台湾地铁），去台北车站，然后换乘火车，（记得去柜台办理，因为自助机上，瑞芳终点站不显示）

到了瑞芳地铁，买平溪线一日游的票，然后就是很多小火车，火车铁轨，就是电影《那些年追过的女孩》中的地点，可以放天灯，摆ｐｏｓｅ。
反正就是各种ｓｈｏｗ恩爱，我都说了台湾适合那种高中，大学情侣来，还有那些喜欢萌物的小清新。
反正我是一项都不符合，而且要景色美撒景色看，要城市建筑，这边也实在一般般。

平溪线玩了之后，原车返回到瑞芳站，出门坐公车去九份。
九份就是宫崎骏，千与千寻中的汤屋的原型，也是电影悲情城市的拍摄地（没看过，别怂我），就是依山而建的小房子，但是前面居然联条河和江都没看到。
有很多灯笼，夜景一般般，很多棒子和鬼子在这里，都堵着。

九份看完了，回瑞芳市区，住金色小站，老板还是很ｎｉｃｅ的。住宿还行吧。

第三天一大早，从瑞芳火车站做火车到花莲，下了，就去找住宿，小羊房，真是绕的，实在没办法，去了７－１１找人问，刚好又碰到一个大妈。
她也是开名宿的，然后聊着聊着就准备宅我过去，他们都开摩托车。

放下包，都下午２点多了，直接去了七星潭，天气是阴天（反正国庆台湾天气都不好，即使好，我觉得。。）。就在海边吹吹风，然后看
中国人在台湾，各种摆ｐｏｓｅ，犯二。

看了会，回去了，那个台湾好行的车，尼玛等的我发狂，最少有１个半小时。在中国旅游，景区内随时有车，都是随到随走的，只有一宗情况：
就是人太多，排队的太长，那你就等着后面慢慢上，但是也不用等车啊。所以，看来台湾的旅游业是相当的不发达。

第三天晚上，完全是对台湾的景点绝望了，本准备找个地方看一天的，但是第四条早上起来，想了想，反正都来了，到处看看吧。
因为错过了，不能订到淘宝99的一日游，太鲁阁，清水断崖，七星潭，也就是这3个景点，所以我就自己打车去了太鲁阁。

哎，来了又后悔来了。晚上在名宿上网，看到了一句：台湾，不来，会遗憾一辈子；来了，会后悔一辈子；真是他妈太经典了。
这
这让我想起了，台湾最美的风景是人，其实也可以这么理解：台湾的风景都不美。。。。

哎，去太鲁阁转了一圈，到中午了，然后就回来了，会来后，真不知道去哪里。
然后好像是洗了个澡，然后外面搞点吃的，就回去睡觉去了。

第五天，一大早就走了，淘宝报的团，拼车从花莲到垦丁，然后走的花动宗谷先，本来一遍遍期待，却是一遍遍失望啊。
就是去了勃朗大道，（其实就是大片稻田，然后中间有一条大柏油马路），坐在那个大树下乘凉还真是的确不错，但是要说景色，感觉一斑斑。

那个暮穗农场的乳酪蛮好吃的，包子一班，就是较软，一点奶油味都没。
池上便当，还可以，但是用料不怎么样，不过本身也实惠，才80NTS，饭的口感有点特别，还蛮好吃。

晚上7点多到的垦丁大街，下来后，就去照吃的，问青旅老板，说是垦丁大街，然后走过去一逛。
感觉和失灵夜市差不多，稍微有兴趣的，都是拍的老长的队伍，算了，会来后，去青旅对面的7-11吃了个快餐便当。

感觉还能吃吧，反正至少是比我第一天台北士林夜市上吃的东西要好吃。

第六天，报了淘宝的垦丁一日游，（因为垦丁太大，景点要包车，一个人保不齐，就平团了），不得不说，天公不作美啊。
早上就是暴雨，然后8点半的车等到10点半了。。。本来就没撒兴致，这样一搞更恼怒了。直接找淘宝的，要退货，一直没得到回复。
然后车来了，就随便上吧，好在，导游司机蛮风趣，而且有3个妹子陪我一个汉子，还是蛮幸福的。
然后就是各种别人玩烂了的景点，什么鹅銮鼻啊，什么猫鼻头啊，什么灯台啊之类的，景点倒是多，但是。。。。
而且每个景点还要收费，60，30的收，虽然就几块钱，但是感觉特不厚道，本身就是一些天然景观，现在台湾人也变了。

一天就这样，到出走走婷婷，说说笑话，聊天中过了。

第7天，做的大巴到高雄，价格比快线贵，而且尼玛，居然到的时间还要晚半个小时，这个巴士到处接人，以后大家要记住了。
到高雄，线找住宿，我居然从美丽岛站，一直走，走了好几条街，最后才发现，原来到了三多上商圈，整整的走了2站地铁。。。
没网络，说起来都是泪啊，我还在用我的iphone4s。

第八天，就要会来了，本来有一上午的时间的，但是实在不知道去哪里，所以就有了，你现在看到的这篇游记。
坑爹啊，终于马上要回去了，会到祖国的怀抱。
