* 国庆旅游计划
  哪里人少

  哪里好玩，便宜

  https://www.douban.com/group/topic/52807568/

  决定去台湾

  去台湾要办理哪些东西？

  深圳 香港飞台湾注意什么？
** 深圳从香港飞台湾的问题
   1.入境香港可以用港澳通行证，离境时给他，证明离开香港，用完一次签证。
   在香港到坐飞机去台湾，这中间不能超过7天。
   2.也可以不用港澳通行证，用大通证和入台证就行，但是入境香港时要填卡片，
   个人信息和航班信息，但不查机票。

** 大陆居民台湾签证
   自由行入台证的全称叫做台湾入境许可证，区别于我们跟团去台湾所需要办理的大陆居民往来台湾通行证。
   台湾通行证、G签（本人去出入境大厅办）以及入台证（代理机构办）。
*** 通行证和G签
    1.材料：身份证原件+复印件（正反面都在同一面A4上），户口本原件和复印件（户主页，本人页都复印），两张两寸近期白底彩照
    2.时长：首次10个工作日，再次是7个工作日。
    G签和港澳通行证上的签注是一样的。
*** 入台证
    办理好通行证和G签后，就可以去找有资质的旅行社代理办入台证啦。
    入台证分：单词和一年多次。
    单次：耗时4-5个工作日，有效期3个月内，逗留15天。
    一年多次：一年内无限次往返，每次逗留15天。

    在职人员需要以下资料：
    大陆居民往来台湾通行证
    台湾个人旅游签注(G签)
    身份证
    户口本
    2寸照片
    紧急联系人身份证、户口本(紧急联系人的页面)
    财力证明（三选一）
    人民币5W一个月以上存款
    年收入12.5W在职收入证明，入职一年以上
    信用卡金卡及以上，正反面扫描件

** 路线
*** 景点
    台北，九份，花莲，垦丁，高雄，阿里山和日月潭，台中。
    我选择台北-日月潭-垦丁-花莲。
   16天，西部交通便利。
   D1.先去台北，
   D2.中正纪念堂和士林官邸，下午到台北故宫博物院
   D3
   提前三个月订便宜一半
** 交通
   台湾高铁：http://www.thsrc.com.tw
   提前有早鸟票。
   台湾台铁：http://railway.hinet.net/
   慢，便宜，玩台湾东线又不包车的话，靠它。
   台湾捷运捷运也就是咱国内的地铁，只有台北和高雄有，基本都是两三分钟一站地。
   这里就得说悠游卡，一定要办，比单买票快并且实用，也可以说它就是一卡通
** 住宿
   http://www.fun-taiwan.com/
   http://okgo.tw/
   http://cingjing.com.tw
   http://www.taipeibackpackers.com/
   booking，携程等
** tips
   准备2张卡，一张VISI或MASTER，一张银联。带着人民币在台湾换台币划算。
   悠游卡，200台币，退押金180。
   高铁只有西部有，最早提前28天买，24小时可订票。但是价格高。
   台湾好行大巴：

蛇口到香港最早是07:45,50分钟一班，40分钟提前换票。

一班耗时40分钟，机票是09:45的，提前一个小时是08:45，
就是所8点的船。

而且我们计划走的路线是北到南或者南到北，如果在台北进出，浪费时间还要花钱买高铁票从高雄回到台北。
