* 2022-04-27 每日任务
** 弄清楚SSO登录逻辑
** 弄清楚查询商家，订单的逻辑

那个nacos连接本地还是出错啊，

** 重点
一个auth服务，一个sso登录服务，这两弄清楚
还有一个system服务，xxjob服务，
sentinel怎么实现的，

还是要将auth和sso弄清楚，

** 供应链金融
B2B平台天然具有企业的交易数据、物流信息和资金数据等，更容易对供应链上下游企业进行增信。
这个模式的典型代表如上海钢联、找钢网、慧聪网、敦煌网等。

做生意最关键的是：稳赚不赔，这个供应链金融，胖猫理财有意思，债权转移给买理财的屁民了。
胖猫就赚利息，仓储费，物流费等，

** file-service 动态配置
  能指定文件上传的云服务，或者动态的选择上传的云服务？动态配置。。
  动态配置几个问题：
  1.是将所有的参数都配置到db中么？或者能用nacos后台修改？
  2.这几个实例是全部生成，然后根据db中配置的type来动态选一个实例么？
  3.实例的参数能动态修改么？？
  4.前端上传文件能通过参数控制选择哪个实例么？
  5.lazy 惰性加载？
*** 现在做第一步最简单的
  将配置改到数据库中，弄清楚spring的application.yml怎么映射到对象的，
  file:config:FastDFS，对的有个prefix是file的，StorageConfig这个对象，对的，
  直接注入到这个对象中，

  FastDFS 系统有三个角色：跟踪服务器(Tracker Server)、存储服务器(Storage Server)和客户端(Client)。

　　Tracker Server：跟踪服务器，主要做调度工作，起到均衡的作用；负责管理所有的 storage server和 group，每个 storage 在启动后会连接 Tracker，告知自己所属 group 等信息，并保持周期性心跳。
** 20220428 今日任务
  弄清楚哪个Spring相关的一些注解，看懂哪个MessageService，然后做FileService的动态配置。
  培训
  你要思考下，为撒公司要花这么多时间做员工培训，培训的内容为撒这样设计，所有的事件背后都是有原因的，因果律。

  看下MessageService中怎么实现的，照葫芦画瓢。
  MessageManager中有实现，
  SmsConfig config = smsConfigMapper.findSmsConfigByEnable();
        Class clazz = Class.forName(config.getType());
        log.info(config.getType());
        SmsMessageClient smsMessageClient = (SmsMessageClient) clazz.newInstance();
        return smsMessageClient.config(config,smsContentMapper);
        这代码写的不敢恭维啊。

        这重试直接写这里，要是服务挂了，咋弄？重试不了。

   大概都清楚了，现在想想怎么弄：
   对，这个StorageConfig是根据那个配置文件自动装配的，项目启动的时候就自动装配的，
   哦，看看这个类和那个yml文件是对应的，

   那个核心的实现在StorageConfigManager中，有注入那个StorageConfig，而这个注入的其实已经生成好了
   create table file_storage_config

   表建立了，现在要做的是在里面替换掉，(
   把mapper包放到resources目录下， 并且application.yml做如下修改：
   mybatis-plus:
  mapper-locations:
    classpath:/mapper/**Mapper.xml
    这个方法是可以的，明天要弄清楚的就是springboot 怎么配置mybatis，

    嗯，看了message-service，那个build目录下的resources下的mappers里面也是有编译的mapper.xml文件的。
** 20220429 今日任务
   1.搞清楚那个mybatis mapper的配置相关
   2.将file-service的动态配置功能完成

** 20220505 今日任务
   使用SpringBoot的方式开发，不用微服务，那就是将原来的项目代码全部塞到一个项目工程中，
   1.再看看message-service的实现，然后check下file-service的代码问题 done
   2.结合周五说的几个微服务干嘛的，想想怎么塞入到新项目中

   saas多租户系统怎么设计？
   1.有个付费的主体，比如某公司，然后公司下面挂多个用户，每个用户有不同的权限
   2.租户有个租期，租约，比如租了哪些功能，类似租房的只有洗衣机或者空调功能，没打扫阿姨功能等
   这个就是有个AOP很切面，使用任何功能的时候回进行租期的验证，租约的验证

   想想这个多租户系统怎么和原来的微服务关联起来，就是怎么塞进去，还有结合业务，真tm烦，

   看这个产品需求，想想你要怎么设计？？
   没得具体的问题，具体的任务，我就不知道干撒了，操。自己提出问题？？

   假设现在就是让你来做整个的底层多租户系统，怎么做？？？
** 20220506
长远来看
1. saas多租户；2.nacos eruka等区别；3.gradle常见问题；4.Spring Cloud；
*** 创建客户
添加一个字段customer_type,1是公司；2是项目
主要使用到的几个表：org_company_info,org_company_qualification,org_company_info_records,user_user，
然后查询注意过滤type=1，

新增的时候选项目类型，带出公司信息，如社会信用码，user_user中的管理员信息，

代码在organazation-service中，

** 20220507
1.完成客户创建，查询，列表
一个客户（公司客户，项目客户）只有一个管理员
2.上班时候就工作提升技能，面向interview学习，产品，商业，更多的偏向商业或者说赚钱模式
3.下班后就看书，继续炒股，妈个狗逼的，思考学习分析事件，基本面等影响

生成初始密码，8到20位的，密码无非就是数字，字母加特殊字符组成的，想想你自己输入密码的过程是一样的，

创建客户之后是否成为待审数据？？

比特币为什么能这么火？创建的初衷是什么？政府瞎几把印钱，洗劫所有储户，
天下苦秦久已，这个会不断积累，形成一种反向的势，就是不断的超发货币，洗劫屁民，
美国不断超发美元洗劫全世界，但是又依赖美元体系，没得办法，

存钱被洗劫，不存钱没投资渠道，股市被洗劫，p2p被割韭菜，比特币被割韭菜
国内投资渠道几乎没有，房地产，股市，基金，理财，货币，债券基金等等，思考一下本质？
现在的情况是经济完全没有活力，因为没有经过杀伐，所以没有生机，没冬不会有春，

现在的情况是市面上流动超印出来的货币已经远远超过了实物或者说国内创造的价值积累总和，
最关键的一点是像所有的工业品如果没有需求的话，全部都是垃圾，一文不值，看看原油就是-36.7美元一桶，
然后历史上的事件，倾倒牛奶，茶叶等等，所以这些jb玩意一文不值，就像我之前写的那些代码一样的，
所以应该不断买入持有稀有的，总量不变的产品，比如古玩，明清的瓷盘，或者黄金，玉，
但古玩这门槛太jb高了。

怎么搞钱报复，钱物钱，钱钱（汇率兑换），钱物（购买），物物（原始社会交换），价值交换交易，
有一致性的共识才能达成交易，但是这共识的形成中又具有天地鸿沟区别，一个买入看涨，一个卖出看跌，
意识形态不同，

要搞钱，还是得看你有什么？有钱，有物即资源，
有钱用钱赚钱，有物，售卖资源，有人脉，资源整合，撮合交易双方，真tmb的烦，还是继续炒股，操。


怎么撬动杠杆？？？用什么撬动杠杆？？？

所有的财富机会都在最前沿，科技前沿，概念前沿，心智前沿，新生事物，未来发展方向，
先进入的入局者，持有仓位坐好，然后等后续的人抬轿子，先发优势，所有的都基于竞争优势，


将整个事物发展过程推演一下，假设到一家公司，你技术的确牛逼，但是不会团结人，不会巴结人，同样职场也发展不行。
然后你搞高并发这套东西，未必有你的机会，你还要上级赏识你，然后假设以上都成立，突然公司高层空降一个领导过来，
你如何弄？这些东西都是你无法决定的，因为有鸿沟，断层，这些不是你能接触到的。

所以最核心的是你能兑现你的技术价值，最好是直接兑现，直接自己做ceo，思考产品，商业等的东西，
因为我本身的心性就决定了如此。但是整个过程中还是要用柔用弱，取势，杠杆，

把一切牢牢掌握在自己手中，然后工作你只是去锻炼你需要的这些能力，仅此而已。

技术学号，产品思考好，商业也思考好，有手下了让别人去做就行。

时间不要浪费，炒股主要是他妈比的赢家通吃，一家吃99家，

而且中层开始就天天开会，到处沟通，交流，管理等等，


把目前的目标拆解一下：
** 20220509
1.客户创建需求代码
2.Spring Cloud gateway inter question
3.发现一下目前项目中的问题并提出解决方案
我发现根本不会培养人，职场的问题太复杂了，主要是人际个方面，其实jump一次的成本和风险都极大，特别是到后期，越后面越大，
更不用谈转行，但是要将职场的寿命或者时间尽量延长一点。技术提升下，jump，延长下寿命，全力投机，

每一步都谨小慎微我tm也只能取得一个勉勉强强的结果，草泥马戈壁的。也是挺不爽的，我曹。

这个如果出错了，异常时怎么处理的？？直接跑出到页面？？

树状接口：到底是用一个接口还是多个接口？

mybatis plus只生成指定的表名，随便添加个配置
project.table.onlyinclude=org_customer_contact

然后代码中，StrategyConfig.setInclude(properties.getProperty("project.table.onlyinclude"))

** 20220510
1.创建客户，客户列表等代码
2.复习

创建客户时看登录的用户角色，如果是admin直接进公海，如果是销售员，就是对的，这两字段要塞到表中，
创建的集团默认level是1，一级客户，
customer_basic要增加几个字段：1.创建人（有了）；2.销售员；3.客户状态，待审，潜在，成交，白名单，异常，

树状表，更加层级组装数据，

@PostMapping(value = "/submitCustomerInfo")
    public Response submitCustomerInfo(@RequestBody CompanyPurchaserVO model) {
        companyInfoService.submitCustomerInfo(model);
        return new Response();
    }

    /**
     * 编辑客户资料保存草稿
     *
     * @param model
     * @return
     */
    @PostMapping(value = "/saveCustomerInfo")
    public Response saveCustomerInfo(@RequestBody CompanyPurchaserVO model) {
        companyInfoService.saveCustomerInfo(model);
        return new Response();
    }

这个完善资料，业务信息可能是新增我曹，然后基础信息应该是更新，真jb恶心，
要看一下递归
** 20220511
1.写一下早上的经历；
2.客户审核，
审核做了什么？1.修改用户信息，

添加个接口，待审中的，无法编辑
提交编辑 是插入Record表中，

提交审核获取企查查接口，拿到信用评级

page接口看CompanyInfoRecordController中的page接口，

现在缺的一个是微服务，一个是项目，操，

意向和潜在都是没合作的
合作后，系统会把类型改为成交

客户公海，潜在客户，成交客户，客户白名单，异常客户，这几个列表是一样的，提供不同的url接口，但是后台调用一个接口

信用评级，就是ExternalClient中的requestQichachaCompanyGrade方法，得到的对应的grade字段。
3.写测试用例
大概清楚了，是啊，本地测试用例mock不现实，微服务依赖太多了，
每次修改配置要重启，每次改表字段要重启，要用本地nacos，不要去改22上的nacos，

客户类型到底是放到那张表？basic是主表，应该放basic，但是这样导致后续查询的时候，下面个实体需要去上面取数据？？
如果冗余的话，需要2个都保持一致，如果放到business表，问题好像也不大，通过业务表查主表，算了，还是jb转化一下，
是啊，这2表数据杂交了，业务信息中的客户名称，本来应该保存客户id，名称就展示，没卵用，
** 2022-05-12
现在主要是把主流程调通，
address @ApiModelProperty(value = "状态 0 正常 1 待审 2 草稿 3 驳回")
    private Integer status;
    public boolean saveCustomerDeliveryAddress(List<InvoiceAddressParam> list, Integer companyId, Integer status) {
        QueryWrapper queryWrapper = new QueryWrapper();
        queryWrapper.eq("company_id",companyId);
        queryWrapper.eq("type",4);
        queryWrapper.ne("status",0);
        if(!list(queryWrapper).isEmpty()){
            remove(queryWrapper);
        }
        List<CompanyAddress> cList=list.stream().map(a->{
            CompanyAddress cc=new CompanyAddress();
            cc.setAddress(a.getAddress());
            cc.setPerson(a.getPerson());
            cc.setPhone(a.getPhone());
            cc.setCompanyId(companyId);
            cc.setStatus(status);
            return cc;
        }).collect(Collectors.toList());
        return saveBatch(cList);
    }
    哪个收货地址和发票地址是一样的，通过type区分，4是发票，1是收货地址
    列表的所在地区  显示所属区域
*** 审核
就是record表永远最多只有1条记录？还是2条？
第一次保存的时候，状态是草稿，点击编辑，load出是草稿的或者被驳回的数据，
第一次提交审核的时候，状态是待审核，有待审核记录的无法再编辑，
第一次审核是插入数据，
审核驳回之后，又能再次编辑，
审核通过之后，更新basic表和状态，更新business表的状态，

这个编辑资料肯定是大问题，最好是拆解了之后好改bug，操。

开票信息和客户联系人的审核是通过status状态来区分的。

不对，这个保存，也应该是保存到record记录中，

保存按钮说的是：没审核之前，一直能不停的编辑，然后保存的数据，详情能够查到。
** 20220513
1.几个客户page查询
2.调试3；客户查询单独字段单独添加
这个级联蛋疼了，1.把groupName，parentName写回去？？然后这里模糊查询就容易了
2.basic做父子表关联，但是假设在多一个business表的字段条件咋弄？？
3.三张表联合查询？？

绩效评级这个我能够实时的去查询，没必要保存数据，
他那边要给我一个接口，把最新的客户信息同步过去，每次审核通过后都要同步

** 20220514
1.根据token拿用户信息，展示销售员，带入当前用户姓名；若当前登录为管理员，销售员为空；

** 20220518
客户名称，所属集团名称能修改，这就是大坑了，
小米公司下属的

DONE1.审核通过之后，还要改所有的父公司，父集团名称，因为做了冗余，

3.第一次提交审核要更新数据，显示刚填充的数据，之后的提交审核显示原来的老数据

DONE4.释放销售员，原来的记录还在，客户公海中加一条，分配销售员后，公海少一条，原来的销售员地方显示出来

DONE 5.标记异常全部进到异常客户中，取消异常之后，回到原来的列表中，因为异常以后无法进行绩效评级，
所以不用更加绩效来判断应该放到成交还是白名单客户中，这里得加个字段
取消异常的时间可能还需要记录，

好几把坑啊，这地方，因为状态关联到其他
撒几把都没有，就这抠细节，我真jb服了



提交审核-》第一次提交，更新所有数据-》驳回，再点编辑，查所有最新的数据，


customer_basic中的audit_status只是用户同步其他表的状态，不用于查询之类的，

就是要关联查其他地方的数据就用这个status，

主要有个jb大坑是第一次提交审核还能都看到状态，

是否第一次提交审核，是，查询待审核的最新数据，否，查询正常的数据？也tm的不对，
真jb大坑，操他妈的，

没有提交过审核，第一次提交审核，已审核通过的？
查草稿的       查待审核的

如果是第一次提交审核，之后又驳回了，查看的驳回的数据，就是customer_basic中的audit_status是几？？

问题1：estbalishTIme没过来，2.待审列表几个字段没有，

** 20220520
1.先看原型，对表结构 ，然后生成代码，回滚覆盖的，写文档，

** 20220521


一些需求的问题：
1.生成了物料模板的 物料改变名称会影响模板么？？


直接把原来的删掉，但是有一种情况是状态正常的不能删，其他的都删，
好像那个分类没关联起来，

2.三级分类和品控资质即协议的对应关系
3.三级分类和配置属性的关系，如何做表关联，是放到主表还是拉到一张单独表

现在是社会化的绝对精细化分工，所以每个人必须精通自己那一块的东西，并且会合作，
我现在会的：编程，炒股，写作，怎么将这三项技能变现？？
炒股变现赚钱的可能性最大，但是风险也最大，
编程，怎么将这个技能卖出去？创造价值或者损害收割其他人的价值，

就是现在什么东西丢到公开性的市场上能够赚钱，
所以第一点是要有需求，大量的需求，第二点你能解决这个问题，也就是提供供给，
有需求就有钱，别人需要什么？？做个网站，app，公众号之类的，让别人提啊，

所以首先要搞出一个正向循环，之后的就是不停的复制，算了，去几把的，
面向面试，把技术搞搞，然后找人带，培养，是啊，妈的，之前应该跟winfer他们的，
最少也该去bat镀金的，操。
1.成熟的不干
2.风险大的不干
3.投资大的不干
收益固定切不错，
4.最好是销售，中介类的，不想那多，要能想清楚早jb想清楚了
编程，炒股，继续干，往死里干，

办个公司，领个皮包，
** 20220523
1.agreement是协议，即使品控，param是规格属性，

prod_category_param表对应到配置属性页面，
prod_agreement 是协议，品控
prod_category_bind_agreenemt是三级分类和协议绑定表

缺个分类和属性绑定表，但是不就是prod_category_param表么？

2.新建物料模板
这个对应关系，几个接口要弄清楚，真tm蛋疼，
三级分类下的规格属性，要提供个接口，groupBy那个name，

物料和规格怎么关联起来？？？
规格属性挂靠到三级分类下面，然后规格属性也会挂靠到物料下面？但是这个规格属性又能随便填？
物料里面少了个规格型号，

临时物料的规格型号和三级分配配置的属性是一回事么？？
这个对应关系怎么弄？ 物料规格信息怎么弄？？

*** 对着原型，看描述，测试，改bug，完善
1.分类税率
感觉又在重蹈覆辙啊，一次次的轮回，失败，佛陀说的轮回原来是真是存在的，不是生死，
但是在小的时间周期内是这样，那么放大这个周期同样也是成立的，道。无大小，无层次的。
分类税率

2.导入
业务流导入的临时物料规格，若临时物料的规格在所属三级分类规格库不存在，该分类新增规格属性；


*** 3个列表给标识，是否有待审数据，有，不让编辑
*** 详情提交审核
1.第一次提交审核，更新所有信息，basic带状态了，这时候带出的其他数据是待审核的，
但是实际它是有正常的数据的，所以要看客户的查询接口

对，已经提交审核过得，但是未必审核通过啊，
就是查客户的信息，正常的数据，查相关的正常的数据，待审核的数据，查待审核的数据，

但我这里是每次都根据客户basic的状态去查其他的数据，就不对，应该按business中的状态，

但是jb也有问题，最好是不要连表查询，问题jb太多了，操

所有的全部不联合，一个个查，妈的，因为business可能有2条记录，这时候就重复了，操真jb蛋疼，
所有地方查询正常的数据，只有待审客户单独的接口查询待审的记录，

就是这个auditStatus的状态，如果提交审核的时候，不应该改这个的状态， basic不要这个状态行吗？？

详情的时候，不能查询待审核的，要查询正常或者草稿的，或者驳回的？？

basic的那个状态不要，查出那个business中的数据，然后拿状态，然后去其他地方查询，


** 20220602
1.临时物料规格在指定三级分类后没有的要新增进去

只有启用状态的才进标准物料？
2.去掉ES done

不能再生成，
** 20220606
1.Spring IOCAOP
*** 先把客户模块的几个bug改了
** 20220607
1.现将企查查的搞好
2.学习spring core
** 202206008
大概懂了，销售订单导入（包括销售单，合同）导入里面的物料到临时物料，生成sku编码，
已存在的，直接返回。
判断这个物料是否已经生成对应的物料模板，没有生成，就不记录回传信息
已经生成了，

然后回传，是哪边传哪边？采购单审核通过之后传给物料这边还是？
然后下面的判断，该物料是否已生成物料模板，审核通过，根据回传字段？？？那些自然段，
生成ssku，有没品控资质，没有，草稿状态，有了？？


这个物料已生成SSKU，根据回传信息，更新对应的销售区域及采购价格，启用。
** 20220609
联系人状态验证，

客户公海里面多了一条数据，我曹
1.把供应链系统搞清楚；2.resume写清楚；3

** 20220610
//TOOD 今日任务，项目描述搞好，然后项目搞清楚，需求，技术栈，架构图，业务图等等
弄清楚供应链是个什么东西，具体的业务是什么，做了什么模块，模块，业务间相互关系
包括客户管理CRM，供应商管理SRM，销售管理，采购管理，物料管理，合同管理，物料管理，财务协同
2.Spring核心实现机制
可以提交个PR，

AbstractAutowireCapableNBeanFactory类

程序员这个的确是不行，干不来，转产品？天天画原型？？也没多大意思，
而且动手能力极差，社会实践经验没有，能力极差，和他人打交道，沟通的能力极差，
那优点了？优点是什么？？没事天天几把脑子瞎想，
技能：编程，炒股，写作，目前来看只能财经写作，股票类的，但是这个也是个红海，
势，道，术，主要是缺术啊。道也没到一定层次，真jb难，

** 20220613
还是学习Spring，CGLIB，

The JSR-250 @PostConstruct and @PreDestroy annotations are generally considered best practice for receiving lifecycle callbacks in a modern Spring application. Using these annotations means that your beans are not coupled to Spring-specific interfaces.

** 20220614
1. 简历写了
2。投简历

项目名称：数智化供应链平台，
项目描述：主要做工业产品的采购，供应链系统，采购商来平台发布产品，创建采购订单等，
然后系统将采购需求单推送给符合的有资质的供应商，撮合交易。
项目主要包括的功能模块有：客户管理，供应商管理，销售管理，采购管理，物料管理，
合同管理，物流管理，财务协同等模块。

负责数智化供应链平台的架构设计，微服务模块划分，框架搭建，技术选型，公共模块开发等

还是要把简历，项目都弄清楚啊，

今天下午就吧1.简历写好，项目的业务搞清楚；2.复习
简单来说就是有供应商和采购商，来我们这个平台发布商品，物料，然后我们通过撮合交易，
开店等收取中介费用，提供各种订单，物料管理来收费。
