* 什么是供应链系统

供应链管理被认为是通过各种中介公司有效地将供应商的产品流或物资流、服务流、信息流、资金流输送到用户的渠道，或是联结卖方和最终用户的物流网络系统；
供应链其实是一个挺大的概念，指的是一个产品从零部件、到半成品、成品，然后通过销售网络把产品送达到用户手中，这个从上游到下游的整体网链结构。

包括我们做硬件产品的企业本身，也身处于供应链中的一环；企业的上游为供应商，下游为客户。


中国供应链有两大优势，一是分工非常细，二是网络非常大。

分工与网络两大特点，给中国供应链带来了效率和规模的核心竞争力；效率保证了响应速度快，规模保证了不仅快、成本还低；
富士康在郑州的工厂，一天可以生产50-60万台苹果手机，换算下就是一分钟350台，每个月的产能达到一亿台以上，规模和速度惊人。

在企业中的供应链管理，主要包括几个方面的工作：商务、成本、采购、计划、物流仓储等。

商务的主要工作包括了：寻源、谈价、供应商管理、供应商关系维护等。
寻源（也叫Sourcing）就是找到合适的供应商资源，寻源（也叫Sourcing）就是找到合适的供应商资源，一个完整的供应商寻源过程包括：需求分析、供应商寻源、供应商分析和供应商决策四个阶段。

所谓采购，是指企业在一定条件下从供应市场获取产品或者服务作为企业资源，以保证企业生产及经营活动正常开展
在采购成本确定之后，采购流程还包括了索样、评估、请购、订购、协调沟通、催交、进货验收、付款等环节。
影响采购的因素包括品质、价格、交期、服务、配合度等等。

计划可以拆解为几个层级，分别是需求计划、MPS主生产计划、MRP物料需求计划、采购计划和DRP配送需求计划。
需求计划即Forecast，也叫FC，是基于历史订单、现有订单、市场情况、企业战略情况预测未来有多少需求；换句话说，就是从市场客户端角度，预测未来每个月/周/天预计销售多少。

5MPS（Master Production Schedule）主生产计划，是确定每一个具体的产品在每一具体时间段之内的生产数量的计划；MPS会考虑经营规划和销售规划，去制定与之协调的生产规划，即根据需求和产能平衡，计划何时生产多少。

然后是MRP（Material Requirement Planning）物料需求计划，产品是由物料组成的，组成物料的清单就是BOM（Bill of Materials）；在需求和主生产计划明确的前提下，结合产品BOM就可以分解到何时需要多少材料和部件的物料需求计划；一般这个步骤都是通过ERP系统，由计算机运算跑出来的。

接着基于MRP制定采购计划，即向谁采购什么，何时下订单，要求何时到货。

最后是DRP（Delivery Requirement Planning）配送需求计划，即多个成品仓库时如何安排每个仓库的配送计划。

所谓仓储物流（Warehousing Logistics），就是利用自建或者租赁库房，储存、保管、装卸、搬运、配送货物，以仓储为中心，促进生产和市场的同步。
仓储物流包括了两个概念，仓储和物流。
仓储主要做的是入库管理、在库管理、出库管理三件事情；
物流管理主要包括几个方面的内容：运输、库存、包装、搬运、流通加工和信息管理。

一个生产企业有销售，有采购，有技术，有生产，有物流，还有支撑部门，单个都是自己的信息化系统。
比如销售是crm，采购是mrp，技术也有专业的工艺和工序aps和bom程序，生产有mes，物流有tms，联合在一起就是erp。
但是erp只能在纵向的在企业内部发展，erp的需求无止境，但是止步于企业内部，如果拔高一层就是协同与自己相关的单位，这就是供应链。

供应链管理包括，供应商管理，采购，生产，客户，销售，是这些职能部门的桥梁

0-1是研发，创造，但是把一个产品做成平摊成本很低，那就是 1-n，1-n才是供应链的发力点，

供应链围绕核心企业，通过对商流（商品所有权发生转移）、物流（商品物质实体发 生转移）、信息流、资金流（以下简称“四流”）的控制，
最后由销售网络把产品送到消费者手中的将供应商，制造商，分销商，零售商， 直到最终用户连成一个整体的功能网链结构。

供应链管理是对整个供应链系统进行计划、协调、操作、控制和优化的各种活动和过程，其目标是要将顾客所需的正确的产品能够在正确的时间、 按照正确的数量、正确的质量和正确的状态送到正确的地点，，并使成本与效率最优化。

计划拆分和执行，反馈，修正，将链主的 计划和预测结合。

职业经理人的职能是管理，管理的核心就是计划和管控。
每个人都有职能， 目标，kpi，汇总成企业的目标和kpi。

预测是重点：基础数据积累，每个都是因果链，预测来增加确定性，预测需要多个维度，多个部门，就像天气预报都是一个维度，每个买菜的都知道，节日要多进点菜，订多了过期，少了没人，做期货更加如此。
