* 2022-04-27 每日任务
** 弄清楚SSO登录逻辑
** 弄清楚查询商家，订单的逻辑

那个nacos连接本地还是出错啊，

** 重点
一个auth服务，一个sso登录服务，这两弄清楚
还有一个system服务，xxjob服务，
sentinel怎么实现的，

还是要将auth和sso弄清楚，

** 供应链金融
B2B平台天然具有企业的交易数据、物流信息和资金数据等，更容易对供应链上下游企业进行增信。
这个模式的典型代表如上海钢联、找钢网、慧聪网、敦煌网等。

做生意最关键的是：稳赚不赔，这个供应链金融，胖猫理财有意思，债权转移给买理财的屁民了。
胖猫就赚利息，仓储费，物流费等，

** file-service 动态配置
  能指定文件上传的云服务，或者动态的选择上传的云服务？动态配置。。
  动态配置几个问题：
  1.是将所有的参数都配置到db中么？或者能用nacos后台修改？
  2.这几个实例是全部生成，然后根据db中配置的type来动态选一个实例么？
  3.实例的参数能动态修改么？？
  4.前端上传文件能通过参数控制选择哪个实例么？
  5.lazy 惰性加载？
*** 现在做第一步最简单的
  将配置改到数据库中，弄清楚spring的application.yml怎么映射到对象的，
  file:config:FastDFS，对的有个prefix是file的，StorageConfig这个对象，对的，
  直接注入到这个对象中，

  FastDFS 系统有三个角色：跟踪服务器(Tracker Server)、存储服务器(Storage Server)和客户端(Client)。

　　Tracker Server：跟踪服务器，主要做调度工作，起到均衡的作用；负责管理所有的 storage server和 group，每个 storage 在启动后会连接 Tracker，告知自己所属 group 等信息，并保持周期性心跳。
** 20220428 今日任务
  弄清楚哪个Spring相关的一些注解，看懂哪个MessageService，然后做FileService的动态配置。
  培训
  你要思考下，为撒公司要花这么多时间做员工培训，培训的内容为撒这样设计，所有的事件背后都是有原因的，因果律。

  看下MessageService中怎么实现的，照葫芦画瓢。
  MessageManager中有实现，
  SmsConfig config = smsConfigMapper.findSmsConfigByEnable();
        Class clazz = Class.forName(config.getType());
        log.info(config.getType());
        SmsMessageClient smsMessageClient = (SmsMessageClient) clazz.newInstance();
        return smsMessageClient.config(config,smsContentMapper);
        这代码写的不敢恭维啊。

        这重试直接写这里，要是服务挂了，咋弄？重试不了。

   大概都清楚了，现在想想怎么弄：
   对，这个StorageConfig是根据那个配置文件自动装配的，项目启动的时候就自动装配的，
   哦，看看这个类和那个yml文件是对应的，

   那个核心的实现在StorageConfigManager中，有注入那个StorageConfig，而这个注入的其实已经生成好了
   create table file_storage_config

   表建立了，现在要做的是在里面替换掉，(
   把mapper包放到resources目录下， 并且application.yml做如下修改：
   mybatis-plus:
  mapper-locations:
    classpath:/mapper/**Mapper.xml
    这个方法是可以的，明天要弄清楚的就是springboot 怎么配置mybatis，

    嗯，看了message-service，那个build目录下的resources下的mappers里面也是有编译的mapper.xml文件的。
** 20220429 今日任务
   1.搞清楚那个mybatis mapper的配置相关
   2.将file-service的动态配置功能完成

** 20220505 今日任务
   使用SpringBoot的方式开发，不用微服务，那就是将原来的项目代码全部塞到一个项目工程中，
   1.再看看message-service的实现，然后check下file-service的代码问题 done
   2.结合周五说的几个微服务干嘛的，想想怎么塞入到新项目中

   saas多租户系统怎么设计？
   1.有个付费的主体，比如某公司，然后公司下面挂多个用户，每个用户有不同的权限
   2.租户有个租期，租约，比如租了哪些功能，类似租房的只有洗衣机或者空调功能，没打扫阿姨功能等
   这个就是有个AOP很切面，使用任何功能的时候回进行租期的验证，租约的验证

   想想这个多租户系统怎么和原来的微服务关联起来，就是怎么塞进去，还有结合业务，真tm烦，

   看这个产品需求，想想你要怎么设计？？
   没得具体的问题，具体的任务，我就不知道干撒了，操。自己提出问题？？

   假设现在就是让你来做整个的底层多租户系统，怎么做？？？
** 20220506
长远来看
1. saas多租户；2.nacos eruka等区别；3.gradle常见问题；4.Spring Cloud；
*** 创建客户
添加一个字段customer_type,1是公司；2是项目
主要使用到的几个表：org_company_info,org_company_qualification,org_company_info_records,user_user，
然后查询注意过滤type=1，

新增的时候选项目类型，带出公司信息，如社会信用码，user_user中的管理员信息，

代码在organazation-service中，

** 20220507
1.完成客户创建，查询，列表
一个客户（公司客户，项目客户）只有一个管理员
2.上班时候就工作提升技能，面向interview学习，产品，商业，更多的偏向商业或者说赚钱模式
3.下班后就看书，继续炒股，妈个狗逼的，思考学习分析事件，基本面等影响

生成初始密码，8到20位的，密码无非就是数字，字母加特殊字符组成的，想想你自己输入密码的过程是一样的，

创建客户之后是否成为待审数据？？

比特币为什么能这么火？创建的初衷是什么？政府瞎几把印钱，洗劫所有储户，
天下苦秦久已，这个会不断积累，形成一种反向的势，就是不断的超发货币，洗劫屁民，
美国不断超发美元洗劫全世界，但是又依赖美元体系，没得办法，

存钱被洗劫，不存钱没投资渠道，股市被洗劫，p2p被割韭菜，比特币被割韭菜
国内投资渠道几乎没有，房地产，股市，基金，理财，货币，债券基金等等，思考一下本质？
现在的情况是经济完全没有活力，因为没有经过杀伐，所以没有生机，没冬不会有春，

现在的情况是市面上流动超印出来的货币已经远远超过了实物或者说国内创造的价值积累总和，
最关键的一点是像所有的工业品如果没有需求的话，全部都是垃圾，一文不值，看看原油就是-36.7美元一桶，
然后历史上的事件，倾倒牛奶，茶叶等等，所以这些jb玩意一文不值，就像我之前写的那些代码一样的，
所以应该不断买入持有稀有的，总量不变的产品，比如古玩，明清的瓷盘，或者黄金，玉，
但古玩这门槛太jb高了。

怎么搞钱报复，钱物钱，钱钱（汇率兑换），钱物（购买），物物（原始社会交换），价值交换交易，
有一致性的共识才能达成交易，但是这共识的形成中又具有天地鸿沟区别，一个买入看涨，一个卖出看跌，
意识形态不同，

要搞钱，还是得看你有什么？有钱，有物即资源，
有钱用钱赚钱，有物，售卖资源，有人脉，资源整合，撮合交易双方，真tmb的烦，还是继续炒股，操。


怎么撬动杠杆？？？用什么撬动杠杆？？？

所有的财富机会都在最前沿，科技前沿，概念前沿，心智前沿，新生事物，未来发展方向，
先进入的入局者，持有仓位坐好，然后等后续的人抬轿子，先发优势，所有的都基于竞争优势，


将整个事物发展过程推演一下，假设到一家公司，你技术的确牛逼，但是不会团结人，不会巴结人，同样职场也发展不行。
然后你搞高并发这套东西，未必有你的机会，你还要上级赏识你，然后假设以上都成立，突然公司高层空降一个领导过来，
你如何弄？这些东西都是你无法决定的，因为有鸿沟，断层，这些不是你能接触到的。

所以最核心的是你能兑现你的技术价值，最好是直接兑现，直接自己做ceo，思考产品，商业等的东西，
因为我本身的心性就决定了如此。但是整个过程中还是要用柔用弱，取势，杠杆，

把一切牢牢掌握在自己手中，然后工作你只是去锻炼你需要的这些能力，仅此而已。

技术学号，产品思考好，商业也思考好，有手下了让别人去做就行。

时间不要浪费，炒股主要是他妈比的赢家通吃，一家吃99家，

而且中层开始就天天开会，到处沟通，交流，管理等等，


把目前的目标拆解一下：
** 20220509
1.客户创建需求代码
2.Spring Cloud gateway inter question
3.发现一下目前项目中的问题并提出解决方案
我发现根本不会培养人，职场的问题太复杂了，主要是人际个方面，其实jump一次的成本和风险都极大，特别是到后期，越后面越大，
更不用谈转行，但是要将职场的寿命或者时间尽量延长一点。技术提升下，jump，延长下寿命，全力投机，

每一步都谨小慎微我tm也只能取得一个勉勉强强的结果，草泥马戈壁的。也是挺不爽的，我曹。

这个如果出错了，异常时怎么处理的？？直接跑出到页面？？

树状接口：到底是用一个接口还是多个接口？

mybatis plus只生成指定的表名，随便添加个配置
project.table.onlyinclude=org_customer_contact

然后代码中，StrategyConfig.setInclude(properties.getProperty("project.table.onlyinclude"))

** 20220510
1.创建客户，客户列表等代码
2.复习

创建客户时看登录的用户角色，如果是admin直接进公海，如果是销售员，就是对的，这两字段要塞到表中，
创建的集团默认level是1，一级客户，
customer_basic要增加几个字段：1.创建人（有了）；2.销售员；3.客户状态，待审，潜在，成交，白名单，异常，

树状表，更加层级组装数据，

@PostMapping(value = "/submitCustomerInfo")
    public Response submitCustomerInfo(@RequestBody CompanyPurchaserVO model) {
        companyInfoService.submitCustomerInfo(model);
        return new Response();
    }

    /**
     * 编辑客户资料保存草稿
     *
     * @param model
     * @return
     */
    @PostMapping(value = "/saveCustomerInfo")
    public Response saveCustomerInfo(@RequestBody CompanyPurchaserVO model) {
        companyInfoService.saveCustomerInfo(model);
        return new Response();
    }

这个完善资料，业务信息可能是新增我曹，然后基础信息应该是更新，真jb恶心，
要看一下递归
** 20220511
1.写一下早上的经历；
2.客户审核，
审核做了什么？1.修改用户信息，

添加个接口，待审中的，无法编辑
提交编辑 是插入Record表中，

提交审核获取企查查接口，拿到信用评级

page接口看CompanyInfoRecordController中的page接口，

现在缺的一个是微服务，一个是项目，操，

意向和潜在都是没合作的
合作后，系统会把类型改为成交

客户公海，潜在客户，成交客户，客户白名单，异常客户，这几个列表是一样的，提供不同的url接口，但是后台调用一个接口

信用评级，就是ExternalClient中的requestQichachaCompanyGrade方法，得到的对应的grade字段。
3.写测试用例
大概清楚了，是啊，本地测试用例mock不现实，微服务依赖太多了，
每次修改配置要重启，每次改表字段要重启，要用本地nacos，不要去改22上的nacos，

客户类型到底是放到那张表？basic是主表，应该放basic，但是这样导致后续查询的时候，下面个实体需要去上面取数据？？
如果冗余的话，需要2个都保持一致，如果放到business表，问题好像也不大，通过业务表查主表，算了，还是jb转化一下，
是啊，这2表数据杂交了，业务信息中的客户名称，本来应该保存客户id，名称就展示，没卵用，
** 2022-05-12
现在主要是把主流程调通，
address @ApiModelProperty(value = "状态 0 正常 1 待审 2 草稿 3 驳回")
    private Integer status;
    public boolean saveCustomerDeliveryAddress(List<InvoiceAddressParam> list, Integer companyId, Integer status) {
        QueryWrapper queryWrapper = new QueryWrapper();
        queryWrapper.eq("company_id",companyId);
        queryWrapper.eq("type",4);
        queryWrapper.ne("status",0);
        if(!list(queryWrapper).isEmpty()){
            remove(queryWrapper);
        }
        List<CompanyAddress> cList=list.stream().map(a->{
            CompanyAddress cc=new CompanyAddress();
            cc.setAddress(a.getAddress());
            cc.setPerson(a.getPerson());
            cc.setPhone(a.getPhone());
            cc.setCompanyId(companyId);
            cc.setStatus(status);
            return cc;
        }).collect(Collectors.toList());
        return saveBatch(cList);
    }
    哪个收货地址和发票地址是一样的，通过type区分，4是发票，1是收货地址
    列表的所在地区  显示所属区域
*** 审核
就是record表永远最多只有1条记录？还是2条？
第一次保存的时候，状态是草稿，点击编辑，load出是草稿的或者被驳回的数据，
第一次提交审核的时候，状态是待审核，有待审核记录的无法再编辑，
第一次审核是插入数据，
审核驳回之后，又能再次编辑，
审核通过之后，更新basic表和状态，更新business表的状态，

这个编辑资料肯定是大问题，最好是拆解了之后好改bug，操。

开票信息和客户联系人的审核是通过status状态来区分的。

不对，这个保存，也应该是保存到record记录中，

保存按钮说的是：没审核之前，一直能不停的编辑，然后保存的数据，详情能够查到。
** 20220513
1.几个客户page查询
2.调试3；客户查询单独字段单独添加
这个级联蛋疼了，1.把groupName，parentName写回去？？然后这里模糊查询就容易了
2.basic做父子表关联，但是假设在多一个business表的字段条件咋弄？？
3.三张表联合查询？？

绩效评级这个我能够实时的去查询，没必要保存数据，
他那边要给我一个接口，把最新的客户信息同步过去，每次审核通过后都要同步

** 20220514
1.根据token拿用户信息，展示销售员，带入当前用户姓名；若当前登录为管理员，销售员为空；
一定要自己创业
