* 肾虚 中药
补肾，中医名词。是指通过饮食、药补、健身运动、气功、针灸、按摩等手段达到改变肾阴虚、阳虚的状态，补肾的食物，最常用的是通过鹿茸片煲汤、泡酒等方法。壮阳，中医名词，指通过气功、饮食、药物、针灸、按摩、运动等手段提高男子阳性气息，达到提高肾阳、强阳健体、提升性能力、增强性欲的目的，男性壮阳是男性追求更高生活质量的一种表现

● 动物肾脏：猪、狗、羊、牛之肾脏均有养肾气、益精髓之功效，如羊肾甘温，可补肾气；猪肾咸平，助肾气、利膀胱；狗肾对增强性功能效果更佳；有些动物的睾丸可治阳痿、遗精、滑精等症。
● 海鲜：海参、鲍鱼、淡菜、泥鳅都是有效的强精食物。鱼、虾、贝及海藻类含丰富的锌，锌是形成睾丸激素的重要物质，也是女性生殖器官分泌润滑液不可缺少的元素，因此，吃海鲜可提高性欲。
● 鸡蛋：含有八种人体必需的氨基酸，可强精益气，提高精液质量，增强精子活力，同时也是性爱后恢复体力的最佳食物。

山药——性平，味甘，为中医“上品”之药，除了具有补肺、健脾作用外，还能益肾填精。凡肾虚之人，宜常食之。

干贝——又称江珧柱。性平，味甘咸，能补肾滋阴，故肾阴虚者宜常食之。     鲈鱼——又称花鲈、鲈子鱼。性平，味甘，既能补脾胃，又可补肝肾，益筋骨。     栗子——性温，味甘，除有补脾健胃作用外，更有补肾壮腰之功，
对肾虚腰痛者，最宜食用。

枸杞子——性平，味甘，具有补肾养肝、益精明目、壮筋骨、除腰痛、久服能益寿延年等功用。尤其是中年女性肾虚之人，食之最宜。

何首乌——有补肝肾、益精血的作用，历代医家均用之于肾虚之人。凡是肾虚之人头发早白，或腰膝软弱、筋骨酸痛，或男子遗精，女子带下者，食之皆宜。

忌吃或少吃——荸荠、柿子、生萝卜、生菜瓜、生黄瓜、生地瓜、西瓜、甜瓜、洋葱、辣椒、芥菜、丁香、茴香、胡椒、薄荷、莼菜、菊花、盐、酱、白酒及香烟等。

1)参元汤：人参(或西洋参)功能益气健脾，桂圆肉功能养血安神；以人参6g加桂圆肉10枚，共煮内服，对慢性肾功能不全病人贫血、心悸怔忡者，有养血安神之功效。

2)参枣汤：人参(或西洋参)功能益气健脾，红枣功能健脾和胃，以人参6g加红枣6枚，共煮内服。对慢性肾功能不全病人贫血者，有提高血红蛋白作用。

3)小米、大枣、赤小豆、山药(鲜)各适量，加水共煮成粥，熬时
加适量食碱；经常服用；慢性肾功能衰竭病人贫血服用，有健脾利水、和胃养血的功效。     鹿茸、巴戟天、海狗肾、海马、肉苁蓉、锁阳、紫河车、蛤蚧、杜仲、续断这些补阳药泡酒都有壮阳补肾，强身健体之功效。其中杜仲、续断、巴戟天还能补肾强腰壮筋骨，是很好的泡酒良药。

附上几个壮阳补肾强身的药酒方：

方1： 仙 茅20g，仙灵脾20g，蜂 房20g，肉苁蓉20g，杜 仲30g，牛 膝20g，续 断30g，锁 阳20g，阳起石20g，枸芪子30g，黄狗肾1具，蜈 蚣4条，黄 精20g，山萸肉20g，白 芍60g，甘 草20g      以上药用滚开水浸透，冷却后，置容器中，加白酒4－5斤泡，两周后即可服用，每日总量50mL．

补肾壮阳药膳的构造配方：     千金秘精方 药方： 早莲蓬、头粉、莲花芯、莲子心各均和。 制法、用法： 碾为细末，炼蜜为丸，如鸡头子大，一二丸口含。 功用： 任意采战不洩。


2、补肾壮阳药膳的构造配方：惹意牵裙散
药方：      牡丹花、天仙子、天茄花各均和。 制法、用法： 上为末，放在茶酒内与妇人食之。      功用： 如增产交合后果，蛇床子加倍；增产坚度，远志加倍；若欲长大，鹿茸加倍；增产射精量，钟乳加倍。

3、补肾壮阳药膳：长相思 药方： 淀粉、蛇床子、川椒（去目）、狗骨（烧灰）各均和。     制法、用法： 碾为细末，津调涂于玉茎上。 功用： 初交一次，令女刻骨铭心。

4、补肾壮阳药膳：浴炉散 药方： 松香、甘松、青皮、荆芥、五味子、蛇床子、朴硝个均和。 制法、用法： 每用一服水二钟，连根葱三枝，温洗阴户。 功用： 行事兴阳。




附上几个补肾壮阳民间偏方

偏方1：
      冬虫夏草、人参、淫羊藿各适量，乌鸡 1只。
将药及乌鸡加水炖服， 早、晚各服1次，服汤食肉。
      本方补精髓，益气血，适用于阴阳气血皆虚的性功能减退。

偏方2：
      九香虫50克，车前子、陈皮、白术各20克，杜仲40
克。先将九
香虫炒至半生半熟，车前子微炒用布包，杜仲微炙，上药共为细末， 炼蜜为丸如
      梧桐子大，每日服5克，晚临睡前再服魔兽世界猎人的宏1
次，淡 盐水或白酒送下。
      本方补肾益气，适用于肾虚性欲低下，兼见阳痿不起。

偏方3：
当归、白芍、柴胡、香附、女贞子、枸杞子、党参、茯苓、甘草各 适量。水煎服，日1剂。
      本方养血柔肝，疏肝理气，适用于性欲低下。
  偏方4：
      补骨脂240克(盐水炒)，云茯苓120
克，韭子印克。将上药浸入陈
醋内，醋高过药面一指，加热煮沸，取渣令干为末，再做成丸如桐子 大，每服
 20丸，早晚各1次。
      本方温补肾阳、固精涩遗，适用于性欲减退，遗精、阳痿。

偏方5：
      生海虾500克，核桃仁80个，淫羊藿200克，白酒250
毫升。先
将酒放人合适的容器内，加热；待酒热后投人生海虾，充分浸透，取酒虾焙干为度。核桃仁去皮盐渍，焙干，与海虾共为细末，分作
20包，1日服1包，每包分2次服用，每次取淫羊藿10克煎水100
毫 升，分送海虾散，1个月为1个疗程，服药期间禁房事。
     本方温肾补阳，适用于肾阳不足，命火衰微，性欲低下，阳痿。

偏方6：
      熟地、山萸肉、枸杞子各15
克，肉苁蓉、锁阳、山药、巴戟肉、白人参、炒枣仁、菟丝子各12克，天门冬、甘草各9
克，淫羊藿叶30克，鹿茸6克。将药研为细末，炼蜜为丸，每丸重9克，日服
3 次，每服1丸，白开水送下，忌食腥冷食物。
      本方滋阴、壮阳、益肾，适用于肾阴、肾阳皆虚所致的性欲低下。

偏方7：
      熟地、山药、山茱萸、枸杞wow钓鱼225
后哪里学、鹿角胶、菟丝子、杜仲、当归、肉桂，巴戟肉、肉苁蓉、黄狗肾等各适量。
水煎服， 日1剂，分2次服。
      本方温阳益肾，填精补血，适用于性欲减退，遗精，阳痿。

偏方8：

韭菜子、女贞子、菟丝子、枸杞子、五味子、覆盆子、巴戟天、淫 羊藿、蛇床子、鹿角霜各适量。水煎服，日1剂。
     本方温肾壮阳，适用于性欲低下，厌倦房事。

偏方9：
      牛鞭1根，韭菜子25克，淫羊藿、菟丝子各15
克，蜂蜜适量。将 上药焙干为末，蜜为丸，黄酒冲服。
     本方补火助阳，适用于性欲低下，阳痿诸症。

偏方10：
      蛇床子末90克，菟丝子(取汁)150毫升。将2
味药相合，外涂于 阴茎上，日五遍。
      本方温肾壮阳，适用于肾阳不足，性欲低下，阳痿。

偏方11：
      阳起石、蛇床子、香附子、韭子各30克，土狗(去翘足煅过)7
个，大枫子3克(去壳)，麝香、硫磺各3
克。将药研末，炼蜜为丸，指顶 大，以油纸盖护贴脐上，用绢袋子缚住。
      本方补火助阳，适用于肾阳虚衰，命火不足的性欲低下，阳痿。
