* 我到底是想要干嘛了？
昨天晚上打游戏打到凌晨才睡觉，本来就没什么意思的，但是还是那么的耗费时间去打游戏，而且浪费了睡眠时间，今天早上到公司，发现头发又掉了一大把。我到底是要怎么样？

但是周末真的是很无聊，除了看JAVA书，看炒股书籍，看股票之外的事情别的没什么事情做，感觉生活非常的没有意思。其实我从过去到现在一直没弄清楚我到底要什么，我未来要过什么样的生活，我一直都是被逼迫，一直逆来顺受，我有时候真的恨不得把他们砍成肉酱。吗D，只会不停的要求别人，从来不帮助也不肯定别人，也没人关心下，只是为了自己的目的。


对于未来，我真的是只能说是非常的模糊。我只想要一个人自由自在的，但是自由这个词汇是多么的昂贵啊，比生命，爱情还要昂贵。曾经听别人说过的，他一直在追求能力，自由和美。但是我怎么总是觉得自己是这么的无能为力了？自己是这么的无力，和无用了，对于宝贵的东西，奋命一求，但是人真的是要讲究手腕，策略。要不等待自己的只能是失败。虽然还是像以前那样的相信着某些东西，但是感觉人却像没气力一样的，负隅顽抗，死命硬撑。


如果对于未来不够明确的话，我想应该可以从自己对现实的不满开始做起。首先，第一点就是对于工资不满，工作不满。第二点就是每天做公交车。第三点就是没有女人。这些问题我都可以去解决，也是实实在在可以去解决的问题，但是我是怎么了？感觉没有意志和力气，对于事物都变得麻木？是我对自己失去了信心了？应该是自己的精气神在丧失。所以问题就在于自己修身养性，聚集起自己的精气神。
1.注重休息，
2.注重饮食
3.基本的欲望得到满足。我觉得最主要的就是第三点。
工资少了，钱少了，工作不好，可以慢慢努力来赚，我是为什么老有那种急于求成，感觉什么事情对自己都很容易成功一样的心态？应该是之前学业的顺利？

为什么你老是去想那些虚无缥缈的东西了？其实我相对于同龄人，我也不缺什么。只是我对于某些东西是不是太过于理想主义，完美主义？但是我觉得人活着就是应该为了追求这些东西而活着的啊。但是我又一次在她面前失败。应该是我自己放弃了才对，但是有时候有些放弃是智慧的，虽然也是无奈的，但是没有别的结局。我总是不知道到底是什么原因，我也老在假设如果这样会怎么样，如果那样会怎么样？但是我知道结局就是这样，即使再多如果结局还是一样。

我应该要规划自己的未来，但是这个太不具体了。我也可以解决现在的不满问题，但是我又很无力？感觉是自己的魂魄和心灵受到了创伤，需要很长时间愈合，但是我没有很多时间了。所以我觉得放弃对于爱情的追求，而是回归到平凡，找一个普普通通的女人过日子，不再要求Vergin或者别的什么之类的，因为我要求的越多付出的必然也越多，要知道越是美好的东西越是要付出与之等价的代价的。而我还要留点气力去追求自由。


首先说工作，之前老早就准备写好简历，换工作的，即使现在这个公司不给加工资我也会跳槽闪人。
